// ─────────────────────────────────────────────────────────────────────────────
// Voting Record API — the read-only "what they actually do" endpoint
// ─────────────────────────────────────────────────────────────────────────────
// Serves the curated voting record (the vr_* tables) filtered, sorted and paginated
// for the client. It is the counterpart to the client-side stance data: where a
// stance is what a politician SAYS, a row here is what they DID (a roll-call vote,
// a co-sponsorship, an amicus brief). Everything is keyed to the SAME issue
// vocabulary the rest of the app uses (ISSUE_MAP issueKeys), so the client can line
// a vote up against the matching stance and derive "stance vs. record" (Phase 2).
//
// Storage is Netlify Database (managed Postgres) via Drizzle — the same stack the
// sync / community / mandate functions use. A full roll-call record is far too large
// and query-heavy to bake into the static client bundle, which is why it lives here
// and is filtered server-side.
//
// POSTURE (matches the Mandate list): read-only and PUBLIC. A roll call is public
// record, so GETs need no auth. There is no write path here — ingest/admin writes
// will be a separate, authenticated route.
//
// VERIFIABILITY: every measure / rollcall / position row carries a NOT NULL
// source_url (enforced by the schema). This Function additionally refuses to EMIT
// any record item that somehow lacks a source, and validates every incoming/returned
// issueKey against the shipped ISSUE_MAP allow-list (db/issue-keys.json) so a vote
// can never be surfaced under an issue the app doesn't know about.
//
// Routes (all under /api/voting-record):
//   GET /member/:politicianId   one member's record (the profile Voting Record tab)
//        query: issue, chamber, actionType, position, result, from, to,
//               q (bill text search), procedural=0|1, sort, page, pageSize
//   GET /issue/:issueKey        every member's votes/positions on one issue
//        query: chamber, position, from, to, sort, page, pageSize
//   GET /measure/:measureId     one measure + its issues, roll calls (with votes),
//                               and non-roll-call positions
//   GET /compare                ?members=a,b,c[&issue=key] side-by-side per member

import type { Config } from "@netlify/functions";
import { and, desc, eq, gte, ilike, inArray, lte, notInArray, or } from "drizzle-orm";
import { db } from "../../db/index.js";
import {
  vrMeasureActions,
  vrMeasureIssues,
  vrMeasureProvisions,
  vrMeasures,
  vrMemberVotes,
  vrPositions,
  vrRollcalls,
  vrDistributionalImpacts,
} from "../../db/schema.js";
// The canonical ISSUE_MAP key allow-list, generated by scripts/gen-issue-keys.mjs.
import issueKeyData from "../../db/issue-keys.json" with { type: "json" };
// Offline-pack build/cache lives in the shared lib (shared with the ingest path).
import { getCachedPack, writeMemberPack } from "../lib/vr-pack.js";

const ISSUE_KEYS = new Set<string>((issueKeyData as { keys: string[] }).keys);

// ── Limits / defaults (defense in depth) ─────────────────────────────────────
const ID_MAX = 128; // politician id / issue key length cap
const Q_MAX = 120; // free-text search cap
const PAGE_SIZE_DEFAULT = 50;
const PAGE_SIZE_MAX = 100;
// Upper bound on how many raw rows one member/issue query pulls before merge +
// pagination. A member rarely exceeds a few hundred votes in a two-year term, so
// this comfortably covers a full record while capping worst-case memory. (A future
// optimization can push pagination fully into SQL via a UNION of votes+positions.)
const FETCH_CAP = 2000;
const MAX_COMPARE_MEMBERS = 8;
// Roll-call action types the UI treats as procedural noise, hidden when the caller
// passes procedural=0.
const PROCEDURAL_TYPES = ["procedural", "motion"];

// ── Distributional Impact Ledger allow-lists (defense in depth) ──────────────
// The client renders a "Who It Affects" panel keyed off these exact values, so the
// Function only ever emits a cohort/direction/strength it recognises.
const IMPACT_COHORTS = new Set<string>([
  "working_middle",
  "small_biz_contractors",
  "large_corporations",
  "high_income_wealth",
  "government_insiders",
]);
const IMPACT_DIRECTIONS = new Set<string>(["benefit", "cost", "mixed", "neutral"]);
const IMPACT_STRENGTHS = new Set<string>(["strong", "moderate", "limited"]);

// ── Offline pack (Netlify Blobs) ─────────────────────────────────────────────
// A compact, precomputed per-member record served at /member/:id/pack. It is what
// the PWA caches (stale-while-revalidate in the service worker) so a previously
// viewed member's record still renders with no network. Built + cached by the
// shared netlify/lib/vr-pack module (also used by the Phase-7 ingest). A cached
// pack is served as-is until it ages past PACK_TTL_MS, then rebuilt on read.
const PACK_TTL_MS = 6 * 60 * 60 * 1000; // 6h

// ── Small helpers ────────────────────────────────────────────────────────────
function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: {
      "content-type": "application/json",
      // Public record: fine to cache briefly at the edge/browser. Kept short so
      // corrections propagate quickly; the client also caches in-memory + SW.
      "cache-control": "public, max-age=60",
    },
  });
}

// Trim + hard-cap an incoming string; "" for anything non-string.
function clean(v: unknown, max: number): string {
  if (typeof v !== "string") return "";
  return v.trim().slice(0, max);
}

// True only for a key that exists in the shipped ISSUE_MAP allow-list.
function assertIssueKey(key: string): boolean {
  return ISSUE_KEYS.has(key);
}

// Parse a date query param into a Date, or null when absent/invalid.
function parseDate(v: string | null): Date | null {
  const s = clean(v, 40);
  if (!s) return null;
  const d = new Date(s);
  return isNaN(d.getTime()) ? null : d;
}

// The normalized filter set shared by /member and /issue.
type Filters = {
  issue: string; // "" when none; guaranteed valid when non-empty
  chamber: string;
  actionType: string;
  position: string;
  result: string;
  q: string;
  from: Date | null;
  to: Date | null;
  hideProcedural: boolean;
  sort: string; // 'date' | 'date_asc' | 'bill'
  page: number; // 1-indexed
  pageSize: number;
};

// Read + normalize every filter/sort/pagination param off the URL. Returns either
// the Filters object or an { error, status } the router turns into a 4xx.
function parseFilters(url: URL): Filters | { error: string; status: number } {
  const issueRaw = clean(url.searchParams.get("issue"), ID_MAX);
  if (issueRaw && !assertIssueKey(issueRaw)) {
    return { error: `Unknown issue key: ${issueRaw}`, status: 400 };
  }

  const chamber = clean(url.searchParams.get("chamber"), 16).toLowerCase();
  if (chamber && !["house", "senate", "joint", "court"].includes(chamber)) {
    return { error: `Invalid chamber: ${chamber}`, status: 400 };
  }

  const proceduralParam = clean(url.searchParams.get("procedural"), 8).toLowerCase();
  const hideProcedural = proceduralParam === "0" || proceduralParam === "false";

  const sortParam = clean(url.searchParams.get("sort"), 16).toLowerCase();
  const sort = ["date", "date_asc", "bill"].includes(sortParam) ? sortParam : "date";

  let pageSize = parseInt(clean(url.searchParams.get("pageSize"), 8), 10);
  if (!Number.isFinite(pageSize) || pageSize <= 0) pageSize = PAGE_SIZE_DEFAULT;
  pageSize = Math.min(pageSize, PAGE_SIZE_MAX);

  let page = parseInt(clean(url.searchParams.get("page"), 8), 10);
  if (!Number.isFinite(page) || page < 1) page = 1;

  return {
    issue: issueRaw,
    chamber,
    actionType: clean(url.searchParams.get("actionType"), 32).toLowerCase(),
    position: clean(url.searchParams.get("position"), 32).toLowerCase(),
    result: clean(url.searchParams.get("result"), 32).toLowerCase(),
    q: clean(url.searchParams.get("q"), Q_MAX),
    from: parseDate(url.searchParams.get("from")),
    to: parseDate(url.searchParams.get("to")),
    hideProcedural,
    sort,
    page,
    pageSize,
  };
}

// A single normalized record item — the same shape whether it came from a roll-call
// vote or a non-roll-call position. Stance-vs-record verdicts are NOT computed here
// (that needs the client-side stance data); the client derives them from `issues`
// (which carries `supportMeaning`) in Phase 2.
type RecordItem = {
  kind: "vote" | "position";
  measureId: number;
  measureType: string;
  number: string | null;
  title: string;
  chamber: string | null;
  status: string;
  date: string | null; // ISO
  action: string | null; // roll-call question, or a position action label
  actionType: string;
  position: string; // 'yea'|'nay'|... for votes; the action type for positions
  result: string | null; // votes only
  isParty: string | null; // votes only
  supports: boolean | null; // positions only
  isProcedural: boolean;
  isAmendment: boolean;
  parentMeasureId: number | null;
  rollcallId: number | null;
  issues: Array<{
    issueKey: string;
    weight: number;
    isPrimary: boolean;
    supportMeaning: string;
    rationale: string | null;
  }>;
  source: { url: string; label: string | null };
};

// Fetch every measure_issues row for a set of measure ids, validate each key
// against the allow-list (defensive — a stray key never reaches the client), and
// return a map: measureId -> issue array.
async function loadIssuesByMeasure(
  measureIds: number[]
): Promise<Map<number, RecordItem["issues"]>> {
  const map = new Map<number, RecordItem["issues"]>();
  if (!measureIds.length) return map;
  const rows = await db
    .select()
    .from(vrMeasureIssues)
    .where(inArray(vrMeasureIssues.measureId, measureIds));
  for (const r of rows) {
    if (!assertIssueKey(r.issueKey)) continue; // skip unknown keys
    const list = map.get(r.measureId) ?? [];
    list.push({
      issueKey: r.issueKey,
      weight: r.weight,
      isPrimary: r.isPrimary,
      supportMeaning: r.supportMeaning,
      rationale: r.rationale,
    });
    map.set(r.measureId, list);
  }
  // Primary issue first, then by descending weight, for stable client rendering.
  for (const list of map.values()) {
    list.sort((a, b) => Number(b.isPrimary) - Number(a.isPrimary) || b.weight - a.weight);
  }
  return map;
}

// Merge fetched vote rows + position rows into normalized RecordItems, attach their
// issues, drop anything without a source (verifiability), then sort.
function assembleRecordItems(
  voteRows: any[],
  positionRows: any[],
  issuesByMeasure: Map<number, RecordItem["issues"]>,
  sort: string
): RecordItem[] {
  const items: RecordItem[] = [];

  for (const v of voteRows) {
    if (!v.rcSourceUrl) continue; // no source → never emitted
    items.push({
      kind: "vote",
      measureId: v.measureId,
      measureType: v.measureType,
      number: v.number,
      title: v.title,
      chamber: v.chamber,
      status: v.status,
      date: v.voteDate ? new Date(v.voteDate).toISOString() : null,
      action: v.question,
      actionType: v.actionType,
      position: v.position,
      result: v.result,
      isParty: v.isParty,
      supports: null,
      isProcedural: PROCEDURAL_TYPES.includes(v.actionType),
      isAmendment: v.measureType === "amendment",
      parentMeasureId: v.parentId ?? null,
      rollcallId: v.rollcallId,
      issues: issuesByMeasure.get(v.measureId) ?? [],
      source: { url: v.rcSourceUrl, label: v.rcSourceLabel },
    });
  }

  for (const p of positionRows) {
    if (!p.posSourceUrl) continue; // no source → never emitted
    items.push({
      kind: "position",
      measureId: p.measureId,
      measureType: p.measureType,
      number: p.number,
      title: p.title,
      chamber: p.chamber,
      status: p.status,
      date: p.actedAt ? new Date(p.actedAt).toISOString() : null,
      action: p.actionType,
      actionType: p.actionType,
      position: p.actionType,
      result: null,
      isParty: null,
      supports: p.supports,
      isProcedural: false,
      isAmendment: p.measureType === "amendment",
      parentMeasureId: p.parentId ?? null,
      rollcallId: null,
      issues: issuesByMeasure.get(p.measureId) ?? [],
      source: { url: p.posSourceUrl, label: p.posSourceLabel ?? null },
    });
  }

  const byDateDesc = (a: RecordItem, b: RecordItem) =>
    (b.date ?? "").localeCompare(a.date ?? "");
  if (sort === "date_asc") items.sort((a, b) => (a.date ?? "").localeCompare(b.date ?? ""));
  else if (sort === "bill") items.sort((a, b) => (a.number ?? "").localeCompare(b.number ?? "", undefined, { numeric: true }));
  else items.sort(byDateDesc); // default: newest first

  return items;
}

// Build the WHERE conditions for a member's roll-call votes from the filters. When
// an issue filter is present it constrains to measures mapped to that issue via a
// subquery on vr_measure_issues (indexed on issue_key).
function buildMemberQuery(politicianId: string, f: Filters) {
  const conds: any[] = [eq(vrMemberVotes.politicianId, politicianId)];
  if (f.chamber) conds.push(eq(vrRollcalls.chamber, f.chamber));
  if (f.actionType) conds.push(eq(vrRollcalls.actionType, f.actionType));
  if (f.position) conds.push(eq(vrMemberVotes.position, f.position));
  if (f.result) conds.push(eq(vrRollcalls.result, f.result));
  if (f.from) conds.push(gte(vrRollcalls.voteDate, f.from));
  if (f.to) conds.push(lte(vrRollcalls.voteDate, f.to));
  if (f.hideProcedural) conds.push(notInArray(vrRollcalls.actionType, PROCEDURAL_TYPES));
  if (f.q) conds.push(or(ilike(vrMeasures.title, `%${f.q}%`), ilike(vrMeasures.number, `%${f.q}%`)));
  if (f.issue) {
    conds.push(
      inArray(
        vrMeasures.id,
        db
          .select({ id: vrMeasureIssues.measureId })
          .from(vrMeasureIssues)
          .where(eq(vrMeasureIssues.issueKey, f.issue))
      )
    );
  }
  return and(...conds);
}

// The columns pulled for a vote row (join member_votes → rollcalls → measures).
const VOTE_COLUMNS = {
  measureId: vrMeasures.id,
  measureType: vrMeasures.measureType,
  number: vrMeasures.number,
  title: vrMeasures.title,
  parentId: vrMeasures.parentId,
  status: vrMeasures.status,
  rollcallId: vrRollcalls.id,
  chamber: vrRollcalls.chamber,
  voteDate: vrRollcalls.voteDate,
  question: vrRollcalls.question,
  actionType: vrRollcalls.actionType,
  result: vrRollcalls.result,
  rcSourceUrl: vrRollcalls.sourceUrl,
  rcSourceLabel: vrRollcalls.sourceLabel,
  position: vrMemberVotes.position,
  isParty: vrMemberVotes.isParty,
} as const;

// The columns pulled for a position row (join positions → measures).
const POSITION_COLUMNS = {
  measureId: vrMeasures.id,
  measureType: vrMeasures.measureType,
  number: vrMeasures.number,
  title: vrMeasures.title,
  parentId: vrMeasures.parentId,
  status: vrMeasures.status,
  chamber: vrMeasures.chamber,
  actionType: vrPositions.actionType,
  supports: vrPositions.supports,
  actedAt: vrPositions.actedAt,
  posSourceUrl: vrPositions.sourceUrl,
  posSourceLabel: vrMeasures.sourceLabel,
} as const;

// Paginate an already-sorted list; return the slice + pagination meta.
function paginate<T>(items: T[], page: number, pageSize: number) {
  const total = items.length;
  const start = (page - 1) * pageSize;
  const slice = items.slice(start, start + pageSize);
  return {
    items: slice,
    page,
    pageSize,
    total,
    totalPages: Math.max(1, Math.ceil(total / pageSize)),
    hasMore: start + pageSize < total,
  };
}

// ── GET /member/:politicianId ────────────────────────────────────────────────
async function getMember(politicianId: string, url: URL): Promise<Response> {
  const f = parseFilters(url);
  if ("error" in f) return json({ error: f.error }, f.status);
  return json(await assembleMemberPayload(politicianId, f));
}

// Run a member's record query for the given filters and shape the response object
// (shared by GET /member/:id and the offline pack builder).
async function assembleMemberPayload(politicianId: string, f: Filters) {
  // Roll-call votes (filtered in SQL, capped), plus this member's positions.
  const voteRows = await db
    .select(VOTE_COLUMNS)
    .from(vrMemberVotes)
    .innerJoin(vrRollcalls, eq(vrMemberVotes.rollcallId, vrRollcalls.id))
    .innerJoin(vrMeasures, eq(vrRollcalls.measureId, vrMeasures.id))
    .where(buildMemberQuery(politicianId, f))
    .orderBy(desc(vrRollcalls.voteDate))
    .limit(FETCH_CAP);

  // Positions carry no roll call; apply the issue/chamber/date/text filters that
  // still make sense. actionType/position/result/procedural are vote concepts, so
  // when any of those vote-specific filters is set we omit positions entirely.
  let positionRows: any[] = [];
  const positionsApplicable = !f.actionType && !f.position && !f.result && !f.hideProcedural;
  if (positionsApplicable) {
    const pConds: any[] = [eq(vrPositions.politicianId, politicianId)];
    if (f.chamber) pConds.push(eq(vrMeasures.chamber, f.chamber));
    if (f.from) pConds.push(gte(vrPositions.actedAt, f.from));
    if (f.to) pConds.push(lte(vrPositions.actedAt, f.to));
    if (f.q) pConds.push(or(ilike(vrMeasures.title, `%${f.q}%`), ilike(vrMeasures.number, `%${f.q}%`)));
    if (f.issue) {
      pConds.push(
        inArray(
          vrMeasures.id,
          db
            .select({ id: vrMeasureIssues.measureId })
            .from(vrMeasureIssues)
            .where(eq(vrMeasureIssues.issueKey, f.issue))
        )
      );
    }
    positionRows = await db
      .select(POSITION_COLUMNS)
      .from(vrPositions)
      .innerJoin(vrMeasures, eq(vrPositions.measureId, vrMeasures.id))
      .where(and(...pConds))
      .limit(FETCH_CAP);
  }

  const measureIds = [
    ...new Set([...voteRows.map((r) => r.measureId), ...positionRows.map((r) => r.measureId)]),
  ];
  const issuesByMeasure = await loadIssuesByMeasure(measureIds);
  const all = assembleRecordItems(voteRows, positionRows, issuesByMeasure, f.sort);

  // Summary strip: totals + a with-party tally (from the fetched votes) so the
  // client can render the header without a second call.
  const votesOnly = all.filter((i) => i.kind === "vote");
  const withParty = votesOnly.filter((i) => i.isParty === "with_party").length;
  const againstParty = votesOnly.filter((i) => i.isParty === "against_party").length;

  const paged = paginate(all, f.page, f.pageSize);
  return {
    politicianId,
    filters: {
      issue: f.issue || null,
      chamber: f.chamber || null,
      actionType: f.actionType || null,
      position: f.position || null,
      result: f.result || null,
      q: f.q || null,
      from: f.from ? f.from.toISOString() : null,
      to: f.to ? f.to.toISOString() : null,
      hideProcedural: f.hideProcedural,
      sort: f.sort,
    },
    summary: {
      totalRecords: all.length,
      votes: votesOnly.length,
      positions: all.length - votesOnly.length,
      withParty,
      againstParty,
    },
    ...paged,
  };
}

// ── GET /member/:politicianId/pack ───────────────────────────────────────────
// Serve the compact offline pack with an ETag so the SW and browser can
// revalidate cheaply. The pack shape + build live in netlify/lib/vr-pack (shared
// with the Phase-7 ingest, which pre-writes packs), so read and ingest can never
// disagree. Served fresh from cache when recent; rebuilt (and re-cached) when
// stale or missing.
async function getMemberPack(politicianId: string, req: Request): Promise<Response> {
  let pack: any = await getCachedPack(politicianId);
  if (!pack || !pack.generatedAt || Date.now() - new Date(pack.generatedAt).getTime() >= PACK_TTL_MS) {
    pack = await writeMemberPack(politicianId);
  }

  // Weak ETag over the generation time + record count — cheap and good enough for
  // revalidation (the pack only changes when it is rebuilt).
  const etag = `W/"vrpack-${politicianId}-${pack.generatedAt}-${pack.summary?.totalRecords ?? 0}"`;
  if ((req.headers.get("if-none-match") || "") === etag) {
    return new Response(null, {
      status: 304,
      headers: { etag, "cache-control": "public, max-age=300" },
    });
  }
  return new Response(JSON.stringify(pack), {
    status: 200,
    headers: {
      "content-type": "application/json",
      "cache-control": "public, max-age=300",
      etag,
    },
  });
}

// ── GET /issue/:issueKey ─────────────────────────────────────────────────────
// Every member's votes/positions on one issue — powers the Stance Library rollup.
async function getIssue(issueKey: string, url: URL): Promise<Response> {
  // 400 (not 404) for an unknown key: it is a client error, it matches how the
  // /member `issue=` filter is validated, and — unlike a 404 — it does not trigger
  // Netlify's function-404 fallthrough to the static/SPA routes.
  if (!assertIssueKey(issueKey)) return json({ error: `Unknown issue key: ${issueKey}` }, 400);
  const f = parseFilters(url);
  if ("error" in f) return json({ error: f.error }, f.status);

  const measureIdRows = await db
    .select({ id: vrMeasureIssues.measureId })
    .from(vrMeasureIssues)
    .where(eq(vrMeasureIssues.issueKey, issueKey));
  const measureIds = measureIdRows.map((r) => r.id);
  if (!measureIds.length) {
    return json({ issueKey, byPolitician: {}, ...paginate([], f.page, f.pageSize) });
  }

  const vConds: any[] = [inArray(vrRollcalls.measureId, measureIds)];
  if (f.chamber) vConds.push(eq(vrRollcalls.chamber, f.chamber));
  if (f.position) vConds.push(eq(vrMemberVotes.position, f.position));
  if (f.from) vConds.push(gte(vrRollcalls.voteDate, f.from));
  if (f.to) vConds.push(lte(vrRollcalls.voteDate, f.to));
  if (f.hideProcedural) vConds.push(notInArray(vrRollcalls.actionType, PROCEDURAL_TYPES));

  const voteRows = await db
    .select({ ...VOTE_COLUMNS, politicianId: vrMemberVotes.politicianId })
    .from(vrMemberVotes)
    .innerJoin(vrRollcalls, eq(vrMemberVotes.rollcallId, vrRollcalls.id))
    .innerJoin(vrMeasures, eq(vrRollcalls.measureId, vrMeasures.id))
    .where(and(...vConds))
    .orderBy(desc(vrRollcalls.voteDate))
    .limit(FETCH_CAP);

  const posRows = await db
    .select({ ...POSITION_COLUMNS, politicianId: vrPositions.politicianId })
    .from(vrPositions)
    .innerJoin(vrMeasures, eq(vrPositions.measureId, vrMeasures.id))
    .where(inArray(vrPositions.measureId, measureIds))
    .limit(FETCH_CAP);

  const issuesByMeasure = await loadIssuesByMeasure(measureIds);
  const all = assembleRecordItems(voteRows, posRows, issuesByMeasure, f.sort);
  // Re-attach politicianId (assembleRecordItems is politician-agnostic).
  const items = all.map((it) => ({
    ...it,
    politicianId:
      it.kind === "vote"
        ? voteRows.find((r) => r.rollcallId === it.rollcallId && r.measureId === it.measureId)?.politicianId ?? null
        : posRows.find((r) => r.measureId === it.measureId)?.politicianId ?? null,
  }));

  // Lightweight per-politician tally the Library uses (yea/nay counts). The
  // stance-vs-record verdict itself is computed client-side (needs stance data).
  const byPolitician: Record<string, { total: number; yea: number; nay: number; other: number }> = {};
  for (const it of items) {
    const pid = (it as any).politicianId;
    if (!pid) continue;
    const b = (byPolitician[pid] ||= { total: 0, yea: 0, nay: 0, other: 0 });
    b.total++;
    if (it.position === "yea") b.yea++;
    else if (it.position === "nay") b.nay++;
    else b.other++;
  }

  return json({ issueKey, byPolitician, ...paginate(items, f.page, f.pageSize) });
}

// ── GET /measure/:measureId ──────────────────────────────────────────────────
async function getMeasure(measureId: number): Promise<Response> {
  const [measure] = await db.select().from(vrMeasures).where(eq(vrMeasures.id, measureId));
  if (!measure) return json({ error: "Measure not found" }, 404);
  if (!measure.sourceUrl) return json({ error: "Measure has no source" }, 404); // verifiability

  const issueRows = await db
    .select()
    .from(vrMeasureIssues)
    .where(eq(vrMeasureIssues.measureId, measureId));
  const issues = issueRows
    .filter((r) => assertIssueKey(r.issueKey))
    .map((r) => ({
      issueKey: r.issueKey,
      weight: r.weight,
      isPrimary: r.isPrimary,
      supportMeaning: r.supportMeaning,
      rationale: r.rationale,
    }))
    .sort((a, b) => Number(b.isPrimary) - Number(a.isPrimary) || b.weight - a.weight);

  const rollcalls = await db
    .select()
    .from(vrRollcalls)
    .where(eq(vrRollcalls.measureId, measureId))
    .orderBy(desc(vrRollcalls.voteDate));

  const rcIds = rollcalls.map((r) => r.id);
  const voteRows = rcIds.length
    ? await db.select().from(vrMemberVotes).where(inArray(vrMemberVotes.rollcallId, rcIds))
    : [];
  const votesByRollcall: Record<number, Array<{ politicianId: string; position: string; isParty: string | null }>> = {};
  for (const v of voteRows) {
    (votesByRollcall[v.rollcallId] ||= []).push({
      politicianId: v.politicianId,
      position: v.position,
      isParty: v.isParty,
    });
  }

  const positions = await db
    .select()
    .from(vrPositions)
    .where(eq(vrPositions.measureId, measureId));

  // Phase 3: the real legislative action timeline and any named omnibus provisions.
  const actions = await db
    .select()
    .from(vrMeasureActions)
    .where(eq(vrMeasureActions.measureId, measureId))
    .orderBy(vrMeasureActions.sortOrder);

  const provisionRows = await db
    .select()
    .from(vrMeasureProvisions)
    .where(eq(vrMeasureProvisions.measureId, measureId))
    .orderBy(vrMeasureProvisions.sortOrder);

  // Distributional Impact Ledger ("Who It Affects"): sourced, per-cohort exposure to
  // this measure. Additive and read-only. VERIFIABILITY — mirrors every other vr_*
  // row: an impact is only emitted when it carries BOTH a source_url and a source
  // label, and its cohort / direction / strength are validated against the known sets
  // so the client never has to guess at an unrecognised value. Wrapped defensively so
  // a measure's core detail never fails to load on account of this additive layer.
  let impactRows: (typeof vrDistributionalImpacts.$inferSelect)[] = [];
  try {
    impactRows = await db
      .select()
      .from(vrDistributionalImpacts)
      .where(eq(vrDistributionalImpacts.measureId, measureId))
      .orderBy(vrDistributionalImpacts.sortOrder);
  } catch (e) {
    console.error("distributional impacts query failed (non-fatal):", e);
  }
  const impacts = impactRows
    .filter((r) => !!r.sourceUrl && !!r.sourceLabel && IMPACT_COHORTS.has(r.cohort))
    .map((r) => ({
      cohort: r.cohort,
      provisionId: r.provisionId ?? null,
      direction: IMPACT_DIRECTIONS.has(r.direction) ? r.direction : "mixed",
      // numeric comes back as a string from pg; expose a real number (or null).
      magnitudeValue: r.magnitudeValue == null ? null : Number(r.magnitudeValue),
      magnitudeUnit: r.magnitudeUnit,
      magnitudeLabel: r.magnitudeLabel,
      metric: r.metric,
      methodology: r.methodology,
      evidenceStrength: IMPACT_STRENGTHS.has(r.evidenceStrength) ? r.evidenceStrength : "moderate",
      asOf: r.asOf ? r.asOf.toISOString() : null,
      source: { url: r.sourceUrl, label: r.sourceLabel },
    }));

  return json({
    measure: {
      id: measure.id,
      measureType: measure.measureType,
      congress: measure.congress,
      chamber: measure.chamber,
      number: measure.number,
      title: measure.title,
      shortTitle: measure.shortTitle,
      summary: measure.summary,
      status: measure.status,
      sponsorId: measure.sponsorId,
      parentId: measure.parentId,
      introducedAt: measure.introducedAt ? measure.introducedAt.toISOString() : null,
      externalIds: measure.externalIds,
      source: { url: measure.sourceUrl, label: measure.sourceLabel },
    },
    issues,
    rollcalls: rollcalls.map((rc) => ({
      id: rc.id,
      chamber: rc.chamber,
      congress: rc.congress,
      session: rc.session,
      rollNumber: rc.rollNumber,
      voteDate: rc.voteDate ? rc.voteDate.toISOString() : null,
      question: rc.question,
      actionType: rc.actionType,
      result: rc.result,
      requiredMajority: rc.requiredMajority,
      totals: rc.totals,
      source: { url: rc.sourceUrl, label: rc.sourceLabel },
      votes: votesByRollcall[rc.id] ?? [],
    })),
    positions: positions
      .filter((p) => !!p.sourceUrl)
      .map((p) => ({
        politicianId: p.politicianId,
        actionType: p.actionType,
        supports: p.supports,
        actedAt: p.actedAt ? p.actedAt.toISOString() : null,
        note: p.note,
        source: { url: p.sourceUrl, label: measure.sourceLabel },
      })),
    actions: actions.map((a) => ({
      stage: a.stage,
      chamber: a.chamber,
      actionDate: a.actionDate ? a.actionDate.toISOString() : null,
      text: a.text,
      source: { url: a.sourceUrl, label: a.sourceLabel },
    })),
    provisions: provisionRows.map((p) => ({
      id: p.id,
      label: p.label,
      description: p.description,
      // Only surface a valid issue key so the panel can safely link/tag it.
      issueKey: p.issueKey && assertIssueKey(p.issueKey) ? p.issueKey : null,
      supportMeaning: p.supportMeaning,
      source: p.sourceUrl ? { url: p.sourceUrl, label: measure.sourceLabel } : null,
    })),
    impacts,
  });
}

// ── GET /compare?members=a,b,c[&issue=key] ───────────────────────────────────
// Side-by-side: each member's record items, optionally scoped to one issue. Powers
// the Comparison view. Kept simple — per-member record arrays the client lays out.
async function getCompare(url: URL): Promise<Response> {
  const membersRaw = clean(url.searchParams.get("members"), 1024);
  const members = [
    ...new Set(
      membersRaw
        .split(",")
        .map((m) => clean(m, ID_MAX))
        .filter(Boolean)
    ),
  ].slice(0, MAX_COMPARE_MEMBERS);
  if (!members.length) return json({ error: "members query param required" }, 400);

  const issue = clean(url.searchParams.get("issue"), ID_MAX);
  if (issue && !assertIssueKey(issue)) return json({ error: `Unknown issue key: ${issue}` }, 400);

  const issueMeasureIds = issue
    ? (
        await db
          .select({ id: vrMeasureIssues.measureId })
          .from(vrMeasureIssues)
          .where(eq(vrMeasureIssues.issueKey, issue))
      ).map((r) => r.id)
    : null;

  const matrix: Record<string, RecordItem[]> = {};
  for (const pid of members) {
    const vConds: any[] = [eq(vrMemberVotes.politicianId, pid)];
    if (issueMeasureIds) {
      if (!issueMeasureIds.length) {
        matrix[pid] = [];
        continue;
      }
      vConds.push(inArray(vrRollcalls.measureId, issueMeasureIds));
    }
    const voteRows = await db
      .select(VOTE_COLUMNS)
      .from(vrMemberVotes)
      .innerJoin(vrRollcalls, eq(vrMemberVotes.rollcallId, vrRollcalls.id))
      .innerJoin(vrMeasures, eq(vrRollcalls.measureId, vrMeasures.id))
      .where(and(...vConds))
      .orderBy(desc(vrRollcalls.voteDate))
      .limit(FETCH_CAP);

    const pConds: any[] = [eq(vrPositions.politicianId, pid)];
    if (issueMeasureIds && issueMeasureIds.length) pConds.push(inArray(vrPositions.measureId, issueMeasureIds));
    const posRows = issueMeasureIds && !issueMeasureIds.length
      ? []
      : await db
          .select(POSITION_COLUMNS)
          .from(vrPositions)
          .innerJoin(vrMeasures, eq(vrPositions.measureId, vrMeasures.id))
          .where(and(...pConds))
          .limit(FETCH_CAP);

    const measureIds = [
      ...new Set([...voteRows.map((r) => r.measureId), ...posRows.map((r) => r.measureId)]),
    ];
    const issuesByMeasure = await loadIssuesByMeasure(measureIds);
    matrix[pid] = assembleRecordItems(voteRows, posRows, issuesByMeasure, "date");
  }

  return json({ members, issue: issue || null, matrix });
}

// ── GET /measures ────────────────────────────────────────────────────────────
// The Legislation / Bill library browse endpoint (Phase 1): a filterable, paginated
// list of measures rendered as compact cards. Per-measure detail (component issues +
// roll calls + votes) stays at /measure/:id. Verifiability is preserved: a measure
// without a source_url is never surfaced. Issue keys are validated against the same
// ISSUE_MAP allow-list every other route uses.
//   Query params: congress, chamber, type, status, issue, q, sort, page, pageSize.
async function getMeasures(url: URL): Promise<Response> {
  const congressRaw = clean(url.searchParams.get("congress"), 8);
  const congress = congressRaw ? parseInt(congressRaw, 10) : null;
  if (congressRaw && !Number.isFinite(congress as number)) {
    return json({ error: `Invalid congress: ${congressRaw}` }, 400);
  }

  const chamber = clean(url.searchParams.get("chamber"), 16).toLowerCase();
  if (chamber && !["house", "senate", "joint", "court"].includes(chamber)) {
    return json({ error: `Invalid chamber: ${chamber}` }, 400);
  }

  const measureType = clean(url.searchParams.get("type"), 24).toLowerCase();
  if (measureType && !["bill", "resolution", "amendment", "nomination", "litigation"].includes(measureType)) {
    return json({ error: `Invalid type: ${measureType}` }, 400);
  }

  const status = clean(url.searchParams.get("status"), 24).toLowerCase();

  const issue = clean(url.searchParams.get("issue"), ID_MAX);
  if (issue && !assertIssueKey(issue)) return json({ error: `Unknown issue key: ${issue}` }, 400);

  const q = clean(url.searchParams.get("q"), Q_MAX);

  const sortParam = clean(url.searchParams.get("sort"), 16).toLowerCase();
  const sort = ["recent", "number", "congress"].includes(sortParam) ? sortParam : "recent";

  let pageSize = parseInt(clean(url.searchParams.get("pageSize"), 8), 10);
  if (!Number.isFinite(pageSize) || pageSize <= 0) pageSize = PAGE_SIZE_DEFAULT;
  pageSize = Math.min(pageSize, PAGE_SIZE_MAX);
  let page = parseInt(clean(url.searchParams.get("page"), 8), 10);
  if (!Number.isFinite(page) || page < 1) page = 1;

  // Issue filter → restrict to measures carrying that issue key (the bridge table).
  let issueMeasureIds: number[] | null = null;
  if (issue) {
    const rows = await db
      .select({ measureId: vrMeasureIssues.measureId })
      .from(vrMeasureIssues)
      .where(eq(vrMeasureIssues.issueKey, issue));
    issueMeasureIds = [...new Set(rows.map((r) => r.measureId))];
    if (!issueMeasureIds.length) {
      return json({ items: [], page, pageSize, total: 0, totalPages: 1, hasMore: false });
    }
  }

  const conds: any[] = [];
  if (congress != null) conds.push(eq(vrMeasures.congress, congress));
  if (chamber) conds.push(eq(vrMeasures.chamber, chamber));
  if (measureType) conds.push(eq(vrMeasures.measureType, measureType));
  if (status) conds.push(eq(vrMeasures.status, status));
  if (issueMeasureIds) conds.push(inArray(vrMeasures.id, issueMeasureIds));
  if (q) {
    const like = `%${q}%`;
    conds.push(or(ilike(vrMeasures.number, like), ilike(vrMeasures.title, like), ilike(vrMeasures.summary, like)));
  }

  let rows = await db
    .select()
    .from(vrMeasures)
    .where(conds.length ? and(...conds) : undefined)
    .limit(FETCH_CAP);

  // Verifiability: never list a measure with no citable source.
  rows = rows.filter((m) => !!m.sourceUrl);

  // Sort in JS — the measure set is small, so one code path covers every sort.
  rows.sort((a, b) => {
    if (sort === "number") {
      return (a.number ?? "").localeCompare(b.number ?? "", undefined, { numeric: true });
    }
    if (sort === "congress") {
      return (b.congress ?? 0) - (a.congress ?? 0) ||
        (a.number ?? "").localeCompare(b.number ?? "", undefined, { numeric: true });
    }
    // recent (default): most-recently-updated first, then newest introduced.
    const upd = (b.updatedAt?.getTime?.() ?? 0) - (a.updatedAt?.getTime?.() ?? 0);
    if (upd !== 0) return upd;
    return (b.introducedAt?.getTime?.() ?? 0) - (a.introducedAt?.getTime?.() ?? 0);
  });

  const pageResult = paginate(rows, page, pageSize);
  const pageRows = pageResult.items;
  const pageIds = pageRows.map((m) => m.id);

  // Batch the per-card enrichments for just this page: issue tags, and roll-call /
  // recorded-vote counts (so a card can show "3 roll calls · 431 votes").
  const issuesByMeasure = await loadIssuesByMeasure(pageIds);

  const rollcalls = pageIds.length
    ? await db
        .select({ id: vrRollcalls.id, measureId: vrRollcalls.measureId })
        .from(vrRollcalls)
        .where(inArray(vrRollcalls.measureId, pageIds))
    : [];
  const rollcallCount: Record<number, number> = {};
  const rcToMeasure: Record<number, number> = {};
  for (const rc of rollcalls) {
    rollcallCount[rc.measureId] = (rollcallCount[rc.measureId] ?? 0) + 1;
    rcToMeasure[rc.id] = rc.measureId;
  }
  const rcIds = rollcalls.map((r) => r.id);
  const voteRows = rcIds.length
    ? await db.select({ rollcallId: vrMemberVotes.rollcallId }).from(vrMemberVotes).where(inArray(vrMemberVotes.rollcallId, rcIds))
    : [];
  const voteCount: Record<number, number> = {};
  for (const v of voteRows) {
    const mid = rcToMeasure[v.rollcallId];
    if (mid != null) voteCount[mid] = (voteCount[mid] ?? 0) + 1;
  }

  const items = pageRows.map((m) => {
    const issues = issuesByMeasure.get(m.id) ?? [];
    const primary = issues.find((i) => i.isPrimary) ?? issues[0] ?? null;
    return {
      id: m.id,
      measureType: m.measureType,
      number: m.number,
      title: m.title,
      shortTitle: m.shortTitle,
      summary: m.summary,
      status: m.status,
      chamber: m.chamber,
      congress: m.congress,
      introducedAt: m.introducedAt ? m.introducedAt.toISOString() : null,
      primaryIssue: primary ? primary.issueKey : null,
      issueKeys: issues.map((i) => i.issueKey),
      isOmnibus: issues.length >= 2,
      rollcallCount: rollcallCount[m.id] ?? 0,
      voteCount: voteCount[m.id] ?? 0,
      externalIds: m.externalIds,
      source: { url: m.sourceUrl, label: m.sourceLabel },
    };
  });

  return json({
    items,
    page: pageResult.page,
    pageSize: pageResult.pageSize,
    total: pageResult.total,
    totalPages: pageResult.totalPages,
    hasMore: pageResult.hasMore,
  });
}

// ── Router ───────────────────────────────────────────────────────────────────
export default async (req: Request): Promise<Response> => {
  const url = new URL(req.url);
  const path = url.pathname.replace(/^\/api\/voting-record/, "").replace(/\/+$/, "");
  const method = req.method.toUpperCase();

  if (method !== "GET") return json({ error: "Method not allowed" }, 405);

  try {
    const packMatch = path.match(/^\/member\/([^/]+)\/pack$/);
    if (packMatch) {
      const id = clean(decodeURIComponent(packMatch[1]), ID_MAX);
      if (!id) return json({ error: "Missing politician id" }, 400);
      return await getMemberPack(id, req);
    }

    const memberMatch = path.match(/^\/member\/([^/]+)$/);
    if (memberMatch) {
      const id = clean(decodeURIComponent(memberMatch[1]), ID_MAX);
      if (!id) return json({ error: "Missing politician id" }, 400);
      return await getMember(id, url);
    }

    const issueMatch = path.match(/^\/issue\/([^/]+)$/);
    if (issueMatch) {
      const key = clean(decodeURIComponent(issueMatch[1]), ID_MAX);
      if (!key) return json({ error: "Missing issue key" }, 400);
      return await getIssue(key, url);
    }

    if (path === "/measures") {
      return await getMeasures(url);
    }

    const measureMatch = path.match(/^\/measure\/(\d+)$/);
    if (measureMatch) {
      return await getMeasure(parseInt(measureMatch[1], 10));
    }

    if (path === "/compare") {
      return await getCompare(url);
    }

    return json({ error: "Not found" }, 404);
  } catch (e: any) {
    console.error("voting-record error:", e);
    return json({ error: "Server error", detail: e?.message || String(e) }, 500);
  }
};

export const config: Config = {
  path: ["/api/voting-record", "/api/voting-record/*"],
};
