// ─────────────────────────────────────────────────────────────────────────────
// Voting Record API — the read-only "what they actually do" endpoint
// ─────────────────────────────────────────────────────────────────────────────
// Serves the curated voting record (the vr_* tables) filtered, sorted and paginated
// for the client. It is the counterpart to the client-side stance data: where a
// stance is what a politician SAYS, a row here is what they DID (a roll-call vote,
// a co-sponsorship, an amicus brief). Everything is keyed to the SAME issue
// vocabulary the rest of the app uses (ISSUE_MAP issueKeys), so the client can line
// a vote up against the matching stance and derive "stance vs. record" (Phase 2).
//
// Storage is Netlify Database (managed Postgres) via Drizzle — the same stack the
// sync / community / mandate functions use. A full roll-call record is far too large
// and query-heavy to bake into the static client bundle, which is why it lives here
// and is filtered server-side.
//
// POSTURE (matches the Mandate list): read-only and PUBLIC. A roll call is public
// record, so GETs need no auth. There is no write path here — ingest/admin writes
// will be a separate, authenticated route.
//
// CORRECTIONS OVERLAY (read-only, and still no write path). Approved rows from
// vr_vote_correction_overlays are laid over member-vote cells on the way out, via
// netlify/lib/vr-corrections.ts. Every read site that emits a `position` or
// `isParty` applies it — the member payload, /issue/:key, /compare,
// /issue-records, and the offline pack in netlify/lib/vr-pack.ts — because a
// corrected cell that is right on the person file and wrong in the comparison, the
// ranking or the offline pack is worse than no correction at all. The stored cell is
// never mutated here; corrections are PROPOSED and APPROVED in
// netlify/functions/vr-corrections.mts, which is moderator-gated. A correction that
// applies is disclosed on the row (from, to, reason, source) rather than silently
// swapping a letter under the clerk link beside it.
//
// VERIFIABILITY: every measure / rollcall / position row carries a NOT NULL
// source_url (enforced by the schema). This Function additionally refuses to EMIT
// any record item that somehow lacks a source, and validates every incoming/returned
// issueKey against the shipped ISSUE_MAP allow-list (db/issue-keys.json) so a vote
// can never be surfaced under an issue the app doesn't know about.
//
// Routes (all under /api/voting-record):
//   GET /member/:politicianId   one member's record (the profile Voting Record tab)
//        query: issue, chamber, actionType, position, result, from, to,
//               q (bill text search), procedural=0|1, sort, page, pageSize
//   GET /issue/:issueKey        every member's votes/positions on one issue
//        query: chamber, position, from, to, sort, page, pageSize
//   GET /measure/:measureId     one measure + its issues, roll calls (with votes),
//                               and non-roll-call positions
//   GET /measure-ref/:sitting/:number
//                               resolve a measure's printed identity to its row —
//                               identity only. The sitting is a congress ("119")
//                               or a state session code ("2024GS"), because a bill
//                               number is only unique inside one sitting
//   GET /rollcall/:congress/:chamber/:roll
//                               resolve an official roll-call address to the measure
//                               it belongs to (identity only, no member tally). This
//                               is what lets a shared /vote/… link either open the
//                               right record or honestly 404.
//   GET /compare                ?members=a,b,c[&issue=key] side-by-side per member
//   GET /issue-records          ?issues=k1,k2 every member's record on a whole issue
//                               bundle in ONE request, de-duplicated: measure and
//                               rollcall metadata once, then a thin per-member ref
//                               list. Built for issue-first RANKING, where the caller
//                               needs the whole field at once and cannot afford one
//                               request per member (or per page).

import type { Config } from "@netlify/functions";
import { and, desc, eq, gte, ilike, inArray, lte, notInArray, or } from "drizzle-orm";
import { db } from "../../db/index.js";
import {
  vrMeasureActions,
  vrMeasureIssues,
  vrMeasureProvisions,
  vrMeasures,
  vrMemberVotes,
  vrPositions,
  vrRollcalls,
  vrDistributionalImpacts,
  vrExecActionStatus,
} from "../../db/schema.js";
import {
  loadCorrections,
  applyCorrections,
  cellValue,
} from "../lib/vr-corrections.js";
// The canonical ISSUE_MAP key allow-list, generated by scripts/gen-issue-keys.mjs.
import issueKeyData from "../../db/issue-keys.json" with { type: "json" };
// The ✒️ Executive Enactment Record vocabulary — the same file exec-record.js and
// the EER tests read. Imported rather than re-typed so the standing tokens the API
// will emit and the tokens the client knows how to render are one list, not two.
import execSummaryKeys from "../../db/exec-summary-keys.json" with { type: "json" };
// Retired → canonical politician_id (db/vr-pid-aliases.json). Applied to every
// incoming politician id so a request for an id a merge migration has already folded
// away returns the real record instead of an empty one.
import { canonicalPid } from "../lib/vr-normalize.js";
// Offline-pack build/cache lives in the shared lib (shared with the ingest path).
import { getCachedPack, writeMemberPack, mappingVersion } from "../lib/vr-pack.js";

const ISSUE_KEYS = new Set<string>((issueKeyData as { keys: string[] }).keys);

// ── Limits / defaults (defense in depth) ─────────────────────────────────────
const ID_MAX = 128; // politician id / issue key length cap
const Q_MAX = 120; // free-text search cap
const PAGE_SIZE_DEFAULT = 50;
const PAGE_SIZE_MAX = 100;
// Upper bound on how many raw rows one member/issue query pulls before merge +
// pagination. A member rarely exceeds a few hundred votes in a two-year term, so
// this comfortably covers a full record while capping worst-case memory. (A future
// optimization can push pagination fully into SQL via a UNION of votes+positions.)
const FETCH_CAP = 2000;
const MAX_COMPARE_MEMBERS = 8;
// /issue-records serves a whole issue BUNDLE (a core issue is several ISSUE_MAP keys),
// so it needs its own two limits: how many keys one request may ask for, and how many
// raw vote rows it will assemble across all of them. The row cap is higher than
// FETCH_CAP because this route deliberately spans every member rather than one, and
// the response discloses when it was hit (`truncated`) so a caller never presents a
// clipped read as a complete one.
const MAX_RANK_ISSUES = 16;
const RANK_FETCH_CAP = 8000;
// Roll-call action types the UI treats as procedural noise, hidden when the caller
// passes procedural=0.
const PROCEDURAL_TYPES = ["procedural", "motion"];

// A YEA normally advances the measure — the assumption every verdict rests on. Three
// questions INVERT it: a yea on a motion to RECOMMIT or to COMMIT sends the bill back to
// committee, and a yea on a motion to TABLE kills it. On those roll calls a yea is a vote
// AGAINST the measure, so reading it the usual way yields a backwards verdict, not just a
// weak one (down-weighting cannot fix direction). "To commit" is listed separately from
// "recommit" because the House uses the bare form for a Senate bill it has not previously
// committed — S. 1071 roll 319 is one. Orthogonal to a mapping's supportMeaning:
// this corrects the vote→measure step, not the measure→issue step. Kept byte-identical
// to yeaBlocksMeasure() in netlify/lib/vr-pack.ts so the live read path and the offline
// pack agree on every verdict.
function yeaBlocksMeasure(question: string | null | undefined): boolean {
  const q = String(question || "").toLowerCase();
  return (
    q.indexOf("recommit") !== -1 ||
    q.indexOf("to commit") !== -1 ||
    q.indexOf("to table") !== -1
  );
}

// ── Distributional Impact Ledger allow-lists (defense in depth) ──────────────
// The client renders a "Who It Affects" panel keyed off these exact values, so the
// Function only ever emits a cohort/direction/strength it recognises.
const IMPACT_COHORTS = new Set<string>([
  "working_middle",
  "small_biz_contractors",
  "large_corporations",
  "high_income_wealth",
  "government_insiders",
]);
const IMPACT_DIRECTIONS = new Set<string>(["benefit", "cost", "mixed", "neutral"]);
const IMPACT_STRENGTHS = new Set<string>(["strong", "moderate", "limited"]);

// ── Executive Enactment Record · Axis B allow-list (defense in depth) ────────
// What happened to a formal executive action AFTER it was signed or issued: in
// force, blocked, partly blocked, struck down, rescinded, superseded, expired, or
// challenged with no ruling on file. Derived from db/exec-summary-keys.json rather
// than restated here, so widening the vocabulary stays a data change.
//
// FAIL CLOSED, TWICE. A status row is emitted only when its token is one this app
// already knows how to label AND its citation survives the same source rule
// exec-record.js applies client-side (https, a document rather than a directory
// index, and not the administration describing its own order). A row that fails
// either test is dropped, never downgraded to "in force" — an action with no
// citable standing is not assumed to be operative.
const EXEC_STANDING_STATUSES = new Set<string>(
  Object.values(
    (execSummaryKeys as { buckets: { actions: { keys: Record<string, { token: string }> } } })
      .buckets.actions.keys
  ).map((k) => k.token)
);
const EXEC_REJECT_SRC: RegExp[] = [
  /^https?:\/\/[^/]+\/?$/i, // bare host — cites nothing
  /^https?:\/\/[^/]+\/presidential-actions\/?$/i, // a directory index, not a document
  /^https?:\/\/[^/]+\/briefing-room\/?$/i,
  /\/fact-sheets?\b/i, // the administration describing its own order
  /\/press-releases?\b/i,
  /\/remarks\//i,
];
function execSourceOk(url: string | null | undefined): boolean {
  if (!url) return false;
  const u = String(url).trim();
  if (!/^https:\/\//i.test(u)) return false; // https only, no protocol-relative
  return !EXEC_REJECT_SRC.some((re) => re.test(u));
}

// ── Offline pack (Netlify Blobs) ─────────────────────────────────────────────
// A compact, precomputed per-member record served at /member/:id/pack. It is what
// the PWA caches (stale-while-revalidate in the service worker) so a previously
// viewed member's record still renders with no network. Built + cached by the
// shared netlify/lib/vr-pack module (also used by the Phase-7 ingest). A cached
// pack is served as-is until it ages past PACK_TTL_MS, then rebuilt on read.
//
// PACK_TTL_MS IS ABOUT ROLL CALLS, AND ONLY ABOUT ROLL CALLS. It is how long a
// built pack may keep serving before it is rebuilt to pick up newly ingested
// VOTES. It used to double as the invalidation window for MAPPING changes too,
// which is why the pack could serve a retired mapping for six hours after a wave
// landed. It no longer carries that job: the mapping version is in the blob key
// and in the URL, so a mapping change invalidates both immediately and the TTL is
// left at six hours on purpose. Shortening it would only make the old hole
// smaller, and it would buy that with a rebuild on every member every few
// minutes. See mappingVersion() in netlify/lib/vr-pack.ts.
const PACK_TTL_MS = 6 * 60 * 60 * 1000; // 6h

// ── Small helpers ────────────────────────────────────────────────────────────
function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: {
      "content-type": "application/json",
      // Public record: fine to cache briefly at the edge/browser. Kept short so
      // corrections propagate quickly; the client also caches in-memory + SW.
      "cache-control": "public, max-age=60",
    },
  });
}

// Trim + hard-cap an incoming string; "" for anything non-string.
function clean(v: unknown, max: number): string {
  if (typeof v !== "string") return "";
  return v.trim().slice(0, max);
}

// True only for a key that exists in the shipped ISSUE_MAP allow-list.
function assertIssueKey(key: string): boolean {
  return ISSUE_KEYS.has(key);
}

// ── Query-filter allow-lists ─────────────────────────────────────────────────
// Defined once and shared by /member and /issue so the two endpoints can never
// drift apart on what they will accept.
//
// The 'executive' chamber and the executive_order | proclamation | memorandum types
// belong to the ✒️ Executive Enactment Record — the second record lane, for figures
// who cast no congressional floor votes. They are additive: widening what a caller
// may FILTER on creates no data and changes no existing response. The precedent is
// already here — measure_type 'litigation' with chamber 'court' lets a court case
// share the issue spine without pretending it is a roll call, and an executive order
// is the same shape of thing. See db/exec-action-types.json for the full vocabulary.
const CHAMBERS = ["house", "senate", "joint", "court", "executive"];
const MEASURE_TYPES = [
  "bill",
  "resolution",
  "amendment",
  "nomination",
  "litigation",
  "executive_order",
  "proclamation",
  "memorandum",
];

// Parse a date query param into a Date, or null when absent/invalid.
function parseDate(v: string | null): Date | null {
  const s = clean(v, 40);
  if (!s) return null;
  const d = new Date(s);
  return isNaN(d.getTime()) ? null : d;
}

// The normalized filter set shared by /member and /issue.
type Filters = {
  issue: string; // "" when none; guaranteed valid when non-empty
  chamber: string;
  actionType: string;
  position: string;
  result: string;
  q: string;
  from: Date | null;
  to: Date | null;
  hideProcedural: boolean;
  sort: string; // 'date' | 'date_asc' | 'bill'
  page: number; // 1-indexed
  pageSize: number;
};

// Read + normalize every filter/sort/pagination param off the URL. Returns either
// the Filters object or an { error, status } the router turns into a 4xx.
function parseFilters(url: URL): Filters | { error: string; status: number } {
  const issueRaw = clean(url.searchParams.get("issue"), ID_MAX);
  if (issueRaw && !assertIssueKey(issueRaw)) {
    return { error: `Unknown issue key: ${issueRaw}`, status: 400 };
  }

  const chamber = clean(url.searchParams.get("chamber"), 16).toLowerCase();
  if (chamber && !CHAMBERS.includes(chamber)) {
    return { error: `Invalid chamber: ${chamber}`, status: 400 };
  }

  const proceduralParam = clean(url.searchParams.get("procedural"), 8).toLowerCase();
  const hideProcedural = proceduralParam === "0" || proceduralParam === "false";

  const sortParam = clean(url.searchParams.get("sort"), 16).toLowerCase();
  const sort = ["date", "date_asc", "bill"].includes(sortParam) ? sortParam : "date";

  let pageSize = parseInt(clean(url.searchParams.get("pageSize"), 8), 10);
  if (!Number.isFinite(pageSize) || pageSize <= 0) pageSize = PAGE_SIZE_DEFAULT;
  pageSize = Math.min(pageSize, PAGE_SIZE_MAX);

  let page = parseInt(clean(url.searchParams.get("page"), 8), 10);
  if (!Number.isFinite(page) || page < 1) page = 1;

  return {
    issue: issueRaw,
    chamber,
    actionType: clean(url.searchParams.get("actionType"), 32).toLowerCase(),
    position: clean(url.searchParams.get("position"), 32).toLowerCase(),
    result: clean(url.searchParams.get("result"), 32).toLowerCase(),
    q: clean(url.searchParams.get("q"), Q_MAX),
    from: parseDate(url.searchParams.get("from")),
    to: parseDate(url.searchParams.get("to")),
    hideProcedural,
    sort,
    page,
    pageSize,
  };
}

// A single normalized record item — the same shape whether it came from a roll-call
// vote or a non-roll-call position. Stance-vs-record verdicts are NOT computed here
// (that needs the client-side stance data); the client derives them from `issues`
// (which carries `supportMeaning`) in Phase 2.
type RecordItem = {
  kind: "vote" | "position";
  measureId: number;
  measureType: string;
  number: string | null;
  title: string;
  chamber: string | null;
  status: string;
  date: string | null; // ISO
  action: string | null; // roll-call question, or a position action label
  actionType: string;
  position: string; // 'yea'|'nay'|... for votes; the action type for positions
  result: string | null; // votes only
  isParty: string | null; // votes only
  supports: boolean | null; // positions only
  isProcedural: boolean;
  // true when a yea on this roll call BLOCKS the measure (recommit / table) — the
  // stance helpers invert the vote→measure read for these.
  advanceInverted: boolean;
  isAmendment: boolean;
  parentMeasureId: number | null;
  rollcallId: number | null;
  // The (congress, session, roll number) tuple behind a vote. Carried so the
  // client can build the CANONICAL public roll-call page rather than printing
  // whatever URL the ingest stored — see receipt-cards.js `canonicalCitation`.
  congress: number | null;
  session: number | null;
  rollNumber: number | null;
  // WHICH SITTING THIS MEASURE BELONGS TO, when the tuple above cannot say it.
  // `congress` is the citation for a federal bill and is null for every state
  // one — a Utah bill belongs to a named session ("2025GS"), and bill numbers
  // are reused every session exactly the way federal ones are reused every
  // congress. Without this a reader looking at "H.B. 208" on a Utah row has no
  // way to know which H.B. 208, and a co-sponsorship row has no way to know it
  // at all (a position has no roll call, so it has no congress or session).
  //   THREE WHITELISTED KEYS, NOT THE BLOB. vr_measures.external_ids is ingest
  // provenance and holds whatever an ingest wanted to keep; only these three are
  // reader-facing facts, so only these three cross the wire. `readFrom` names
  // WHICH TEXT the issue mapping was read against (enrolled, last substitute)
  // and `readFromUrl` links it — the mapping rationale is a claim about a
  // specific version of a bill, and a claim about a version nobody can name is
  // not checkable.
  measureIdent: {
    session: string | null;
    readFrom: string | null;
    readFromUrl: string | null;
    officialTitle: string | null;
    billUrl: string | null;
  } | null;
  issues: Array<{
    issueKey: string;
    weight: number;
    isPrimary: boolean;
    supportMeaning: string;
    rationale: string | null;
  }>;
  source: { url: string; label: string | null };
  // CORRECTION DISCLOSURE (optional, present only when one applied). A corrected
  // cell says so out loud: what it was, what it is, why, and on what source. See
  // netlify/lib/vr-corrections.ts — the stored ingest value is never mutated, so
  // without this field a reader would have no way to tell that the letter shown
  // here differs from the one on the clerk page it links to.
  corrections?: Array<Record<string, unknown>>;
  // A correction whose reviewed value no longer matches the cell. NOT applied —
  // surfaced so a moderator can see the review has to be redone.
  correctionsStale?: Array<Record<string, unknown>>;
};

// ── MEASURE IDENTITY, PROJECTED ─────────────────────────────────────────────
// external_ids is a free-form provenance bag: a federal ingest files a
// billStatus package id in it, the Utah committee ingest files a session code, a
// sponsor name, the URL of the text a mapping was read against, the official
// title as the GPO prints it and the bill page. A reader needs five of those and
// no surface needs the rest, so this projects the five rather than shipping the
// bag — a whitelist, so a future ingest key cannot reach the client by accident
// just because someone added it upstream.
//
// The five split cleanly by government, and that is the point rather than an
// accident. A Utah measure has a session code and a recorded mapping-text kind
// and no GPO title; a federal measure has an official title and a congress.gov
// page and gets its sitting from `congress`. Neither government's vocabulary
// reaches the other's rows, because the keys the other side never wrote come
// back null.
//
// Returns null when none of the five is present, which is the case for the older
// federal rows the identity backfill has not reached: `congress` already answers
// "which sitting" there, and a null here is what tells the client to keep using
// it and print nothing else.
function measureIdent(externalIds: unknown): RecordItem["measureIdent"] {
  if (!externalIds || typeof externalIds !== "object") return null;
  const x = externalIds as Record<string, unknown>;
  const str = (v: unknown) => (typeof v === "string" && v.trim() ? v.trim() : null);
  const session = str(x.utahSession);
  const readFrom = str(x.mappingReadFrom);
  const readFromUrl = str(x.mappingTextUrl);
  const officialTitle = str(x.officialTitle);
  // congress.gov before the BILLSTATUS XML: both are citable and both are already
  // on file, but one of them is a page a reader can actually read.
  const billUrl = str(x.congressGovUrl) || str(x.billStatusUrl);
  if (!session && !readFrom && !readFromUrl && !officialTitle && !billUrl) return null;
  return { session, readFrom, readFromUrl, officialTitle, billUrl };
}

// Fetch every measure_issues row for a set of measure ids, validate each key
// against the allow-list (defensive — a stray key never reaches the client), and
// return a map: measureId -> issue array.
async function loadIssuesByMeasure(
  measureIds: number[]
): Promise<Map<number, RecordItem["issues"]>> {
  const map = new Map<number, RecordItem["issues"]>();
  if (!measureIds.length) return map;
  const rows = await db
    .select()
    .from(vrMeasureIssues)
    .where(inArray(vrMeasureIssues.measureId, measureIds));
  for (const r of rows) {
    if (!assertIssueKey(r.issueKey)) continue; // skip unknown keys
    const list = map.get(r.measureId) ?? [];
    list.push({
      issueKey: r.issueKey,
      weight: r.weight,
      isPrimary: r.isPrimary,
      supportMeaning: r.supportMeaning,
      rationale: r.rationale,
    });
    map.set(r.measureId, list);
  }
  // Primary issue first, then by descending weight, for stable client rendering.
  for (const list of map.values()) {
    list.sort((a, b) => Number(b.isPrimary) - Number(a.isPrimary) || b.weight - a.weight);
  }
  return map;
}

// Merge fetched vote rows + position rows into normalized RecordItems, attach their
// issues, drop anything without a source (verifiability), then sort.
function assembleRecordItems(
  voteRows: any[],
  positionRows: any[],
  issuesByMeasure: Map<number, RecordItem["issues"]>,
  sort: string
): RecordItem[] {
  const items: RecordItem[] = [];

  for (const v of voteRows) {
    if (!v.rcSourceUrl) continue; // no source → never emitted
    items.push({
      kind: "vote",
      measureId: v.measureId,
      measureType: v.measureType,
      number: v.number,
      title: v.title,
      chamber: v.chamber,
      status: v.status,
      date: v.voteDate ? new Date(v.voteDate).toISOString() : null,
      action: v.question,
      actionType: v.actionType,
      position: v.position,
      result: v.result,
      isParty: v.isParty,
      supports: null,
      isProcedural: PROCEDURAL_TYPES.includes(v.actionType),
      advanceInverted: yeaBlocksMeasure(v.question),
      isAmendment: v.measureType === "amendment",
      parentMeasureId: v.parentId ?? null,
      rollcallId: v.rollcallId,
      congress: v.congress ?? null,
      session: v.session ?? null,
      rollNumber: v.rollNumber ?? null,
      measureIdent: measureIdent(v.externalIds),
      issues: issuesByMeasure.get(v.measureId) ?? [],
      source: { url: v.rcSourceUrl, label: v.rcSourceLabel },
      // Present only when the overlay actually changed this cell (or refused to).
      ...(v.corrections ? { corrections: v.corrections } : {}),
      ...(v.correctionsStale ? { correctionsStale: v.correctionsStale } : {}),
    });
  }

  for (const p of positionRows) {
    if (!p.posSourceUrl) continue; // no source → never emitted
    items.push({
      kind: "position",
      measureId: p.measureId,
      measureType: p.measureType,
      number: p.number,
      title: p.title,
      chamber: p.chamber,
      status: p.status,
      date: p.actedAt ? new Date(p.actedAt).toISOString() : null,
      action: p.actionType,
      actionType: p.actionType,
      position: p.actionType,
      result: null,
      isParty: null,
      supports: p.supports,
      isProcedural: false,
      advanceInverted: false, // a co-sponsorship / amicus has no procedural inversion
      isAmendment: p.measureType === "amendment",
      parentMeasureId: p.parentId ?? null,
      rollcallId: null,
      // A co-sponsorship / amicus has no roll call, so it has no roll-call page.
      congress: null,
      session: null,
      rollNumber: null,
      // …which is exactly why this one matters more here than on a vote row: a
      // committee vote or a co-sponsorship has no roll call to carry a sitting,
      // so without the measure's own session code the row cannot say which
      // H.B. 208 it is.
      measureIdent: measureIdent(p.externalIds),
      issues: issuesByMeasure.get(p.measureId) ?? [],
      source: { url: p.posSourceUrl, label: p.posSourceLabel ?? null },
    });
  }

  const byDateDesc = (a: RecordItem, b: RecordItem) =>
    (b.date ?? "").localeCompare(a.date ?? "");
  if (sort === "date_asc") items.sort((a, b) => (a.date ?? "").localeCompare(b.date ?? ""));
  else if (sort === "bill") items.sort((a, b) => (a.number ?? "").localeCompare(b.number ?? "", undefined, { numeric: true }));
  else items.sort(byDateDesc); // default: newest first

  return items;
}

// Build the WHERE conditions for a member's roll-call votes from the filters. When
// an issue filter is present it constrains to measures mapped to that issue via a
// subquery on vr_measure_issues (indexed on issue_key).
// `skipPosition` exists because of the corrections overlay. The position filter is
// normally pushed into SQL, where it matches the STORED value — but once a correction
// can change the value a reader sees, an SQL-only filter is wrong in both directions:
// it keeps rows whose corrected position no longer matches, and hides rows whose
// corrected position now does. When the member has any approved correction, the
// caller drops the filter here and re-applies it AFTER the overlay instead.
function buildMemberQuery(politicianId: string, f: Filters, skipPosition = false) {
  const conds: any[] = [eq(vrMemberVotes.politicianId, politicianId)];
  if (f.chamber) conds.push(eq(vrRollcalls.chamber, f.chamber));
  if (f.actionType) conds.push(eq(vrRollcalls.actionType, f.actionType));
  if (f.position && !skipPosition) conds.push(eq(vrMemberVotes.position, f.position));
  if (f.result) conds.push(eq(vrRollcalls.result, f.result));
  if (f.from) conds.push(gte(vrRollcalls.voteDate, f.from));
  if (f.to) conds.push(lte(vrRollcalls.voteDate, f.to));
  if (f.hideProcedural) conds.push(notInArray(vrRollcalls.actionType, PROCEDURAL_TYPES));
  if (f.q) conds.push(or(ilike(vrMeasures.title, `%${f.q}%`), ilike(vrMeasures.number, `%${f.q}%`)));
  if (f.issue) {
    conds.push(
      inArray(
        vrMeasures.id,
        db
          .select({ id: vrMeasureIssues.measureId })
          .from(vrMeasureIssues)
          .where(eq(vrMeasureIssues.issueKey, f.issue))
      )
    );
  }
  return and(...conds);
}

// The columns pulled for a vote row (join member_votes → rollcalls → measures).
const VOTE_COLUMNS = {
  measureId: vrMeasures.id,
  measureType: vrMeasures.measureType,
  number: vrMeasures.number,
  title: vrMeasures.title,
  parentId: vrMeasures.parentId,
  status: vrMeasures.status,
  rollcallId: vrRollcalls.id,
  chamber: vrRollcalls.chamber,
  congress: vrRollcalls.congress,
  session: vrRollcalls.session,
  rollNumber: vrRollcalls.rollNumber,
  voteDate: vrRollcalls.voteDate,
  question: vrRollcalls.question,
  actionType: vrRollcalls.actionType,
  result: vrRollcalls.result,
  rcSourceUrl: vrRollcalls.sourceUrl,
  rcSourceLabel: vrRollcalls.sourceLabel,
  externalIds: vrMeasures.externalIds,
  position: vrMemberVotes.position,
  isParty: vrMemberVotes.isParty,
} as const;

// The columns pulled for a position row (join positions → measures).
const POSITION_COLUMNS = {
  measureId: vrMeasures.id,
  measureType: vrMeasures.measureType,
  number: vrMeasures.number,
  title: vrMeasures.title,
  parentId: vrMeasures.parentId,
  status: vrMeasures.status,
  chamber: vrMeasures.chamber,
  actionType: vrPositions.actionType,
  supports: vrPositions.supports,
  actedAt: vrPositions.actedAt,
  externalIds: vrMeasures.externalIds,
  posSourceUrl: vrPositions.sourceUrl,
  posSourceLabel: vrMeasures.sourceLabel,
} as const;

// Paginate an already-sorted list; return the slice + pagination meta.
function paginate<T>(items: T[], page: number, pageSize: number) {
  const total = items.length;
  const start = (page - 1) * pageSize;
  const slice = items.slice(start, start + pageSize);
  return {
    items: slice,
    page,
    pageSize,
    total,
    totalPages: Math.max(1, Math.ceil(total / pageSize)),
    hasMore: start + pageSize < total,
  };
}

// ── GET /member/:politicianId ────────────────────────────────────────────────
// The profile's first request, and the one a cold /p/<pid> waits on. Same
// payload and same filters as before — the only additions are revalidation
// headers, because the client now asks for this page earlier and more often
// (the head of index.html starts it before the app exists, and a back/forward
// re-asks for the same query).
//
// `stale-while-revalidate=300` lets the browser paint the record it already has
// and refresh behind the paint, instead of holding the profile on a loading
// state for a payload that is 60 seconds old. The weak ETag turns a revalidation
// into a 304 with no body, which for Chew's first page is ~60KB not sent.
//
// Honest about what it does NOT do: the ETag is computed from the assembled
// payload, so a 304 saves the transfer, not the query. It is a bandwidth and
// paint-latency win, not a database one.
async function getMember(politicianId: string, url: URL, req: Request): Promise<Response> {
  const f = parseFilters(url);
  if ("error" in f) return json({ error: f.error }, f.status);
  const body = JSON.stringify(await assembleMemberPayload(politicianId, f));
  const etag = `W/"vrm-${weakHash(body)}"`;
  const cache = "public, max-age=60, stale-while-revalidate=300";
  if ((req.headers.get("if-none-match") || "") === etag) {
    return new Response(null, { status: 304, headers: { etag, "cache-control": cache } });
  }
  return new Response(body, {
    status: 200,
    headers: { "content-type": "application/json", "cache-control": cache, etag },
  });
}

// FNV-1a over the serialized payload, plus its length. Weak by declaration: it
// is a revalidation token, not a content hash anyone stores or compares across
// versions, and any change to the payload (a correction landing, a new roll call
// ingested) changes it.
function weakHash(s: string): string {
  let h = 0x811c9dc5;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return (h >>> 0).toString(36) + "-" + s.length.toString(36);
}

// Run a member's record query for the given filters and shape the response object
// (shared by GET /member/:id and the offline pack builder).
async function assembleMemberPayload(politicianId: string, f: Filters) {
  // CORRECTIONS OVERLAY, loaded first because it changes how the query is built.
  // Approved corrections to this member's vote cells are laid over the rows on the
  // way out; the stored value is never mutated. If the overlay table is not there
  // yet, this is an empty overlay and the record reads exactly as it did before.
  const overlay = await loadCorrections([politicianId]);

  // Roll-call votes (filtered in SQL, capped), plus this member's positions.
  const voteRows = await db
    .select(VOTE_COLUMNS)
    .from(vrMemberVotes)
    .innerJoin(vrRollcalls, eq(vrMemberVotes.rollcallId, vrRollcalls.id))
    .innerJoin(vrMeasures, eq(vrRollcalls.measureId, vrMeasures.id))
    // The position filter moves out of SQL when a correction could change the value
    // it filters on — see buildMemberQuery.
    .where(buildMemberQuery(politicianId, f, !!overlay.byCell.size))
    .orderBy(desc(vrRollcalls.voteDate))
    .limit(FETCH_CAP);

  // Positions carry no roll call; apply the issue/chamber/date/text filters that
  // still make sense. actionType/position/result/procedural are vote concepts, so
  // when any of those vote-specific filters is set we omit positions entirely.
  let positionRows: any[] = [];
  const positionsApplicable = !f.actionType && !f.position && !f.result && !f.hideProcedural;
  if (positionsApplicable) {
    const pConds: any[] = [eq(vrPositions.politicianId, politicianId)];
    if (f.chamber) pConds.push(eq(vrMeasures.chamber, f.chamber));
    if (f.from) pConds.push(gte(vrPositions.actedAt, f.from));
    if (f.to) pConds.push(lte(vrPositions.actedAt, f.to));
    if (f.q) pConds.push(or(ilike(vrMeasures.title, `%${f.q}%`), ilike(vrMeasures.number, `%${f.q}%`)));
    if (f.issue) {
      pConds.push(
        inArray(
          vrMeasures.id,
          db
            .select({ id: vrMeasureIssues.measureId })
            .from(vrMeasureIssues)
            .where(eq(vrMeasureIssues.issueKey, f.issue))
        )
      );
    }
    positionRows = await db
      .select(POSITION_COLUMNS)
      .from(vrPositions)
      .innerJoin(vrMeasures, eq(vrPositions.measureId, vrMeasures.id))
      .where(and(...pConds))
      .limit(FETCH_CAP);
  }

  // Apply the overlay, then re-apply the position filter against the CORRECTED
  // value if it was dropped from SQL above. Both directions matter: a row whose
  // corrected position no longer matches leaves, and a row whose corrected position
  // now matches stays.
  let correctedVoteRows: any[] = applyCorrections(voteRows as any[], overlay, politicianId);
  if (f.position && overlay.byCell.size) {
    correctedVoteRows = correctedVoteRows.filter((r) => cellValue(r.position) === f.position);
  }

  const measureIds = [
    ...new Set([...correctedVoteRows.map((r) => r.measureId), ...positionRows.map((r) => r.measureId)]),
  ];
  const issuesByMeasure = await loadIssuesByMeasure(measureIds);
  const all = assembleRecordItems(correctedVoteRows, positionRows, issuesByMeasure, f.sort);

  // Summary strip: totals + a with-party tally (from the fetched votes) so the
  // client can render the header without a second call.
  const votesOnly = all.filter((i) => i.kind === "vote");
  const withParty = votesOnly.filter((i) => i.isParty === "with_party").length;
  const againstParty = votesOnly.filter((i) => i.isParty === "against_party").length;

  const paged = paginate(all, f.page, f.pageSize);
  return {
    politicianId,
    filters: {
      issue: f.issue || null,
      chamber: f.chamber || null,
      actionType: f.actionType || null,
      position: f.position || null,
      result: f.result || null,
      q: f.q || null,
      from: f.from ? f.from.toISOString() : null,
      to: f.to ? f.to.toISOString() : null,
      hideProcedural: f.hideProcedural,
      sort: f.sort,
    },
    summary: {
      totalRecords: all.length,
      votes: votesOnly.length,
      positions: all.length - votesOnly.length,
      withParty,
      againstParty,
      // Counts of corrected cells in this read — an inventory line, not a quality
      // score. `stale` means an approved correction did NOT apply because the cell
      // no longer holds the value it was reviewed against.
      corrected: votesOnly.filter((i: any) => i.corrections?.length).length,
      correctionsStale: votesOnly.filter((i: any) => i.correctionsStale?.length).length,
      // Disclosed so a client can say why no corrections are shown: none exist, or
      // the overlay could not be read at all (the migration has not landed yet).
      correctionsAvailable: !overlay.unavailable,
    },
    ...paged,
  };
}

// ── GET /member/:politicianId/pack[/<mappingVersion>] ────────────────────────
// Serve the compact offline pack with an ETag so the SW and browser can
// revalidate cheaply. The pack shape + build live in netlify/lib/vr-pack (shared
// with the Phase-7 ingest, which pre-writes packs), so read and ingest can never
// disagree. Served fresh from cache when recent; rebuilt (and re-cached) when
// stale or missing.
//
// ── THE VERSIONED URL, AND WHY IT IS A REDIRECT ─────────────────────────────
// Versioning the BLOB key (netlify/lib/vr-pack.ts) closes the server-side hole on
// its own: a mapping change changes the key, the new key misses, the pack is
// rebuilt. It does nothing about the copy the service worker is holding, which is
// keyed on the request URL and served stale-while-revalidate. So the URL has to
// change too, and the version has to get INTO the URL.
//
// The client cannot put it there. `fetchPack` fires on a cold profile open before
// the live read that would have told it the current version, and on the offline
// path there is no live read at all — any client-side copy of the version is a
// guess that is wrong exactly when a wave has just landed, which is the moment
// this feature exists for. So the server owns it:
//
//   GET /member/:id/pack                  → 302 → /member/:id/pack/m825-e21bb4b7021e
//   GET /member/:id/pack/m825-e21bb4b7021e → 200, the pack for that mapping
//   GET /member/:id/pack/m801-9c3f...      → 302 → the current version
//
// The client keeps asking for the unversioned URL and needs no knowledge at all
// (voting-record.js is untouched). The redirect is `no-store`, so nothing caches
// the indirection; the versioned response is what the service worker caches, under
// a URL that a mapping change makes different. A stale versioned URL — an old SW
// copy revalidating — is redirected forward rather than answered, which is how a
// device that has been offline across a wave catches up on its first success.
//
// AND WHY NOT SERVE THE REQUESTED OLD VERSION. Because its blob is unreachable by
// design and rebuilding it is impossible: the mapping it was built from is not in
// the database any more. An old version is a request for a pack that no longer
// exists, and the honest answer is the current one.
//
// OFFLINE IS THE SERVICE WORKER'S JOB, NOT THIS FUNCTION'S. Neither hop can be
// reached with no network, so sw.js answers a pack request from the newest cached
// version it holds for that member, whatever version that is. See the pack
// handler there.
const PACK_VERSION_RE = /^m[0-9]+-[a-z0-9]+$/;

async function getMemberPack(
  politicianId: string,
  req: Request,
  requestedVersion: string | null,
): Promise<Response> {
  const mv = await mappingVersion();

  // No version, or not the current one → point at the current one. A 302 (not a
  // 301) because "current" is a moving target: the next wave has to be able to
  // move it, and a permanently-cached redirect would pin a device to this wave's
  // pack for as long as its HTTP cache lives.
  if (requestedVersion !== mv) {
    // A root-relative Location, built as a string rather than through URL so the
    // already-encoded id cannot be re-encoded by the pathname setter. Same origin
    // by construction, and no query string: the pack takes no parameters, and
    // carrying one across the hop would be a second cache key for one artifact.
    const location =
      `/api/voting-record/member/${encodeURIComponent(politicianId)}/pack/${mv}`;
    return new Response(null, {
      status: 302,
      headers: {
        location,
        // The indirection itself is never cached, by anyone. It is the one thing
        // in this path that must always be re-asked, because it is the thing that
        // knows the answer changed.
        "cache-control": "no-store",
        "x-pdx-mapping-version": mv,
      },
    });
  }

  let pack: any = await getCachedPack(politicianId, mv);
  if (!pack || !pack.generatedAt || Date.now() - new Date(pack.generatedAt).getTime() >= PACK_TTL_MS) {
    pack = await writeMemberPack(politicianId, undefined, mv);
  }

  // Weak ETag over the generation time + record count — cheap and good enough for
  // revalidation (the pack only changes when it is rebuilt). The mapping version
  // is in it too, so a rebuild that changes nothing but the mapping still
  // invalidates a conditional request that somehow reached this handler with the
  // old body in hand.
  const etag = `W/"vrpack-${politicianId}-${mv}-${pack.generatedAt}-${pack.summary?.totalRecords ?? 0}"`;
  if ((req.headers.get("if-none-match") || "") === etag) {
    return new Response(null, {
      status: 304,
      headers: { etag, "cache-control": "public, max-age=300", "x-pdx-mapping-version": mv },
    });
  }
  return new Response(JSON.stringify(pack), {
    status: 200,
    headers: {
      "content-type": "application/json",
      // A versioned URL is immutable in the only sense that matters: the mapping
      // it names cannot change under it. It is still not `immutable`, because the
      // roll calls behind it can — that is what PACK_TTL_MS is for, and 300s of
      // shared caching is what it was before.
      "cache-control": "public, max-age=300",
      etag,
      "x-pdx-mapping-version": mv,
    },
  });
}

// ── GET /issue/:issueKey/impacts ─────────────────────────────────────────────
// Read-only. Net distributional summary for an ISSUE as a whole: aggregates the
// Distributional Impact Ledger rows that concern this issue, by cohort. An impact
// concerns the issue when its provision is tagged to the issue key, or (for a
// whole-measure impact with no provision) when the measure's PRIMARY issue is this
// key — so a bundled megabill contributes each impact only to the issue it actually
// touches, never to every issue it spans. Additive; same source + cohort guards as
// /measure/:id.
async function getIssueImpacts(issueKey: string): Promise<Response> {
  if (!assertIssueKey(issueKey)) return json({ error: `Unknown issue key: ${issueKey}` }, 400);

  // The ledger table is small; fetch all rows joined to their provision's issue key,
  // then attribute precisely in code.
  const rows = await db
    .select({
      measureId: vrDistributionalImpacts.measureId,
      provisionId: vrDistributionalImpacts.provisionId,
      cohort: vrDistributionalImpacts.cohort,
      direction: vrDistributionalImpacts.direction,
      sourceLabel: vrDistributionalImpacts.sourceLabel,
      sourceUrl: vrDistributionalImpacts.sourceUrl,
      provIssue: vrMeasureProvisions.issueKey,
    })
    .from(vrDistributionalImpacts)
    .leftJoin(vrMeasureProvisions, eq(vrDistributionalImpacts.provisionId, vrMeasureProvisions.id));

  const primaries = await db
    .select({ measureId: vrMeasureIssues.measureId, issueKey: vrMeasureIssues.issueKey })
    .from(vrMeasureIssues)
    .where(eq(vrMeasureIssues.isPrimary, true));
  const primaryByMeasure = new Map<number, string>();
  for (const p of primaries) primaryByMeasure.set(p.measureId, p.issueKey);

  // Only impacts that concern THIS issue, source-guarded + cohort-validated.
  const relevant = rows.filter((r) => {
    if (!r.sourceUrl || !r.sourceLabel || !IMPACT_COHORTS.has(r.cohort)) return false;
    if (r.provisionId != null) return r.provIssue === issueKey;
    return primaryByMeasure.get(r.measureId) === issueKey;
  });
  if (!relevant.length) {
    return json({ issueKey, cohortSummary: {}, cohorts: [], measures: [], sources: 0 });
  }

  const cohortSummary: Record<string, { benefit: number; cost: number; mixed: number; neutral: number }> = {};
  const measureSet = new Set<number>();
  const srcSet = new Set<string>();
  for (const r of relevant) {
    const dir = IMPACT_DIRECTIONS.has(r.direction) ? r.direction : "mixed";
    const c = (cohortSummary[r.cohort] ||= { benefit: 0, cost: 0, mixed: 0, neutral: 0 });
    (c as any)[dir]++;
    measureSet.add(r.measureId);
    srcSet.add(r.sourceLabel);
  }
  // Net direction per cohort: benefit vs cost tally (mixed when both, else the sole side).
  const cohorts = Object.keys(cohortSummary).map((k) => {
    const s = cohortSummary[k];
    let net: string;
    if (s.benefit && s.cost) net = "mixed";
    else if (s.benefit) net = "benefit";
    else if (s.cost) net = "cost";
    else net = s.mixed ? "mixed" : "neutral";
    return { cohort: k, net, benefit: s.benefit, cost: s.cost, mixed: s.mixed, neutral: s.neutral };
  });

  const measureIds = [...measureSet];
  const meta = await db
    .select({ id: vrMeasures.id, number: vrMeasures.number, title: vrMeasures.title, shortTitle: vrMeasures.shortTitle })
    .from(vrMeasures)
    .where(inArray(vrMeasures.id, measureIds));
  const measures = meta.map((m) => ({ measureId: m.id, number: m.number, title: m.shortTitle || m.title || m.number }));

  return json({ issueKey, cohortSummary, cohorts, measures, sources: srcSet.size });
}

// ── GET /issue/:issueKey ─────────────────────────────────────────────────────
// Every member's votes/positions on one issue — powers the Stance Library rollup.
async function getIssue(issueKey: string, url: URL): Promise<Response> {
  // Netlify's function-404 fallthrough to the static/SPA routes.
  if (!assertIssueKey(issueKey)) return json({ error: `Unknown issue key: ${issueKey}` }, 400);
  const f = parseFilters(url);
  if ("error" in f) return json({ error: f.error }, f.status);

  const measureIdRows = await db
    .select({ id: vrMeasureIssues.measureId })
    .from(vrMeasureIssues)
    .where(eq(vrMeasureIssues.issueKey, issueKey));
  const measureIds = measureIdRows.map((r) => r.id);
  if (!measureIds.length) {
    return json({ issueKey, byPolitician: {}, ...paginate([], f.page, f.pageSize) });
  }

  const vConds: any[] = [inArray(vrRollcalls.measureId, measureIds)];
  if (f.chamber) vConds.push(eq(vrRollcalls.chamber, f.chamber));
  // Left in SQL here, unlike the member route: this view spans every member, so
  // pre-loading the whole overlay to decide whether to drop the filter would cost
  // more than the correction can change. The overlay is still applied to the rows
  // that come back, so a corrected cell is never displayed as its stored value —
  // the only edge is a row whose CORRECTED position would newly match a position
  // filter, which this view does not claim to find.
  if (f.position) vConds.push(eq(vrMemberVotes.position, f.position));
  if (f.from) vConds.push(gte(vrRollcalls.voteDate, f.from));
  if (f.to) vConds.push(lte(vrRollcalls.voteDate, f.to));
  if (f.hideProcedural) vConds.push(notInArray(vrRollcalls.actionType, PROCEDURAL_TYPES));

  const rawVoteRows = await db
    .select({ ...VOTE_COLUMNS, politicianId: vrMemberVotes.politicianId })
    .from(vrMemberVotes)
    .innerJoin(vrRollcalls, eq(vrMemberVotes.rollcallId, vrRollcalls.id))
    .innerJoin(vrMeasures, eq(vrRollcalls.measureId, vrMeasures.id))
    .where(and(...vConds))
    .orderBy(desc(vrRollcalls.voteDate))
    .limit(FETCH_CAP);
  const voteRows = applyCorrections(
    rawVoteRows as any[],
    await loadCorrections(rawVoteRows.map((r: any) => r.politicianId))
  );

  const posRows = await db
    .select({ ...POSITION_COLUMNS, politicianId: vrPositions.politicianId })
    .from(vrPositions)
    .innerJoin(vrMeasures, eq(vrPositions.measureId, vrMeasures.id))
    .where(inArray(vrPositions.measureId, measureIds))
    .limit(FETCH_CAP);

  const issuesByMeasure = await loadIssuesByMeasure(measureIds);
  const all = assembleRecordItems(voteRows, posRows, issuesByMeasure, f.sort);
  // Re-attach politicianId (assembleRecordItems is politician-agnostic).
  const items = all.map((it) => ({
    ...it,
    politicianId:
      it.kind === "vote"
        ? voteRows.find((r) => r.rollcallId === it.rollcallId && r.measureId === it.measureId)?.politicianId ?? null
        : posRows.find((r) => r.measureId === it.measureId)?.politicianId ?? null,
  }));

  // Lightweight per-politician tally the Library uses (yea/nay counts). The
  // stance-vs-record verdict itself is computed client-side (needs stance data).
  const byPolitician: Record<string, { total: number; yea: number; nay: number; other: number }> = {};
  for (const it of items) {
    const pid = (it as any).politicianId;
    if (!pid) continue;
    const b = (byPolitician[pid] ||= { total: 0, yea: 0, nay: 0, other: 0 });
    b.total++;
    if (it.position === "yea") b.yea++;
    else if (it.position === "nay") b.nay++;
    else b.other++;
  }

  return json({ issueKey, byPolitician, ...paginate(items, f.page, f.pageSize) });
}

// ── GET /member/:politicianId/impacts ────────────────────────────────────────
// Read-only. The measures this member has a recorded vote or position on that ALSO
// carry Distributional Impact Ledger rows — the "who their key votes affect" side of
// the Follow-the-Money pairing on a profile. Additive; reuses the same source +
// cohort/direction/strength guards as GET /measure/:id, so it never emits an impact
// without a source. Returns only measures that actually have ledger data.
async function getMemberImpacts(politicianId: string): Promise<Response> {
  // Measures this member has a recorded vote on (keep the rollcall action type so a
  // passage vote is preferred for the displayed position), plus non-roll-call positions.
  const voteRows = await db
    .select({
      measureId: vrRollcalls.measureId,
      position: vrMemberVotes.position,
      actionType: vrRollcalls.actionType,
    })
    .from(vrMemberVotes)
    .innerJoin(vrRollcalls, eq(vrMemberVotes.rollcallId, vrRollcalls.id))
    .where(eq(vrMemberVotes.politicianId, politicianId))
    .limit(FETCH_CAP);

  const posRows = await db
    .select({ measureId: vrPositions.measureId, actionType: vrPositions.actionType })
    .from(vrPositions)
    .where(eq(vrPositions.politicianId, politicianId))
    .limit(FETCH_CAP);

  const measureIds = [
    ...new Set([...voteRows.map((r) => r.measureId), ...posRows.map((r) => r.measureId)]),
  ];
  if (!measureIds.length) return json({ politicianId, measures: [], cohortSummary: {} });

  const impactRows = await db
    .select()
    .from(vrDistributionalImpacts)
    .where(inArray(vrDistributionalImpacts.measureId, measureIds))
    .orderBy(vrDistributionalImpacts.sortOrder);
  if (!impactRows.length) return json({ politicianId, measures: [], cohortSummary: {} });

  const impactedIds = [...new Set(impactRows.map((r) => r.measureId))];
  const measureMeta = await db
    .select({
      id: vrMeasures.id,
      number: vrMeasures.number,
      title: vrMeasures.title,
      shortTitle: vrMeasures.shortTitle,
      sourceUrl: vrMeasures.sourceUrl,
      sourceLabel: vrMeasures.sourceLabel,
    })
    .from(vrMeasures)
    .where(inArray(vrMeasures.id, impactedIds));
  const metaById = new Map(measureMeta.map((m) => [m.id, m]));

  // The member's displayed action per measure: prefer a passage vote, then any vote,
  // then a mapped non-roll-call position. Neutral, factual labels only.
  const VOTE_LABEL: Record<string, string> = {
    yea: "Voted Yea",
    nay: "Voted Nay",
    present: "Voted Present",
    not_voting: "Did not vote",
  };
  // Kept word-for-word in step with the act table in stance-helpers.js
  // (_ACT_CLASSES[...].label), which is what the client pill and the record-pattern
  // chip both read. The server cannot import that file — this is a hand-mirrored
  // copy, so it is the one place a drift can start. If a label changes there,
  // change it here in the same edit. Every entry is an act, none is a ballot verb:
  // "Voted" belongs to VOTE_LABEL above and appears nowhere in this map.
  const POS_LABEL: Record<string, string> = {
    sponsor: "Lead sponsor",
    cosponsor: "Co-sponsored",
    amicus: "Joined amicus brief",
    plaintiff: "Party to the case",
    committee_vote: "Committee vote",
    statement: "On-record statement",
  };
  const actionByMeasure = new Map<number, string>();
  for (const v of voteRows) {
    if (!metaById.has(v.measureId)) continue;
    const label = VOTE_LABEL[v.position] || "Voted " + v.position;
    if (v.actionType === "passage" || !actionByMeasure.has(v.measureId)) {
      actionByMeasure.set(v.measureId, label);
    }
  }
  for (const p of posRows) {
    if (!metaById.has(p.measureId)) continue;
    if (!actionByMeasure.has(p.measureId)) {
      actionByMeasure.set(p.measureId, POS_LABEL[p.actionType] || "On record");
    }
  }

  // Impacts grouped by measure — source-guarded and value-validated exactly like getMeasure.
  const byMeasure = new Map<number, any[]>();
  const cohortSummary: Record<string, { benefit: number; cost: number; mixed: number; neutral: number }> = {};
  for (const r of impactRows) {
    if (!r.sourceUrl || !r.sourceLabel || !IMPACT_COHORTS.has(r.cohort)) continue;
    const direction = IMPACT_DIRECTIONS.has(r.direction) ? r.direction : "mixed";
    const item = {
      cohort: r.cohort,
      direction,
      magnitudeValue: r.magnitudeValue == null ? null : Number(r.magnitudeValue),
      magnitudeUnit: r.magnitudeUnit,
      magnitudeLabel: r.magnitudeLabel,
      metric: r.metric,
      evidenceStrength: IMPACT_STRENGTHS.has(r.evidenceStrength) ? r.evidenceStrength : "moderate",
      asOf: r.asOf ? r.asOf.toISOString() : null,
      source: { url: r.sourceUrl, label: r.sourceLabel },
    };
    let arr = byMeasure.get(r.measureId);
    if (!arr) { arr = []; byMeasure.set(r.measureId, arr); }
    arr.push(item);
    const c = (cohortSummary[r.cohort] ||= { benefit: 0, cost: 0, mixed: 0, neutral: 0 });
    (c as any)[direction]++;
  }

  const measures = impactedIds
    .filter((id) => byMeasure.get(id) && byMeasure.get(id)!.length)
    .map((id) => {
      const meta = metaById.get(id);
      return {
        measureId: id,
        number: meta ? meta.number : null,
        title: meta ? meta.shortTitle || meta.title || meta.number : "Measure " + id,
        memberAction: actionByMeasure.get(id) || null,
        source: meta && meta.sourceUrl ? { url: meta.sourceUrl, label: meta.sourceLabel } : null,
        impacts: byMeasure.get(id),
      };
    });

  return json({ politicianId, measures, cohortSummary });
}

// ── GET /measure-ref/:sitting/:number ────────────────────────────────────────
// Resolve a measure's NATURAL key — the sitting plus the printed identifier
// ("H.R. 9311", "H.B. 257") that a shared bill link carries — to its identity row.
//
// The client already deep-links bills by congress + number; until now the only
// way to turn that pair into a measure was to page through /measures and match
// client-side, which a social scraper cannot do. This is the same resolution done
// once, server-side, returning identity only.
//
// THE FIRST SEGMENT IS A SITTING, NOT ONLY A CONGRESS. A bill number is unique
// inside one sitting of one legislature and nowhere else: "H.B. 257" names a
// different Utah bill in every general session, which is precisely why the ingest's
// uniqueness index for state rows is (chamber, number, external_ids->>'utahSession')
// rather than (congress, number). So this resolves either kind of sitting —
// "119" against `congress`, "2024GS" against the recorded session — and a state
// measure, whose congress column is NULL by design, becomes addressable for the
// first time. An empty sitting resolves only when the number is unambiguous across
// the whole archive; where it is not, the address is genuinely incomplete and
// picking one row for the reader would be a guess.
async function getMeasureRef(sitting: string, number: string): Promise<Response> {
  const wanted = number.trim();
  if (!wanted) return json({ error: "Missing measure number" }, 400);
  const sit = String(sitting || "").trim();
  const congress = /^\d+$/.test(sit) ? parseInt(sit, 10) : NaN;

  // The indexed pair first, unchanged, for the federal address this route was born
  // serving. Only when that misses is the number looked up on its own — the archive
  // holds a few hundred measures, and a state row has no congress to index on.
  let rows: (typeof vrMeasures.$inferSelect)[] = Number.isFinite(congress)
    ? await db
        .select()
        .from(vrMeasures)
        .where(and(eq(vrMeasures.congress, congress), eq(vrMeasures.number, wanted)))
        .limit(2)
    : [];
  if (!rows.some((m) => m.sourceUrl)) {
    const byNumber = await db.select().from(vrMeasures).where(eq(vrMeasures.number, wanted)).limit(40);
    const citable = byNumber.filter((m) => m.sourceUrl);
    const sessionOf = (m: typeof vrMeasures.$inferSelect) => {
      const x = m.externalIds;
      const v = x && typeof x === "object" ? (x as Record<string, unknown>).utahSession : null;
      return typeof v === "string" ? v.trim().toUpperCase() : "";
    };
    rows = sit
      ? citable.filter((m) =>
          Number.isFinite(congress) ? m.congress === congress : sessionOf(m) === sit.toUpperCase()
        )
      : citable.length === 1
        ? citable
        : [];
  }

  const measure = rows.find((m) => m.sourceUrl);
  if (!measure) return json({ error: "Measure not found" }, 404);

  return json({
    measure: {
      id: measure.id,
      measureType: measure.measureType,
      congress: measure.congress,
      // The sitting for a row that has no congress, projected through the same
      // whitelist the record items use. A caller that has to build the measure's
      // address back — a share card, a canonical link — cannot do it from a null.
      session: measureIdent(measure.externalIds)?.session ?? null,
      chamber: measure.chamber,
      number: measure.number,
      title: measure.title,
      shortTitle: measure.shortTitle,
      status: measure.status,
      sourceUrl: measure.sourceUrl,
    },
  });
}

// ── GET /rollcall/:congress/:chamber/:roll ───────────────────────────────────
// Resolve an OFFICIAL roll-call address — the chamber/congress/number triple that
// clerk.house.gov and senate.gov print, and the one a /vote/… share link carries —
// to the measure it belongs to.
//
// This exists so a shared /vote/119/house/190 link can be answered truthfully by
// the edge before any JavaScript runs: either this returns the roll call and the
// link opens that measure, or it returns 404 and the link says so. It deliberately
// returns identity only (what was voted on, when, how it came out) and NOT the
// member-by-member tally — a preview needs an address, not a scoreboard, and the
// full detail is one request away at /measure/:id.
async function getRollcall(
  congress: number,
  chamber: string,
  rollNumber: number
): Promise<Response> {
  const [rc] = await db
    .select()
    .from(vrRollcalls)
    .where(
      and(
        eq(vrRollcalls.chamber, chamber),
        eq(vrRollcalls.congress, congress),
        eq(vrRollcalls.rollNumber, rollNumber)
      )
    )
    .orderBy(desc(vrRollcalls.voteDate));
  if (!rc) return json({ error: "Roll call not found" }, 404);
  // VERIFIABILITY: the same rule the rest of this Function follows — nothing is
  // emitted that a reader cannot go and check for themselves.
  if (!rc.sourceUrl) return json({ error: "Roll call has no source" }, 404);

  const [measure] = await db.select().from(vrMeasures).where(eq(vrMeasures.id, rc.measureId));
  if (!measure || !measure.sourceUrl) return json({ error: "Measure not found" }, 404);

  return json({
    rollcall: {
      id: rc.id,
      chamber: rc.chamber,
      congress: rc.congress,
      session: rc.session,
      rollNumber: rc.rollNumber,
      voteDate: rc.voteDate,
      question: rc.question,
      actionType: rc.actionType,
      result: rc.result,
      totals: rc.totals,
      sourceUrl: rc.sourceUrl,
      sourceLabel: rc.sourceLabel,
    },
    measure: {
      id: measure.id,
      measureType: measure.measureType,
      congress: measure.congress,
      chamber: measure.chamber,
      number: measure.number,
      title: measure.title,
      shortTitle: measure.shortTitle,
      status: measure.status,
      sourceUrl: measure.sourceUrl,
    },
  });
}

// ── GET /measure/:measureId ──────────────────────────────────────────────────
async function getMeasure(measureId: number): Promise<Response> {
  const [measure] = await db.select().from(vrMeasures).where(eq(vrMeasures.id, measureId));
  if (!measure) return json({ error: "Measure not found" }, 404);
  if (!measure.sourceUrl) return json({ error: "Measure has no source" }, 404); // verifiability

  const issueRows = await db
    .select()
    .from(vrMeasureIssues)
    .where(eq(vrMeasureIssues.measureId, measureId));
  const issues = issueRows
    .filter((r) => assertIssueKey(r.issueKey))
    .map((r) => ({
      issueKey: r.issueKey,
      weight: r.weight,
      isPrimary: r.isPrimary,
      supportMeaning: r.supportMeaning,
      rationale: r.rationale,
    }))
    .sort((a, b) => Number(b.isPrimary) - Number(a.isPrimary) || b.weight - a.weight);

  const rollcalls = await db
    .select()
    .from(vrRollcalls)
    .where(eq(vrRollcalls.measureId, measureId))
    .orderBy(desc(vrRollcalls.voteDate));

  const rcIds = rollcalls.map((r) => r.id);
  const voteRows = rcIds.length
    ? await db.select().from(vrMemberVotes).where(inArray(vrMemberVotes.rollcallId, rcIds))
    : [];
  const votesByRollcall: Record<number, Array<{ politicianId: string; position: string; isParty: string | null }>> = {};
  for (const v of voteRows) {
    (votesByRollcall[v.rollcallId] ||= []).push({
      politicianId: v.politicianId,
      position: v.position,
      isParty: v.isParty,
    });
  }

  const positions = await db
    .select()
    .from(vrPositions)
    .where(eq(vrPositions.measureId, measureId));

  // ── Executive Enactment Record · Axis B: what happened afterwards ──────────
  // vr_exec_action_status is an APPEND-ONLY log: one row per standing CHANGE, each
  // carrying its own citation, never an UPDATE. So the whole history is served, not
  // just the latest row — an order that was in force, then partly blocked, then
  // partly restored is three sourced facts, and collapsing it to the last one throws
  // away the two the reader most needs to judge it.
  //
  // "Current" is the latest CITABLE entry by effective_at, matching exec-record.js's
  // standingOf() exactly so the API and the client cannot disagree about where an
  // action stands. An undated row sorts as the oldest and can still be current only
  // when it is the only one — deliberately, since a change we cannot date cannot be
  // proved to have superseded a dated one.
  //
  // Wrapped defensively like the impact ledger: this layer is additive, and a measure
  // must never fail to load on its account.
  const positionIds = positions.map((p) => p.id);
  let standingRows: (typeof vrExecActionStatus.$inferSelect)[] = [];
  try {
    standingRows = positionIds.length
      ? await db
          .select()
          .from(vrExecActionStatus)
          .where(inArray(vrExecActionStatus.positionId, positionIds))
          .orderBy(vrExecActionStatus.effectiveAt)
      : [];
  } catch (e) {
    console.error("exec action standing query failed (non-fatal):", e);
  }
  type StandingEntry = {
    status: string;
    effectiveAt: string | null;
    authority: string;
    note: string;
    source: { url: string; label: string };
  };
  const standingByPosition: Record<number, StandingEntry[]> = {};
  for (const r of standingRows) {
    if (!EXEC_STANDING_STATUSES.has(r.status)) continue;
    if (!execSourceOk(r.sourceUrl) || !r.sourceLabel || !r.sourceLabel.trim()) continue;
    (standingByPosition[r.positionId] ||= []).push({
      status: r.status,
      effectiveAt: r.effectiveAt ? r.effectiveAt.toISOString() : null,
      authority: r.authority || "",
      note: r.note || "",
      source: { url: r.sourceUrl, label: r.sourceLabel },
    });
  }
  // Oldest → newest, so the client can render the log in the order it happened.
  for (const id of Object.keys(standingByPosition)) {
    standingByPosition[Number(id)].sort(
      (a, b) => (Date.parse(a.effectiveAt || "") || 0) - (Date.parse(b.effectiveAt || "") || 0)
    );
  }

  // Phase 3: the real legislative action timeline and any named omnibus provisions.
  const actions = await db
    .select()
    .from(vrMeasureActions)
    .where(eq(vrMeasureActions.measureId, measureId))
    .orderBy(vrMeasureActions.sortOrder);

  const provisionRows = await db
    .select()
    .from(vrMeasureProvisions)
    .where(eq(vrMeasureProvisions.measureId, measureId))
    .orderBy(vrMeasureProvisions.sortOrder);

  // Distributional Impact Ledger ("Who It Affects"): sourced, per-cohort exposure to
  // this measure. Additive and read-only. VERIFIABILITY — mirrors every other vr_*
  // row: an impact is only emitted when it carries BOTH a source_url and a source
  // label, and its cohort / direction / strength are validated against the known sets
  // so the client never has to guess at an unrecognised value. Wrapped defensively so
  // a measure's core detail never fails to load on account of this additive layer.
  let impactRows: (typeof vrDistributionalImpacts.$inferSelect)[] = [];
  try {
    impactRows = await db
      .select()
      .from(vrDistributionalImpacts)
      .where(eq(vrDistributionalImpacts.measureId, measureId))
      .orderBy(vrDistributionalImpacts.sortOrder);
  } catch (e) {
    console.error("distributional impacts query failed (non-fatal):", e);
  }
  const impacts = impactRows
    .filter((r) => !!r.sourceUrl && !!r.sourceLabel && IMPACT_COHORTS.has(r.cohort))
    .map((r) => ({
      cohort: r.cohort,
      provisionId: r.provisionId ?? null,
      direction: IMPACT_DIRECTIONS.has(r.direction) ? r.direction : "mixed",
      // numeric comes back as a string from pg; expose a real number (or null).
      magnitudeValue: r.magnitudeValue == null ? null : Number(r.magnitudeValue),
      magnitudeUnit: r.magnitudeUnit,
      magnitudeLabel: r.magnitudeLabel,
      metric: r.metric,
      methodology: r.methodology,
      evidenceStrength: IMPACT_STRENGTHS.has(r.evidenceStrength) ? r.evidenceStrength : "moderate",
      asOf: r.asOf ? r.asOf.toISOString() : null,
      source: { url: r.sourceUrl, label: r.sourceLabel },
    }));

  return json({
    measure: {
      id: measure.id,
      measureType: measure.measureType,
      congress: measure.congress,
      chamber: measure.chamber,
      number: measure.number,
      title: measure.title,
      shortTitle: measure.shortTitle,
      summary: measure.summary,
      status: measure.status,
      sponsorId: measure.sponsorId,
      parentId: measure.parentId,
      introducedAt: measure.introducedAt ? measure.introducedAt.toISOString() : null,
      externalIds: measure.externalIds,
      source: { url: measure.sourceUrl, label: measure.sourceLabel },
    },
    issues,
    rollcalls: rollcalls.map((rc) => ({
      id: rc.id,
      chamber: rc.chamber,
      congress: rc.congress,
      session: rc.session,
      rollNumber: rc.rollNumber,
      voteDate: rc.voteDate ? rc.voteDate.toISOString() : null,
      question: rc.question,
      actionType: rc.actionType,
      result: rc.result,
      requiredMajority: rc.requiredMajority,
      totals: rc.totals,
      source: { url: rc.sourceUrl, label: rc.sourceLabel },
      votes: votesByRollcall[rc.id] ?? [],
    })),
    positions: positions
      .filter((p) => !!p.sourceUrl)
      .map((p) => {
        const history = standingByPosition[p.id] || [];
        return {
          politicianId: p.politicianId,
          actionType: p.actionType,
          supports: p.supports,
          actedAt: p.actedAt ? p.actedAt.toISOString() : null,
          note: p.note,
          source: { url: p.sourceUrl, label: measure.sourceLabel },
          // Axis B. Empty array + null current when nothing citable is on file —
          // an honest "we do not know", never an implied "in force".
          standing: history,
          standingCurrent: history.length ? history[history.length - 1] : null,
        };
      }),
    actions: actions.map((a) => ({
      stage: a.stage,
      chamber: a.chamber,
      actionDate: a.actionDate ? a.actionDate.toISOString() : null,
      text: a.text,
      source: { url: a.sourceUrl, label: a.sourceLabel },
    })),
    provisions: provisionRows.map((p) => ({
      id: p.id,
      label: p.label,
      description: p.description,
      // Only surface a valid issue key so the panel can safely link/tag it.
      issueKey: p.issueKey && assertIssueKey(p.issueKey) ? p.issueKey : null,
      supportMeaning: p.supportMeaning,
      source: p.sourceUrl ? { url: p.sourceUrl, label: measure.sourceLabel } : null,
    })),
    impacts,
  });
}

// ── GET /compare?members=a,b,c[&issue=key] ───────────────────────────────────
// Side-by-side: each member's record items, optionally scoped to one issue. Powers
// the Comparison view. Kept simple — per-member record arrays the client lays out.
async function getCompare(url: URL): Promise<Response> {
  const membersRaw = clean(url.searchParams.get("members"), 1024);
  const members = [
    ...new Set(
      membersRaw
        .split(",")
        .map((m) => canonicalPid(clean(m, ID_MAX)))
        .filter(Boolean)
    ),
  ].slice(0, MAX_COMPARE_MEMBERS);
  if (!members.length) return json({ error: "members query param required" }, 400);

  const issue = clean(url.searchParams.get("issue"), ID_MAX);
  if (issue && !assertIssueKey(issue)) return json({ error: `Unknown issue key: ${issue}` }, 400);

  const issueMeasureIds = issue
    ? (
        await db
          .select({ id: vrMeasureIssues.measureId })
          .from(vrMeasureIssues)
          .where(eq(vrMeasureIssues.issueKey, issue))
      ).map((r) => r.id)
    : null;

  const matrix: Record<string, RecordItem[]> = {};
  for (const pid of members) {
    const vConds: any[] = [eq(vrMemberVotes.politicianId, pid)];
    if (issueMeasureIds) {
      if (!issueMeasureIds.length) {
        matrix[pid] = [];
        continue;
      }
      vConds.push(inArray(vrRollcalls.measureId, issueMeasureIds));
    }
    const rawVoteRows = await db
      .select(VOTE_COLUMNS)
      .from(vrMemberVotes)
      .innerJoin(vrRollcalls, eq(vrMemberVotes.rollcallId, vrRollcalls.id))
      .innerJoin(vrMeasures, eq(vrRollcalls.measureId, vrMeasures.id))
      .where(and(...vConds))
      .orderBy(desc(vrRollcalls.voteDate))
      .limit(FETCH_CAP);
    // Side by side, an uncorrected cell next to a corrected one would be the worst
    // place for the two to disagree — a comparison is exactly where a reader reads
    // one letter against another.
    const voteRows = applyCorrections(
      rawVoteRows as any[],
      await loadCorrections([pid]),
      pid
    );

    const pConds: any[] = [eq(vrPositions.politicianId, pid)];
    if (issueMeasureIds && issueMeasureIds.length) pConds.push(inArray(vrPositions.measureId, issueMeasureIds));
    const posRows = issueMeasureIds && !issueMeasureIds.length
      ? []
      : await db
          .select(POSITION_COLUMNS)
          .from(vrPositions)
          .innerJoin(vrMeasures, eq(vrPositions.measureId, vrMeasures.id))
          .where(and(...pConds))
          .limit(FETCH_CAP);

    const measureIds = [
      ...new Set([...voteRows.map((r) => r.measureId), ...posRows.map((r) => r.measureId)]),
    ];
    const issuesByMeasure = await loadIssuesByMeasure(measureIds);
    matrix[pid] = assembleRecordItems(voteRows, posRows, issuesByMeasure, "date");
  }

  return json({ members, issue: issue || null, matrix });
}

// ── GET /issue-records?issues=k1,k2,… ────────────────────────────────────────
// Every tracked member's record on a whole issue bundle, in ONE request.
//
// WHY THIS EXISTS: issue-first ranking needs the vote evidence for the entire field
// before it can order anybody. The existing routes can't serve that shape —
// /member/:id is one member per request, /compare caps at 8 members, and /issue/:key
// paginates the flat item list (so a ranker would have to walk pages just to learn
// who is in the field). Reading "whoever happens to be warm in a client cache"
// instead is worse than either: the ordering would silently depend on which profiles
// the visitor had already opened.
//
// The payload is de-duplicated rather than compressed by dropping detail: measure and
// rollcall metadata appear ONCE under `measures` / `rollcalls`, and each member gets a
// thin ref list pointing into them. Every field the client needs to rebuild the
// canonical record item is present, so the client rehydrates the SAME item shape
// assembleRecordItems() produces here and feeds it to the same stance-vs-record engine
// every other surface uses. Nothing about a verdict is computed on this side: the
// stated stance a vote is judged against lives in the client's ISSUE_STANCE_DATA.
//
// Verifiability is unchanged — assembleRecordItems() already refuses to emit an item
// without a source_url, and every issue key is checked against the shipped allow-list.
async function getIssueRecords(url: URL): Promise<Response> {
  const raw = clean(url.searchParams.get("issues"), 1024);
  const keys = [
    ...new Set(
      raw
        .split(",")
        .map((k) => clean(k, ID_MAX))
        .filter(Boolean)
    ),
  ].slice(0, MAX_RANK_ISSUES);
  if (!keys.length) return json({ error: "issues query param required" }, 400);
  const unknown = keys.find((k) => !assertIssueKey(k));
  if (unknown) return json({ error: `Unknown issue key: ${unknown}` }, 400);

  const empty = {
    issues: keys,
    measures: {},
    rollcalls: {},
    byPolitician: {},
    counts: { politicians: 0, votes: 0, positions: 0 },
    truncated: false,
  };

  const measureIdRows = await db
    .select({ id: vrMeasureIssues.measureId })
    .from(vrMeasureIssues)
    .where(inArray(vrMeasureIssues.issueKey, keys));
  const measureIds = [...new Set(measureIdRows.map((r) => r.id))];
  if (!measureIds.length) return json(empty);

  // One row cap across the whole bundle, +1 so the overflow is detectable rather than
  // guessed at. Most recent first, so a clipped read is still the current record.
  const rawVoteRows = await db
    .select({ ...VOTE_COLUMNS, politicianId: vrMemberVotes.politicianId })
    .from(vrMemberVotes)
    .innerJoin(vrRollcalls, eq(vrMemberVotes.rollcallId, vrRollcalls.id))
    .innerJoin(vrMeasures, eq(vrRollcalls.measureId, vrMeasures.id))
    .where(inArray(vrRollcalls.measureId, measureIds))
    .orderBy(desc(vrRollcalls.voteDate))
    .limit(RANK_FETCH_CAP + 1);
  const truncated = rawVoteRows.length > RANK_FETCH_CAP;
  if (truncated) rawVoteRows.length = RANK_FETCH_CAP;
  // This feed is what issue-first ranking orders the field on, so a corrected cell
  // has to be corrected HERE too — otherwise the ranking and the person file would
  // disagree about the same vote, and the person file would be the one that looked
  // wrong.
  const voteRows = applyCorrections(
    rawVoteRows as any[],
    await loadCorrections(rawVoteRows.map((r: any) => r.politicianId))
  );

  const posRows = await db
    .select({ ...POSITION_COLUMNS, politicianId: vrPositions.politicianId })
    .from(vrPositions)
    .innerJoin(vrMeasures, eq(vrPositions.measureId, vrMeasures.id))
    .where(inArray(vrPositions.measureId, measureIds))
    .limit(FETCH_CAP);

  const issuesByMeasure = await loadIssuesByMeasure(measureIds);

  // Group by member first, then assemble per member — so the canonical items are built
  // by the shared function, and politicianId never has to be reattached by search.
  const votesByPid = new Map<string, any[]>();
  const posByPid = new Map<string, any[]>();
  for (const v of voteRows) {
    if (!v.politicianId) continue;
    const list = votesByPid.get(v.politicianId);
    if (list) list.push(v);
    else votesByPid.set(v.politicianId, [v]);
  }
  for (const p of posRows) {
    if (!p.politicianId) continue;
    const list = posByPid.get(p.politicianId);
    if (list) list.push(p);
    else posByPid.set(p.politicianId, [p]);
  }

  const measures: Record<string, unknown> = {};
  const rollcalls: Record<string, unknown> = {};
  const byPolitician: Record<string, unknown[]> = {};
  let voteCount = 0;
  let positionCount = 0;

  for (const pid of new Set([...votesByPid.keys(), ...posByPid.keys()])) {
    const items = assembleRecordItems(
      votesByPid.get(pid) ?? [],
      posByPid.get(pid) ?? [],
      issuesByMeasure,
      "date"
    );
    if (!items.length) continue;
    const refs: unknown[] = [];
    for (const it of items) {
      // Shared once per measure: everything that describes the bill itself.
      if (!measures[it.measureId]) {
        measures[it.measureId] = {
          number: it.number,
          title: it.title,
          measureType: it.measureType,
          status: it.status,
          chamber: it.chamber,
          parentMeasureId: it.parentMeasureId,
          // Shared here for the same reason the rest of this object is: which
          // sitting a bill belongs to, and which text its mappings were read
          // against, are facts about the MEASURE, identical for every member who
          // acted on it. A per-member ref would carry N copies of one string.
          measureIdent: it.measureIdent,
          issues: it.issues,
        };
      }
      if (it.kind === "vote") {
        // Shared once per roll call: the question asked and how it was read.
        if (it.rollcallId != null && !rollcalls[it.rollcallId]) {
          rollcalls[it.rollcallId] = {
            measureId: it.measureId,
            chamber: it.chamber,
            congress: it.congress,
            session: it.session,
            rollNumber: it.rollNumber,
            date: it.date,
            action: it.action,
            actionType: it.actionType,
            result: it.result,
            isProcedural: it.isProcedural,
            advanceInverted: it.advanceInverted,
            source: it.source,
          };
        }
        // Per member: only what differs between members on the same roll call.
        refs.push({ kind: "vote", rollcallId: it.rollcallId, position: it.position, isParty: it.isParty });
        voteCount++;
      } else {
        // A co-sponsorship / amicus is already one row per member, so it keeps its
        // own date and source; only the bill metadata is shared.
        refs.push({
          kind: "position",
          measureId: it.measureId,
          action: it.action,
          supports: it.supports,
          date: it.date,
          source: it.source,
        });
        positionCount++;
      }
    }
    byPolitician[pid] = refs;
  }

  return json({
    issues: keys,
    measures,
    rollcalls,
    byPolitician,
    counts: {
      politicians: Object.keys(byPolitician).length,
      votes: voteCount,
      positions: positionCount,
    },
    // True only when the row cap actually clipped the read. The client surfaces this
    // rather than quietly ranking on a partial record.
    truncated,
  });
}

// ── GET /measures ────────────────────────────────────────────────────────────
// The Legislation / Bill library browse endpoint (Phase 1): a filterable, paginated
// list of measures rendered as compact cards. Per-measure detail (component issues +
// roll calls + votes) stays at /measure/:id. Verifiability is preserved: a measure
// without a source_url is never surfaced. Issue keys are validated against the same
// ISSUE_MAP allow-list every other route uses.
//   Query params: congress, chamber, type, status, issue, q, sort, page, pageSize.
async function getMeasures(url: URL): Promise<Response> {
  const congressRaw = clean(url.searchParams.get("congress"), 8);
  const congress = congressRaw ? parseInt(congressRaw, 10) : null;
  if (congressRaw && !Number.isFinite(congress as number)) {
    return json({ error: `Invalid congress: ${congressRaw}` }, 400);
  }

  const chamber = clean(url.searchParams.get("chamber"), 16).toLowerCase();
  if (chamber && !CHAMBERS.includes(chamber)) {
    return json({ error: `Invalid chamber: ${chamber}` }, 400);
  }

  const measureType = clean(url.searchParams.get("type"), 24).toLowerCase();
  if (measureType && !MEASURE_TYPES.includes(measureType)) {
    return json({ error: `Invalid type: ${measureType}` }, 400);
  }

  const status = clean(url.searchParams.get("status"), 24).toLowerCase();

  const issue = clean(url.searchParams.get("issue"), ID_MAX);
  if (issue && !assertIssueKey(issue)) return json({ error: `Unknown issue key: ${issue}` }, 400);

  const q = clean(url.searchParams.get("q"), Q_MAX);

  const sortParam = clean(url.searchParams.get("sort"), 16).toLowerCase();
  const sort = ["recent", "number", "congress"].includes(sortParam) ? sortParam : "recent";

  let pageSize = parseInt(clean(url.searchParams.get("pageSize"), 8), 10);
  if (!Number.isFinite(pageSize) || pageSize <= 0) pageSize = PAGE_SIZE_DEFAULT;
  pageSize = Math.min(pageSize, PAGE_SIZE_MAX);
  let page = parseInt(clean(url.searchParams.get("page"), 8), 10);
  if (!Number.isFinite(page) || page < 1) page = 1;

  // Issue filter → restrict to measures carrying that issue key (the bridge table).
  let issueMeasureIds: number[] | null = null;
  if (issue) {
    const rows = await db
      .select({ measureId: vrMeasureIssues.measureId })
      .from(vrMeasureIssues)
      .where(eq(vrMeasureIssues.issueKey, issue));
    issueMeasureIds = [...new Set(rows.map((r) => r.measureId))];
    if (!issueMeasureIds.length) {
      return json({ items: [], page, pageSize, total: 0, totalPages: 1, hasMore: false });
    }
  }

  const conds: any[] = [];
  if (congress != null) conds.push(eq(vrMeasures.congress, congress));
  if (chamber) conds.push(eq(vrMeasures.chamber, chamber));
  if (measureType) conds.push(eq(vrMeasures.measureType, measureType));
  if (status) conds.push(eq(vrMeasures.status, status));
  if (issueMeasureIds) conds.push(inArray(vrMeasures.id, issueMeasureIds));
  if (q) {
    const like = `%${q}%`;
    conds.push(or(ilike(vrMeasures.number, like), ilike(vrMeasures.title, like), ilike(vrMeasures.summary, like)));
  }

  let rows = await db
    .select()
    .from(vrMeasures)
    .where(conds.length ? and(...conds) : undefined)
    .limit(FETCH_CAP);

  // Verifiability: never list a measure with no citable source.
  rows = rows.filter((m) => !!m.sourceUrl);

  // Sort in JS — the measure set is small, so one code path covers every sort.
  rows.sort((a, b) => {
    if (sort === "number") {
      return (a.number ?? "").localeCompare(b.number ?? "", undefined, { numeric: true });
    }
    if (sort === "congress") {
      return (b.congress ?? 0) - (a.congress ?? 0) ||
        (a.number ?? "").localeCompare(b.number ?? "", undefined, { numeric: true });
    }
    // recent (default): most-recently-updated first, then newest introduced.
    const upd = (b.updatedAt?.getTime?.() ?? 0) - (a.updatedAt?.getTime?.() ?? 0);
    if (upd !== 0) return upd;
    return (b.introducedAt?.getTime?.() ?? 0) - (a.introducedAt?.getTime?.() ?? 0);
  });

  const pageResult = paginate(rows, page, pageSize);
  const pageRows = pageResult.items;
  const pageIds = pageRows.map((m) => m.id);

  // Batch the per-card enrichments for just this page: issue tags, and roll-call /
  // recorded-vote counts (so a card can show "3 roll calls · 431 votes").
  const issuesByMeasure = await loadIssuesByMeasure(pageIds);

  // The chamber, the day and the tally ride along with the count. A browse card
  // could already say "3 roll calls", which answers how many times a measure was
  // voted on and not one thing about WHEN or HOW it went - and the issue page's
  // row line is exactly "chamber . last roll date . Yea-Nay", sorted by that date.
  // Widening the select the page already runs is the whole cost; no extra query.
  const rollcalls = pageIds.length
    ? await db
        .select({
          id: vrRollcalls.id,
          measureId: vrRollcalls.measureId,
          chamber: vrRollcalls.chamber,
          voteDate: vrRollcalls.voteDate,
          question: vrRollcalls.question,
          result: vrRollcalls.result,
          totals: vrRollcalls.totals,
        })
        .from(vrRollcalls)
        .where(inArray(vrRollcalls.measureId, pageIds))
    : [];
  const rollcallCount: Record<number, number> = {};
  const rcToMeasure: Record<number, number> = {};
  // The LAST roll on each measure, by vote date - the most recent thing that
  // happened to it on a floor. Ties break on the higher id, which is the later
  // ingest of two rolls stamped the same day.
  const lastRc: Record<number, (typeof rollcalls)[number]> = {};
  for (const rc of rollcalls) {
    rollcallCount[rc.measureId] = (rollcallCount[rc.measureId] ?? 0) + 1;
    rcToMeasure[rc.id] = rc.measureId;
    const held = lastRc[rc.measureId];
    const t = rc.voteDate?.getTime?.() ?? 0;
    const ht = held?.voteDate?.getTime?.() ?? -1;
    if (!held || t > ht || (t === ht && rc.id > held.id)) lastRc[rc.measureId] = rc;
  }
  const num = (v: unknown): number | null => (typeof v === "number" && Number.isFinite(v) ? v : null);
  const rcIds = rollcalls.map((r) => r.id);
  const voteRows = rcIds.length
    ? await db.select({ rollcallId: vrMemberVotes.rollcallId }).from(vrMemberVotes).where(inArray(vrMemberVotes.rollcallId, rcIds))
    : [];
  const voteCount: Record<number, number> = {};
  for (const v of voteRows) {
    const mid = rcToMeasure[v.rollcallId];
    if (mid != null) voteCount[mid] = (voteCount[mid] ?? 0) + 1;
  }

  const items = pageRows.map((m) => {
    const issues = issuesByMeasure.get(m.id) ?? [];
    const primary = issues.find((i) => i.isPrimary) ?? issues[0] ?? null;
    return {
      id: m.id,
      measureType: m.measureType,
      number: m.number,
      title: m.title,
      shortTitle: m.shortTitle,
      summary: m.summary,
      status: m.status,
      chamber: m.chamber,
      congress: m.congress,
      introducedAt: m.introducedAt ? m.introducedAt.toISOString() : null,
      primaryIssue: primary ? primary.issueKey : null,
      // EVERY primary flag, not just the one that sorted first. An act can be the
      // subject of two axes at once (H.R. 6644 is a housing act AND a housing-supply
      // act), and `primaryIssue` can only name one of them - so a caller filtered to
      // one issue key had no way to tell "this bill's subject" from "rode inside"
      // for the key it actually asked about.
      primaryIssueKeys: issues.filter((i) => i.isPrimary).map((i) => i.issueKey),
      issueKeys: issues.map((i) => i.issueKey),
      isOmnibus: issues.length >= 2,
      rollcallCount: rollcallCount[m.id] ?? 0,
      lastRoll: lastRc[m.id]
        ? {
            chamber: lastRc[m.id].chamber,
            voteDate: lastRc[m.id].voteDate ? lastRc[m.id].voteDate.toISOString() : null,
            question: lastRc[m.id].question ?? null,
            result: lastRc[m.id].result ?? null,
            yea: num((lastRc[m.id].totals ?? {}).yea),
            nay: num((lastRc[m.id].totals ?? {}).nay),
          }
        : null,
      voteCount: voteCount[m.id] ?? 0,
      externalIds: m.externalIds,
      source: { url: m.sourceUrl, label: m.sourceLabel },
    };
  });

  return json({
    items,
    page: pageResult.page,
    pageSize: pageResult.pageSize,
    total: pageResult.total,
    totalPages: pageResult.totalPages,
    hasMore: pageResult.hasMore,
  });
}

// ── Router ───────────────────────────────────────────────────────────────────
export default async (req: Request): Promise<Response> => {
  const url = new URL(req.url);
  const path = url.pathname.replace(/^\/api\/voting-record/, "").replace(/\/+$/, "");
  const method = req.method.toUpperCase();

  if (method !== "GET") return json({ error: "Method not allowed" }, 405);

  try {
    // Both pack forms land here: the unversioned URL the client asks for, which
    // is answered with a redirect, and the versioned URL that redirect points at.
    // A third path segment that is not version-shaped is a 404 rather than a
    // silent redirect, so a typo in a hand-written URL is not disguised as a
    // stale version.
    const packMatch = path.match(/^\/member\/([^/]+)\/pack(?:\/([^/]+))?$/);
    if (packMatch) {
      const id = canonicalPid(clean(decodeURIComponent(packMatch[1]), ID_MAX));
      if (!id) return json({ error: "Missing politician id" }, 400);
      const raw = packMatch[2] ? clean(decodeURIComponent(packMatch[2]), 64) : "";
      if (raw && !PACK_VERSION_RE.test(raw)) return json({ error: "Not found" }, 404);
      return await getMemberPack(id, req, raw || null);
    }

    const memberImpactsMatch = path.match(/^\/member\/([^/]+)\/impacts$/);
    if (memberImpactsMatch) {
      const id = canonicalPid(clean(decodeURIComponent(memberImpactsMatch[1]), ID_MAX));
      if (!id) return json({ error: "Missing politician id" }, 400);
      return await getMemberImpacts(id);
    }

    const memberMatch = path.match(/^\/member\/([^/]+)$/);
    if (memberMatch) {
      const id = canonicalPid(clean(decodeURIComponent(memberMatch[1]), ID_MAX));
      if (!id) return json({ error: "Missing politician id" }, 400);
      return await getMember(id, url, req);
    }

    const issueImpactsMatch = path.match(/^\/issue\/([^/]+)\/impacts$/);
    if (issueImpactsMatch) {
      const key = clean(decodeURIComponent(issueImpactsMatch[1]), ID_MAX);
      if (!key) return json({ error: "Missing issue key" }, 400);
      return await getIssueImpacts(key);
    }

    const issueMatch = path.match(/^\/issue\/([^/]+)$/);
    if (issueMatch) {
      const key = clean(decodeURIComponent(issueMatch[1]), ID_MAX);
      if (!key) return json({ error: "Missing issue key" }, 400);
      return await getIssue(key, url);
    }

    if (path === "/measures") {
      return await getMeasures(url);
    }

    const measureMatch = path.match(/^\/measure\/(\d+)$/);
    if (measureMatch) {
      return await getMeasure(parseInt(measureMatch[1], 10));
    }

    // The printed bill identifier ("H.R. 9311") carries spaces and dots, so the
    // number is whatever remains after the congress segment.
    // The sitting segment may be a congress ("119"), a state session code
    // ("2024GS"), or empty for a number that is unique on its own — see
    // getMeasureRef. Anything outside that alphabet is not a sitting.
    const measureRefMatch = path.match(/^\/measure-ref\/([A-Za-z0-9]*)\/(.+)$/);
    if (measureRefMatch) {
      const sitting = clean(decodeURIComponent(measureRefMatch[1]), 12);
      const number = clean(decodeURIComponent(measureRefMatch[2]), 80);
      return await getMeasureRef(sitting, number);
    }

    // The official roll-call address: /rollcall/119/house/190. Anything that is
    // not that exact shape is a bad address, not an empty result — say 400 rather
    // than pretend to have looked.
    const rollcallMatch = path.match(/^\/rollcall\/(\d+)\/([a-z]+)\/(\d+)$/i);
    if (rollcallMatch) {
      const congress = parseInt(rollcallMatch[1], 10);
      const chamber = rollcallMatch[2].toLowerCase();
      const rollNumber = parseInt(rollcallMatch[3], 10);
      if (chamber !== "house" && chamber !== "senate") {
        return json({ error: "Chamber must be house or senate" }, 400);
      }
      if (!Number.isFinite(congress) || !Number.isFinite(rollNumber)) {
        return json({ error: "Congress and roll number must be integers" }, 400);
      }
      return await getRollcall(congress, chamber, rollNumber);
    }

    if (path === "/compare") {
      return await getCompare(url);
    }

    if (path === "/issue-records") {
      return await getIssueRecords(url);
    }

    return json({ error: "Not found" }, 404);
  } catch (e: any) {
    console.error("voting-record error:", e);
    return json({ error: "Server error", detail: e?.message || String(e) }, 500);
  }
};

export const config: Config = {
  path: ["/api/voting-record", "/api/voting-record/*"],
};
