// ─────────────────────────────────────────────────────────────────────────────
// 🧾 Hero receipt — the one piece of proof that renders before anything loads
// ─────────────────────────────────────────────────────────────────────────────
// Renders a single real, sourced, verdict-stamped receipt into #hero-receipt so
// a first-time visitor sees evidence, not a promise, without scrolling.
//
// WHY THIS EXISTS SEPARATELY FROM say-vs-do.js
// The full engine needs acct-spotlight-data.js (~154 KB gz), which is
// deliberately lazy-loaded. Nothing that depends on it can be on screen at first
// paint. So this reads window.PDX_HERO_RECEIPT — a ~2 KB gz seed of the engine's
// own collect() output, generated by scripts/gen-hero-receipt.mjs — and paints
// from that. It is a VIEWPORT onto the engine's verdicts, not a second engine:
// no selection logic, no verdict logic, no sourcing rules live here. This file
// only draws what the seed already decided.
//
// HANDOFF
// Tapping the card opens the real receipt via PDXReceipts.open(pid, issueKey)
// once the engine has loaded; before then it falls back to navigating to the
// full Say-vs-Do section, which is what triggers that load anyway.
//
// FAIL CLOSED
// Missing seed, empty seed, malformed entry, or an entry without a checkable
// source URL → the slot stays hidden and the hero renders exactly as it did
// before. There is deliberately no placeholder, no skeleton and no "example"
// receipt: an empty proof slot is honest, a fake one is not.
// ─────────────────────────────────────────────────────────────────────────────
(function () {
  'use strict';

  var host = document.getElementById('hero-receipt');
  if (!host) return;

  var all = Array.isArray(window.PDX_HERO_RECEIPT) ? window.PDX_HERO_RECEIPT : [];

  // Re-check the sourcing gate at render time. The generator already enforces
  // this, but the cost of checking again is nil and the cost of painting an
  // unsourced verdict on the front page is not.
  var data = all.filter(function (r) {
    return r && r.name && r.sub && r.did && r.verdict && r.verdict.label &&
           r.source && typeof r.source.url === 'string' && /^https?:\/\//i.test(r.source.url);
  });

  if (!data.length) { host.hidden = true; return; }

  function esc(s) {
    return String(s == null ? '' : s)
      .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
  }

  // ENTRY BEHAVIOUR — stable within a visit, rotating between days.
  //
  // This used to be Math.random() on every load, for a good reason: with a fixed
  // start index one person becomes the permanent face of the front page and —
  // because the seed is party-interleaved — one party becomes the permanent first
  // impression. That reason still holds. What it got wrong was the GRANULARITY:
  // re-rolling per page load meant a reload dealt a different stranger, so the
  // card read as arbitrary rather than as one item drawn from a set. A visitor
  // cannot tell "sampled fairly" from "thrown in at random" if the sample changes
  // while they are looking at it.
  //
  // Rotating on the day instead keeps the fairness property (nobody is the
  // permanent face; the interleave means the party rotates too) and drops the
  // arbitrariness: within a visit the card is a fixed thing the reader can go
  // back to, and the "N of M" counter and the intro line below say out loud that
  // it is one of a set — which is the actual fix for reading as dropped-in.
  var day = Math.floor(Date.now() / 86400000);
  var i = ((day % data.length) + data.length) % data.length;

  function card(r) {
    var vkey = (r.verdict.key || 'note').replace(/[^a-z]/gi, '');
    var party = r.party && r.party.label
      ? '<span class="pdx-hr-party" style="--p:' + esc(r.party.color || '#94a3b8') + '">' + esc(r.party.label) + '</span>'
      : '';
    var said = r.said && r.said.text
      ? '<p class="pdx-hr-line"><span class="pdx-hr-k">Said</span>' + esc(r.said.text) + '</p>'
      : '';
    var issue = r.issue && r.issue.label
      ? '<span class="pdx-hr-issue">' + esc(r.issue.icon || '') + ' ' + esc(r.issue.label) + '</span>'
      : '';
    var when = r.date ? '<span class="pdx-hr-date">· ' + esc(r.date) + '</span>' : '';

    return '' +
      '<article class="pdx-hr-card pdx-hr-' + esc(vkey) + '">' +
        '<div class="pdx-hr-stamp"><span aria-hidden="true">' + esc(r.verdict.ico || '') + '</span>' + esc(r.verdict.label) + '</div>' +
        '<div class="pdx-hr-who">' +
          '<h2 class="pdx-hr-name">' + esc(r.name) + '</h2>' + party +
        '</div>' +
        '<p class="pdx-hr-sub">' + esc(r.sub) + '</p>' +
        '<div class="pdx-hr-body">' +
          said +
          '<p class="pdx-hr-line"><span class="pdx-hr-k">Did</span>' + esc(r.did) + '</p>' +
        '</div>' +
        '<div class="pdx-hr-foot">' +
          issue +
          // The source is a real anchor, not a button: it must be openable,
          // copyable and inspectable without JavaScript having to cooperate.
          '<a class="pdx-hr-src" href="' + esc(r.source.url) + '" target="_blank" rel="noopener noreferrer">' +
            esc(r.source.label) + when + ' ↗' +
          '</a>' +
        '</div>' +
        '<button type="button" class="pdx-hr-open" data-pid="' + esc(r.pid) + '" data-issue="' + esc(r.issueKey || '') + '">' +
          'See the full receipt' +
        '</button>' +
      '</article>';
  }

  function draw() {
    var r = data[i % data.length];
    var pos = (i % data.length) + 1;
    // FRAMING — why a stranger is looking at a stamped card about a politician
    // they may not know, before they have been told what this site is.
    //
    // The card was correct and completely unexplained: a verdict stamp, a name and
    // a source link, dropped between "BUILD YOUR TEAM." and the paragraph that
    // says what PolitiDex does. Read cold it looks like an ad for a grievance
    // against one person. Two lines fix that without touching the card, the
    // verdicts or the seed: the counter says it is one of a set rather than a
    // singled-out target, and the intro says what the reader is meant to DO with
    // it — check the source before believing anything else on the page. That is
    // the argument the placement was already making silently.
    host.innerHTML =
      '<div class="pdx-hr-rail">' +
        '<span class="pdx-hr-rail-l">' +
          '<span class="pdx-hr-eyebrow">Receipt on record</span>' +
          (data.length > 1
            ? '<span class="pdx-hr-pos">' + pos + ' of ' + data.length + '</span>'
            : '') +
        '</span>' +
        (data.length > 1
          ? '<button type="button" class="pdx-hr-next">Next receipt <span aria-hidden="true">→</span></button>'
          : '') +
      '</div>' +
      '<p class="pdx-hr-intro">' +
        'Don’t take our word for it — take theirs. One documented promise or position, ' +
        'checked against what they actually did, with the source attached. ' +
        (data.length > 1 ? 'Every politician here carries the same record.' : '') +
      '</p>' +
      card(r);
    host.hidden = false;
    // ANNOUNCEMENT — "Next receipt" swaps the whole card. A screen-reader user
    // otherwise hears nothing: focus stays on a button whose label did not change.
    // The attribute goes on the host because draw() replaces this element's
    // contents, and a live region nested inside the replaced markup is destroyed
    // and rebuilt with it — a region that did not exist before a mutation does not
    // announce it. Armed AFTER the first paint, so page load stays silent.
    host.setAttribute('aria-live', 'polite');
  }

  host.addEventListener('click', function (e) {
    var next = e.target.closest && e.target.closest('.pdx-hr-next');
    if (next) { i = (i + 1) % data.length; draw(); return; }

    var open = e.target.closest && e.target.closest('.pdx-hr-open');
    if (!open) return;
    // Hand off to the real engine when it is here; otherwise send the reader to
    // the full Say-vs-Do band, whose own lazy-load trigger pulls the engine in.
    if (window.PDXReceipts && typeof window.PDXReceipts.open === 'function') {
      try {
        window.PDXReceipts.open(open.getAttribute('data-pid'), open.getAttribute('data-issue') || '');
        return;
      } catch (err) { /* fall through to navigation */ }
    }
    location.hash = '#say-vs-do';
  });

  draw();
})();
