// ─────────────────────────────────────────────────────────────────────────────
// 🧾 Hero receipt — the one piece of proof that renders before anything loads
// ─────────────────────────────────────────────────────────────────────────────
// Renders a single real, sourced, verdict-stamped receipt into #hero-receipt so
// a first-time visitor sees evidence, not a promise, without scrolling.
//
// WHY THIS EXISTS SEPARATELY FROM say-vs-do.js
// The full engine needs acct-spotlight-data.js (~154 KB gz), which is
// deliberately lazy-loaded. Nothing that depends on it can be on screen at first
// paint. So this reads window.PDX_HERO_RECEIPT — a ~2 KB gz seed of the engine's
// own collect() output, generated by scripts/gen-hero-receipt.mjs — and paints
// from that. It is a VIEWPORT onto the engine's verdicts, not a second engine:
// no selection logic, no verdict logic, no sourcing rules live here. This file
// only draws what the seed already decided.
//
// HANDOFF
// Tapping the card opens the real receipt via PDXReceipts.open(pid, issueKey)
// once the engine has loaded; before then it falls back to navigating to the
// full Say-vs-Do section, which is what triggers that load anyway.
//
// FAIL CLOSED
// Missing seed, empty seed, malformed entry, or an entry without a checkable
// source URL → the slot stays hidden and the hero renders exactly as it did
// before. There is deliberately no placeholder, no skeleton and no "example"
// receipt: an empty proof slot is honest, a fake one is not.
// ─────────────────────────────────────────────────────────────────────────────
(function () {
  'use strict';

  var host = document.getElementById('hero-receipt');
  if (!host) return;

  var all = Array.isArray(window.PDX_HERO_RECEIPT) ? window.PDX_HERO_RECEIPT : [];

  // Re-check the sourcing gate at render time. The generator already enforces
  // this, but the cost of checking again is nil and the cost of painting an
  // unsourced verdict on the front page is not.
  var data = all.filter(function (r) {
    return r && r.name && r.sub && r.did && r.verdict && r.verdict.label &&
           r.source && typeof r.source.url === 'string' && /^https?:\/\//i.test(r.source.url);
  });

  if (!data.length) { host.hidden = true; return; }

  function esc(s) {
    return String(s == null ? '' : s)
      .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
  }

  // Start on a different receipt each visit. This is a fairness measure, not a
  // gimmick: with a fixed start index one person would be the permanent face of
  // the front page, and — because the seed is party-interleaved — one party
  // would be the permanent first impression.
  var i = Math.floor(Math.random() * data.length);

  function card(r) {
    var vkey = (r.verdict.key || 'note').replace(/[^a-z]/gi, '');
    var party = r.party && r.party.label
      ? '<span class="pdx-hr-party" style="--p:' + esc(r.party.color || '#94a3b8') + '">' + esc(r.party.label) + '</span>'
      : '';
    var said = r.said && r.said.text
      ? '<p class="pdx-hr-line"><span class="pdx-hr-k">Said</span>' + esc(r.said.text) + '</p>'
      : '';
    var issue = r.issue && r.issue.label
      ? '<span class="pdx-hr-issue">' + esc(r.issue.icon || '') + ' ' + esc(r.issue.label) + '</span>'
      : '';
    var when = r.date ? '<span class="pdx-hr-date">· ' + esc(r.date) + '</span>' : '';

    return '' +
      '<article class="pdx-hr-card pdx-hr-' + esc(vkey) + '">' +
        '<div class="pdx-hr-stamp"><span aria-hidden="true">' + esc(r.verdict.ico || '') + '</span>' + esc(r.verdict.label) + '</div>' +
        '<div class="pdx-hr-who">' +
          '<h2 class="pdx-hr-name">' + esc(r.name) + '</h2>' + party +
        '</div>' +
        '<p class="pdx-hr-sub">' + esc(r.sub) + '</p>' +
        '<div class="pdx-hr-body">' +
          said +
          '<p class="pdx-hr-line"><span class="pdx-hr-k">Did</span>' + esc(r.did) + '</p>' +
        '</div>' +
        '<div class="pdx-hr-foot">' +
          issue +
          // The source is a real anchor, not a button: it must be openable,
          // copyable and inspectable without JavaScript having to cooperate.
          '<a class="pdx-hr-src" href="' + esc(r.source.url) + '" target="_blank" rel="noopener noreferrer">' +
            esc(r.source.label) + when + ' ↗' +
          '</a>' +
        '</div>' +
        '<button type="button" class="pdx-hr-open" data-pid="' + esc(r.pid) + '" data-issue="' + esc(r.issueKey || '') + '">' +
          'See the full receipt' +
        '</button>' +
      '</article>';
  }

  function draw() {
    var r = data[i % data.length];
    host.innerHTML =
      '<div class="pdx-hr-rail">' +
        '<span class="pdx-hr-eyebrow">Receipt on record</span>' +
        (data.length > 1
          ? '<button type="button" class="pdx-hr-next">Next <span class="pdx-hr-count">' +
            ((i % data.length) + 1) + '/' + data.length + '</span></button>'
          : '') +
      '</div>' + card(r);
    host.hidden = false;
  }

  host.addEventListener('click', function (e) {
    var next = e.target.closest && e.target.closest('.pdx-hr-next');
    if (next) { i = (i + 1) % data.length; draw(); return; }

    var open = e.target.closest && e.target.closest('.pdx-hr-open');
    if (!open) return;
    // Hand off to the real engine when it is here; otherwise send the reader to
    // the full Say-vs-Do band, whose own lazy-load trigger pulls the engine in.
    if (window.PDXReceipts && typeof window.PDXReceipts.open === 'function') {
      try {
        window.PDXReceipts.open(open.getAttribute('data-pid'), open.getAttribute('data-issue') || '');
        return;
      } catch (err) { /* fall through to navigation */ }
    }
    location.hash = '#say-vs-do';
  });

  draw();
})();
