/* ═══════════════════════════════════════════════════════════════════════════
   pdx-return.js — GENERATED by scripts/gen-pdx-return.mjs. DO NOT EDIT.
   ───────────────────────────────────────────────────────────────────────────
   window.PDXReturn, copied byte for byte from voter-hub-location.js, which
   owns it. Loaded by the district boards that do not load that file, so
   their sign-in doors carry the same `next` intent /find already uses.
   ═══════════════════════════════════════════════════════════════════════════ */
(function () {
  if (window.PDXReturn) return;
  window.PDXReturn = (function () {
    var HOME = '/voice';
    var PARAM = 'next';
    // THE FINDER'S ADDRESS, IN ONE PLACE. It is a path and no longer a fragment,
    // and losing the fragment took a bug with it: the old href composed
    // '/?next=…' + '/#who-represents-me', which put FINDER's own leading slash
    // INSIDE the query value, so the intent read back as '/voice/' rather than
    // '/voice'. There is nothing to compose now — the query goes on the end of a
    // path with no fragment behind it.
    var FINDER = '/find';
    // AND THE BAND THAT SHOWS THE ANSWER, which is a different place from the
    // picker that sets it and always was. #who-represents-me is still on the
    // front page, still lists the reader's seats, and is where settled() returns
    // a reader who finished on /find without carrying an intent. The nav rows
    // across the app point at it for the same reason: reading is not setting.
    var FRAGMENT = '#who-represents-me';
    // THE ALLOW-LIST. /voice, /me, /ballot, /district/<slug> — and '/', because
    // the front page is a real destination for this lane: a reader whose door was
    // the homepage's own "set my location" control is going back to the band that
    // shows the answer. It is safe to admit for the same reason it is needed:
    // consume() refuses to navigate to the address it is already standing on, so
    // '/' can only ever move a reader who is NOT on the front page.
    //
    // /find IS DELIBERATELY NOT IN HERE. The finder is where this lane starts,
    // never where it ends; a next=/find would be a door that leads back to the
    // door, and a save that lands on the picker that made it is a loop.
    var OK_RE = /^\/(?:voice|me|ballot|district\/[a-z0-9][a-z0-9-]{0,63})?\/?$/;

    function strip(p) {
      return String(p == null ? '' : p).replace(/\.html$/, '').replace(/\/+$/, '') || '/';
    }

    function sanitize(raw) {
      var s = String(raw == null ? '' : raw);
      if (!s) return '';
      try { s = decodeURIComponent(s); } catch (e) {}
      s = s.trim();
      if (s.indexOf('//') === 0) return '';        // protocol-relative: off-origin
      if (s.indexOf(':') >= 0) return '';          // any scheme at all
      if (s.indexOf('\\') >= 0) return '';         // a backslash some engines read as /
      var cut = s.search(/[?#]/);
      if (cut >= 0) s = s.slice(0, cut);
      s = s.toLowerCase();
      return OK_RE.test(s) ? s : '';
    }

    // The intent in THIS page's URL, or '' when there is none. A `next` that is
    // present and does not survive sanitize() lands on HOME rather than on '',
    // because somebody did ask to go somewhere and /voice is where this lane
    // lives — '' would silently strand a reader who followed a mangled link.
    function read() {
      var m = null;
      try { m = /[?&]next=([^&#]*)/.exec(String(window.location.search || '')); } catch (e) { m = null; }
      if (!m) return '';
      return sanitize(m[1]) || HOME;
    }

    // Where a door on THIS document should send the reader back to: the address
    // they are standing on when it is one of ours, and /voice otherwise. This is
    // the rule that makes a location CTA on /district/ut-sd-3 return to that
    // board instead of to the hub.
    function here() {
      var p = '';
      try { p = String(window.location.pathname || ''); } catch (e) { p = ''; }
      return sanitize(strip(p)) || HOME;
    }

    // THE DOOR ITSELF, built in one place. A real anchor to a real address —
    // never href="#", never a button that needs JavaScript to mean anything. The
    // address is the finder's own document, so following this link costs the
    // finder and not the archive homepage that used to host it.
    function finderHref(next) {
      return FINDER + '?' + PARAM + '=' + encodeURIComponent(sanitize(next) || HOME);
    }

    // ── THE ACCOUNT DOOR — THE SAME INTENT, CARRIED TO THE SIGN-IN SHEET ─────
    // THE BUG THIS CLOSES. A district board has no sign-in UI of its own: the
    // front page owns the auth modal, so "Join the People" in a board's chrome
    // and the composer's "Sign in to start" were both a plain trip to '/'. The
    // reader arrived on the homepage with no sheet open and no way back to the
    // board that asked them for an account — the exact shape of the finder bug
    // above, one door over.
    //
    // SO IT IS THE SAME PARAMETER AND THE SAME ALLOW-LIST, not a second stash.
    // joinHref() puts `next` on the front page's address plus one marker, JOIN,
    // which says "open the account sheet on arrival". The front page opens it;
    // closing it — a real sign-in or a dismiss, both end in closeAuthModal() —
    // calls authSettled(), which is consume() with the second gate it needs.
    //
    // NO INTENT, NO MARKER. A door whose own address is not on OK_RE (or is the
    // front page itself) gets plain '/', which is today's Join exactly: nobody
    // expressed anywhere to come back to, so nothing is invented.
    var JOIN = 'join';

    function joinHref(next) {
      var n = '';
      if (next == null) {
        try { n = sanitize(strip(window.location.pathname)); } catch (e) { n = ''; }
      } else {
        n = sanitize(next);
      }
      if (!n || strip(n) === '/') return '/';
      return '/?' + JOIN + '=1&' + PARAM + '=' + encodeURIComponent(n);
    }

    // The marker on THIS page's URL. Only a door that went through joinHref()
    // sets it, so a `next` that came for the location picker never rides a
    // sign-in out of the page.
    function wantsJoin() {
      try { return /[?&]join=1(?:[&#]|$)/.test(String(window.location.search || '')); } catch (e) { return false; }
    }

    // The account intent, or '' — STRICT where read() is forgiving. read() lands
    // a mangled `next` on /voice because the finder is this lane's own tool; a
    // sign-in that came with a mangled intent has no lane to fall back to, and
    // the rule is that a settled sheet never lands anywhere it was not asked to.
    function joinIntent() {
      if (!wantsJoin()) return '';
      var m = null;
      try { m = /[?&]next=([^&#]*)/.exec(String(window.location.search || '')); } catch (e) { m = null; }
      return m ? sanitize(m[1]) : '';
    }

    function consume() {
      var next = read();
      if (!next) return false;
      if (!window._pdxLocSaved || !window._hasUserLocation) {
        // No location was saved on this page view, so the only thing that can
        // still spend the intent is a settled account sheet that was opened FOR
        // it. Anything else stays exactly where it is.
        if (!window._pdxAuthSettled) return false;
        next = joinIntent();
        if (!next) return false;
      }
      var at = '';
      try { at = strip(window.location.pathname); } catch (e) { at = ''; }
      if (at === strip(next)) return false;
      try { window.location.assign(next); return true; } catch (e) { return false; }
    }

    // ── settled() — consume(), PLUS THE ONE DOCUMENT THAT CANNOT STAY ────────
    // "NO PARAMETER, NO JUMP" IS THE RIGHT RULE EVERYWHERE THE PICKER IS PART OF
    // A PAGE, and /find is the one place it is not. On the front page, on /me, on
    // a board, a save with no `next` means "the reader chose to be here and
    // changed their location while they were" — moving them would be this module
    // deciding where they were going. On /find there is nothing to stay for: the
    // page is a tool with one job, the job just finished, and leaving a reader
    // standing on a picker they have already used is the dead end the move would
    // otherwise have introduced.
    //
    // SO THE FALLBACK IS GATED ON THE DOCUMENT SAYING IT IS THE FINDER, not on a
    // pathname test — /find, /find/ and a preview server's /find.html are three
    // spellings of one page, and window.__PDX_FIND_DOC is declared exactly once,
    // in find.html's head. On every other document settled() IS consume(), byte
    // for byte, which is why both callers can spell it this way.
    //
    // AND IT STILL CANNOT FIRE WITHOUT A SAVE. Same two flags consume() checks,
    // for the same reason: a reader who opened the finder and pressed Escape has
    // expressed no intent and is owed no navigation.
    function settled() {
      if (consume()) return true;
      if (!window.__PDX_FIND_DOC) return false;
      if (!window._pdxLocSaved || !window._hasUserLocation) return false;
      // The band that SHOWS the seats, which is where the answer is read. It is
      // not in OK_RE's business — this is a literal destination, not an
      // attacker-supplied one.
      try { window.location.assign('/' + FRAGMENT); return true; } catch (e) { return false; }
    }

    // ── authSettled() — THE SHEET CLOSED; SPEND THE ACCOUNT INTENT ──────────
    // Called by the front page's closeAuthModal() on every close: a sign-in, a
    // sign-up, a Google popup that came back, or the reader pressing ✕. Success
    // and dismiss are one answer on purpose — the board asked, the reader
    // answered, and either way the board is where they were standing.
    function authSettled() {
      window._pdxAuthSettled = true;
      return consume();
    }

    return {
      HOME: HOME, PARAM: PARAM, FINDER: FINDER, OK_RE: OK_RE, FRAGMENT: FRAGMENT, JOIN: JOIN,
      sanitize: sanitize, read: read, here: here,
      finderHref: finderHref, consume: consume, settled: settled,
      joinHref: joinHref, wantsJoin: wantsJoin, joinIntent: joinIntent, authSettled: authSettled
    };
  })();
})();
