// ─────────────────────────────────────────────────────────────────────────────
// spotlight-index.js — the front page's card-sized view of the Spotlight shelf
//
// GENERATED FILE. Do not hand-edit: run `node scripts/gen-spotlight-index.mjs`
// (the template lives at scripts/spotlight-index.head.js). scripts/
// test-spotlight-shell.mjs rebuilds it in memory and fails on any drift.
//
// WHAT THIS IS, AND WHAT IT DELIBERATELY IS NOT
// /issue/<slug> is its own document now (spotlight.html), and the 1.2 MB
// spotlights-data.js corpus went with it. But the homepage still legitimately
// needs to KNOW about Spotlights: Local Issues shows the fights near where you
// vote, the profile modal calls out a Spotlight that features the person you
// are reading, search offers them as suggestions. All of that needs a slug, a
// title, a place, a blurb, a few issue keys and the documentation badge —
// roughly 1.5% of the corpus. So this file carries exactly that, and every
// door it feeds is an ordinary navigation to /issue/<slug>.
//
// It is NOT a second Spotlight UI and NOT a reader. There is no timeline here,
// no evidence, no case-for/case-against, no stance roster, no body copy. A
// caller that wants any of that must go to the address. Accordingly:
//   • open(slug) NAVIGATES. It does not open an overlay — there is no overlay
//     on the front page any more, by design.
//   • close() is a no-op kept only so old guarded callers do not throw.
//   • forPolitician() answers from a precomputed id → slug map rather than by
//     scanning 1,260 roster rows that are not here.
// The shape of the records is the subset of the corpus record that the
// homepage actually read, with the same field names, so the consumers that
// were written against window.PDXSpotlight keep working unchanged.
// ─────────────────────────────────────────────────────────────────────────────
(function () {
  'use strict';
  if (window.PDXSpotlight) return; // spotlight-engine.js owns the name on /issue/*

  var ROWS = [{"slug":"government-contracting-influence-waste","title":"Government Contracting, Influence & Waste","eyebrow":"Issue Spotlight","place":"National","updated":"Updated July 18, 2026","blurb":"The federal government spends on the order of $750 billion a year buying goods and services from private companies, and a large share flows to a small number of big contractors. That scale, plus limited competition and a revolving door between agencies and industry, is where waste and influence take root. Here is what is verified and the case on each side.","searchKeywords":"government contracting federal contracts procurement waste fraud abuse no-bid sole source competition usaspending gao high-risk list improper payments 236 billion pentagon audit dod defense contractors lockheed martin raytheon boeing general dynamics northrop grumman f-35 sentinel icbm cost overrun revolving door lobbying influence consultants booz allen deloitte set-aside small business doge department of government efficiency inspector general oversight sole-source bridge contract earmarks lowest price technically acceptable cost-plus fixed-price","primaryIssueKey":"gov_waste","communityIssueKeys":["gov_waste","audit_spending","gov_transparency","national_debt","cut_spending","strong_defense"],"st":{"receipts":0,"strong":0,"sources":6,"level":"strong","label":"Well documented"},"standsIssueKeys":["gov_waste","audit_spending","gov_transparency","national_debt","cut_spending"]},
    {"slug":"trust-institutions-social-capital-2026","title":"Trust in Institutions & the Decline of Social Capital","eyebrow":"Issue Spotlight","place":"National","updated":"Updated July 17, 2026","blurb":"Public confidence in nearly every major institution — government, media, science, business, even churches — sits at or near record lows, while community ties, civic membership, and friendships have frayed. A society runs on trust, so this is a foundational challenge. Here is what is verified and the case on each side.","searchKeywords":"trust in institutions social capital decline civic engagement bowling alone robert putnam loneliness epidemic surgeon general confidence gallup pew media science congress church community associational life polarization civil society national service localism federalism disinformation friendship recession religious attendance volunteering","primaryIssueKey":"gov_transparency","communityIssueKeys":["gov_transparency","democracy_balance","gov_services","religious_liberty"],"st":{"receipts":0,"strong":0,"sources":5,"level":"strong","label":"Well documented"},"standsIssueKeys":["gov_transparency","democracy_balance","gov_services","religious_liberty"]},
    {"slug":"infrastructure-maintenance-crisis-2026","title":"America’s Crumbling Infrastructure & the Maintenance Crisis","eyebrow":"Issue Spotlight","place":"National","updated":"Updated July 17, 2026","blurb":"A generation of deferred maintenance has left thousands of bridges deficient, water systems leaking, and the fund that pays for highways chronically short — even after a historic 2021 law. Keeping the physical backbone of the economy working is foundational to prosperity. Here is what is verified and the case on each side.","searchKeywords":"infrastructure maintenance crisis crumbling roads bridges water systems dams asce report card highway trust fund gas tax insolvency deferred maintenance iija bipartisan infrastructure law lead pipes vmt vehicle miles traveled fee transit transmission backlog investment gap structurally deficient bridges potholes","primaryIssueKey":"infrastructure","communityIssueKeys":["infrastructure","water_storage","gov_services","energy_production"],"st":{"receipts":0,"strong":0,"sources":5,"level":"strong","label":"Well documented"},"standsIssueKeys":["infrastructure","water_storage","gov_services","energy_production"]},
    {"slug":"trade-policy-reshoring-supply-chain-2026","title":"Trade Policy, Reshoring & Supply-Chain Security","eyebrow":"Issue Spotlight","place":"National","updated":"Updated July 17, 2026","blurb":"After decades of free-trade consensus, both parties have turned toward tariffs, reshoring, and treating supply chains as national security. How America trades shapes prices, jobs, and its leverage over rivals. Here is what is verified, what is developing, and the case on each side.","searchKeywords":"trade policy reshoring supply chain security free trade protectionism tariffs trade deficit wto trade agreements usmca nafta china pntr decoupling friend-shoring ally-shoring export controls semiconductors national security globalization realignment smoot hawley comparative advantage industrial policy","primaryIssueKey":"econ_trade","communityIssueKeys":["econ_trade","tariffs_growth","america_first","econ_workers"],"st":{"receipts":0,"strong":0,"sources":5,"level":"strong","label":"Well documented"},"standsIssueKeys":["econ_trade","tariffs_growth","america_first","econ_workers"]},
    {"slug":"food-security-farming-future-2026","title":"Food Security & the Future of American Farming","eyebrow":"Issue Spotlight","place":"National","updated":"Updated July 17, 2026","blurb":"America still grows abundant food, but the farm sector is consolidating, farmers are aging, foreign entities own a growing share of farmland, and the Farm Bill that governs it all is overdue for renewal. Here is what is verified, what is developing, and the case on each side.","searchKeywords":"food security american farming future farm bill agriculture foreign ownership farmland china consolidation family farms aging farmers average age 58 food prices grocery inflation snap nutrition subsidies commodity crops biofuels ethanol supply chain fertilizer rural economy usda reauthorization crop insurance","primaryIssueKey":"rural_ag","communityIssueKeys":["rural_ag","econ_smallbiz","econ_trade","water"],"st":{"receipts":0,"strong":0,"sources":5,"level":"strong","label":"Well documented"},"standsIssueKeys":["rural_ag","econ_smallbiz","econ_trade","water"]},
    {"slug":"veterans-military-readiness-recruitment-2026","title":"Veterans, Military Readiness & the Recruitment Crisis","eyebrow":"Issue Spotlight","place":"National","updated":"Updated July 17, 2026","blurb":"The all-volunteer force has faced some of its toughest recruiting years in a generation, veteran suicide remains a national tragedy, and the VA is caught between reform and expansion. Caring for those who served and keeping the force ready is foundational to national security. Here is what is verified and the case on each side.","searchKeywords":"veterans military readiness recruitment crisis va department of veterans affairs pact act veteran suicide 22 a day homelessness gi bill recruiting shortfall all-volunteer force eligibility obesity community care privatization mission act national guard reserves defense industrial base readiness","primaryIssueKey":"veterans","communityIssueKeys":["veterans","health_mental","healthcare","restraint"],"st":{"receipts":0,"strong":0,"sources":5,"level":"strong","label":"Well documented"},"standsIssueKeys":["veterans","health_mental","healthcare","restraint"]},
    {"slug":"raising-a-family-child-care-cost-2026","title":"The Cost of Raising a Family: Child Care & the Child Tax Credit","eyebrow":"Issue Spotlight","place":"National","updated":"Updated July 17, 2026","blurb":"Child care can cost as much as college, paid family leave is far from universal, and the Child Tax Credit swings with every tax fight — making the price of raising kids a defining kitchen-table issue. Here is what is verified, what is developing, and the case on each side.","searchKeywords":"cost of raising a family child care child tax credit paid family leave affordability child care deserts pre-k early childhood ctc expansion 2021 poverty universal pre-k stay at home parents birth rate family policy pro-family baby bonus daycare cost tuition college of daycare working parents","primaryIssueKey":"family_support","communityIssueKeys":["family_support","child_care","paid_leave","healthcare_costs"],"st":{"receipts":0,"strong":0,"sources":5,"level":"strong","label":"Well documented"},"standsIssueKeys":["family_support","child_care","paid_leave","healthcare_costs"]},
    {"slug":"rural-healthcare-hospital-closures-2026","title":"Rural Healthcare & the Hospital-Closure Crisis","eyebrow":"Issue Spotlight","place":"National · Rural America","updated":"Updated July 17, 2026","blurb":"Rural hospitals are closing or dropping services, maternity wards are vanishing, and provider shortages leave millions far from care. Keeping medicine within reach of rural America is foundational to whether those communities survive. Here is what is verified and the case on each side.","searchKeywords":"rural healthcare hospital closures crisis maternity deserts obstetric units closing critical access hospital physician shortage provider workforce telehealth medicaid reimbursement 340b ambulance ems emergency care rural america aging population workforce pipeline nurse doctor shortage broadband","primaryIssueKey":"health_rural","communityIssueKeys":["health_rural","healthcare","healthcare_costs","health_mental"],"st":{"receipts":0,"strong":0,"sources":5,"level":"strong","label":"Well documented"},"standsIssueKeys":["health_rural","healthcare","healthcare_costs","health_mental"]},
    {"slug":"water-security-western-scarcity-2026","title":"Water Security & the Western Water Crisis","eyebrow":"Issue Spotlight","place":"National · American West","updated":"Updated July 17, 2026","blurb":"The Colorado River that supplies ~40 million people is over-allocated, the Great Salt Lake and the Ogallala Aquifer are shrinking, and the rules governing the river expire at the end of 2026 — forcing hard choices. Here is what is verified, what is developing, and the case on each side.","searchKeywords":"water security western scarcity colorado river lake mead lake powell great salt lake ogallala high plains aquifer drought megadrought interim guidelines 2026 reclamation allocation acre-feet agriculture irrigation conservation reallocation pipeline storage water rights prior appropriation dust snowpack seven states arizona nevada california upper basin lower basin","primaryIssueKey":"water","communityIssueKeys":["water","water_storage","rural_ag","infrastructure"],"st":{"receipts":0,"strong":0,"sources":5,"level":"strong","label":"Well documented"},"standsIssueKeys":["water","water_storage","rural_ag","lands_energy"]},
    {"slug":"fentanyl-addiction-overdose-crisis-2026","title":"The Fentanyl & Addiction Crisis","eyebrow":"Issue Spotlight","place":"National","updated":"Updated July 17, 2026","blurb":"Fentanyl-driven overdoses became the leading cause of death for Americans under 50, peaking above 100,000 a year before a notable recent decline. The crisis links the border, China’s chemical exports, and a strained treatment system. Here is what is verified and the case on each side.","searchKeywords":"fentanyl addiction overdose crisis synthetic opioids deaths cdc precursor chemicals china mexico cartels naloxone narcan treatment recovery harm reduction interdiction border deaths of despair leading cause of death under 50 medication assisted treatment involuntary commitment decriminalization scheduling xylazine tranq public health enforcement","primaryIssueKey":"immig_fentanyl","communityIssueKeys":["immig_fentanyl","health_mental","border_security","justice_reform"],"st":{"receipts":0,"strong":0,"sources":5,"level":"strong","label":"Well documented"},"standsIssueKeys":["health_mental","immig_fentanyl","border_security","justice_balance"]},
    {"slug":"digital-privacy-surveillance-2026","title":"Digital Privacy & Government Surveillance","eyebrow":"Issue Spotlight","place":"National","updated":"Updated July 17, 2026","blurb":"Warrantless surveillance authorities, a booming data-broker economy, facial recognition, and digital-ID proposals mean Americans are tracked as never before — making Fourth Amendment privacy a defining freedom question of the AI age. Here is what is verified and the case on each side.","searchKeywords":"digital privacy government surveillance fisa section 702 warrantless data brokers fourth amendment carpenter facial recognition license plate readers flock digital id ai surveillance backdoor search risaa reauthorization civil liberties nsa location data geofence warrant reform consumer data privacy","primaryIssueKey":"privacy_rights","communityIssueKeys":["privacy_rights","tech_balance","free_speech","gov_transparency"],"st":{"receipts":0,"strong":0,"sources":5,"level":"strong","label":"Well documented"},"standsIssueKeys":["privacy_rights","tech_balance","gov_transparency","free_speech"]},
    {"slug":"congressional-reform-corruption-trust-2026","title":"Government Corruption, Term Limits & Restoring Trust","eyebrow":"Issue Spotlight","place":"National","updated":"Updated July 17, 2026","blurb":"Trust in Congress sits near record lows, yet reforms with overwhelming bipartisan public support — term limits, a ban on congressional stock trading, tighter ethics and transparency — remain stuck. Restoring faith in self-government is foundational to a stable republic. Here is what is verified and the case on each side.","searchKeywords":"government corruption term limits congressional stock trading ban restoring trust transparency ethics revolving door lobbying campaign finance stock act pelosi insider trading approval rating pew gallup twenty second amendment us term limits thornton accountability self-dealing conflict of interest reform mandate","primaryIssueKey":"gov_transparency","communityIssueKeys":["gov_transparency","term_limits","stock_trading_ban","campaign_finance"],"st":{"receipts":0,"strong":0,"sources":5,"level":"strong","label":"Well documented"},"standsIssueKeys":["gov_transparency","term_limits","stock_trading_ban","campaign_finance","gov_waste"]},
    {"slug":"energy-abundance-grid-reliability-2026","title":"Energy Abundance & Grid Reliability","eyebrow":"Issue Spotlight","place":"National","updated":"Updated July 17, 2026","blurb":"For the first time in two decades U.S. electricity demand is climbing fast — driven by data centers, new factories, and electrification — while grid operators warn that firm power is retiring faster than it is being replaced. Here is what is verified, what is developing, and the case on each side.","searchKeywords":"energy abundance grid reliability electricity demand data centers ai power baseload dispatchable coal gas retirements nerc long-term reliability assessment interconnection queue transmission pjm capacity auction eia electrification reshoring operation gigawatt blackout brownout permitting nuclear natural gas renewables solar wind battery storage all of the above energy dominance cost of living electricity prices","primaryIssueKey":"energy_production","communityIssueKeys":["energy_production","infrastructure","datacenter_power","enviro_energy"],"st":{"receipts":0,"strong":0,"sources":5,"level":"strong","label":"Well documented"},"standsIssueKeys":["energy_production","infrastructure","datacenter_power","enviro_energy"]},
    {"slug":"learning-crisis-student-achievement-2026","title":"America’s Learning Crisis: Test Scores & Absenteeism","eyebrow":"Issue Spotlight","place":"National","updated":"Updated July 17, 2026","blurb":"The Nation’s Report Card shows reading at its lowest in decades and math still below pre-pandemic levels, while chronic absenteeism roughly doubled. Because today’s students are tomorrow’s workers and citizens, this is a foundational challenge. Here is what is verified and the case on each side.","searchKeywords":"learning crisis student achievement naep nations report card reading math scores decline pandemic learning loss chronic absenteeism science of reading phonics literacy numeracy mississippi miracle test scores nces tutoring accountability cellphone ban schools education recovery human capital fourth grade eighth grade","primaryIssueKey":"public_schools","communityIssueKeys":["public_schools","edu_balance","school_choice","edu_parental"],"st":{"receipts":0,"strong":0,"sources":5,"level":"strong","label":"Well documented"},"standsIssueKeys":["public_schools","edu_balance","school_choice","edu_parental"]},
    {"slug":"reindustrialization-supply-chains-critical-minerals-2026","title":"Rebuilding American Industry & Supply Chains","eyebrow":"Issue Spotlight","place":"National","updated":"Updated July 17, 2026","blurb":"Decades of offshoring left the U.S. dependent on rivals for critical minerals, medicines, and chips — a prosperity and national-security vulnerability now drawing action from both parties. Here is what is verified, what is developing, and the case on each side.","searchKeywords":"reindustrialization manufacturing supply chains critical minerals rare earths china dependence semiconductors chips act reshoring industrial policy tariffs national security pharmaceuticals active ingredients defense industrial base offshoring manufacturing jobs bls tsmc arizona intel ohio economic security decoupling friendshoring","primaryIssueKey":"econ_trade","communityIssueKeys":["econ_trade","econ_workers","tech_innovation","infrastructure"],"st":{"receipts":0,"strong":0,"sources":5,"level":"strong","label":"Well documented"},"standsIssueKeys":["econ_trade","econ_workers","tech_innovation","econ_growth","infrastructure"]},
    {"slug":"permitting-reform-infrastructure-abundance-2026","title":"Can America Still Build? Permitting & Infrastructure","eyebrow":"Issue Spotlight","place":"National","updated":"Updated July 17, 2026","blurb":"Housing shortages, stalled transmission lines, and slow, costly infrastructure share one root cause: it takes too long and costs too much to build. The cross-partisan “abundance” debate asks how to fix that. Here is what is verified and the case on each side.","searchKeywords":"permitting reform infrastructure abundance nepa environmental review can america build cost to build transmission housing supply zoning transit costs project litigation regulatory delay manchin barrasso fiscal responsibility act ceq environmental impact statement yimby deregulation stranded process housing shortage clean energy queue","primaryIssueKey":"infrastructure","communityIssueKeys":["infrastructure","gov_regulation","housing_build","energy_production"],"st":{"receipts":0,"strong":0,"sources":5,"level":"strong","label":"Well documented"},"standsIssueKeys":["infrastructure","gov_regulation","energy_production","housing_build"]},
    {"slug":"utah-bears-ears-grand-staircase-monument-reductions","title":"Bears Ears & Grand Staircase-Escalante Monument Reductions","eyebrow":"Issue Spotlight","place":"Southern Utah","updated":"Updated July 14, 2026","blurb":"On July 13, 2026, two southern Utah monuments were cut by about 90% (~2.9M acres). The land stays federal but shifts to multiple-use management. Here is what is verified, what is developing, and the case on each side.","searchKeywords":"bears ears grand staircase escalante national monument reduction shrink trump 2026 antiquities act blm public lands multiple use mining oil gas uranium geothermal leasing tribal navajo hopi ute zuni co-stewardship mike lee cox proclamation acres wilderness study area earthjustice","primaryIssueKey":"lands_energy","communityIssueKeys":["lands_energy","water","enviro_energy","property_rights"],"st":{"receipts":0,"strong":0,"sources":4,"level":"moderate","label":"Documented"}},
    {"slug":"utah-wildfires-public-lands-management-2026","title":"Utah Wildfires & Public Lands Management","eyebrow":"Issue Spotlight","place":"Statewide · Utah","updated":"Updated July 16, 2026","blurb":"Utah’s 2026 fire season is among its worst on record — by July 6, more acres had burned than in all of 2021–2025 combined. Behind the smoke is a long-running debate over how public lands should be managed to cut fire risk. Here is what is verified, what is developing, and the case on each side.","searchKeywords":"utah wildfire 2026 fire season babylon cottonwood snyder fire eagle point ski resort beaver san juan grand county acres burned containment fireworks restriction stage 2 cox state of emergency federal land blm forest service thinning prescribed burn grazing logging fix our forests act shared stewardship catastrophic wildfire reduction cheatgrass drought great salt lake climate firefighter staffing wildland fire service inciweb nifc","primaryIssueKey":"disaster_resilience","communityIssueKeys":["disaster_resilience","lands_energy","enviro_energy","water"],"st":{"receipts":0,"strong":0,"sources":4,"level":"moderate","label":"Documented"}},
    {"slug":"tariffs-cost-of-living-inflation","title":"Tariffs & the Cost of Living","eyebrow":"Issue Spotlight","place":"National","updated":"Updated July 16, 2026","blurb":"Since 2025, sweeping new U.S. tariffs pushed the average import tax to its highest level since the 1930s — then the Supreme Court struck down most of them in February 2026. What that means for prices, revenue, and the cost of living is still unfolding. Here is what is verified, what is developing, and the case on each side.","searchKeywords":"tariffs cost of living inflation 2026 liberation day reciprocal tariff ieepa emergency powers section 232 section 301 section 122 steel aluminum autos copper china trade war supreme court learning resources vos selections effective tariff rate consumer prices household cost federal reserve interest rates cpi reshoring manufacturing revenue refunds farmers retaliation congress article i trade authority","primaryIssueKey":"cost_living","communityIssueKeys":["cost_living","tariffs_prices","tariffs_growth","tariffs_authority"],"st":{"receipts":0,"strong":0,"sources":5,"level":"strong","label":"Well documented"},"standsIssueKeys":["econ_trade","tariffs_growth","tariffs_prices","tariffs_authority","tariffs_china","cost_living"]},
    {"slug":"mass-deportations-immigration-enforcement-2026","title":"Mass Deportations & Immigration Enforcement","eyebrow":"Issue Spotlight","place":"National","updated":"Updated July 16, 2026","blurb":"In 2026 interior immigration enforcement scaled up sharply — record detention, ~$170B in new funding from H.R. 1, and a wave of court fights. Here is what is verified, what is developing, and the case on each side.","searchKeywords":"mass deportations immigration enforcement 2026 ice interior enforcement detention laken riley act public law 119-1 one big beautiful bill hr1 obbba funding 170 billion 10000 officers third country removal expedited removal habeas due process sanctuary cities state cooperation worksite raids trump vance noem dhs border security asylum tps daca sovereignty labor agriculture construction cost of living trac migration policy","primaryIssueKey":"border_security","communityIssueKeys":["border_security","deportations","immig_balance","immigration_reform","immig_fentanyl"],"st":{"receipts":0,"strong":0,"sources":4,"level":"moderate","label":"Documented"},"standsIssueKeys":["border_security","deportations","immig_balance","immigration_reform","immig_fentanyl"]},
    {"slug":"housing-affordability-crisis-2026","title":"The Housing Affordability Crisis","eyebrow":"Issue Spotlight","place":"National","updated":"Updated July 16, 2026","blurb":"Buying a home costs far more than five years ago — the payment on a median home nearly doubled since 2020 while mortgage rates sit stuck above 6%. In July 2026 a bipartisan supply-focused housing law became law. Here is what is verified, what is developing, and the case on each side.","searchKeywords":"housing affordability crisis 2026 home prices mortgage rates 6 percent lock-in effect zoning reform yimby abundance single-family zoning adu accessory dwelling unit parking minimums 21st century road to housing act supply shortage 1.2 million 4.7 million units redfin harvard joint center nahb freddie mac rent renters first-time buyers property tax cost of living federal reserve city of yes filtering","primaryIssueKey":"housing_build","communityIssueKeys":["housing_build","housing_support","housing_first_time","cost_living","property_tax"],"st":{"receipts":0,"strong":0,"sources":4,"level":"moderate","label":"Documented"},"standsIssueKeys":["housing_build","housing_support","housing_first_time","housing","cost_living","property_tax"]},
    {"slug":"government-spending-debt-entitlement-reform","title":"Government Spending, Debt & Entitlement Reform","eyebrow":"Issue Spotlight","place":"National","updated":"Updated July 16, 2026","blurb":"The 2026 deficit is about $1.9 trillion, interest on the debt now tops $1 trillion a year, and the Social Security and Medicare trust funds are projected to fall short in the early 2030s. Here is what is verified, what is developing, and the case on each side.","searchKeywords":"national debt deficit federal spending entitlement reform 2026 cbo budget economic outlook interest costs 1 trillion social security medicare trust fund insolvency 2032 2033 oasi hospital insurance doge department of government efficiency rescissions act hr4 mandatory discretionary spending medicaid snap balanced budget amendment fiscal commission payroll tax debt held by public gdp crfb peterson foundation reconciliation public law 119-21","primaryIssueKey":"national_debt","communityIssueKeys":["national_debt","cut_spending","gov_waste","social_security","gov_balance","lower_taxes"],"st":{"receipts":0,"strong":0,"sources":4,"level":"moderate","label":"Documented"},"standsIssueKeys":["national_debt","cut_spending","gov_waste","social_security","gov_balance","lower_taxes"]},
    {"slug":"abortion-rights-state-vs-federal-2026","title":"Abortion Rights & State vs. Federal Battles","eyebrow":"Issue Spotlight","place":"National","updated":"Updated July 16, 2026","blurb":"Since Dobbs, abortion is governed state by state — but the sharpest 2026 fights are federal: the abortion pill in court, the 1873 Comstock Act, and emergency care. Here is what is verified, what is developing, and the case on each side.","searchKeywords":"abortion 2026 dobbs roe state bans ballot measures mifepristone medication abortion louisiana v fda comstock act 1873 emtala moyle idaho fifth circuit supreme court telehealth shield laws misoprostol reproductive rights pro-life pro-choice missouri nevada virginia nebraska guttmacher kff born-alive controlled substances hb7","primaryIssueKey":"pro_life","communityIssueKeys":["pro_life","pro_choice","repro_balance"],"st":{"receipts":0,"strong":0,"sources":4,"level":"moderate","label":"Documented"},"standsIssueKeys":["pro_life","pro_choice","repro_balance"]},
    {"slug":"us-israel-iran-conflict-2026","title":"U.S. Involvement in the Israel-Iran Conflict","eyebrow":"Issue Spotlight","place":"National · Middle East","updated":"Updated July 16, 2026","blurb":"After a 2025 “Twelve-Day War,” the U.S. and Israel launched a larger air campaign against Iran on Feb. 28, 2026; a fragile June ceasefire is now on the brink. Here is what is verified, what is developing, and the case on each side.","searchKeywords":"israel iran conflict 2026 escalation twelve-day war 2025 us strikes fordow natanz isfahan nuclear enrichment ballistic missiles ceasefire april 8 memorandum of understanding versailles pezeshkian khamenei strait of hormuz naval blockade hezbollah lebanon war powers authorization aumf regime change middle east oil prices rubio graham netanyahu deterrence forever war restraint gabbard khanna rand paul","primaryIssueKey":"strong_defense","communityIssueKeys":["strong_defense","foreign_balance","restraint","america_first_fp","veterans"],"st":{"receipts":0,"strong":0,"sources":5,"level":"strong","label":"Well documented"},"standsIssueKeys":["strong_defense","foreign_balance","restraint","america_first_fp","america_first"]},
    {"slug":"us-israel-relations-foreign-aid-partnership-2026","title":"U.S.-Israel Relations, Foreign Aid & Strategic Partnership","eyebrow":"Issue Spotlight","place":"National · U.S. foreign policy","updated":"Updated July 16, 2026","blurb":"The U.S. gives Israel about $3.8 billion a year under a 2016 ten-year agreement, and Israel provides the U.S. intelligence, missile-defense technology, and battlefield testing in return. Here are the hard numbers, the mutual benefits, and the honest debate over cost and conditions.","searchKeywords":"us israel relations foreign aid strategic partnership 2026 memorandum of understanding mou 2016 2019 2028 38 billion 3.8 billion 3.3 billion foreign military financing fmf 500 million missile defense iron dome david sling arrow iron beam qualitative military edge qme major non-nato ally war reserve stockpile wrsa october 7 supplemental 26 billion national security supplemental leahy law nsm-20 conditioning aid offshore procurement aipac quincy institute j street congressional research service largest cumulative recipient","primaryIssueKey":"strong_defense","communityIssueKeys":["strong_defense","foreign_balance","restraint","america_first_fp","national_debt"],"st":{"receipts":0,"strong":0,"sources":6,"level":"strong","label":"Well documented"},"standsIssueKeys":["strong_defense","foreign_balance","restraint","america_first_fp","america_first"]},
    {"slug":"ukraine-russia-war-us-aid-peace-2026","title":"Ukraine-Russia War & U.S. Aid / Peace Negotiations","eyebrow":"Issue Spotlight","place":"National · Eastern Europe","updated":"Updated July 16, 2026","blurb":"President Trump is pushing a rapid negotiated end to the Ukraine war; a U.S. framework would trade territory and bar NATO membership, while a short May 2026 truce held only days. Here is what is verified, what is developing, and the case on each side.","searchKeywords":"ukraine russia war 2026 us aid peace negotiations ceasefire trump plan putin zelensky vance oval office donetsk kharkiv kherson zaporizhzhia nato membership army cap 600000 prisoner exchange victory day rubio umerov miami alaska summit secondary sanctions graham america first not one more penny forever war attrition congress supplemental european counterproposal","primaryIssueKey":"america_first_fp","communityIssueKeys":["america_first_fp","strong_defense","foreign_balance","restraint","america_first"],"st":{"receipts":0,"strong":0,"sources":5,"level":"strong","label":"Well documented"},"standsIssueKeys":["strong_defense","america_first_fp","america_first","restraint","foreign_balance"]},
    {"slug":"voter-id-election-integrity-2026","title":"Voter ID Requirements & Election Integrity","eyebrow":"Issue Spotlight","place":"National","updated":"Updated July 16, 2026","blurb":"About 35 states now ask for some ID at the polls, and a 2026 push — the SAVE Act plus executive orders — would add proof of citizenship to register and photo ID to vote nationwide. Here is what is verified, what is developing, and the case on each side.","searchKeywords":"voter id election integrity 2026 photo id proof of citizenship save act hr 22 hava help america vote act 2002 crawford indiana strict non-strict provisional ballot brennan center ncsl mit election lab noncitizen voting registration real id trump executive order mail voting ballot access voting rights suppression fraud lee ossoff crockett titus","primaryIssueKey":"election_integrity","communityIssueKeys":["election_integrity","election_security","voter_id","voting_access","democracy_balance"],"st":{"receipts":0,"strong":0,"sources":5,"level":"strong","label":"Well documented"},"standsIssueKeys":["election_integrity","election_security","voter_id","voting_access","democracy_balance"]},
    {"slug":"china-taiwan-tensions-us-defense-2026","title":"China-Taiwan Tensions & U.S. Defense Strategy","eyebrow":"Issue Spotlight","place":"National · Indo-Pacific","updated":"Updated July 16, 2026","blurb":"The 2026 U.S. National Defense Strategy calls China the “pacing challenge” and centers deterrence in the Indo-Pacific — yet omits Taiwan by name. How far the U.S. should commit is fiercely debated. Here is what is verified, what is developing, and the case on each side.","searchKeywords":"china taiwan tensions 2026 us defense strategy national defense strategy nds first island chain deterrence by denial strategic ambiguity taiwan relations act 1979 one china policy pla adiz incursions lai ching-te odni threat assessment 2027 invasion tsmc semiconductors silicon shield chip tariffs burden sharing 5% gdp indo-pacific rubio graham nikki haley colby restraint america first","primaryIssueKey":"strong_defense","communityIssueKeys":["strong_defense","america_first_fp","restraint","foreign_balance","tariffs_china"],"st":{"receipts":0,"strong":0,"sources":5,"level":"strong","label":"Well documented"},"standsIssueKeys":["strong_defense","america_first_fp","restraint","foreign_balance","tariffs_china","america_first"]},
    {"slug":"big-tech-censorship-free-speech-2026","title":"Big Tech Censorship vs. Free Speech","eyebrow":"Issue Spotlight","place":"National","updated":"Updated July 16, 2026","blurb":"Do social-media platforms “censor” lawful speech, or do they have their own First Amendment right to moderate? Recent Supreme Court cases left the biggest questions unresolved. Here is what is verified, what is developing, and the case on each side.","searchKeywords":"big tech censorship free speech 2026 content moderation section 230 first amendment murthy v missouri jawboning netchoice moody paxton texas hb20 florida sb7072 deplatforming social media supreme court age verification kids online safety utah social media regulation act jim jordan vance hawley trump executive order restoring freedom of speech","primaryIssueKey":"free_speech","communityIssueKeys":["free_speech","tech_balance","tech_innovation","privacy_rights","gov_regulation"],"st":{"receipts":0,"strong":0,"sources":5,"level":"strong","label":"Well documented"},"standsIssueKeys":["tech_balance","free_speech","gov_regulation","tech_innovation","privacy_rights"]},
    {"slug":"federal-reserve-inflation-control-2026","title":"Federal Reserve Policy & Inflation Control","eyebrow":"Issue Spotlight","place":"National","updated":"Updated July 16, 2026","blurb":"The Fed has held its benchmark rate at 3.5–3.75% into 2026 with inflation stuck near 3%, defying President Trump’s calls for aggressive cuts amid an escalating fight over the Fed’s independence. Here is what is verified, what is developing, and the case on each side.","searchKeywords":"federal reserve fed 2026 interest rates inflation control jerome powell fomc rate cut hold monetary policy independence trump pressure kevin warsh lisa cook doj investigation dual mandate cpi pce 2 percent target tariffs energy prices national debt 39 trillion audit the fed borrowing costs mortgage rates recession soft landing","primaryIssueKey":"cost_living","communityIssueKeys":["cost_living","econ_growth","national_debt","lower_taxes","tariffs_prices"],"st":{"receipts":0,"strong":0,"sources":5,"level":"strong","label":"Well documented"},"standsIssueKeys":["cost_living","econ_growth","national_debt","lower_taxes","tariffs_prices"]},
    {"slug":"transgender-rights-sports-youth-care-2026","title":"Transgender Rights, Sports & Youth Medical Care","eyebrow":"Issue Spotlight","place":"National","updated":"Updated July 16, 2026","blurb":"After the Supreme Court’s 2025 Skrmetti ruling, states may ban gender-affirming care for minors, and trans-athlete sports bans have been upheld — creating a sharp state-by-state divide. Here is what is verified, what is developing, and the case on each side.","searchKeywords":"transgender rights 2026 sports youth medical care gender-affirming care puberty blockers hormones minors skrmetti tennessee sb1 supreme court rational basis title ix hecox bpj idaho west virginia athletes womens sports state bans parental rights cass review section 1557 executive order lambda legal aclu records hegseth military","primaryIssueKey":"lgbtq_rights","communityIssueKeys":["lgbtq_rights","rights_balance","edu_parental","medical_freedom","health_balance"],"st":{"receipts":0,"strong":0,"sources":5,"level":"strong","label":"Well documented"},"standsIssueKeys":["lgbtq_rights","rights_balance","edu_parental","medical_freedom"]},
    {"slug":"electric-vehicles-mandates-energy-2026","title":"Electric Vehicles, Mandates & Energy Independence","eyebrow":"Issue Spotlight","place":"National","updated":"Updated July 16, 2026","blurb":"Federal EV tax credits ended in late 2025, and the administration is rolling back the Biden-era tailpipe standards critics call an “EV mandate” while pushing to expand oil and gas. Here is what is verified, what is developing, and the case on each side.","searchKeywords":"electric vehicles ev mandate 2026 energy independence epa tailpipe clean car standards endangerment finding 2009 tax credit 7500 30d 25e 45w charger 30c one big beautiful bill unleashing american energy executive order california waiver drilling lng oil gas coal transportation freedom act batteries critical minerals china grid climate","primaryIssueKey":"enviro_energy","communityIssueKeys":["enviro_energy","energy_production","climate_action","enviro_balance","lands_energy"],"st":{"receipts":0,"strong":0,"sources":5,"level":"strong","label":"Well documented"},"standsIssueKeys":["enviro_energy","energy_production","climate_action","enviro_balance","lands_energy"]},
    {"slug":"ai-regulation-job-displacement-2026","title":"AI Regulation, Job Displacement & Tech Power","eyebrow":"Issue Spotlight","place":"National","updated":"Updated July 16, 2026","blurb":"There is no comprehensive federal AI law — just a December 2025 executive order pushing a light-touch framework, a fight to override state AI laws, and an early debate over AI’s effect on jobs. Here is what is verified, what is developing, and the case on each side.","searchKeywords":"ai regulation 2026 artificial intelligence job displacement automation tech power executive order 14365 national framework doj litigation task force state ai laws moratorium california sb 53 frontier model texas colorado bead broadband preemption federalism warner rounds economy of the future clarity act automation tax ubi layoffs data centers","primaryIssueKey":"tech_balance","communityIssueKeys":["tech_balance","gov_regulation","tech_innovation","econ_workers","datacenter_power"],"st":{"receipts":0,"strong":0,"sources":5,"level":"strong","label":"Well documented"},"standsIssueKeys":["tech_balance","gov_regulation","tech_innovation","econ_workers","datacenter_power"]},
    {"slug":"social-security-medicare-solvency-2026","title":"Social Security & Medicare Solvency","eyebrow":"Issue Spotlight","place":"National","updated":"Updated July 16, 2026","blurb":"The 2026 Trustees Reports say Social Security can pay full benefits only through about 2032 and Medicare’s hospital fund through about 2033 — after which automatic cuts hit unless Congress acts. Here is what is verified, what is developing, and the case on each side.","searchKeywords":"social security medicare solvency 2026 trustees report oasi trust fund 2032 2033 insolvency 22 percent 28 percent benefit cut hospital insurance part a payroll tax cap retirement age means testing cola reform revenue entitlement one big beautiful bill senior deduction greenspan commission 1983 aarp crfb cbo","primaryIssueKey":"social_security","communityIssueKeys":["social_security","national_debt","healthcare"],"st":{"receipts":0,"strong":0,"sources":5,"level":"strong","label":"Well documented"},"standsIssueKeys":["social_security","national_debt","healthcare"]},
    {"slug":"border-security-asylum-reform-2026","title":"Border Security & Asylum System Reform","eyebrow":"Issue Spotlight","place":"National · U.S.–Mexico Border","updated":"Updated July 16, 2026","blurb":"Border crossings have fallen to their lowest levels since the 1960s while access to asylum is effectively suspended and litigation continues. Here is what is verified, what is developing, and the case on each side.","searchKeywords":"border security asylum reform 2026 crossings encounters cbp border patrol title 8 metering credible fear proclamation suspending asylum cbp one parole remain in mexico noem al otro lado laken riley act border wall construction ports of entry fentanyl migrants 60-year low family units single adults dhs","primaryIssueKey":"border_security","communityIssueKeys":["border_security","immig_balance","immigration_reform","immig_fentanyl","deportations"],"st":{"receipts":0,"strong":0,"sources":5,"level":"strong","label":"Well documented"},"standsIssueKeys":["border_security","immig_balance","immigration_reform","immig_fentanyl","deportations"]},
    {"slug":"cryptocurrency-regulation-cbdc-debate-2026","title":"Cryptocurrency Regulation & the CBDC Debate","eyebrow":"Issue Spotlight","place":"National · Financial regulation","updated":"Updated July 16, 2026","blurb":"Congress has enacted the first federal stablecoin framework, but the broader crypto rulebook and the fight over a government-issued digital dollar remain unsettled. Here is what is law, what is pending, and the strongest case on each side.","searchKeywords":"cryptocurrency regulation cbdc debate 2026 bitcoin stablecoin genius act public law 119 27 clarity act digital asset market structure sec cftc treasury federal reserve central bank digital currency anti surveillance digital dollar financial privacy consumer protection illicit finance reserve requirements","primaryIssueKey":"crypto_cbdc","communityIssueKeys":["crypto_cbdc","tech_innovation","gov_regulation","privacy_rights","econ_corp_account"],"st":{"receipts":0,"strong":0,"sources":5,"level":"strong","label":"Well documented"},"standsIssueKeys":["crypto_cbdc"]},
    {"slug":"school-choice-education-reform-parental-rights-2026","title":"School Choice, Education Reform & Parental Rights","eyebrow":"Issue Spotlight","place":"National · State-by-state implementation","updated":"Updated July 16, 2026","blurb":"School choice has moved from a mostly state-level fight to a national tax-credit program beginning in 2027, while states keep battling over vouchers, accountability, curriculum, and parents’ authority. Here is what changed and why it remains contested.","searchKeywords":"school choice education reform parental rights 2026 vouchers education savings accounts esa charter schools homeschool education freedom tax credit scholarship granting organizations 2027 state opt in public school funding accountability special education religious schools curriculum books parents bill of rights utah fits all","primaryIssueKey":"school_choice","communityIssueKeys":["school_choice","edu_parental","public_schools","edu_balance","religious_liberty"],"st":{"receipts":0,"strong":0,"sources":5,"level":"strong","label":"Well documented"},"standsIssueKeys":["school_choice","edu_parental","public_schools","edu_balance"]},
    {"slug":"prescription-drug-prices-pharmaceutical-reform-2026","title":"Prescription Drug Prices & Pharmaceutical Reform","eyebrow":"Issue Spotlight","place":"National · Medicare and commercial markets","updated":"Updated July 16, 2026","blurb":"Medicare’s first negotiated prices are now in effect, seniors have a yearly Part D spending cap, and the administration is pursuing international-reference pricing while Congress debates PBM reform. Here is what patients are seeing and why the fight continues.","searchKeywords":"prescription drug prices pharmaceutical reform 2026 medicare negotiation maximum fair price inflation reduction act part d out of pocket cap 2100 insulin 35 dollars pbm pharmacy benefit managers rebates spread pricing most favored nation trump executive order pharma innovation generic biosimilar patents orange book ftc","primaryIssueKey":"health_drug_prices","communityIssueKeys":["health_drug_prices","healthcare_costs","healthcare_market","social_security","econ_corp_account"],"st":{"receipts":0,"strong":0,"sources":6,"level":"strong","label":"Well documented"},"standsIssueKeys":["health_drug_prices","healthcare_costs","healthcare_market"]},
    {"slug":"mental-health-gun-violence-prevention-2026","title":"Mental Health Crisis & Gun Violence Prevention","eyebrow":"Issue Spotlight","place":"National · Federal and state","updated":"Updated July 16, 2026","blurb":"Firearm injury is now the leading cause of death for U.S. children and teens, most gun deaths are suicides, and the mental-health system is strained. Here is what the data show, what the law does, and where the two debates meet — and diverge.","searchKeywords":"mental health crisis gun violence prevention 2026 988 suicide crisis lifeline red flag law extreme risk protection order erpo bipartisan safer communities act background checks assault weapons ban second amendment bruen rahimi safe storage youth suicide firearm deaths leading cause children teens ccbhc community mental health nami samhsa rand giffords everytown nra","primaryIssueKey":"gun_safety","communityIssueKeys":["gun_safety","gun_balance","health_mental","gun_rights","healthcare"],"st":{"receipts":0,"strong":0,"sources":5,"level":"strong","label":"Well documented"},"standsIssueKeys":["gun_safety","gun_balance","health_mental","gun_rights"]},
    {"slug":"universal-basic-income-ai-job-displacement-2026","title":"Universal Basic Income & AI-Driven Job Displacement Solutions","eyebrow":"Issue Spotlight","place":"National · Federal, state, and local pilots","updated":"Updated July 16, 2026","blurb":"As AI reshapes work, an old idea is back in the debate: send people money with no strings attached. Here is what universal basic income actually is, what the pilots found, the alternatives, and the case on each side.","searchKeywords":"universal basic income ubi guaranteed income ai job displacement automation 2026 stockton seed openresearch sam altman alaska permanent fund dividend automation tax robot tax retraining wioa wage insurance portable benefits earned income tax credit negative income tax future of work reskilling worker transition andrew yang freedom dividend","primaryIssueKey":"econ_workers","communityIssueKeys":["econ_workers","tech_balance","tech_innovation","gov_regulation","econ_balance"],"st":{"receipts":0,"strong":0,"sources":5,"level":"strong","label":"Well documented"},"standsIssueKeys":["econ_workers","tech_balance","tech_innovation","gov_regulation","datacenter_power"]},
    {"slug":"crime-criminal-justice-reform-urban-safety-2026","title":"Crime, Criminal Justice Reform & Urban Safety","eyebrow":"Issue Spotlight","place":"National · Federal, state, and local","updated":"Updated July 16, 2026","blurb":"Violent crime and murder have fallen sharply from their 2020–2021 peak, yet many Americans believe crime is rising. Here is what the data show, why enforcement and reform advocates read them differently, and where the fight goes next.","searchKeywords":"crime criminal justice reform urban safety 2026 violent crime murder rate decline fbi ucr nibrs council on criminal justice first step act bail reform retail theft recidivism reentry fentanyl halt fentanyl act policing defund refund police perception gap national guard dc federalization brennan center marshall project","primaryIssueKey":"back_police","communityIssueKeys":["back_police","tough_on_crime","justice_balance","justice_reform","cannabis_reform"],"st":{"receipts":0,"strong":0,"sources":5,"level":"strong","label":"Well documented"},"standsIssueKeys":["back_police","tough_on_crime","justice_balance","justice_reform","cannabis_reform"]},
    {"slug":"campus-free-speech-university-protests-2026","title":"Campus Free Speech & University Protests","eyebrow":"Issue Spotlight","place":"National · Higher education","updated":"Updated July 16, 2026","blurb":"Campus protests, antisemitism complaints, DEI bans, and federal funding threats have collided on American campuses. Here is what the law actually protects, what it does not, and the honest debate over speech, protest, and university power.","searchKeywords":"campus free speech university protests 2026 first amendment public private university encampments columbia harvard antisemitism task force federal funding cuts research grants visa revocation student activists mahmoud khalil due process fire foundation individual rights expression aclu aaup dei ban institutional neutrality kalven heckler veto time place manner deplatforming academic freedom title vi office civil rights","primaryIssueKey":"free_speech","communityIssueKeys":["free_speech","rights_balance","end_dei","edu_parental","religious_liberty"],"st":{"receipts":0,"strong":0,"sources":5,"level":"strong","label":"Well documented"},"standsIssueKeys":["free_speech","rights_balance","end_dei","religious_liberty","edu_parental"]},
    {"slug":"pandemic-preparedness-gain-of-function-2026","title":"Pandemic Preparedness & Gain-of-Function Research","eyebrow":"Issue Spotlight","place":"National · Public health and biosecurity","updated":"Updated July 16, 2026","blurb":"How should the U.S. prepare for the next pandemic — and how tightly should it control the risky research meant to study one? Here is what the rules say, what is known versus unproven, and the honest debate.","searchKeywords":"pandemic preparedness gain-of-function research 2026 gain of function p3co durc pepp dual use research concern pathogens enhanced pandemic potential biosecurity lab leak covid origins wuhan ecohealth nih fauci rand paul risky research review act executive order may 2025 strategic national stockpile pahpa cdc reform hhs rfk jr acip vaccines mandates medical freedom bioweapons johns hopkins center health security odni","primaryIssueKey":"medical_freedom","communityIssueKeys":["medical_freedom","healthcare","health_balance","gov_regulation","reform_balance"],"st":{"receipts":0,"strong":0,"sources":5,"level":"strong","label":"Well documented"},"standsIssueKeys":["medical_freedom","healthcare","health_balance","reform_balance","gov_regulation"]},
    {"slug":"nuclear-energy-revival-renewable-mandates-2026","title":"Nuclear Energy Revival vs. Renewable Mandates","eyebrow":"Issue Spotlight","place":"National · Energy and the grid","updated":"Updated July 16, 2026","blurb":"Soaring electricity demand from data centers and electrification has revived nuclear power and reignited the fight over renewable mandates. Here are the real numbers, what is proven versus promised, and the honest case for each path.","searchKeywords":"nuclear energy revival renewable mandates 2026 small modular reactor smr advance act 2024 nrc licensing trump executive order 400 gw 2050 three mile island crane palisades restart vogtle terrapower natrium x-energy uranium enrichment data center ai power demand grid reliability renewable portfolio standard clean energy standard inflation reduction act credits solar wind storage baseload firm clean power union of concerned scientists nuclear energy institute","primaryIssueKey":"energy_production","communityIssueKeys":["energy_production","enviro_energy","climate_action","enviro_balance","datacenter_power"],"st":{"receipts":0,"strong":0,"sources":5,"level":"strong","label":"Well documented"},"standsIssueKeys":["energy_production","enviro_energy","climate_action","enviro_balance","lands_energy"]},
    {"slug":"declining-birth-rates-family-formation-2026","title":"Declining Birth Rates & the Family Formation Crisis","eyebrow":"Issue Spotlight","place":"National · Demography and family policy","updated":"Updated July 16, 2026","blurb":"The U.S. birth rate has fallen well below the level needed to replace the population, with long-run consequences for the workforce, Social Security, and growth. Here are the numbers, the root causes, and the honest debate over what — if anything — government should do.","searchKeywords":"declining birth rates family formation crisis 2026 fertility rate replacement 2.1 total fertility rate 1.6 baby bust natalism pronatalism child tax credit trump accounts baby bonus paid family leave childcare costs marriage rate delayed marriage housing affordability student debt dependency ratio social security medicare workforce immigration demographic decline vance orban hungary south korea","primaryIssueKey":"family_support","communityIssueKeys":["family_support","child_care","paid_leave","housing_first_time","tax_middle_class"],"st":{"receipts":0,"strong":0,"sources":5,"level":"strong","label":"Well documented"},"standsIssueKeys":["family_support","child_care","paid_leave","tax_middle_class"]},
    {"slug":"obesity-chronic-disease-healthcare-costs-2026","title":"Obesity, Chronic Disease & the Healthcare Cost Explosion","eyebrow":"Issue Spotlight","place":"National · Public health and healthcare costs","updated":"Updated July 16, 2026","blurb":"Chronic diseases like obesity and diabetes drive the vast majority of U.S. healthcare spending, and the \"Make America Healthy Again\" agenda has made them a political flashpoint. Here are the numbers, the root causes, and the honest debate over mandates versus markets and personal responsibility.","searchKeywords":"obesity chronic disease healthcare cost explosion 2026 make america healthy again maha rfk jr ultra-processed food snap soda ban food dyes school lunch nutrition standards glp-1 ozempic wegovy medicare medicaid coverage diabetes heart disease preventable prevention personal responsibility food industry farm subsidies price transparency 90 percent healthcare spending chronic conditions","primaryIssueKey":"healthcare_costs","communityIssueKeys":["healthcare_costs","healthcare_market","medical_freedom","health_balance","healthcare"],"st":{"receipts":0,"strong":0,"sources":5,"level":"strong","label":"Well documented"},"standsIssueKeys":["healthcare_costs","healthcare_market","medical_freedom","health_balance"]},
    {"slug":"social-media-youth-mental-health-2026","title":"Social Media, Loneliness & the Youth Mental Health Collapse","eyebrow":"Issue Spotlight","place":"National · Youth, technology, and mental health","updated":"Updated July 16, 2026","blurb":"Teen depression, anxiety, and loneliness have climbed alongside smartphones and social media, and governments are moving to regulate. Here are the numbers, the debate over whether social media is the cause, and the honest fight over mandates versus free speech.","searchKeywords":"social media loneliness youth mental health collapse 2026 teen depression anxiety suicide smartphones jonathan haidt anxious generation surgeon general warning label age verification kids online safety act kosa utah social media law netchoice first amendment phone-free schools cell phone bans loneliness epidemic screen time algorithm section 230 parental consent","primaryIssueKey":"health_mental","communityIssueKeys":["health_mental","tech_balance","privacy_rights","edu_parental","gov_regulation"],"st":{"receipts":0,"strong":0,"sources":5,"level":"strong","label":"Well documented"},"standsIssueKeys":["health_mental","tech_balance","privacy_rights","edu_parental"]},
    {"slug":"administrative-state-regulatory-power-2026","title":"The Administrative State, Regulatory Power & Post-Chevron Reform","eyebrow":"Issue Spotlight","place":"National · Government power and structure","updated":"Updated July 16, 2026","blurb":"Who actually makes the rules Americans live under — Congress, the courts, or federal agencies? After the Supreme Court ended \"Chevron deference,\" that question is being rewritten. Here is what changed, what reforms are proposed, and the power-versus-accountability debate.","searchKeywords":"administrative state regulatory power post-chevron 2026 loper bright chevron deference supreme court major questions doctrine schedule f federal workforce civil service deregulation executive orders congressional review act nondelegation west virginia epa omb russ vought dismantling agencies rulemaking separation of powers unelected bureaucrats regulatory reform paperwork red tape","primaryIssueKey":"gov_regulation","communityIssueKeys":["gov_regulation","reform_balance","gov_waste","cut_spending","gov_transparency"],"st":{"receipts":0,"strong":0,"sources":5,"level":"strong","label":"Well documented"},"standsIssueKeys":["gov_regulation","reform_balance","gov_waste","cut_spending","audit_spending"]},
    {"slug":"student-loan-debt-higher-education-cost-2026","title":"Student Loan Debt & the Cost of Higher Education","eyebrow":"Issue Spotlight","place":"National · Higher education and the economy","updated":"Updated July 16, 2026","blurb":"Americans owe about $1.7 trillion in student loans, tuition has far outpaced inflation, and the fight over forgiveness, repayment, and college value is unresolved. Here are the numbers, the root causes, and the honest debate over who should pay.","searchKeywords":"student loan debt higher education cost 2026 1.7 trillion forgiveness cancellation save plan repayment supreme court biden borrower defense income driven repayment pell grant tuition inflation college roi apprenticeship trade school workforce accountability gainful employment public service loan forgiveness pslf default resumption garnishment","primaryIssueKey":"edu_college_cost","communityIssueKeys":["edu_college_cost","edu_balance","econ_workers","national_debt","tax_middle_class"],"st":{"receipts":0,"strong":0,"sources":5,"level":"strong","label":"Well documented"},"standsIssueKeys":["edu_college_cost","edu_balance","econ_workers"]},
    {"slug":"high-skilled-immigration-h1b-visas-2026","title":"High-Skilled Immigration, H-1B Visas & the Talent Debate","eyebrow":"Issue Spotlight","place":"National · Immigration and the workforce","updated":"Updated July 16, 2026","blurb":"Should the U.S. import more high-skilled workers to stay competitive, or protect American workers from being undercut? A 2025 shakeup to H-1B fees reignited the fight. Here are the numbers and the honest debate.","searchKeywords":"high-skilled immigration h-1b visas talent debate 2026 100000 fee proclamation lottery cap 85000 stem opt green card backlog eb-1 eb-2 country cap tech workers displacement wage floor prevailing wage outsourcing american workers global talent merit-based points system o-1 genius visa startup","primaryIssueKey":"immigration_reform","communityIssueKeys":["immigration_reform","immig_balance","econ_workers","tech_innovation","econ_growth"],"st":{"receipts":0,"strong":0,"sources":5,"level":"strong","label":"Well documented"},"standsIssueKeys":["immigration_reform","immig_balance","border_security","econ_workers"]},
    {"slug":"jeffrey-epstein-case-accountability-2026","title":"The Jeffrey Epstein Case, Connections & Accountability","eyebrow":"Issue Spotlight","place":"National","updated":"Updated July 19, 2026","blurb":"A calm, documented look at the Epstein case: the established facts, what has been released, what remains sealed or unknown, and the accountability questions — sticking to the public record and flagging the gaps.","searchKeywords":"jeffrey epstein case 2026 ghislaine maxwell conviction files documents released doj fbi memo client list suicide 2019 2008 plea deal non-prosecution agreement giuffre v maxwell unsealed epstein files transparency act khanna massie discharge petition house oversight redactions special master accountability","primaryIssueKey":"gov_transparency","communityIssueKeys":["gov_transparency","justice_balance","justice_reform"],"st":{"receipts":0,"strong":0,"sources":8,"level":"strong","label":"Well documented"},"standsIssueKeys":["gov_transparency"]},
    {"slug":"one-big-beautiful-bill-hr1","title":"The One Big Beautiful Bill Act (H.R. 1)","eyebrow":"Issue Spotlight","place":"U.S. Congress · Washington, D.C.","updated":"Updated July 2026","blurb":"One law seen from every seat: Trump signed it, Vance broke the 51–50 Senate tie, Jeffries spoke for 8h44m against it. Here is who stood where — with the recorded votes.","searchKeywords":"hr1 h.r.1 h.r. 1 one big beautiful bill act obbba reconciliation 2025 tax law trump vance thune jeffries schumer johnson scalise barrasso emmer jason smith cruz aoc crockett khanna sanders rand paul durbin clark medicaid snap tax cuts deficit debt cbo tie-breaking vote 218-214 51-50 signed july 4 roll call 190","primaryIssueKey":"lower_taxes","communityIssueKeys":["lower_taxes","healthcare","national_debt","cut_spending","border_security"],"st":{"receipts":11,"strong":11,"sources":4,"level":"strong","label":"Strongly documented"}},
    {"slug":"box-elder-stratos-data-center","title":"The Stratos Data Center","eyebrow":"Issue Spotlight","place":"Box Elder County, Utah","updated":"Updated June 2026","blurb":"A proposed hyperscale data center near the Great Salt Lake — who approved it, the water-rights fight, and the primary that unseated two commissioners.","searchKeywords":"stratos data center box elder county great salt lake water rights mida hyperscale referendum commission tueller smith perry bingham vincent","primaryIssueKey":"property_rights","communityIssueKeys":["property_rights","water","gov_transparency","gov_services"],"st":{"receipts":8,"strong":5,"sources":4,"level":"strong","label":"Strongly documented"}},
    {"slug":"utah-county-alpine-school-district-split","title":"The Alpine School District Split","eyebrow":"Issue Spotlight","place":"Utah County, Utah","updated":"Updated June 2026","blurb":"Voters broke up Utah’s largest school district into three. On the way out, the old board raised taxes 5–2 and bonded $238M — here’s who stood where.","searchKeywords":"alpine school district split utah county aspen peaks lake mountain timpanogos west district tax increase property tax 238 million bond lease revenue truth in taxation saratoga springs eagle mountain bateman beeson wilson brammer hb3003 prop 11 prop 14 dissolution","primaryIssueKey":"public_schools","communityIssueKeys":["public_schools","property_tax","housing_build","gov_waste"],"st":{"receipts":11,"strong":6,"sources":6,"level":"strong","label":"Strongly documented"}},
    {"slug":"utah-county-saratoga-springs-public-safety-tax","title":"The Saratoga Springs Public-Safety Tax","eyebrow":"Issue Spotlight","place":"Utah County, Utah","updated":"Updated June 2026","blurb":"One of Utah County’s fastest-growing cities is weighing its first property-tax increase since 2008 — about $200 a year — to keep police and fire funded. Here’s the proposal, in context.","searchKeywords":"saratoga springs public safety property tax increase utah county chris carn mayor truth in taxation 2008 police fire ems fire station 2028 growth budget shortfall lehi free press hansen hd51 proposal 3.1 million first since 2008 nonpartisan","primaryIssueKey":"property_tax","communityIssueKeys":["property_tax","back_police","housing_build","gov_transparency"],"st":{"receipts":5,"strong":0,"sources":5,"level":"strong","label":"Well documented"}},
    {"slug":"utah-county-vineyard-spending-scandal","title":"The Vineyard “Utah City” Spending Fight","eyebrow":"Issue Spotlight","place":"Vineyard · Utah County, Utah","updated":"Updated June 2026","blurb":"A State Auditor review found Vineyard failed to report $35M+, an audit flagged purchase-card misuse, and voters curbed the mayor’s office 74% — here’s who stood where.","searchKeywords":"vineyard utah city geneva steel spending scandal state auditor unreported transactions 35 million purchase card audit redevelopment agency rda prop 10 mayor council reform julie fullmer jacob holdaway zack stratton transparency utah county trade mission","primaryIssueKey":"gov_transparency","communityIssueKeys":["gov_transparency","housing_build","gov_services","gov_waste"],"st":{"receipts":10,"strong":5,"sources":6,"level":"strong","label":"Strongly documented"}},
    {"slug":"utah-county-eagle-mountain-data-centers","title":"Eagle Mountain’s Data Centers & Water","eyebrow":"Issue Spotlight","place":"Utah County, Utah","updated":"Updated July 2026","blurb":"Eagle Mountain has become one of Utah’s biggest data-center hubs. Mayor Jared Gray calls the campuses “literally what funds our general fund” — as the city’s water use, and a once-secret water agreement, draw scrutiny.","searchKeywords":"eagle mountain data center data centers water meta google qts campus jared gray mayor general fund revenue property tax sales tax incentives confidential water agreement secret hb 76 water reporting transparency utah county emily buss growth great salt lake drought","primaryIssueKey":"water","communityIssueKeys":["water","gov_transparency","gov_services","infrastructure"],"st":{"receipts":6,"strong":0,"sources":4,"level":"strong","label":"Well documented"}},
    {"slug":"maha-food-system-additives-2026","title":"MAHA & the Food System: Additives, Dyes, and What’s in Our Food","eyebrow":"Issue Spotlight","place":"National · Food safety and public health","updated":"Updated July 18, 2026","blurb":"The \"Make America Healthy Again\" movement put the food supply itself on the agenda — synthetic dyes, additives, and ultra-processed foods. Here is what is actually in the food, how the FDA reviews it, what is changing, and the honest debate over how far government should go.","searchKeywords":"maha make america healthy again rfk robert kennedy jr hhs food dyes red 3 red 40 yellow 5 6 blue 1 petroleum synthetic dyes additives ultra-processed food upf gras generally recognized as safe fda loophole titanium dioxide bha bht potassium bromate brominated vegetable oil bvo seed oils snap soda candy school lunch whole milk food industry regulation childhood chronic disease maha report front-of-package labeling","primaryIssueKey":"health_balance","communityIssueKeys":["health_balance","healthcare","medical_freedom","gov_regulation","rural_ag"],"st":{"receipts":0,"strong":0,"sources":5,"level":"strong","label":"Well documented"},"standsIssueKeys":["health_balance","healthcare","medical_freedom","gov_regulation"]},
    {"slug":"pesticides-liability-regulation-2026","title":"Pesticides: Liability Shields, Glyphosate & Chemical Regulation","eyebrow":"Issue Spotlight","place":"National · Agriculture, environmental health, and the courts","updated":"Updated July 18, 2026","blurb":"When a weedkiller is approved by the EPA but later linked to harm, who is liable — and how tightly should Washington regulate the chemicals farmers rely on? Here is the record on liability shields, the glyphosate fight, the specific pesticides in dispute, and the honest case on each side.","searchKeywords":"pesticides herbicides insecticides glyphosate roundup bayer monsanto liability shield failure to warn fifra epa label preemption bates v dow right to sue iarc probably carcinogenic ninth circuit atrazine endocrine chlorpyrifos organophosphate children paraquat parkinsons dicamba drift neonicotinoids bees pollinators farmworkers worker protection standard food quality protection act crop tools farm bill preemption rider","primaryIssueKey":"enviro_balance","communityIssueKeys":["enviro_balance","econ_corp_account","gov_regulation","rural_ag","health_balance"],"st":{"receipts":0,"strong":0,"sources":5,"level":"strong","label":"Well documented"},"standsIssueKeys":["enviro_balance","econ_corp_account","gov_regulation","health_balance"]},
    {"slug":"pfas-forever-chemicals-2026","title":"PFAS “Forever Chemicals”: Drinking Water, Health & Cleanup","eyebrow":"Issue Spotlight","place":"National · Drinking water, environmental health, and cleanup","updated":"Updated July 18, 2026","blurb":"PFAS \"forever chemicals\" are in most Americans’ blood and in drinking water nationwide. Here is what they are, what the health science does and doesn’t show, the fight over federal limits and who pays to clean them up, and the honest case on each side.","searchKeywords":"pfas per polyfluoroalkyl forever chemicals pfoa pfos genx hfpo-da pfhxs pfna pfbs drinking water mcl 4 ppt maximum contaminant level epa 2024 rule 2025 rollback rescind hazard index superfund cercla hazardous substance passive receiver tsca new chemicals approval regrettable substitution afff firefighting foam military base contamination 3m dupont chemours corteva settlement water utilities maine minnesota amaras law product ban biosolids sludge farmland pfas in blood","primaryIssueKey":"enviro_balance","communityIssueKeys":["enviro_balance","water","gov_regulation","econ_corp_account","health_balance"],"st":{"receipts":0,"strong":0,"sources":5,"level":"strong","label":"Well documented"},"standsIssueKeys":["enviro_balance","water","gov_regulation","econ_corp_account"]}];

  var BY_PERSON = {"grassley":[0,1,11,18,37,40,58],
    "comer":[0,1,21],
    "jon_ossoff":[0,1,11,24,26,32,37],
    "whitehouse":[0,1,12,58,59],
    "collins":[0,1,15,21,22,24,47],
    "thune":[0,1,3,18,21,24,51],
    "crockett":[1,11,19,21,26,34,50,51],
    "dina_titus":[1,2,22,26,34],
    "julie_fedorchak":[1,4,7,9,11,12,15,40,43],
    "jon_atkin":[1],
    "mwinder":[1],
    "michael_guest":[1,11],
    "stephanie_bice":[1,2,5],
    "roy_cooper":[1,22],
    "booker":[1,6,40,44,49,57,58,59],
    "raskin":[1,32,34,47],
    "schiff":[1,32],
    "aguilar":[1,21,34],
    "warnock":[1,24],
    "robert_garcia":[1,19,34],
    "angus_king":[1,12,24],
    "ted_lieu":[1,24,32],
    "tillis":[1,21,25,34],
    "clyburn":[1],
    "nadler":[1],
    "merkley":[1,12],
    "dan_goldman":[1,24],
    "hirono":[1,34],
    "andy_kim":[1,24],
    "maxwell_frost":[1],
    "neguse":[1],
    "jim_himes":[1,25,27],
    "zoe_lofgren":[1,32],
    "steny_hoyer":[1,21,24],
    "curtis":[2,3,10,12,14,15,18,19,26,29,31,33,34,35,43,46],
    "bennie_thompson":[2],
    "mike_ezell":[2],
    "rob_bresnahan":[2],
    "michelle_kaufusi":[2],
    "kay_christofferson":[2],
    "bob_stevenson":[2,8],
    "terry_willis_price":[2],
    "duffy":[2,12,15],
    "capito":[2,12,15,59],
    "cantwell":[2,3,18,32],
    "heinrich":[2,12,15],
    "rick_larsen":[2],
    "kevin_cramer":[2,12],
    "gretchen_whitmer":[2,14,22,31],
    "trump":[3,12,18,19,20,21,23,24,25,26,27,29,31,34,35,37,40,41,42,43,44,45,48,49,50,51],
    "vance":[3,14,18,19,25,28,29,34,41,44,49,51],
    "lutnick":[3,18],
    "hawley":[3,14,18,28,32,39,47,49,51],
    "jason_smith":[3,4,18,51],
    "sherrod_brown":[3,21,29,33],
    "haley_stevens":[3],
    "lee":[3,10,12,14,18,19,20,21,23,24,25,26,27,29,31,33,35,38,44,46,48,51],
    "cox":[3,8,12,13,15,19,20,22,26,28,29,31,32,34,36,39,43,46],
    "trygve_hammer":[3],
    "crapo":[3,18,21],
    "neal":[3,18,21],
    "mccormick":[3,12,18,32,34],
    "banks":[3,18,32,34],
    "moreno":[3,18,21,34,35],
    "greer":[3,18],
    "hassett":[3,18],
    "jared_golden":[3,18,21,25],
    "chavez_deremer":[3,18],
    "delbene":[3,18,32],
    "daines":[3,12,18,21,27],
    "rollins":[3,6,18,57,58],
    "peter_navarro":[3,14,18],
    "stephen_miran":[3,18],
    "mcconnell":[3,21,24,25,27],
    "adrian_smith":[4,7],
    "rick_crawford":[4],
    "frank_lucas":[4,8],
    "tom_cole":[4,5,21,33],
    "mariannette_miller_meeks":[4,5,7],
    "jferry":[4],
    "don_davis":[4,5,33],
    "chellie_pingree":[4,12,15,31,43],
    "jim_mcgovern":[4,57],
    "mike_rounds":[4,32],
    "tommy_tuberville":[4,22,34],
    "kim_reynolds":[4,22,36],
    "zach_nunn":[5,33],
    "mike_flood":[5,20],
    "susie_lee":[5],
    "trent_kelly":[5],
    "hegseth":[5,24,25,27,30,42],
    "kaylee_peterson":[5],
    "dan_crenshaw":[5,12,25,34],
    "seth_moulton":[5,25,32],
    "wes_moore":[5,40],
    "lindsay_james":[6],
    "luz_escamilla":[6],
    "candice_pierucci":[6],
    "cheryl_acton":[6],
    "wayne_harper":[6],
    "stephanie_gricius":[6,30,32,39,47],
    "keith_grover":[6],
    "lincoln_fillmore":[6],
    "chris_jones":[7],
    "aaron_flint":[7],
    "becky_stille":[7],
    "logan_monson":[7],
    "stewart_e_barlow":[7,42],
    "dhinkins":[7,8],
    "nthurston":[7,37],
    "josh_green":[7,12,20],
    "janet_mills":[7,22,30],
    "bmoore":[8,35],
    "melanie_stansbury":[8,12,15,22,26,43],
    "gabe_vasquez":[8,12,34,43,49],
    "victor_iverson_washco":[8],
    "maloy":[8,19,21,22,26,30,31,34,35],
    "mike_simpson":[8,43],
    "troy_downing":[8],
    "katie_hobbs":[8,22,34],
    "kris_mayes":[8,22,34],
    "kate_gallego":[8,20,34],
    "heath_flora":[8,12,40],
    "rubio":[9,19,23,24,25,27],
    "bondi":[9,19,34],
    "mike_collins":[9],
    "derek_brown_ut":[9,28,46],
    "paul_a_cutler":[9,32,39],
    "evan_vickers":[9,37,45],
    "mike_mckell":[9,28,46],
    "jennifer_plumb":[9,38],
    "steve_eliason":[9,38],
    "tom_homan":[9,19,34],
    "dan_bongino":[9,40],
    "mike_dewine":[9,14,38],
    "rand_paul":[10,18,21,23,24,27,29,33,41,42,46,51,57],
    "massie":[10,13,14,18,21,22,23,24,25,26,27,29,36,38,44,45,46,48,50,57],
    "tgabbard":[10,11,23,24,27,28,47],
    "mtg":[10,25,50],
    "ryan_d_wilcox":[10],
    "kirk_cullimore":[10],
    "doug_fiefia":[10,32,39],
    "stephanie_pitcher":[10,40],
    "khanna":[11,23,24,27,50,51],
    "sanders":[11,12,14,24,31,32,33,37,39,41,48,51],
    "rob_bishop":[11],
    "salvador_giove":[11],
    "chris_wright":[12,31],
    "russ_fulcher":[12,43],
    "cruz":[12,13,31,32,36,39,47,51],
    "risch":[12,24],
    "kennedy_john":[12,18,21,34],
    "guthrie":[12,15,32],
    "lummis":[12,35],
    "pallone":[12,15,32],
    "britt":[12,21,34],
    "coons":[12,24],
    "sheehy":[12],
    "bruce_westerman":[12],
    "sam_graves":[12],
    "angie_craig":[12,18],
    "cortez_masto":[12,34,35],
    "donalds":[12,21,34],
    "padilla":[12,32,34],
    "stefanik":[12,21,24,34],
    "schatz":[12,24,32],
    "markey":[12,24,32,59],
    "lujan":[12,34],
    "fitzpatrick":[12,25,34],
    "rosen":[12,24,32],
    "pfluger":[12,21,34],
    "dan_sullivan":[12,24,27],
    "hickenlooper":[12,32],
    "tina_smith":[12],
    "zeldin":[12,15,47,59],
    "burgum":[12,32],
    "scalise":[12,21,34,38,51],
    "mullin":[12],
    "hudson":[12],
    "blunt_rochester":[12],
    "mike_bost":[12,34],
    "jared_huffman":[12],
    "jim_justice":[12,34],
    "hoeven":[12],
    "debbie_dingell":[12,59],
    "ted_budd":[12,34,38],
    "kevin_hern":[12,21],
    "kelly_loeffler":[12,21],
    "greg_abbott":[12,19,22,34,36],
    "gavin_newsom":[12,19,20,22,31],
    "josh_shapiro":[12,22,24,36],
    "glenn_youngkin":[12,22,36],
    "jeff_landry":[12,34,36,40],
    "jared_polis":[12,37],
    "kevin_stitt":[12,34,36],
    "patrick_morrisey":[12,34],
    "greg_gianforte":[12,21,34],
    "michelle_lujan_grisham":[12,22,34,38],
    "bill_lee":[12,22,34,36],
    "henry_mcmaster":[12,22,34,36],
    "kay_ivey":[12,22,36],
    "maura_healey":[12,20,22,30,34],
    "tina_kotek":[12,20,22,30],
    "mikie_sherrill":[12,22,38],
    "dunleavy":[12,22,36,40],
    "tate_reeves":[12,22,36],
    "kelly_armstrong":[12,22],
    "mark_gordon":[12,22],
    "dan_mckee":[12,20,22],
    "phil_scott":[12,22,38],
    "liz_murrill":[12,22,34],
    "brenna_bird":[12,22,34,40],
    "rob_bonta":[12,22,34],
    "kwame_raoul":[12,22,34,38],
    "dan_patrick":[12,22,34,36],
    "mike_mcguire":[12,20,22,38],
    "robert_rivas":[12,20,22,34],
    "stewart_cousins":[12,20,22,38],
    "dana_nessel":[12,22,30],
    "kim_ward":[12,26,36],
    "matt_hall":[12],
    "winnie_brinks":[12,22,38],
    "rob_mccolley":[12],
    "laurie_jinkins":[12,20,22],
    "julie_mccluskie":[12,20,36],
    "bill_ferguson":[12,36],
    "pat_grassley":[12,36],
    "phillip_devillier":[12,40],
    "owens":[13,14,19,22,23,24,25,26,27,29,30,31,34,35,36,45],
    "kennedy":[13,36,45],
    "val_peterson":[13,48],
    "karen_kwan":[13,48],
    "james_talarico":[13,36],
    "lisa_dean":[13,36],
    "stephen_otterstrom":[13,36],
    "sarah_huckabee_sanders":[13,22,34,36],
    "tim_walz":[13,22,38],
    "fetterman":[14,19,23,24,34,39],
    "mike_schultz":[14,20,48],
    "marie_gluesenkamp_perez":[14,21,34],
    "andy_beshear":[14,22],
    "ken_paxton":[15,47],
    "vought":[15,21,47,51],
    "daniel_mccay":[15,47],
    "tim_scott":[15,35],
    "bessent":[18,21],
    "jeffries":[18,20,21,29,51],
    "aoc":[18,19,20,29,31,34,41,47,49,51],
    "wyden":[18,32],
    "hagerty":[18,24,35],
    "boozman":[18,21,34,58],
    "glenn_thompson":[18],
    "tammy_baldwin":[18,21],
    "rick_scott":[18,21,34],
    "roger_marshall":[18,21,34,58,59],
    "stephen_miller":[19,34],
    "casar":[19,21,32,34],
    "noem":[19,34,49],
    "jim_jordan":[19,21,28,34,41],
    "delia_ramirez":[19,20,34,37],
    "ron_desantis":[19,22,34,36],
    "jb_pritzker":[19,22,34],
    "mike_johnson":[19,21,33,50,51],
    "durbin":[19,38,49,51],
    "graham":[19,21,23,24,25,27],
    "sadams":[20],
    "mike_kohler":[20],
    "jake_auchincloss":[20,24,25,32],
    "ayanna_pressley":[20,37,40,48],
    "matt_meyer":[20,22,36,38],
    "carl_heastie":[20,22],
    "daniel_lurie":[20,40],
    "cherelle_parker":[20,40],
    "zohran_mamdani":[20,34,40],
    "don_scott":[20,22,38],
    "ron_mariano":[20,38],
    "todd_huston":[20,36],
    "julie_fahey":[20,38],
    "matt_ritter":[20,22,38],
    "ryan_fecteau":[20,22],
    "james_coleman":[20],
    "wicker":[21,24],
    "arrington":[21],
    "ernst":[21],
    "lankford":[21,24,34],
    "delauro":[21],
    "murray":[21],
    "chip_roy":[21,34],
    "cassidy":[21],
    "jerry_moran":[21,24],
    "van_hollen":[21,24],
    "foxx":[21],
    "ron_johnson":[21,34],
    "mcclain":[21,24,34],
    "luna":[21,34,35],
    "andy_harris":[21,34,57],
    "ricketts":[21,24,27],
    "brendan_boyle":[21,33],
    "josh_gottheimer":[21,23,24],
    "greg_landsman":[21,24,33],
    "mike_braun":[21,37],
    "murkowski":[22],
    "mallory_mcmorrow":[22],
    "sarah_mcbride":[22,30],
    "kathy_hochul":[22,38,40],
    "brian_kemp":[22,26,34],
    "bob_ferguson":[22,38],
    "evers":[22,36,38],
    "josh_stein":[22,36],
    "joe_lombardo":[22,34,36,40],
    "mike_kehoe":[22,34,36,40],
    "ned_lamont":[22,38],
    "laura_kelly":[22,36],
    "kelly_ayotte":[22,34,36,40],
    "brad_little":[22,36],
    "jim_pillen":[22,36],
    "larry_rhoden":[22,34],
    "letitia_james":[22,34,38],
    "keith_ellison":[22],
    "raul_labrador":[22,30,34],
    "chris_carr":[22,26,34,40],
    "dave_yost":[22],
    "tom_suozzi":[22,24,34],
    "don_bacon":[22,24,25,34],
    "josh_kaul":[22,26,38],
    "aaron_ford":[22,34,40],
    "jeff_jackson":[22,40],
    "james_uthmeier":[22,34,40],
    "jonathan_skrmetti":[22,30],
    "kris_kobach":[22,26,34],
    "joanna_mcclinton":[22,38],
    "don_harmon":[22,38],
    "chris_welch":[22,36],
    "nicole_cannizzaro":[22,38],
    "phil_berger":[22,26,36],
    "ranjeev_puri":[22,38],
    "greta_neubauer":[22,36],
    "bryan_hughes":[22,26,36],
    "erin_murphy":[22,38],
    "karen_spilka":[22,36,38],
    "robert_stivers":[22],
    "jon_patterson":[22,40],
    "ty_masterson":[22],
    "nhaley":[23,24,25,27],
    "cotton":[24,32,34],
    "schumer":[24,37,51],
    "slotkin":[24,34],
    "brian_mast":[24],
    "mark_kelly":[24,34],
    "chris_murphy":[24],
    "kaine":[24],
    "meeks":[24],
    "adam_smith":[24],
    "reed":[24],
    "shaheen":[24,59],
    "jayapal":[24,32,34],
    "duckworth":[24],
    "ratcliffe":[24],
    "witkoff":[24,25],
    "torres":[24,35],
    "omar":[24,34],
    "mike_waltz":[24,25,27],
    "tlaib":[24,34],
    "mike_lawler":[24,34],
    "summer_lee":[24],
    "keith_kellogg":[24,25],
    "john_cornyn":[24,25,27,34,38],
    "boebert":[25,38],
    "gaetz":[25],
    "warren_petersen":[26,34,36],
    "robin_vos":[26,36],
    "mike_rogers":[27,37],
    "todd_young":[27,32],
    "schmitt":[27,32,34],
    "raja_krishnamoorthi":[27,32,49],
    "brady_brammer":[28,41,46,53],
    "andrew_ferguson":[28,32],
    "jerome_powell":[29,35],
    "nicholeen_p_peck":[30],
    "jennifer_dailey_provost":[30],
    "evan_done":[30],
    "sahara_hayes":[30],
    "nancy_mace":[30,34],
    "ariel_defay":[32,44],
    "brinker_harding":[32,39],
    "tcamp":[32,39],
    "klobuchar":[32],
    "warner":[32,35],
    "peters":[32,34],
    "blackburn":[32,34],
    "blumenthal":[32,57,58,59],
    "brendan_carr":[32],
    "alsobrooks":[32],
    "yvette_clarke":[32],
    "brian_babin":[32],
    "bennet":[32],
    "gillibrand":[32,59],
    "jan_schakowsky":[32,37],
    "christina_bohannan":[33],
    "gallego":[34],
    "patel":[34],
    "garbarino":[34],
    "ashley_moody":[34],
    "maggie_hassan":[34,59],
    "dustin_burrows":[34,36],
    "ben_albritton":[34,36],
    "daniel_perez_fl":[34,36],
    "karen_bass":[34,40],
    "brandon_johnson":[34,40],
    "mike_johnston":[34,40],
    "john_whitmire":[34,40],
    "dave_sunday":[34,40],
    "cameron_sexton":[34,36,40],
    "french_hill":[35],
    "emmer":[35,51],
    "warren":[35,37,47,48],
    "paul_atkins":[35],
    "maxine_waters":[35],
    "destin_hall":[36],
    "jon_burns":[36,40],
    "gene_wu":[36,38],
    "matt_huffman":[36],
    "sharon_carson":[36,40],
    "lisa_demuth":[36],
    "mehmet_oz":[37,45],
    "kclark":[38,44,51],
    "steven_horsford":[38],
    "dthatcher":[38,46],
    "jay_costa":[38],
    "nicholas_scutari":[38],
    "ryan_arbon":[40],
    "rosie_rivera":[40],
    "sandra_hollins":[40],
    "angela_romero":[40],
    "mattie_parker":[40],
    "eric_johnson_dallas":[40],
    "murrell_smith":[40],
    "john_johnson":[41],
    "katy_hall":[41],
    "karianne_lisonbee":[41],
    "ray_ward":[42,45],
    "matt_macpherson":[42],
    "jake_fitisemanu":[42],
    "rfkjr":[42,45,47,57],
    "trevor_lee":[42,45],
    "walt_brooks":[42],
    "jordan_leonard_emery":[43],
    "teresa_leger_fernandez":[43],
    "tracy_miller":[44],
    "mark_strong":[44],
    "barrasso":[45,51],
    "marty_makary":[45,57],
    "jay_bhattacharya":[45],
    "diana_degette":[45],
    "jordan_teuscher":[46],
    "ann_millner":[48],
    "tyler_vincent":[52],
    "lee_perry":[52],
    "boyd_bingham":[52],
    "stephen_hadfield":[52],
    "nathan_tueller":[52],
    "vance_smith":[52],
    "stacy_bateman":[53],
    "ada_wilson":[53],
    "sarah_beeson":[53],
    "chris_carn":[54],
    "leah_hansen":[54],
    "julie_fullmer":[55],
    "jacob_holdaway":[55],
    "zack_stratton":[55],
    "jared_gray":[56],
    "emily_buss":[56]};
  var BY_SLUG = {};
  ROWS.forEach(function (r) { BY_SLUG[r.slug] = r; });

  // The one address in this file. Spotlight doors kept their /issue/<slug>
  // spelling through the split; what changed is that it is now a document
  // boundary rather than an in-page overlay, so this is a real navigation.
  function urlFor(slug) { return '/issue/' + encodeURIComponent(String(slug || '')); }

  window.PDXSpotlight = {
    url: urlFor,
    open: function (slug) {
      if (!slug || !BY_SLUG[slug]) return false;
      try { location.assign(urlFor(slug)); } catch (e) { location.href = urlFor(slug); }
      return true;
    },
    close: function () { /* no overlay on this document — see header */ },
    has: function (slug) { return !!(slug && BY_SLUG[slug]); },
    get: function (slug) { return BY_SLUG[slug] || null; },
    registry: BY_SLUG,
    list: function () { return ROWS.slice(); },
    strength: function (slug) { return BY_SLUG[slug] ? BY_SLUG[slug].st : null; },
    strengthFor: function (sp) {
      if (!sp) return { receipts: 0, strong: 0, sources: 0, level: 'limited', label: 'Emerging' };
      return sp.st || (BY_SLUG[sp.slug] ? BY_SLUG[sp.slug].st : null) ||
        { receipts: 0, strong: 0, sources: 0, level: 'limited', label: 'Emerging' };
    },
    forPolitician: function (id) {
      var idx = id ? BY_PERSON[id] : null;
      if (!idx || !idx.length) return [];
      return idx.map(function (i) { return ROWS[i]; }).filter(Boolean);
    },
    forIssueKey: function (key) {
      if (!key) return [];
      return ROWS.filter(function (r) {
        if (r.primaryIssueKey === key) return true;
        if ((r.communityIssueKeys || []).indexOf(key) !== -1) return true;
        if ((r.standsIssueKeys || []).indexOf(key) !== -1) return true;
        return false;
      });
    },
    // Token match over title + place + keywords, identical to the engine's.
    match: function (q) {
      q = String(q || '').toLowerCase().trim();
      if (!q) return [];
      var terms = q.split(/\s+/).filter(Boolean);
      return ROWS.filter(function (r) {
        var hay = (r.title + ' ' + r.place + ' ' + (r.searchKeywords || '')).toLowerCase();
        return terms.every(function (t) { return hay.indexOf(t) !== -1; });
      });
    }
  };
})();
