-- ═══════════════════════════════════════════════════════════════════════════
-- Utah 2023 General Session — floor votes unlocked by the wave-9 name admit
-- ═══════════════════════════════════════════════════════════════════════════
--
-- 20261003000000_vr_utah_2023gs_state_record.sql
-- created these roll calls, their measures and their issue mappings, and wrote
-- the member votes the floor map could attribute at the time.
-- 514 other recorded votes on those SAME rolls were parsed and DISCARDED, because
-- db/vr-utah-member-map-2023GS.json can only map a printed name onto a roster id, and
-- the 15 people behind these printed forms were on no PolitiDex roster at all. The map
-- said so in writing and called adding them a roster decision for a later wave.
--
-- The roster then grew — wave 2's identity-only records and the committee waves' roster
-- door — and nothing went back to the floor map. So these votes stayed parsed and
-- dropped while the people they belong to sat on the roster with an empty or thin file.
-- scripts/vr-utah-name-admit.mjs closed that stale fence. This migration carries the votes.
--
-- NOTHING WAS GUESSED. Each printed form had to clear three independent gates before its
-- votes could land here: scripts/vr-utah-ingest.mjs --collect resolved it on its own
-- through the UNCHANGED uniqueness rule (surname plus a compatible first name, exactly one
-- candidate in the whole pool); the reviewed db/vr-utah-committee-map-2023GS.json
-- already carried the same person under the same surname and initial in the same chamber;
-- and the legislature's own 2023 roster (https://le.utah.gov/asp/roster/roster.asp?year=2023)
-- seats that full name in that chamber with the party and district the committee map's
-- confirmedBy line claims. A name that failed any gate is still unattributed, and the
-- printed forms the committee map REFUSES by name are still refused.
--
-- Additive and idempotent: member votes only, ON CONFLICT (rollcall_id, politician_id)
-- DO NOTHING. No measure, roll call or issue row is touched. A missing roll call RAISEs
-- rather than being created — this file holds none of the verified question, tally, date
-- or source that one needs.
--
-- Unlike 20261001000000_vr_utah_2025gs_roster_attribution_votes.sql, which re-asserted
-- every attributed vote on its rolls and let ON CONFLICT sort out the overlap, this file
-- emits ONLY the 15 newly admitted members' rows. Nothing else on these rolls can be
-- new — every other pid was already mapped when the state record landed — so re-stating
-- thousands of rows to have them all conflict away would hide the people this wave is
-- responsible for. The admitted set is not re-derived here: it is read off `_wave9Admitted`
-- in db/vr-utah-member-map-2023GS.json, the same file that records the mapping, and
-- cross-checked against `chambers` so the note and the mapping cannot disagree.
--
-- Roll calls are looked up on (chamber, session, roll_number) WITH congress IS NULL, the
-- tuple vr_rollcalls_state_unique is built on. vr_rollcalls_unique includes congress,
-- which is NULL on every state row, and Postgres treats NULLs as distinct.
--
-- Source of truth: db/vr-utah-vote-seed-2023GS.json, rebuilt by
-- scripts/vr-utah-ingest.mjs --seed from the cached le.utah.gov vote pages. Generated by
-- scripts/vr-gen-utah-name-admit-migration.mjs --session 2023GS.
--
-- Members gaining floor votes here (15), with the count each gains:
--   brett_garner              36
--   brian_king                38
--   david_buxton              11
--   jacob_anderegg            11
--   james_cobb                38
--   jeffrey_stenquist         38
--   judy_weeks_rohner         38
--   kera_birkeland            38
--   mark_wheatley             38
--   quinn_kotter              38
--   robert_spendlove          38
--   rosemary_lesser           38
--   steven_lund               38
--   susan_pulsipher           38
--   tim_jimenez               38
-- ═══════════════════════════════════════════════════════════════════════════

DO $$
DECLARE rc bigint;
BEGIN

  -- utah house 2023 roll 60 — H.B. 215 Funding for Teacher Salaries and Optional Education Opportunities
  --   54-20-0, 12 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2023GS&voteid=60&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2023
     AND roll_number = 60;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: utah house 2023 roll 60 is missing — 20261003000000_vr_utah_2023gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brian_king', 'nay'),
    (rc, 'james_cobb', 'nay'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'judy_weeks_rohner', 'nay'),
    (rc, 'kera_birkeland', 'yea'),
    (rc, 'mark_wheatley', 'nay'),
    (rc, 'quinn_kotter', 'nay'),
    (rc, 'robert_spendlove', 'yea'),
    (rc, 'rosemary_lesser', 'nay'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah senate 2023 roll 105 — H.B. 215 Funding for Teacher Salaries and Optional Education Opportunities
  --   20-8-1, 2 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2023GS&voteid=105&house=S
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah senate' AND congress IS NULL AND session = 2023
     AND roll_number = 105;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: utah senate 2023 roll 105 is missing — 20261003000000_vr_utah_2023gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'david_buxton', 'yea'),
    (rc, 'jacob_anderegg', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2023 roll 1621 — H.B. 398 Special Needs Opportunity Scholarship Program Amendments
  --   51-14-10, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2023GS&voteid=1621&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2023
     AND roll_number = 1621;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: utah house 2023 roll 1621 is missing — 20261003000000_vr_utah_2023gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'nay'),
    (rc, 'brian_king', 'nay'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'judy_weeks_rohner', 'yea'),
    (rc, 'kera_birkeland', 'yea'),
    (rc, 'mark_wheatley', 'nay'),
    (rc, 'quinn_kotter', 'yea'),
    (rc, 'robert_spendlove', 'not_voting'),
    (rc, 'rosemary_lesser', 'yea'),
    (rc, 'steven_lund', 'nay'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'not_voting')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2023 roll 887 — H.B. 477 Full-day Kindergarten Amendments
  --   51-14-10, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2023GS&voteid=887&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2023
     AND roll_number = 887;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: utah house 2023 roll 887 is missing — 20261003000000_vr_utah_2023gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'yea'),
    (rc, 'brian_king', 'yea'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'judy_weeks_rohner', 'yea'),
    (rc, 'kera_birkeland', 'nay'),
    (rc, 'mark_wheatley', 'yea'),
    (rc, 'quinn_kotter', 'not_voting'),
    (rc, 'robert_spendlove', 'yea'),
    (rc, 'rosemary_lesser', 'yea'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'nay')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2023 roll 1306 — H.B. 400 School Absenteeism Amendments
  --   53-19-3, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2023GS&voteid=1306&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2023
     AND roll_number = 1306;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: utah house 2023 roll 1306 is missing — 20261003000000_vr_utah_2023gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'yea'),
    (rc, 'brian_king', 'yea'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'judy_weeks_rohner', 'yea'),
    (rc, 'kera_birkeland', 'nay'),
    (rc, 'mark_wheatley', 'yea'),
    (rc, 'quinn_kotter', 'nay'),
    (rc, 'robert_spendlove', 'yea'),
    (rc, 'rosemary_lesser', 'yea'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'nay'),
    (rc, 'tim_jimenez', 'nay')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2023 roll 955 — H.B. 465 Public School Library Transparency Amendments
  --   62-10-3, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2023GS&voteid=955&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2023
     AND roll_number = 955;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: utah house 2023 roll 955 is missing — 20261003000000_vr_utah_2023gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'nay'),
    (rc, 'brian_king', 'yea'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'judy_weeks_rohner', 'yea'),
    (rc, 'kera_birkeland', 'not_voting'),
    (rc, 'mark_wheatley', 'not_voting'),
    (rc, 'quinn_kotter', 'yea'),
    (rc, 'robert_spendlove', 'yea'),
    (rc, 'rosemary_lesser', 'nay'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2023 roll 1514 — H.B. 427 Individual Freedom in Public Education
  --   53-18-4, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2023GS&voteid=1514&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2023
     AND roll_number = 1514;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: utah house 2023 roll 1514 is missing — 20261003000000_vr_utah_2023gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'nay'),
    (rc, 'brian_king', 'nay'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'judy_weeks_rohner', 'yea'),
    (rc, 'kera_birkeland', 'yea'),
    (rc, 'mark_wheatley', 'nay'),
    (rc, 'quinn_kotter', 'yea'),
    (rc, 'robert_spendlove', 'yea'),
    (rc, 'rosemary_lesser', 'nay'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'nay'),
    (rc, 'tim_jimenez', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2023 roll 1626 — H.B. 348 Participation Waiver Amendments
  --   51-17-7, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2023GS&voteid=1626&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2023
     AND roll_number = 1626;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: utah house 2023 roll 1626 is missing — 20261003000000_vr_utah_2023gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'nay'),
    (rc, 'brian_king', 'nay'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'judy_weeks_rohner', 'yea'),
    (rc, 'kera_birkeland', 'yea'),
    (rc, 'mark_wheatley', 'nay'),
    (rc, 'quinn_kotter', 'yea'),
    (rc, 'robert_spendlove', 'not_voting'),
    (rc, 'rosemary_lesser', 'nay'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'not_voting')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2023 roll 117 — S.B. 16 Transgender Medical Treatments and Procedures Amendments
  --   58-14-2, 12 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2023GS&voteid=117&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2023
     AND roll_number = 117;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: utah house 2023 roll 117 is missing — 20261003000000_vr_utah_2023gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brian_king', 'nay'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'judy_weeks_rohner', 'yea'),
    (rc, 'kera_birkeland', 'not_voting'),
    (rc, 'mark_wheatley', 'nay'),
    (rc, 'quinn_kotter', 'nay'),
    (rc, 'robert_spendlove', 'yea'),
    (rc, 'rosemary_lesser', 'nay'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah senate 2023 roll 109 — S.B. 16 Transgender Medical Treatments and Procedures Amendments
  --   20-8-1, 2 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2023GS&voteid=109&house=S
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah senate' AND congress IS NULL AND session = 2023
     AND roll_number = 109;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: utah senate 2023 roll 109 is missing — 20261003000000_vr_utah_2023gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'david_buxton', 'yea'),
    (rc, 'jacob_anderegg', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2023 roll 1524 — H.B. 467 Abortion Changes
  --   56-14-5, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2023GS&voteid=1524&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2023
     AND roll_number = 1524;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: utah house 2023 roll 1524 is missing — 20261003000000_vr_utah_2023gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'nay'),
    (rc, 'brian_king', 'nay'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'judy_weeks_rohner', 'not_voting'),
    (rc, 'kera_birkeland', 'yea'),
    (rc, 'mark_wheatley', 'nay'),
    (rc, 'quinn_kotter', 'yea'),
    (rc, 'robert_spendlove', 'yea'),
    (rc, 'rosemary_lesser', 'nay'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2023 roll 392 — H.B. 219 Firearms Regulations
  --   60-13-2, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2023GS&voteid=392&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2023
     AND roll_number = 392;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: utah house 2023 roll 392 is missing — 20261003000000_vr_utah_2023gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'nay'),
    (rc, 'brian_king', 'nay'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'judy_weeks_rohner', 'yea'),
    (rc, 'kera_birkeland', 'yea'),
    (rc, 'mark_wheatley', 'nay'),
    (rc, 'quinn_kotter', 'yea'),
    (rc, 'robert_spendlove', 'yea'),
    (rc, 'rosemary_lesser', 'nay'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2023 roll 313 — H.B. 107 Concealed Weapons Permit Fee Amendments
  --   57-12-6, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2023GS&voteid=313&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2023
     AND roll_number = 313;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: utah house 2023 roll 313 is missing — 20261003000000_vr_utah_2023gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'nay'),
    (rc, 'brian_king', 'nay'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'judy_weeks_rohner', 'yea'),
    (rc, 'kera_birkeland', 'yea'),
    (rc, 'mark_wheatley', 'not_voting'),
    (rc, 'quinn_kotter', 'yea'),
    (rc, 'robert_spendlove', 'yea'),
    (rc, 'rosemary_lesser', 'nay'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah senate 2023 roll 1642 — H.B. 107 Concealed Weapons Permit Fee Amendments
  --   22-6-1, 2 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2023GS&voteid=1642&house=S
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah senate' AND congress IS NULL AND session = 2023
     AND roll_number = 1642;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: utah senate 2023 roll 1642 is missing — 20261003000000_vr_utah_2023gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'david_buxton', 'yea'),
    (rc, 'jacob_anderegg', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2023 roll 908 — H.B. 461 Airport Firearm Possession Amendments
  --   58-14-3, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2023GS&voteid=908&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2023
     AND roll_number = 908;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: utah house 2023 roll 908 is missing — 20261003000000_vr_utah_2023gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'nay'),
    (rc, 'brian_king', 'nay'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'judy_weeks_rohner', 'yea'),
    (rc, 'kera_birkeland', 'yea'),
    (rc, 'mark_wheatley', 'nay'),
    (rc, 'quinn_kotter', 'yea'),
    (rc, 'robert_spendlove', 'yea'),
    (rc, 'rosemary_lesser', 'nay'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2023 roll 315 — H.B. 165 Firearm Discharge on Private Property Amendments
  --   58-11-6, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2023GS&voteid=315&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2023
     AND roll_number = 315;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: utah house 2023 roll 315 is missing — 20261003000000_vr_utah_2023gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'nay'),
    (rc, 'brian_king', 'nay'),
    (rc, 'james_cobb', 'not_voting'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'judy_weeks_rohner', 'yea'),
    (rc, 'kera_birkeland', 'yea'),
    (rc, 'mark_wheatley', 'not_voting'),
    (rc, 'quinn_kotter', 'yea'),
    (rc, 'robert_spendlove', 'yea'),
    (rc, 'rosemary_lesser', 'nay'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2023 roll 137 — H.B. 131 Vaccine Passport Prohibition
  --   60-13-2, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2023GS&voteid=137&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2023
     AND roll_number = 137;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: utah house 2023 roll 137 is missing — 20261003000000_vr_utah_2023gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'nay'),
    (rc, 'brian_king', 'nay'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'judy_weeks_rohner', 'yea'),
    (rc, 'kera_birkeland', 'yea'),
    (rc, 'mark_wheatley', 'nay'),
    (rc, 'quinn_kotter', 'yea'),
    (rc, 'robert_spendlove', 'yea'),
    (rc, 'rosemary_lesser', 'nay'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah senate 2023 roll 1592 — H.B. 131 Vaccine Passport Prohibition
  --   21-5-3, 2 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2023GS&voteid=1592&house=S
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah senate' AND congress IS NULL AND session = 2023
     AND roll_number = 1592;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: utah senate 2023 roll 1592 is missing — 20261003000000_vr_utah_2023gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'david_buxton', 'yea'),
    (rc, 'jacob_anderegg', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2023 roll 1194 — S.B. 133 Modifications to Medicaid Coverage
  --   43-29-3, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2023GS&voteid=1194&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2023
     AND roll_number = 1194;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: utah house 2023 roll 1194 is missing — 20261003000000_vr_utah_2023gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'yea'),
    (rc, 'brian_king', 'yea'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'not_voting'),
    (rc, 'judy_weeks_rohner', 'yea'),
    (rc, 'kera_birkeland', 'nay'),
    (rc, 'mark_wheatley', 'yea'),
    (rc, 'quinn_kotter', 'yea'),
    (rc, 'robert_spendlove', 'yea'),
    (rc, 'rosemary_lesser', 'yea'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'nay'),
    (rc, 'tim_jimenez', 'nay')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2023 roll 359 — S.B. 19 Medicaid Dental Waiver Amendments
  --   51-15-9, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2023GS&voteid=359&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2023
     AND roll_number = 359;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: utah house 2023 roll 359 is missing — 20261003000000_vr_utah_2023gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'yea'),
    (rc, 'brian_king', 'yea'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'judy_weeks_rohner', 'yea'),
    (rc, 'kera_birkeland', 'nay'),
    (rc, 'mark_wheatley', 'not_voting'),
    (rc, 'quinn_kotter', 'yea'),
    (rc, 'robert_spendlove', 'yea'),
    (rc, 'rosemary_lesser', 'yea'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'nay')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah senate 2023 roll 1757 — S.B. 217 Children's Health Coverage Amendments
  --   25-3-1, 2 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2023GS&voteid=1757&house=S
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah senate' AND congress IS NULL AND session = 2023
     AND roll_number = 1757;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: utah senate 2023 roll 1757 is missing — 20261003000000_vr_utah_2023gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'david_buxton', 'yea'),
    (rc, 'jacob_anderegg', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2023 roll 1165 — S.B. 204 Autism Coverage Amendments
  --   62-10-3, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2023GS&voteid=1165&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2023
     AND roll_number = 1165;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: utah house 2023 roll 1165 is missing — 20261003000000_vr_utah_2023gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'yea'),
    (rc, 'brian_king', 'yea'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'judy_weeks_rohner', 'yea'),
    (rc, 'kera_birkeland', 'not_voting'),
    (rc, 'mark_wheatley', 'yea'),
    (rc, 'quinn_kotter', 'nay'),
    (rc, 'robert_spendlove', 'yea'),
    (rc, 'rosemary_lesser', 'yea'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'nay')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2023 roll 407 — H.B. 315 Recreational Therapy Medicaid Coverage Amendments
  --   60-10-5, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2023GS&voteid=407&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2023
     AND roll_number = 407;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: utah house 2023 roll 407 is missing — 20261003000000_vr_utah_2023gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'yea'),
    (rc, 'brian_king', 'yea'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'judy_weeks_rohner', 'yea'),
    (rc, 'kera_birkeland', 'nay'),
    (rc, 'mark_wheatley', 'yea'),
    (rc, 'quinn_kotter', 'nay'),
    (rc, 'robert_spendlove', 'not_voting'),
    (rc, 'rosemary_lesser', 'yea'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'nay')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2023 roll 609 — H.B. 105 Public Employee Disability Benefits Amendments
  --   38-30-7, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2023GS&voteid=609&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2023
     AND roll_number = 609;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: utah house 2023 roll 609 is missing — 20261003000000_vr_utah_2023gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'yea'),
    (rc, 'brian_king', 'yea'),
    (rc, 'james_cobb', 'nay'),
    (rc, 'jeffrey_stenquist', 'nay'),
    (rc, 'judy_weeks_rohner', 'yea'),
    (rc, 'kera_birkeland', 'nay'),
    (rc, 'mark_wheatley', 'yea'),
    (rc, 'quinn_kotter', 'nay'),
    (rc, 'robert_spendlove', 'not_voting'),
    (rc, 'rosemary_lesser', 'yea'),
    (rc, 'steven_lund', 'nay'),
    (rc, 'susan_pulsipher', 'nay'),
    (rc, 'tim_jimenez', 'nay')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2023 roll 709 — H.B. 425 Energy Security Amendments
  --   58-12-5, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2023GS&voteid=709&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2023
     AND roll_number = 709;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: utah house 2023 roll 709 is missing — 20261003000000_vr_utah_2023gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'nay'),
    (rc, 'brian_king', 'nay'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'judy_weeks_rohner', 'yea'),
    (rc, 'kera_birkeland', 'yea'),
    (rc, 'mark_wheatley', 'yea'),
    (rc, 'quinn_kotter', 'yea'),
    (rc, 'robert_spendlove', 'not_voting'),
    (rc, 'rosemary_lesser', 'not_voting'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2023 roll 1262 — S.B. 288 Utility Bill Assistance Program
  --   50-24-1, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2023GS&voteid=1262&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2023
     AND roll_number = 1262;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: utah house 2023 roll 1262 is missing — 20261003000000_vr_utah_2023gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'yea'),
    (rc, 'brian_king', 'yea'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'judy_weeks_rohner', 'yea'),
    (rc, 'kera_birkeland', 'yea'),
    (rc, 'mark_wheatley', 'yea'),
    (rc, 'quinn_kotter', 'nay'),
    (rc, 'robert_spendlove', 'yea'),
    (rc, 'rosemary_lesser', 'yea'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'nay'),
    (rc, 'tim_jimenez', 'nay')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2023 roll 1354 — S.B. 118 Water Efficient Landscaping Incentives
  --   60-12-3, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2023GS&voteid=1354&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2023
     AND roll_number = 1354;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: utah house 2023 roll 1354 is missing — 20261003000000_vr_utah_2023gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'yea'),
    (rc, 'brian_king', 'yea'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'judy_weeks_rohner', 'yea'),
    (rc, 'kera_birkeland', 'yea'),
    (rc, 'mark_wheatley', 'yea'),
    (rc, 'quinn_kotter', 'nay'),
    (rc, 'robert_spendlove', 'yea'),
    (rc, 'rosemary_lesser', 'yea'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2023 roll 1516 — H.B. 217 School Energy and Water Reductions
  --   63-8-4, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2023GS&voteid=1516&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2023
     AND roll_number = 1516;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: utah house 2023 roll 1516 is missing — 20261003000000_vr_utah_2023gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'yea'),
    (rc, 'brian_king', 'yea'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'judy_weeks_rohner', 'yea'),
    (rc, 'kera_birkeland', 'yea'),
    (rc, 'mark_wheatley', 'yea'),
    (rc, 'quinn_kotter', 'yea'),
    (rc, 'robert_spendlove', 'yea'),
    (rc, 'rosemary_lesser', 'yea'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'nay')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2023 roll 1337 — S.B. 174 Local Land Use and Development Revisions
  --   55-13-7, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2023GS&voteid=1337&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2023
     AND roll_number = 1337;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: utah house 2023 roll 1337 is missing — 20261003000000_vr_utah_2023gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'yea'),
    (rc, 'brian_king', 'yea'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'judy_weeks_rohner', 'nay'),
    (rc, 'kera_birkeland', 'not_voting'),
    (rc, 'mark_wheatley', 'nay'),
    (rc, 'quinn_kotter', 'nay'),
    (rc, 'robert_spendlove', 'not_voting'),
    (rc, 'rosemary_lesser', 'yea'),
    (rc, 'steven_lund', 'not_voting'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2023 roll 1555 — S.B. 271 Home Ownership Requirements
  --   56-16-3, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2023GS&voteid=1555&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2023
     AND roll_number = 1555;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: utah house 2023 roll 1555 is missing — 20261003000000_vr_utah_2023gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'nay'),
    (rc, 'brian_king', 'nay'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'judy_weeks_rohner', 'nay'),
    (rc, 'kera_birkeland', 'nay'),
    (rc, 'mark_wheatley', 'nay'),
    (rc, 'quinn_kotter', 'nay'),
    (rc, 'robert_spendlove', 'yea'),
    (rc, 'rosemary_lesser', 'yea'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2023 roll 1155 — S.B. 240 First-time Homebuyer Assistance Program
  --   60-8-7, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2023GS&voteid=1155&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2023
     AND roll_number = 1155;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: utah house 2023 roll 1155 is missing — 20261003000000_vr_utah_2023gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'yea'),
    (rc, 'brian_king', 'yea'),
    (rc, 'james_cobb', 'nay'),
    (rc, 'jeffrey_stenquist', 'nay'),
    (rc, 'judy_weeks_rohner', 'nay'),
    (rc, 'kera_birkeland', 'not_voting'),
    (rc, 'mark_wheatley', 'yea'),
    (rc, 'quinn_kotter', 'nay'),
    (rc, 'robert_spendlove', 'yea'),
    (rc, 'rosemary_lesser', 'yea'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2023 roll 1386 — H.B. 364 Housing Affordability Amendments
  --   63-9-3, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2023GS&voteid=1386&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2023
     AND roll_number = 1386;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: utah house 2023 roll 1386 is missing — 20261003000000_vr_utah_2023gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'yea'),
    (rc, 'brian_king', 'yea'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'judy_weeks_rohner', 'nay'),
    (rc, 'kera_birkeland', 'not_voting'),
    (rc, 'mark_wheatley', 'yea'),
    (rc, 'quinn_kotter', 'nay'),
    (rc, 'robert_spendlove', 'yea'),
    (rc, 'rosemary_lesser', 'yea'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2023 roll 878 — H.B. 468 Employment Screening Requirements
  --   41-25-9, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2023GS&voteid=878&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2023
     AND roll_number = 878;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: utah house 2023 roll 878 is missing — 20261003000000_vr_utah_2023gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'yea'),
    (rc, 'brian_king', 'yea'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'judy_weeks_rohner', 'nay'),
    (rc, 'kera_birkeland', 'nay'),
    (rc, 'mark_wheatley', 'yea'),
    (rc, 'quinn_kotter', 'nay'),
    (rc, 'robert_spendlove', 'not_voting'),
    (rc, 'rosemary_lesser', 'yea'),
    (rc, 'steven_lund', 'nay'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah senate 2023 roll 466 — H.B. 114 Theft Defense Amendments
  --   19-7-3, 2 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2023GS&voteid=466&house=S
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah senate' AND congress IS NULL AND session = 2023
     AND roll_number = 466;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: utah senate 2023 roll 466 is missing — 20261003000000_vr_utah_2023gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'david_buxton', 'yea'),
    (rc, 'jacob_anderegg', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2023 roll 975 — H.B. 208 Criminal Trespass Amendments
  --   54-17-4, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2023GS&voteid=975&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2023
     AND roll_number = 975;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: utah house 2023 roll 975 is missing — 20261003000000_vr_utah_2023gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'nay'),
    (rc, 'brian_king', 'yea'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'nay'),
    (rc, 'judy_weeks_rohner', 'not_voting'),
    (rc, 'kera_birkeland', 'yea'),
    (rc, 'mark_wheatley', 'yea'),
    (rc, 'quinn_kotter', 'yea'),
    (rc, 'robert_spendlove', 'not_voting'),
    (rc, 'rosemary_lesser', 'nay'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah senate 2023 roll 1307 — H.B. 208 Criminal Trespass Amendments
  --   22-4-3, 2 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2023GS&voteid=1307&house=S
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah senate' AND congress IS NULL AND session = 2023
     AND roll_number = 1307;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: utah senate 2023 roll 1307 is missing — 20261003000000_vr_utah_2023gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'david_buxton', 'yea'),
    (rc, 'jacob_anderegg', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2023 roll 1219 — S.B. 156 Investigative Genetic Genealogy Modifications
  --   46-24-5, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2023GS&voteid=1219&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2023
     AND roll_number = 1219;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: utah house 2023 roll 1219 is missing — 20261003000000_vr_utah_2023gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'yea'),
    (rc, 'brian_king', 'yea'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'judy_weeks_rohner', 'yea'),
    (rc, 'kera_birkeland', 'nay'),
    (rc, 'mark_wheatley', 'yea'),
    (rc, 'quinn_kotter', 'nay'),
    (rc, 'robert_spendlove', 'not_voting'),
    (rc, 'rosemary_lesser', 'yea'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'nay')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2023 roll 1296 — H.B. 281 Social Credit Score Amendments
  --   60-14-1, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2023GS&voteid=1296&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2023
     AND roll_number = 1296;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: utah house 2023 roll 1296 is missing — 20261003000000_vr_utah_2023gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'nay'),
    (rc, 'brian_king', 'nay'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'judy_weeks_rohner', 'yea'),
    (rc, 'kera_birkeland', 'yea'),
    (rc, 'mark_wheatley', 'nay'),
    (rc, 'quinn_kotter', 'yea'),
    (rc, 'robert_spendlove', 'yea'),
    (rc, 'rosemary_lesser', 'nay'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah senate 2023 roll 1608 — H.B. 281 Social Credit Score Amendments
  --   18-5-6, 2 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2023GS&voteid=1608&house=S
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah senate' AND congress IS NULL AND session = 2023
     AND roll_number = 1608;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: utah senate 2023 roll 1608 is missing — 20261003000000_vr_utah_2023gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'david_buxton', 'yea'),
    (rc, 'jacob_anderegg', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2023 roll 462 — H.B. 347 Ballot Drop Box Amendments
  --   54-16-5, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2023GS&voteid=462&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2023
     AND roll_number = 462;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: utah house 2023 roll 462 is missing — 20261003000000_vr_utah_2023gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'nay'),
    (rc, 'brian_king', 'nay'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'judy_weeks_rohner', 'yea'),
    (rc, 'kera_birkeland', 'yea'),
    (rc, 'mark_wheatley', 'nay'),
    (rc, 'quinn_kotter', 'yea'),
    (rc, 'robert_spendlove', 'yea'),
    (rc, 'rosemary_lesser', 'nay'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2023 roll 329 — H.B. 243 Public Transit Employee Collective Bargaining Amendments
  --   49-21-5, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2023GS&voteid=329&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2023
     AND roll_number = 329;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: utah house 2023 roll 329 is missing — 20261003000000_vr_utah_2023gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'nay'),
    (rc, 'brian_king', 'nay'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'judy_weeks_rohner', 'nay'),
    (rc, 'kera_birkeland', 'yea'),
    (rc, 'mark_wheatley', 'not_voting'),
    (rc, 'quinn_kotter', 'yea'),
    (rc, 'robert_spendlove', 'nay'),
    (rc, 'rosemary_lesser', 'nay'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah senate 2023 roll 864 — H.B. 243 Public Transit Employee Collective Bargaining Amendments
  --   20-9-0, 2 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2023GS&voteid=864&house=S
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah senate' AND congress IS NULL AND session = 2023
     AND roll_number = 864;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: utah senate 2023 roll 864 is missing — 20261003000000_vr_utah_2023gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'david_buxton', 'yea'),
    (rc, 'jacob_anderegg', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2023 roll 1640 — S.B. 260 Transportation Funding Requirements
  --   57-17-1, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2023GS&voteid=1640&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2023
     AND roll_number = 1640;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: utah house 2023 roll 1640 is missing — 20261003000000_vr_utah_2023gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'yea'),
    (rc, 'brian_king', 'yea'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'judy_weeks_rohner', 'nay'),
    (rc, 'kera_birkeland', 'yea'),
    (rc, 'mark_wheatley', 'yea'),
    (rc, 'quinn_kotter', 'nay'),
    (rc, 'robert_spendlove', 'yea'),
    (rc, 'rosemary_lesser', 'yea'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah senate 2023 roll 2100 — S.B. 260 Transportation Funding Requirements
  --   23-3-3, 2 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2023GS&voteid=2100&house=S
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah senate' AND congress IS NULL AND session = 2023
     AND roll_number = 2100;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: utah senate 2023 roll 2100 is missing — 20261003000000_vr_utah_2023gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'david_buxton', 'yea'),
    (rc, 'jacob_anderegg', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2023 roll 1400 — S.B. 153 Governor's Office of Economic Opportunity Amendments
  --   62-11-2, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2023GS&voteid=1400&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2023
     AND roll_number = 1400;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: utah house 2023 roll 1400 is missing — 20261003000000_vr_utah_2023gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'yea'),
    (rc, 'brian_king', 'yea'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'judy_weeks_rohner', 'yea'),
    (rc, 'kera_birkeland', 'yea'),
    (rc, 'mark_wheatley', 'yea'),
    (rc, 'quinn_kotter', 'nay'),
    (rc, 'robert_spendlove', 'yea'),
    (rc, 'rosemary_lesser', 'yea'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'nay')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2023 roll 286 — H.B. 42 Technology Commercialization Amendments
  --   51-20-4, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2023GS&voteid=286&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2023
     AND roll_number = 286;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: utah house 2023 roll 286 is missing — 20261003000000_vr_utah_2023gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'yea'),
    (rc, 'brian_king', 'not_voting'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'judy_weeks_rohner', 'nay'),
    (rc, 'kera_birkeland', 'nay'),
    (rc, 'mark_wheatley', 'yea'),
    (rc, 'quinn_kotter', 'nay'),
    (rc, 'robert_spendlove', 'yea'),
    (rc, 'rosemary_lesser', 'yea'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'nay')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah senate 2023 roll 986 — H.B. 42 Technology Commercialization Amendments
  --   19-6-4, 2 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2023GS&voteid=986&house=S
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah senate' AND congress IS NULL AND session = 2023
     AND roll_number = 986;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: utah senate 2023 roll 986 is missing — 20261003000000_vr_utah_2023gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'david_buxton', 'yea'),
    (rc, 'jacob_anderegg', 'nay')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2023 roll 328 — H.B. 289 Blockchain Provider Registration
  --   61-10-4, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2023GS&voteid=328&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2023
     AND roll_number = 328;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: utah house 2023 roll 328 is missing — 20261003000000_vr_utah_2023gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'nay'),
    (rc, 'brian_king', 'nay'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'judy_weeks_rohner', 'nay'),
    (rc, 'kera_birkeland', 'yea'),
    (rc, 'mark_wheatley', 'not_voting'),
    (rc, 'quinn_kotter', 'yea'),
    (rc, 'robert_spendlove', 'yea'),
    (rc, 'rosemary_lesser', 'not_voting'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2023 roll 1298 — H.B. 357 Decentralized Autonomous Organizations Amendments
  --   62-11-2, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2023GS&voteid=1298&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2023
     AND roll_number = 1298;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: utah house 2023 roll 1298 is missing — 20261003000000_vr_utah_2023gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'nay'),
    (rc, 'brian_king', 'yea'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'judy_weeks_rohner', 'nay'),
    (rc, 'kera_birkeland', 'yea'),
    (rc, 'mark_wheatley', 'yea'),
    (rc, 'quinn_kotter', 'nay'),
    (rc, 'robert_spendlove', 'yea'),
    (rc, 'rosemary_lesser', 'yea'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;
END $$;

-- ── Verification ─────────────────────────────────────────────────────────
DO $$
DECLARE n_rolls integer; short text;
BEGIN
  WITH want (chamber, session, roll_number) AS (VALUES
    ('utah house'::text, 2023::integer, 60::integer),
    ('utah senate'::text, 2023::integer, 105::integer),
    ('utah house'::text, 2023::integer, 1621::integer),
    ('utah house'::text, 2023::integer, 887::integer),
    ('utah house'::text, 2023::integer, 1306::integer),
    ('utah house'::text, 2023::integer, 955::integer),
    ('utah house'::text, 2023::integer, 1514::integer),
    ('utah house'::text, 2023::integer, 1626::integer),
    ('utah house'::text, 2023::integer, 117::integer),
    ('utah senate'::text, 2023::integer, 109::integer),
    ('utah house'::text, 2023::integer, 1524::integer),
    ('utah house'::text, 2023::integer, 392::integer),
    ('utah house'::text, 2023::integer, 313::integer),
    ('utah senate'::text, 2023::integer, 1642::integer),
    ('utah house'::text, 2023::integer, 908::integer),
    ('utah house'::text, 2023::integer, 315::integer),
    ('utah house'::text, 2023::integer, 137::integer),
    ('utah senate'::text, 2023::integer, 1592::integer),
    ('utah house'::text, 2023::integer, 1194::integer),
    ('utah house'::text, 2023::integer, 359::integer),
    ('utah senate'::text, 2023::integer, 1757::integer),
    ('utah house'::text, 2023::integer, 1165::integer),
    ('utah house'::text, 2023::integer, 407::integer),
    ('utah house'::text, 2023::integer, 609::integer),
    ('utah house'::text, 2023::integer, 709::integer),
    ('utah house'::text, 2023::integer, 1262::integer),
    ('utah house'::text, 2023::integer, 1354::integer),
    ('utah house'::text, 2023::integer, 1516::integer),
    ('utah house'::text, 2023::integer, 1337::integer),
    ('utah house'::text, 2023::integer, 1555::integer),
    ('utah house'::text, 2023::integer, 1155::integer),
    ('utah house'::text, 2023::integer, 1386::integer),
    ('utah house'::text, 2023::integer, 878::integer),
    ('utah senate'::text, 2023::integer, 466::integer),
    ('utah house'::text, 2023::integer, 975::integer),
    ('utah senate'::text, 2023::integer, 1307::integer),
    ('utah house'::text, 2023::integer, 1219::integer),
    ('utah house'::text, 2023::integer, 1296::integer),
    ('utah senate'::text, 2023::integer, 1608::integer),
    ('utah house'::text, 2023::integer, 462::integer),
    ('utah house'::text, 2023::integer, 329::integer),
    ('utah senate'::text, 2023::integer, 864::integer),
    ('utah house'::text, 2023::integer, 1640::integer),
    ('utah senate'::text, 2023::integer, 2100::integer),
    ('utah house'::text, 2023::integer, 1400::integer),
    ('utah house'::text, 2023::integer, 286::integer),
    ('utah senate'::text, 2023::integer, 986::integer),
    ('utah house'::text, 2023::integer, 328::integer),
    ('utah house'::text, 2023::integer, 1298::integer)
  ), roll_ids AS (
    SELECT r.id FROM vr_rollcalls r JOIN want w
      ON r.chamber = w.chamber AND r.session = w.session AND r.roll_number = w.roll_number
     WHERE r.congress IS NULL
  ), expected (politician_id, n) AS (VALUES
    ('brett_garner'::text, 36::integer),
    ('brian_king'::text, 38::integer),
    ('david_buxton'::text, 11::integer),
    ('jacob_anderegg'::text, 11::integer),
    ('james_cobb'::text, 38::integer),
    ('jeffrey_stenquist'::text, 38::integer),
    ('judy_weeks_rohner'::text, 38::integer),
    ('kera_birkeland'::text, 38::integer),
    ('mark_wheatley'::text, 38::integer),
    ('quinn_kotter'::text, 38::integer),
    ('robert_spendlove'::text, 38::integer),
    ('rosemary_lesser'::text, 38::integer),
    ('steven_lund'::text, 38::integer),
    ('susan_pulsipher'::text, 38::integer),
    ('tim_jimenez'::text, 38::integer)
  ), got AS (
    SELECT e.politician_id, e.n AS want_n,
           (SELECT count(*) FROM vr_member_votes v
             WHERE v.rollcall_id IN (SELECT id FROM roll_ids) AND v.politician_id = e.politician_id) AS have_n
      FROM expected e
  )
  SELECT (SELECT count(*) FROM roll_ids),
         (SELECT string_agg(politician_id || ' (' || have_n || ' of ' || want_n || ')', ', ')
            FROM got WHERE have_n < want_n)
    INTO n_rolls, short;
  RAISE NOTICE 'Utah 2023GS name admit: % roll calls, 15 members, 514 votes expected', n_rolls;
  IF n_rolls <> 49 THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: expected 49 state roll calls, found % — the state record did not land', n_rolls;
  END IF;
  IF short IS NOT NULL THEN
    RAISE EXCEPTION 'Utah 2023GS name admit: newly admitted member(s) arrived short: %', short;
  END IF;
END $$;
