-- ---------------------------------------------------------------------------
-- SAVE America Act — the February 2026 vehicle roll the facet pass could not see
-- ---------------------------------------------------------------------------
-- Generated by scripts/vr-gen-election-vehicle-migration.mjs from db/vr-elections-vote-seed.json.
-- Do not hand-edit: regenerate, or roll forward with a new migration.
--
-- 1 roll call · 56 attributed member votes · 1 measure
-- 1 election_security mapping · 1 voting_access mapping
--
-- A FORWARD DELTA, NOT A REGENERATION
-- The election-facet pass in 20260816000000_vr_election_facet_rollcalls.sql is applied
-- and is left alone. This migration adds the one roll call that pass concluded did not
-- exist, and nothing else: no row it already wrote is restated, and no facet it already
-- decided is re-filed.
--
-- THE CORRECTION, STATED PLAINLY
-- That pass recorded that the 119th Congress's second session contained no
-- election-administration measure of any kind. It contained this one. The Clerk's index
-- row and the roll's own vote-desc both read "Veterans Accessibility Advisory Committee
-- Act", the Senate bill S. 1383 as it passed the Senate by unanimous consent on
-- 2025-12-18. On 2026-02-11 the House considered it under a closed rule, adopted an
-- amendment in the nature of a substitute replacing the veterans text with the SAVE
-- America Act, and passed it 218-213. A keyword scan of titles cannot see a vehicle,
-- which is why the earlier finding was wrong and why every selection in this family is
-- verified on <legis-num> and question rather than on a caption.
--
-- HOW THE SUBSTITUTE WAS IDENTIFIED
-- Three members' own releases dated February 11, 2026 describe that day's vote as
-- passage of the SAVE America Act. The bill's GovInfo BILLSTATUS record confirms it: S.
-- 1383 carries the short titles "Safeguard American Voter Eligibility Act" and "SAVE
-- America Act" from the engrossed House amendment onward, and the House action at 18:44
-- on 2026-02-11 reads "On passage Passed by the Yeas and Nays: 218 - 213 (Roll no. 69).
-- (text of amendment in the nature of a substitute: CR H2138-2141)". The Clerk's XML for
-- the roll supplies the tally and every member position used below.
--
-- DIRECTION IS READ FROM THE SUBSTITUTE'S PROVISIONS
-- Both facets are mapped, in opposite directions, from the text of the engrossed House
-- amendment rather than from the vote's margin or its sponsors. election_security is
-- yea_supports: documentary proof of citizenship at registration, photo identification
-- at casting, comparison of state voter lists against the Department of Homeland
-- Security's SAVE system, and criminal penalties for officials who register an applicant
-- without proof. voting_access is yea_opposes: a mail-form applicant must present proof
-- in person to an election official, and an in-person voter without photo identification
-- may cast only a provisional ballot subject to a three-day cure. The substitute's own
-- easing provisions — an alternative-evidence pathway on a perjury attestation, a
-- former-name process, free public access to a copier, and exemptions for
-- uniformed-services and certain elderly and disabled voters — were read and weighed;
-- each accommodates the new requirement rather than widening access on its own, so the
-- yea does not point both ways and the access facet is not declined the way it is on
-- H.R. 1 and H.R. 5746. Full rationales are on the rows themselves.
--
-- SAME DAY, DECLINED
-- · S. 1383 house 119/2 roll 68 (214-217) — motion to commit the SAVE America Act
--   substitute to the Committee on House Administration, offered by Mr. Morelle — a
--   procedural disposition taken minutes before passage, not a vote on what the text does;
--   roll 69 is the passage vote
-- · H.Res. 1057 house 119/2 roll n/a (—) — closed rule providing for consideration of S.
--   1383 and three unrelated bills — rules are not policy, and
--   scripts/test-mapping-discipline.mjs refuses to let one be mapped at all. Its roll is
--   also a four-measure package, so no single position is readable from it
--
-- ATTRIBUTION IS FAIL-CLOSED
-- 56 of 432 voting members are on db/vr-member-map.json; the other 376 are skipped and
-- counted, never guessed. totals is the full chamber tally and is_party is computed from
-- the full recorded vote before the roster filter, so the roster subset cannot invent a
-- margin or a crossover. Unlike H.R. 22's roll 102, this roll has no earlier wider
-- ingest behind it, so the verification block's orphan check covers it in full.
--
-- Idempotent: the measure is created only when absent, and the roll call, member votes
-- and issue rows are all ON CONFLICT DO NOTHING.
-- ---------------------------------------------------------------------------

DO $$
DECLARE
  m_s1383 integer;
  rc integer;
BEGIN

  -- ── measure ───────────────────────────────────────────────────────────────
  -- S. 1383 (119th senate) — SAVE America Act
  -- Keyed on (congress, chamber, number): 'senate' is the bill's own chamber. The roll it
  -- was passed on is a House roll and is inserted as such below.
  SELECT id INTO m_s1383 FROM vr_measures
   WHERE congress = 119 AND chamber = 'senate' AND number = 'S. 1383' LIMIT 1;
  IF m_s1383 IS NULL THEN
    INSERT INTO vr_measures (measure_type, congress, chamber, number, title, short_title, summary, introduced_at, status, source_url, source_label, external_ids)
    VALUES ('bill', 119, 'senate', 'S. 1383', 'SAVE America Act', 'SAVE America Act',
      'The text the House substituted into S. 1383 — a Senate veterans-accessibility bill that passed the Senate by unanimous consent on 2025-12-18 — and passed 218-213 on 2026-02-11. Requires documentary proof of United States citizenship before a state may register an applicant for a federal election under any registration method, with mail-form applicants required to present their proof in person to an election official; requires a valid physical photo identification to receive an in-person ballot and a photo-ID copy or the last four Social Security digits with an affidavit to vote by mail; requires states to submit their voter lists to the Department of Homeland Security for comparison against the SAVE system and to remove non-citizens on verified information; and creates criminal penalties for an official who registers an applicant without the documentation. Carries an alternative-evidence pathway on a perjury attestation, a former-name process, a three-day cure for provisional ballots, and exemptions for uniformed-services and certain elderly and disabled voters. The Senate has not disposed of the House amendment: the motion to proceed to the House message carried 51-48 on 2026-03-17 and the chamber was still considering it in late March 2026.',
      DATE '2025-04-09', 'passed_house', 'https://www.govinfo.gov/content/pkg/BILLS-119s1383eah/html/BILLS-119s1383eah.htm', 'GovInfo — engrossed House amendment', '{"congressGovId":"s1383-119","billStatus":"https://www.govinfo.gov/bulkdata/BILLSTATUS/119/s/BILLSTATUS-119s1383.xml"}'::jsonb)
    RETURNING id INTO m_s1383;
  END IF;

  -- ── roll call and member votes ────────────────────────────────────────────
  -- house 119/2 roll 69 · S. 1383 · On Passage
  --   218-213, 1 not voting (D 1-213, R 217-0) · passed
  --   56 of 432 voting members are on the roster; 376 skipped as unmapped
  --   Clerk vote-desc reads "Veterans Accessibility Advisory Committee Act" — the vehicle's Senate title, not the substitute's
  INSERT INTO vr_rollcalls (measure_id, chamber, congress, session, roll_number, vote_date, question, action_type, result, required_majority, totals, source_url, source_label)
  VALUES (m_s1383, 'house', 119, 2, 69, TIMESTAMPTZ '2026-02-11T18:43:00-05:00', 'On Passage', 'passage', 'passed', 'simple',
    '{"yea":218,"nay":213,"present":0,"notVoting":1,"byParty":{"D":{"yea":1,"nay":213},"R":{"yea":217,"nay":0}}}'::jsonb, 'https://clerk.house.gov/evs/2026/roll069.xml', 'U.S. House Clerk')
  ON CONFLICT (chamber, congress, session, roll_number) DO NOTHING;
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'house' AND congress = 119 AND session = 2 AND roll_number = 69 LIMIT 1;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'SAVE America Act vehicle: house 119/2 roll 69 could not be read back after insert.';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position, is_party) VALUES
    (rc, 'adam_smith', 'nay', 'with_party'),
    (rc, 'aoc', 'nay', 'with_party'),
    (rc, 'bennie_thompson', 'nay', 'with_party'),
    (rc, 'bmoore', 'yea', 'with_party'),
    (rc, 'boebert', 'yea', 'with_party'),
    (rc, 'brian_mast', 'yea', 'with_party'),
    (rc, 'bruce_westerman', 'yea', 'with_party'),
    (rc, 'crockett', 'nay', 'with_party'),
    (rc, 'dan_goldman', 'nay', 'with_party'),
    (rc, 'don_bacon', 'yea', 'with_party'),
    (rc, 'don_davis', 'nay', 'with_party'),
    (rc, 'emmer', 'yea', 'with_party'),
    (rc, 'frank_lucas', 'yea', 'with_party'),
    (rc, 'french_hill', 'yea', 'with_party'),
    (rc, 'greg_landsman', 'nay', 'with_party'),
    (rc, 'haley_stevens', 'nay', 'with_party'),
    (rc, 'jake_auchincloss', 'nay', 'with_party'),
    (rc, 'jason_smith', 'yea', 'with_party'),
    (rc, 'jayapal', 'nay', 'with_party'),
    (rc, 'jeffries', 'nay', 'with_party'),
    (rc, 'jim_jordan', 'yea', 'with_party'),
    (rc, 'josh_brecheen', 'yea', 'with_party'),
    (rc, 'josh_gottheimer', 'nay', 'with_party'),
    (rc, 'julie_fedorchak', 'yea', 'with_party'),
    (rc, 'kclark', 'nay', 'with_party'),
    (rc, 'kennedy', 'yea', 'with_party'),
    (rc, 'khanna', 'nay', 'with_party'),
    (rc, 'mariannette_miller_meeks', 'yea', 'with_party'),
    (rc, 'massie', 'yea', 'with_party'),
    (rc, 'maxine_waters', 'nay', 'with_party'),
    (rc, 'meeks', 'nay', 'with_party'),
    (rc, 'michael_guest', 'yea', 'with_party'),
    (rc, 'mike_collins', 'yea', 'with_party'),
    (rc, 'mike_ezell', 'yea', 'with_party'),
    (rc, 'mike_flood', 'yea', 'with_party'),
    (rc, 'mike_johnson', 'yea', 'with_party'),
    (rc, 'mike_lawler', 'yea', 'with_party'),
    (rc, 'mike_simpson', 'yea', 'with_party'),
    (rc, 'omar', 'nay', 'with_party'),
    (rc, 'owens', 'yea', 'with_party'),
    (rc, 'rick_crawford', 'yea', 'with_party'),
    (rc, 'rob_bresnahan', 'yea', 'with_party'),
    (rc, 'ryan_mackenzie', 'yea', 'with_party'),
    (rc, 'scalise', 'yea', 'with_party'),
    (rc, 'scott_perry', 'yea', 'with_party'),
    (rc, 'stefanik', 'yea', 'with_party'),
    (rc, 'steny_hoyer', 'nay', 'with_party'),
    (rc, 'stephanie_bice', 'yea', 'with_party'),
    (rc, 'steve_womack', 'yea', 'with_party'),
    (rc, 'summer_lee', 'nay', 'with_party'),
    (rc, 'tlaib', 'nay', 'with_party'),
    (rc, 'tom_cole', 'yea', 'with_party'),
    (rc, 'tom_suozzi', 'nay', 'with_party'),
    (rc, 'torres', 'nay', 'with_party'),
    (rc, 'trent_kelly', 'yea', 'with_party'),
    (rc, 'troy_downing', 'yea', 'with_party')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- ── issue mappings ────────────────────────────────────────────────────────
  -- Curated in db/vr-issue-seed.json, with the provision-level rationale on every row.
  -- S. 1383 (119th) — election_security yea_supports, voting_access yea_opposes
  INSERT INTO vr_measure_issues (measure_id, issue_key, weight, is_primary, support_meaning, rationale, source_url) VALUES
    (m_s1383, 'election_security', 100, true, 'yea_supports',
      'SAVE America Act, the text the House substituted into S. 1383 on 2026-02-11 and passed 218-213 on roll 69. Mapped on the substitute''s own provisions, read from the engrossed House amendment: a state "shall not accept and process an application to register to vote in an election for Federal office unless the applicant presents documentary proof" of citizenship under any registration method; a new HAVA section bars an official from providing a ballot to an in-person voter who does not present "a valid physical photo identification" and requires mail voters to enclose a copy or the last four Social Security digits with an affidavit; states must submit their full voter lists to the Department of Homeland Security for comparison against the SAVE system and remove non-citizens on verified information; and new criminal penalties reach an official who registers an applicant without the documentation. Verification at registration, identification at casting, roll maintenance and fraud enforcement are the four things this facet covers, and the substitute does all four in the same direction, so a yea is a vote for tighter safeguards. The Clerk''s record for roll 69 still shows the Senate short title "Veterans Accessibility Advisory Committee Act" because S. 1383 was the vehicle; the substituted text is what the House voted on and what this mapping is made from.',
      'https://www.govinfo.gov/content/pkg/BILLS-119s1383eah/html/BILLS-119s1383eah.htm'),
    (m_s1383, 'voting_access', 80, false, 'yea_opposes',
      'The substitute adds a barrier at both steps this facet measures. At registration, a mail-form applicant must present proof "in person to the office of the appropriate election official" by the registration deadline, which closes mail and online registration to anyone who cannot appear; at casting, photo identification becomes a precondition for receiving an in-person ballot, and an in-person voter without one may only cast a provisional ballot and must cure it within three days. The bill''s easing provisions were read and weighed rather than ignored: an alternative-evidence pathway on a perjury attestation, a required process for applicants whose documents carry a former name, free public access to a copier or scanner in government buildings, and exemptions for uniformed-services and certain elderly and disabled voters. Each of those accommodates the new requirement rather than widening access on its own, so the yea does not point both ways here and the facet is not declined the way it is on H.R. 1 and H.R. 5746. Weighted above H.R. 8281''s 70 because that bill reached only the registration step while this one also conditions casting.',
      'https://www.govinfo.gov/content/pkg/BILLS-119s1383eah/html/BILLS-119s1383eah.htm')
  ON CONFLICT (measure_id, issue_key) DO NOTHING;

END $$;

-- ---------------------------------------------------------------------------
-- Verification
-- ---------------------------------------------------------------------------
-- Read-only, and scoped to this one roll call and this one measure. A global count would
-- drag in the seven rolls the earlier pass wrote and stop meaning anything.
-- ---------------------------------------------------------------------------
DO $$
DECLARE
  n_rolls integer;
  n_votes integer;
  n_orphan integer;
  n_sec integer;
  n_acc integer;
BEGIN
  WITH roll_ids AS (
    SELECT r.id FROM vr_rollcalls r
     WHERE r.chamber = 'house' AND r.congress = 119
       AND r.session = 2 AND r.roll_number = 69
  ), measure_ids AS (
    SELECT m.id FROM vr_measures m
     WHERE m.congress = 119 AND m.chamber = 'senate' AND m.number = 'S. 1383'
  )
  SELECT (SELECT count(*) FROM roll_ids),
         (SELECT count(*) FROM vr_member_votes v WHERE v.rollcall_id IN (SELECT id FROM roll_ids)),
         (SELECT count(*) FROM vr_member_votes v WHERE v.rollcall_id IN (SELECT id FROM roll_ids)
            AND v.politician_id NOT IN (
              'adam_smith', 'andy_kim', 'aoc', 'barrasso', 'bennie_thompson', 'bmoore', 'boebert', 'booker', 'brian_mast', 'britt', 'bruce_westerman', 'chris_murphy', 'collins', 'crockett', 'cruz', 'cstewart', 'curtis', 'dan_goldman', 'don_bacon', 'don_davis', 'durbin', 'emmer', 'ernst', 'fetterman', 'frank_lucas', 'french_hill', 'gaetz', 'gallego', 'graham', 'grassley', 'greg_landsman', 'haley_stevens', 'hawley', 'jake_auchincloss', 'jason_smith', 'jayapal', 'jeffries', 'jim_jordan', 'john_cornyn', 'jon_ossoff', 'josh_brecheen', 'josh_gottheimer', 'julie_fedorchak', 'kaine', 'kclark', 'kennedy', 'kennedy_john', 'khanna', 'lankford', 'lee', 'mariannette_miller_meeks', 'mark_kelly', 'massie', 'maxine_waters', 'mcconnell', 'meeks', 'michael_guest', 'mike_collins', 'mike_ezell', 'mike_flood', 'mike_johnson', 'mike_lawler', 'mike_simpson', 'mike_waltz', 'mtg', 'murkowski', 'omar', 'owens', 'rand_paul', 'reed', 'rick_crawford', 'risch', 'rob_bresnahan', 'rosen', 'rubio', 'ryan_mackenzie', 'sanders', 'scalise', 'schiff', 'schumer', 'scott_perry', 'shaheen', 'slotkin', 'stefanik', 'steny_hoyer', 'stephanie_bice', 'steve_womack', 'summer_lee', 'tgabbard', 'thune', 'tim_scott', 'tlaib', 'tom_cole', 'tom_suozzi', 'torres', 'trent_kelly', 'troy_downing', 'van_hollen', 'warnock', 'warren', 'zeldin'
            )),
         (SELECT count(*) FROM vr_measure_issues i WHERE i.issue_key = 'election_security'
            AND i.measure_id IN (SELECT id FROM measure_ids)),
         (SELECT count(*) FROM vr_measure_issues i WHERE i.issue_key = 'voting_access'
            AND i.measure_id IN (SELECT id FROM measure_ids))
    INTO n_rolls, n_votes, n_orphan, n_sec, n_acc;

  RAISE NOTICE 'SAVE America Act vehicle: % roll call, % member votes, % election_security and % voting_access mappings', n_rolls, n_votes, n_sec, n_acc;

  IF n_rolls <> 1 THEN
    RAISE EXCEPTION 'SAVE America Act vehicle: expected 1 roll call for house 119/2 roll 69, found %', n_rolls;
  END IF;
  IF n_votes < 56 THEN
    RAISE EXCEPTION 'SAVE America Act vehicle: expected at least 56 member votes on this roll call, found %', n_votes;
  END IF;
  IF n_orphan > 0 THEN
    RAISE EXCEPTION 'SAVE America Act vehicle: % member vote(s) carry a politician_id outside db/vr-member-map.json', n_orphan;
  END IF;
  IF n_sec <> 1 THEN
    RAISE EXCEPTION 'SAVE America Act vehicle: expected 1 election_security mapping, found %', n_sec;
  END IF;
  IF n_acc <> 1 THEN
    RAISE EXCEPTION 'SAVE America Act vehicle: expected 1 voting_access mapping, found %', n_acc;
  END IF;
END $$;
