-- ─────────────────────────────────────────────────────────────────────────────
-- vr_measures / vr_measure_issues / vr_positions — Utah 2025GS committee-only measures
-- ─────────────────────────────────────────────────────────────────────────────
-- WHAT THIS ADDS. 2 Utah bills whose committee rows changed after the earlier
-- 2025GS migration shipped, restated in full: 2 reviewed issue mappings and
-- 15 committee positions across 2 standing-committee actions, of which whatever
-- the database already holds is a no-op. Every one of these bills was already in the
-- committee ingest's refusal bucket for 2025GS: a CONTESTED pass-out-favorably vote,
-- confirmed against the published minutes PDF, with every voting name resolved through
-- the reviewed printed-name map — refused only because nobody had reviewed an issue
-- mapping for the parent bill. Wave 4 read the enrolled text and reviewed them.
--
-- WHERE THE MAPPINGS CAME FROM. db/vr-utah-committee-bills-2025GS.json, one entry per
-- bill, each carrying a direction, a weight, exactly one primary key and prose saying
-- what in the text supports it. 92 of the 170 bills in the bucket are REFUSED in the
-- same file, in writing. No issue key was added to the vocabulary for this pass.
--
-- NO FLOOR VOTES. These measures carry no vr_rollcalls row. A bill reaches this file
-- precisely because it has no admitted floor roll for 2025GS — its floor votes were
-- near-unanimous under the shipped 10%-minority bar, or it never reached a floor vote,
-- or it died in the second chamber. No floor action code was widened and no margin bar
-- was lowered to manufacture one. The consequence is stated rather than hidden:
-- 15 of the 15 positions are the member's ONLY act on that bill and all of them
-- count, because there is no floor vote on these measures for stance-helpers to
-- supersede them with (0 are superseded).
--
-- ACTION TYPE AND WEIGHT ARE UNCHANGED. 'committee_vote' at 0.60 in stance-helpers'
-- act table, printing as "Committee vote", exactly as 20261004000000 wrote it. This
-- file changes no weight, no label, no floor and no threshold.
--
-- THE TIME OF DAY IS NOT KNOWN. The minutes state the meeting's date and do not
-- timestamp the motion, so acted_at is that date at midnight Mountain Standard Time.
--
-- SOURCES. Every measure cites its bill page; every position cites the minutes PDF the
-- act was confirmed against. Each measure's external_ids records which document the
-- mapping was read out of — enrolled text, or the last substitute where the bill never
-- enrolled — so a reader can check the mapping against the same file the curator used.
--
-- THIS IS A DELTA, NOT THE WHOLE SEED. The 2025GS committee mapping already shipped
-- in an earlier migration and that file is applied, so it is not edited. This one
-- carries only the 2 bill(s) whose rows changed afterwards:
--   HB0528 · H.B. 528
--   SB0186 · S.B. 186
--
-- WHY THEY CHANGED.
-- These two bills are the 2025GS half of the four the vocabulary wave V1
-- (20261010000000) deliberately deferred: H.B. 528 under sound_money and
-- S.B. 186 under tobacco_nicotine. V1 refused to attribute their committee
-- votes because doing so needed the minutes bucket that
-- scripts/vr-utah-committee-ingest.mjs --bucket produces, and without it the
-- pass would have had to guess who was in the room. The bucket exists now,
-- the two curator mappings were already reviewed in
-- db/vr-utah-committee-bills-2025GS.json, and every printed name on both
-- acts resolved through db/vr-utah-committee-map.json's existing doors.
-- Nothing else in the 2025GS mapping lane changed: no other bill in the seed
-- gained or lost a row, no issue key was added, no weight moved and the
-- reviewed printed-name map for this session was not touched.
--
-- Each block below is the same generated block as before, unmodified: it selects the
-- measure before inserting, guards every issue mapping with NOT EXISTS, and ends every
-- position insert with ON CONFLICT DO NOTHING. Re-stating a bill that is already in
-- the database is a no-op; only rows that are genuinely new land.
-- Generated by scripts/vr-utah-committee-mapping.mjs --sql --session 2025GS --bills HB0528,SB0186. Idempotent.
-- ─────────────────────────────────────────────────────────────────────────────

-- HB0528 · H.B. 528 · Tax Payments with Precious Metals
--   mapping read from the substitute_1 text: https://le.utah.gov/Session/2025/bills/introduced/HB0528S01.xml
--   1 issue mapping(s), 1 committee action(s), 10 position(s)
DO $$
DECLARE m_id integer;
BEGIN
  SELECT id INTO m_id FROM vr_measures
   WHERE number = 'H.B. 528' AND chamber = 'utah house'
     AND external_ids->>'utahSession' = '2025GS' LIMIT 1;
  IF m_id IS NULL THEN
    INSERT INTO vr_measures (measure_type, congress, chamber, number, title,
      short_title, summary, status, source_url, source_label, external_ids)
    VALUES ('bill', NULL, 'utah house', 'H.B. 528', 'Tax Payments with Precious Metals',
      'Tax Payments with Precious Metals', 'This bill modifies provisions related to tax payments.', 'introduced',
      'https://le.utah.gov/~2025/bills/static/HB0528.html', 'Utah State Legislature',
      jsonb_build_object('utahSession', '2025GS', 'utahBill', 'HB0528',
        'primeSponsor', 'Rep. Ivory, Ken', 'floorSponsor', NULL,
        'mappingReadFrom', 'substitute_1', 'mappingTextUrl', 'https://le.utah.gov/Session/2025/bills/introduced/HB0528S01.xml',
        'committeeOnly', true))
    RETURNING id INTO m_id;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM vr_measure_issues
                  WHERE measure_id = m_id AND issue_key = 'sound_money') THEN
    INSERT INTO vr_measure_issues (measure_id, issue_key, weight, is_primary,
      support_meaning, rationale, source_url)
    VALUES (m_id, 'sound_money', 70, true,
      'yea_supports', 'First substitute text lets severance and income taxes be paid in gold, sets a reduced severance rate for a mine operator who remits in gold, and creates an income tax credit for doing so. Making the state accept metal as payment, and paying operators to use it, is the whole bill, so a yea widens the role of specie. The reduced rate and the credit are the inducement to remit in gold rather than a tax-policy ask of their own, which is why lower_taxes is not mapped here.', 'https://le.utah.gov/Session/2025/bills/introduced/HB0528S01.xml');
  END IF;
  -- 2025-03-03 · House Transportation Standing Committee · Vice Chair Defay moved to pass 1st Substitute H.B. 528 out favorably.
  --   printed tally 6-4-2 (yea-nay-absent); 10 named voter(s) on the PolitiDex roster
  INSERT INTO vr_positions (measure_id, politician_id, action_type, supports, acted_at, source_url, note) VALUES
    (m_id, 'aromero', 'committee_vote', false, '2025-03-03T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2025/pdf/00001894.pdf', 'House Transportation Standing Committee · meeting 19912 · Vice Chair Defay moved to pass 1st Substitute H.B. 528 out favorably.'),
    (m_id, 'ashlee_matthews', 'committee_vote', true, '2025-03-03T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2025/pdf/00001894.pdf', 'House Transportation Standing Committee · meeting 19912 · Vice Chair Defay moved to pass 1st Substitute H.B. 528 out favorably.'),
    (m_id, 'calvin_roberts', 'committee_vote', true, '2025-03-03T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2025/pdf/00001894.pdf', 'House Transportation Standing Committee · meeting 19912 · Vice Chair Defay moved to pass 1st Substitute H.B. 528 out favorably.'),
    (m_id, 'defay_h15', 'committee_vote', true, '2025-03-03T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2025/pdf/00001894.pdf', 'House Transportation Standing Committee · meeting 19912 · Vice Chair Defay moved to pass 1st Substitute H.B. 528 out favorably.'),
    (m_id, 'ivory_h39', 'committee_vote', true, '2025-03-03T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2025/pdf/00001894.pdf', 'House Transportation Standing Committee · meeting 19912 · Vice Chair Defay moved to pass 1st Substitute H.B. 528 out favorably.'),
    (m_id, 'jake_sawyer', 'committee_vote', true, '2025-03-03T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2025/pdf/00001894.pdf', 'House Transportation Standing Committee · meeting 19912 · Vice Chair Defay moved to pass 1st Substitute H.B. 528 out favorably.'),
    (m_id, 'kay_christofferson', 'committee_vote', false, '2025-03-03T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2025/pdf/00001894.pdf', 'House Transportation Standing Committee · meeting 19912 · Vice Chair Defay moved to pass 1st Substitute H.B. 528 out favorably.'),
    (m_id, 'mike_petersen', 'committee_vote', true, '2025-03-03T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2025/pdf/00001894.pdf', 'House Transportation Standing Committee · meeting 19912 · Vice Chair Defay moved to pass 1st Substitute H.B. 528 out favorably.'),
    (m_id, 'nthurston', 'committee_vote', false, '2025-03-03T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2025/pdf/00001894.pdf', 'House Transportation Standing Committee · meeting 19912 · Vice Chair Defay moved to pass 1st Substitute H.B. 528 out favorably.'),
    (m_id, 'rosalba_dominguez', 'committee_vote', false, '2025-03-03T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2025/pdf/00001894.pdf', 'House Transportation Standing Committee · meeting 19912 · Vice Chair Defay moved to pass 1st Substitute H.B. 528 out favorably.')
  ON CONFLICT (measure_id, politician_id, action_type) DO NOTHING;
END $$;

-- SB0186 · S.B. 186 · Tobacco and Electronic Cigarette Amendments
--   mapping read from the substitute_1 text: https://le.utah.gov/Session/2025/bills/introduced/SB0186S01.xml
--   1 issue mapping(s), 1 committee action(s), 5 position(s)
DO $$
DECLARE m_id integer;
BEGIN
  SELECT id INTO m_id FROM vr_measures
   WHERE number = 'S.B. 186' AND chamber = 'utah senate'
     AND external_ids->>'utahSession' = '2025GS' LIMIT 1;
  IF m_id IS NULL THEN
    INSERT INTO vr_measures (measure_type, congress, chamber, number, title,
      short_title, summary, status, source_url, source_label, external_ids)
    VALUES ('bill', NULL, 'utah senate', 'S.B. 186', 'Tobacco and Electronic Cigarette Amendments',
      'Tobacco and Electronic Cigarette Amendments', 'This bill amends provisions related to tobacco and electronic cigarette products.', 'introduced',
      'https://le.utah.gov/~2025/bills/static/SB0186.html', 'Utah State Legislature',
      jsonb_build_object('utahSession', '2025GS', 'utahBill', 'SB0186',
        'primeSponsor', 'Sen. Plumb, Jen', 'floorSponsor', 'Rep. Burton, Jefferson S.',
        'mappingReadFrom', 'substitute_1', 'mappingTextUrl', 'https://le.utah.gov/Session/2025/bills/introduced/SB0186S01.xml',
        'committeeOnly', true))
    RETURNING id INTO m_id;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM vr_measure_issues
                  WHERE measure_id = m_id AND issue_key = 'tobacco_nicotine') THEN
    INSERT INTO vr_measure_issues (measure_id, issue_key, weight, is_primary,
      support_meaning, rationale, source_url)
    VALUES (m_id, 'tobacco_nicotine', 80, true,
      'yea_supports', 'First substitute text adds registry and search provisions for tobacco and electronic cigarette products, creates penalties for a retailer selling flavored electronic cigarette products, raises permit fees for general retailers and specialty businesses, and amends the criminal penalties for illegal sales. Enforcement against nicotine retailers is the whole bill, and every provision tightens it, so a yea tightens the rules.', 'https://le.utah.gov/Session/2025/bills/introduced/SB0186S01.xml');
  END IF;
  -- 2025-01-30 · Senate Business and Labor Standing Committee · Sen. Pitcher moved to pass S.B. 186 out favorably.
  --   printed tally 4-1-3 (yea-nay-absent); 5 named voter(s) on the PolitiDex roster
  INSERT INTO vr_positions (measure_id, politician_id, action_type, supports, acted_at, source_url, note) VALUES
    (m_id, 'cmusselman', 'committee_vote', true, '2025-01-30T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2025/pdf/00000726.pdf', 'Senate Business and Labor Standing Committee · meeting 19597 · Sen. Pitcher moved to pass S.B. 186 out favorably.'),
    (m_id, 'dipson', 'committee_vote', true, '2025-01-30T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2025/pdf/00000726.pdf', 'Senate Business and Labor Standing Committee · meeting 19597 · Sen. Pitcher moved to pass S.B. 186 out favorably.'),
    (m_id, 'kcullimore', 'committee_vote', true, '2025-01-30T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2025/pdf/00000726.pdf', 'Senate Business and Labor Standing Committee · meeting 19597 · Sen. Pitcher moved to pass S.B. 186 out favorably.'),
    (m_id, 'stephanie_pitcher', 'committee_vote', true, '2025-01-30T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2025/pdf/00000726.pdf', 'Senate Business and Labor Standing Committee · meeting 19597 · Sen. Pitcher moved to pass S.B. 186 out favorably.'),
    (m_id, 'tweiler', 'committee_vote', false, '2025-01-30T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2025/pdf/00000726.pdf', 'Senate Business and Labor Standing Committee · meeting 19597 · Sen. Pitcher moved to pass S.B. 186 out favorably.')
  ON CONFLICT (measure_id, politician_id, action_type) DO NOTHING;
END $$;

