-- ═══════════════════════════════════════════════════════════════════════════
-- Utah 2024 General Session — floor votes unlocked by the wave-9 name admit
-- ═══════════════════════════════════════════════════════════════════════════
--
-- 20261002000000_vr_utah_2024gs_state_record.sql
-- 20261010000000_vr_vocab_wave_v1.sql
-- created these roll calls between them, their measures and their issue mappings, and wrote
-- the member votes the floor map could attribute at the time.
-- 364 other recorded votes on those SAME rolls were parsed and DISCARDED, because
-- db/vr-utah-member-map-2024GS.json can only map a printed name onto a roster id, and
-- the 14 people behind these printed forms were on no PolitiDex roster at all. The map
-- said so in writing and called adding them a roster decision for a later wave.
--
-- The roster then grew — wave 2's identity-only records and the committee waves' roster
-- door — and nothing went back to the floor map. So these votes stayed parsed and
-- dropped while the people they belong to sat on the roster with an empty or thin file.
-- scripts/vr-utah-name-admit.mjs closed that stale fence. This migration carries the votes.
--
-- NOTHING WAS GUESSED. Each printed form had to clear three independent gates before its
-- votes could land here: scripts/vr-utah-ingest.mjs --collect resolved it on its own
-- through the UNCHANGED uniqueness rule (surname plus a compatible first name, exactly one
-- candidate in the whole pool); the reviewed db/vr-utah-committee-map-2024GS.json
-- already carried the same person under the same surname and initial in the same chamber;
-- and the legislature's own 2024 roster (https://le.utah.gov/asp/roster/roster.asp?year=2024)
-- seats that full name in that chamber with the party and district the committee map's
-- confirmedBy line claims. A name that failed any gate is still unattributed, and the
-- printed forms the committee map REFUSES by name are still refused.
--
-- Additive and idempotent: member votes only, ON CONFLICT (rollcall_id, politician_id)
-- DO NOTHING. No measure, roll call or issue row is touched. A missing roll call RAISEs
-- rather than being created — this file holds none of the verified question, tally, date
-- or source that one needs.
--
-- Unlike 20261001000000_vr_utah_2025gs_roster_attribution_votes.sql, which re-asserted
-- every attributed vote on its rolls and let ON CONFLICT sort out the overlap, this file
-- emits ONLY the 14 newly admitted members' rows. Nothing else on these rolls can be
-- new — every other pid was already mapped when the state record landed — so re-stating
-- thousands of rows to have them all conflict away would hide the people this wave is
-- responsible for. The admitted set is not re-derived here: it is read off `_wave9Admitted`
-- in db/vr-utah-member-map-2024GS.json, the same file that records the mapping, and
-- cross-checked against `chambers` so the note and the mapping cannot disagree.
--
-- Roll calls are looked up on (chamber, session, roll_number) WITH congress IS NULL, the
-- tuple vr_rollcalls_state_unique is built on. vr_rollcalls_unique includes congress,
-- which is NULL on every state row, and Postgres treats NULLs as distinct.
--
-- Source of truth: db/vr-utah-vote-seed-2024GS.json, rebuilt by
-- scripts/vr-utah-ingest.mjs --seed from the cached le.utah.gov vote pages. Generated by
-- scripts/vr-gen-utah-name-admit-migration.mjs --session 2024GS.
--
-- Members gaining floor votes here (14), with the count each gains:
--   brett_garner              27
--   brian_king                27
--   david_buxton              13
--   james_cobb                27
--   jeffrey_stenquist         27
--   joel_briscoe              27
--   judy_weeks_rohner         27
--   kera_birkeland            27
--   mark_wheatley             27
--   robert_spendlove          27
--   rosemary_lesser           27
--   steven_lund               27
--   susan_pulsipher           27
--   tim_jimenez               27
-- ═══════════════════════════════════════════════════════════════════════════

DO $$
DECLARE rc bigint;
BEGIN

  -- utah house 2024 roll 49 — H.B. 257 Sex-based Designations for Privacy, Anti-bullying, and Women's Opportunities
  --   52-17-6, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2024GS&voteid=49&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2024
     AND roll_number = 49;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2024GS name admit: utah house 2024 roll 49 is missing — 20261002000000_vr_utah_2024gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'nay'),
    (rc, 'brian_king', 'nay'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'joel_briscoe', 'nay'),
    (rc, 'judy_weeks_rohner', 'nay'),
    (rc, 'kera_birkeland', 'yea'),
    (rc, 'mark_wheatley', 'nay'),
    (rc, 'robert_spendlove', 'yea'),
    (rc, 'rosemary_lesser', 'nay'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'not_voting'),
    (rc, 'tim_jimenez', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah senate 2024 roll 118 — H.B. 257 Sex-based Designations for Privacy, Anti-bullying, and Women's Opportunities
  --   21-8-0, 1 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2024GS&voteid=118&house=S
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah senate' AND congress IS NULL AND session = 2024
     AND roll_number = 118;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2024GS name admit: utah senate 2024 roll 118 is missing — 20261002000000_vr_utah_2024gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'david_buxton', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2024 roll 121 — H.B. 261 Equal Opportunity Initiatives
  --   60-14-1, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2024GS&voteid=121&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2024
     AND roll_number = 121;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2024GS name admit: utah house 2024 roll 121 is missing — 20261002000000_vr_utah_2024gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'nay'),
    (rc, 'brian_king', 'nay'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'joel_briscoe', 'nay'),
    (rc, 'judy_weeks_rohner', 'yea'),
    (rc, 'kera_birkeland', 'yea'),
    (rc, 'mark_wheatley', 'nay'),
    (rc, 'robert_spendlove', 'not_voting'),
    (rc, 'rosemary_lesser', 'nay'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah senate 2024 roll 114 — H.B. 261 Equal Opportunity Initiatives
  --   23-6-0, 1 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2024GS&voteid=114&house=S
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah senate' AND congress IS NULL AND session = 2024
     AND roll_number = 114;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2024GS name admit: utah senate 2024 roll 114 is missing — 20261002000000_vr_utah_2024gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'david_buxton', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2024 roll 123 — S.B. 57 Utah Constitutional Sovereignty Act
  --   58-15-2, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2024GS&voteid=123&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2024
     AND roll_number = 123;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2024GS name admit: utah house 2024 roll 123 is missing — 20261002000000_vr_utah_2024gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'nay'),
    (rc, 'brian_king', 'nay'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'joel_briscoe', 'nay'),
    (rc, 'judy_weeks_rohner', 'not_voting'),
    (rc, 'kera_birkeland', 'yea'),
    (rc, 'mark_wheatley', 'nay'),
    (rc, 'robert_spendlove', 'yea'),
    (rc, 'rosemary_lesser', 'nay'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah senate 2024 roll 45 — S.B. 57 Utah Constitutional Sovereignty Act
  --   22-7-0, 1 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2024GS&voteid=45&house=S
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah senate' AND congress IS NULL AND session = 2024
     AND roll_number = 45;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2024GS name admit: utah senate 2024 roll 45 is missing — 20261002000000_vr_utah_2024gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'david_buxton', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2024 roll 1289 — H.B. 529 Utah Fits All Scholarship Program Amendments
  --   53-16-6, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2024GS&voteid=1289&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2024
     AND roll_number = 1289;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2024GS name admit: utah house 2024 roll 1289 is missing — 20261002000000_vr_utah_2024gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'nay'),
    (rc, 'brian_king', 'nay'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'not_voting'),
    (rc, 'joel_briscoe', 'nay'),
    (rc, 'judy_weeks_rohner', 'yea'),
    (rc, 'kera_birkeland', 'not_voting'),
    (rc, 'mark_wheatley', 'nay'),
    (rc, 'robert_spendlove', 'yea'),
    (rc, 'rosemary_lesser', 'nay'),
    (rc, 'steven_lund', 'not_voting'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah senate 2024 roll 1477 — S.B. 44 Alternative Education Scholarship Combination
  --   23-6-0, 1 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2024GS&voteid=1477&house=S
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah senate' AND congress IS NULL AND session = 2024
     AND roll_number = 1477;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2024GS name admit: utah senate 2024 roll 1477 is missing — 20261002000000_vr_utah_2024gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'david_buxton', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2024 roll 1273 — H.B. 119 School Employee Firearm Possession Amendments
  --   53-13-9, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2024GS&voteid=1273&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2024
     AND roll_number = 1273;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2024GS name admit: utah house 2024 roll 1273 is missing — 20261002000000_vr_utah_2024gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'nay'),
    (rc, 'brian_king', 'nay'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'not_voting'),
    (rc, 'joel_briscoe', 'nay'),
    (rc, 'judy_weeks_rohner', 'yea'),
    (rc, 'kera_birkeland', 'yea'),
    (rc, 'mark_wheatley', 'not_voting'),
    (rc, 'robert_spendlove', 'yea'),
    (rc, 'rosemary_lesser', 'nay'),
    (rc, 'steven_lund', 'not_voting'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2024 roll 1186 — S.B. 194 Social Media Regulation Amendments
  --   61-11-3, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2024GS&voteid=1186&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2024
     AND roll_number = 1186;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2024GS name admit: utah house 2024 roll 1186 is missing — 20261002000000_vr_utah_2024gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'nay'),
    (rc, 'brian_king', 'yea'),
    (rc, 'james_cobb', 'not_voting'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'joel_briscoe', 'nay'),
    (rc, 'judy_weeks_rohner', 'nay'),
    (rc, 'kera_birkeland', 'nay'),
    (rc, 'mark_wheatley', 'yea'),
    (rc, 'robert_spendlove', 'yea'),
    (rc, 'rosemary_lesser', 'yea'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'nay')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2024 roll 934 — H.B. 374 State Energy Policy Amendments
  --   60-7-8, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2024GS&voteid=934&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2024
     AND roll_number = 934;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2024GS name admit: utah house 2024 roll 934 is missing — 20261002000000_vr_utah_2024gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'nay'),
    (rc, 'brian_king', 'yea'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'joel_briscoe', 'not_voting'),
    (rc, 'judy_weeks_rohner', 'yea'),
    (rc, 'kera_birkeland', 'yea'),
    (rc, 'mark_wheatley', 'yea'),
    (rc, 'robert_spendlove', 'not_voting'),
    (rc, 'rosemary_lesser', 'yea'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah senate 2024 roll 1317 — H.B. 374 State Energy Policy Amendments
  --   21-5-3, 1 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2024GS&voteid=1317&house=S
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah senate' AND congress IS NULL AND session = 2024
     AND roll_number = 1317;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2024GS name admit: utah senate 2024 roll 1317 is missing — 20261002000000_vr_utah_2024gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'david_buxton', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2024 roll 1368 — H.B. 215 Home Solar Energy Amendments
  --   59-8-8, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2024GS&voteid=1368&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2024
     AND roll_number = 1368;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2024GS name admit: utah house 2024 roll 1368 is missing — 20261002000000_vr_utah_2024gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'nay'),
    (rc, 'brian_king', 'nay'),
    (rc, 'james_cobb', 'not_voting'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'joel_briscoe', 'nay'),
    (rc, 'judy_weeks_rohner', 'yea'),
    (rc, 'kera_birkeland', 'not_voting'),
    (rc, 'mark_wheatley', 'yea'),
    (rc, 'robert_spendlove', 'yea'),
    (rc, 'rosemary_lesser', 'yea'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah senate 2024 roll 1934 — H.B. 215 Home Solar Energy Amendments
  --   19-5-5, 1 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2024GS&voteid=1934&house=S
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah senate' AND congress IS NULL AND session = 2024
     AND roll_number = 1934;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2024GS name admit: utah senate 2024 roll 1934 is missing — 20261002000000_vr_utah_2024gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'david_buxton', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2024 roll 1434 — S.B. 224 Energy Independence Amendments
  --   54-19-2, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2024GS&voteid=1434&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2024
     AND roll_number = 1434;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2024GS name admit: utah house 2024 roll 1434 is missing — 20261002000000_vr_utah_2024gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'nay'),
    (rc, 'brian_king', 'nay'),
    (rc, 'james_cobb', 'nay'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'joel_briscoe', 'nay'),
    (rc, 'judy_weeks_rohner', 'yea'),
    (rc, 'kera_birkeland', 'not_voting'),
    (rc, 'mark_wheatley', 'nay'),
    (rc, 'robert_spendlove', 'yea'),
    (rc, 'rosemary_lesser', 'nay'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah senate 2024 roll 2154 — S.B. 224 Energy Independence Amendments
  --   21-6-2, 1 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2024GS&voteid=2154&house=S
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah senate' AND congress IS NULL AND session = 2024
     AND roll_number = 2154;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2024GS name admit: utah senate 2024 roll 2154 is missing — 20261002000000_vr_utah_2024gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'david_buxton', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2024 roll 1177 — S.B. 161 Energy Security Amendments
  --   47-25-3, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2024GS&voteid=1177&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2024
     AND roll_number = 1177;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2024GS name admit: utah house 2024 roll 1177 is missing — 20261002000000_vr_utah_2024gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'nay'),
    (rc, 'brian_king', 'nay'),
    (rc, 'james_cobb', 'nay'),
    (rc, 'jeffrey_stenquist', 'nay'),
    (rc, 'joel_briscoe', 'nay'),
    (rc, 'judy_weeks_rohner', 'yea'),
    (rc, 'kera_birkeland', 'yea'),
    (rc, 'mark_wheatley', 'nay'),
    (rc, 'robert_spendlove', 'yea'),
    (rc, 'rosemary_lesser', 'nay'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'nay'),
    (rc, 'tim_jimenez', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah senate 2024 roll 1839 — S.B. 161 Energy Security Amendments
  --   18-10-1, 1 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2024GS&voteid=1839&house=S
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah senate' AND congress IS NULL AND session = 2024
     AND roll_number = 1839;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2024GS name admit: utah senate 2024 roll 1839 is missing — 20261002000000_vr_utah_2024gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'david_buxton', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2024 roll 760 — H.B. 11 Water Efficient Landscaping Requirements
  --   59-12-4, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2024GS&voteid=760&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2024
     AND roll_number = 760;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2024GS name admit: utah house 2024 roll 760 is missing — 20261002000000_vr_utah_2024gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'yea'),
    (rc, 'brian_king', 'yea'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'joel_briscoe', 'yea'),
    (rc, 'judy_weeks_rohner', 'yea'),
    (rc, 'kera_birkeland', 'nay'),
    (rc, 'mark_wheatley', 'yea'),
    (rc, 'robert_spendlove', 'not_voting'),
    (rc, 'rosemary_lesser', 'yea'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah senate 2024 roll 2022 — S.B. 208 Housing and Transit Reinvestment Zone Amendments
  --   23-3-3, 1 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2024GS&voteid=2022&house=S
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah senate' AND congress IS NULL AND session = 2024
     AND roll_number = 2022;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2024GS name admit: utah senate 2024 roll 2022 is missing — 20261002000000_vr_utah_2024gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'david_buxton', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2024 roll 1166 — S.B. 268 First Home Investment Zone Act
  --   55-18-2, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2024GS&voteid=1166&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2024
     AND roll_number = 1166;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2024GS name admit: utah house 2024 roll 1166 is missing — 20261002000000_vr_utah_2024gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'nay'),
    (rc, 'brian_king', 'yea'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'joel_briscoe', 'yea'),
    (rc, 'judy_weeks_rohner', 'not_voting'),
    (rc, 'kera_birkeland', 'nay'),
    (rc, 'mark_wheatley', 'nay'),
    (rc, 'robert_spendlove', 'yea'),
    (rc, 'rosemary_lesser', 'yea'),
    (rc, 'steven_lund', 'nay'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah senate 2024 roll 1844 — S.B. 268 First Home Investment Zone Act
  --   20-7-2, 1 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2024GS&voteid=1844&house=S
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah senate' AND congress IS NULL AND session = 2024
     AND roll_number = 1844;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2024GS name admit: utah senate 2024 roll 1844 is missing — 20261002000000_vr_utah_2024gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'david_buxton', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2024 roll 1147 — H.B. 153 Child Care Revisions
  --   50-21-4, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2024GS&voteid=1147&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2024
     AND roll_number = 1147;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2024GS name admit: utah house 2024 roll 1147 is missing — 20261002000000_vr_utah_2024gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'nay'),
    (rc, 'brian_king', 'nay'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'joel_briscoe', 'nay'),
    (rc, 'judy_weeks_rohner', 'yea'),
    (rc, 'kera_birkeland', 'yea'),
    (rc, 'mark_wheatley', 'yea'),
    (rc, 'robert_spendlove', 'yea'),
    (rc, 'rosemary_lesser', 'yea'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2024 roll 968 — H.B. 461 Child Care Grant Amendments
  --   57-15-3, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2024GS&voteid=968&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2024
     AND roll_number = 968;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2024GS name admit: utah house 2024 roll 968 is missing — 20261002000000_vr_utah_2024gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'yea'),
    (rc, 'brian_king', 'yea'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'joel_briscoe', 'yea'),
    (rc, 'judy_weeks_rohner', 'yea'),
    (rc, 'kera_birkeland', 'not_voting'),
    (rc, 'mark_wheatley', 'yea'),
    (rc, 'robert_spendlove', 'yea'),
    (rc, 'rosemary_lesser', 'yea'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'nay')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2024 roll 1168 — S.B. 173 Market Informed Compensation for Teachers
  --   40-32-3, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2024GS&voteid=1168&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2024
     AND roll_number = 1168;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2024GS name admit: utah house 2024 roll 1168 is missing — 20261002000000_vr_utah_2024gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'nay'),
    (rc, 'brian_king', 'nay'),
    (rc, 'james_cobb', 'nay'),
    (rc, 'jeffrey_stenquist', 'nay'),
    (rc, 'joel_briscoe', 'nay'),
    (rc, 'judy_weeks_rohner', 'not_voting'),
    (rc, 'kera_birkeland', 'yea'),
    (rc, 'mark_wheatley', 'nay'),
    (rc, 'robert_spendlove', 'yea'),
    (rc, 'rosemary_lesser', 'nay'),
    (rc, 'steven_lund', 'nay'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'nay')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah senate 2024 roll 1575 — S.B. 173 Market Informed Compensation for Teachers
  --   21-6-2, 1 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2024GS&voteid=1575&house=S
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah senate' AND congress IS NULL AND session = 2024
     AND roll_number = 1575;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2024GS name admit: utah senate 2024 roll 1575 is missing — 20261002000000_vr_utah_2024gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'david_buxton', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2024 roll 1193 — H.B. 68 Drug Sentencing Modifications
  --   39-31-5, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2024GS&voteid=1193&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2024
     AND roll_number = 1193;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2024GS name admit: utah house 2024 roll 1193 is missing — 20261002000000_vr_utah_2024gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'yea'),
    (rc, 'brian_king', 'yea'),
    (rc, 'james_cobb', 'nay'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'joel_briscoe', 'yea'),
    (rc, 'judy_weeks_rohner', 'nay'),
    (rc, 'kera_birkeland', 'nay'),
    (rc, 'mark_wheatley', 'yea'),
    (rc, 'robert_spendlove', 'yea'),
    (rc, 'rosemary_lesser', 'yea'),
    (rc, 'steven_lund', 'nay'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'nay')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2024 roll 1293 — H.B. 273 Sentencing Modifications for Certain DUI Offenses
  --   47-24-4, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2024GS&voteid=1293&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2024
     AND roll_number = 1293;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2024GS name admit: utah house 2024 roll 1293 is missing — 20261002000000_vr_utah_2024gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'yea'),
    (rc, 'brian_king', 'yea'),
    (rc, 'james_cobb', 'nay'),
    (rc, 'jeffrey_stenquist', 'not_voting'),
    (rc, 'joel_briscoe', 'yea'),
    (rc, 'judy_weeks_rohner', 'nay'),
    (rc, 'kera_birkeland', 'yea'),
    (rc, 'mark_wheatley', 'yea'),
    (rc, 'robert_spendlove', 'nay'),
    (rc, 'rosemary_lesser', 'yea'),
    (rc, 'steven_lund', 'not_voting'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'nay')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2024 roll 1338 — S.B. 60 Drug Paraphernalia Amendments
  --   56-16-3, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2024GS&voteid=1338&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2024
     AND roll_number = 1338;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2024GS name admit: utah house 2024 roll 1338 is missing — 20261002000000_vr_utah_2024gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'yea'),
    (rc, 'brian_king', 'yea'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'joel_briscoe', 'yea'),
    (rc, 'judy_weeks_rohner', 'yea'),
    (rc, 'kera_birkeland', 'nay'),
    (rc, 'mark_wheatley', 'yea'),
    (rc, 'robert_spendlove', 'yea'),
    (rc, 'rosemary_lesser', 'yea'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'nay')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2024 roll 1074 — H.B. 471 Public Lands Possession Amendments
  --   59-11-5, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2024GS&voteid=1074&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2024
     AND roll_number = 1074;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2024GS name admit: utah house 2024 roll 1074 is missing — 20261002000000_vr_utah_2024gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'nay'),
    (rc, 'brian_king', 'nay'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'joel_briscoe', 'nay'),
    (rc, 'judy_weeks_rohner', 'yea'),
    (rc, 'kera_birkeland', 'yea'),
    (rc, 'mark_wheatley', 'nay'),
    (rc, 'robert_spendlove', 'not_voting'),
    (rc, 'rosemary_lesser', 'nay'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2024 roll 1170 — S.B. 69 Income Tax Amendments
  --   63-11-1, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2024GS&voteid=1170&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2024
     AND roll_number = 1170;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2024GS name admit: utah house 2024 roll 1170 is missing — 20261002000000_vr_utah_2024gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'nay'),
    (rc, 'brian_king', 'nay'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'joel_briscoe', 'nay'),
    (rc, 'judy_weeks_rohner', 'yea'),
    (rc, 'kera_birkeland', 'yea'),
    (rc, 'mark_wheatley', 'nay'),
    (rc, 'robert_spendlove', 'yea'),
    (rc, 'rosemary_lesser', 'yea'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah senate 2024 roll 246 — S.B. 69 Income Tax Amendments
  --   23-6-0, 1 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2024GS&voteid=246&house=S
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah senate' AND congress IS NULL AND session = 2024
     AND roll_number = 246;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2024GS name admit: utah senate 2024 roll 246 is missing — 20261002000000_vr_utah_2024gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'david_buxton', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2024 roll 1000 — H.B. 165 Federal Law Enforcement Amendments
  --   63-11-1, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2024GS&voteid=1000&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2024
     AND roll_number = 1000;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2024GS name admit: utah house 2024 roll 1000 is missing — 20261002000000_vr_utah_2024gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'nay'),
    (rc, 'brian_king', 'nay'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'joel_briscoe', 'nay'),
    (rc, 'judy_weeks_rohner', 'yea'),
    (rc, 'kera_birkeland', 'yea'),
    (rc, 'mark_wheatley', 'nay'),
    (rc, 'robert_spendlove', 'yea'),
    (rc, 'rosemary_lesser', 'yea'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2024 roll 859 — H.B. 269 Public School History Curricula Amendments
  --   49-16-10, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2024GS&voteid=859&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2024
     AND roll_number = 859;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2024GS name admit: utah house 2024 roll 859 is missing — 20261002000000_vr_utah_2024gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'nay'),
    (rc, 'brian_king', 'nay'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'joel_briscoe', 'nay'),
    (rc, 'judy_weeks_rohner', 'yea'),
    (rc, 'kera_birkeland', 'yea'),
    (rc, 'mark_wheatley', 'nay'),
    (rc, 'robert_spendlove', 'yea'),
    (rc, 'rosemary_lesser', 'not_voting'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'nay'),
    (rc, 'tim_jimenez', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2024 roll 638 — H.B. 182 Student Survey Amendments
  --   57-11-7, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2024GS&voteid=638&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2024
     AND roll_number = 638;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2024GS name admit: utah house 2024 roll 638 is missing — 20261002000000_vr_utah_2024gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'nay'),
    (rc, 'brian_king', 'nay'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'joel_briscoe', 'yea'),
    (rc, 'judy_weeks_rohner', 'yea'),
    (rc, 'kera_birkeland', 'not_voting'),
    (rc, 'mark_wheatley', 'nay'),
    (rc, 'robert_spendlove', 'not_voting'),
    (rc, 'rosemary_lesser', 'nay'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2024 roll 314 — H.B. 158 Criminal Defamation Amendments
  --   61-11-3, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2024GS&voteid=314&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2024
     AND roll_number = 314;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2024GS name admit: utah house 2024 roll 314 is missing — 20261002000000_vr_utah_2024gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'yea'),
    (rc, 'brian_king', 'yea'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'joel_briscoe', 'nay'),
    (rc, 'judy_weeks_rohner', 'yea'),
    (rc, 'kera_birkeland', 'yea'),
    (rc, 'mark_wheatley', 'yea'),
    (rc, 'robert_spendlove', 'not_voting'),
    (rc, 'rosemary_lesser', 'yea'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2024 roll 1377 — H.B. 405 Public Health Amendments
  --   58-11-6, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2024GS&voteid=1377&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2024
     AND roll_number = 1377;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2024GS name admit: utah house 2024 roll 1377 is missing — 20261002000000_vr_utah_2024gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'yea'),
    (rc, 'brian_king', 'nay'),
    (rc, 'james_cobb', 'yea'),
    (rc, 'jeffrey_stenquist', 'yea'),
    (rc, 'joel_briscoe', 'yea'),
    (rc, 'judy_weeks_rohner', 'not_voting'),
    (rc, 'kera_birkeland', 'yea'),
    (rc, 'mark_wheatley', 'nay'),
    (rc, 'robert_spendlove', 'yea'),
    (rc, 'rosemary_lesser', 'nay'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2024 roll 1362 — S.B. 272 Capital City Revitalization Zone
  --   50-20-5, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2024GS&voteid=1362&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2024
     AND roll_number = 1362;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2024GS name admit: utah house 2024 roll 1362 is missing — 20261002000000_vr_utah_2024gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'nay'),
    (rc, 'brian_king', 'yea'),
    (rc, 'james_cobb', 'nay'),
    (rc, 'jeffrey_stenquist', 'nay'),
    (rc, 'joel_briscoe', 'yea'),
    (rc, 'judy_weeks_rohner', 'nay'),
    (rc, 'kera_birkeland', 'not_voting'),
    (rc, 'mark_wheatley', 'yea'),
    (rc, 'robert_spendlove', 'yea'),
    (rc, 'rosemary_lesser', 'yea'),
    (rc, 'steven_lund', 'nay'),
    (rc, 'susan_pulsipher', 'nay'),
    (rc, 'tim_jimenez', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah senate 2024 roll 2040 — S.B. 272 Capital City Revitalization Zone
  --   22-4-3, 1 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2024GS&voteid=2040&house=S
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah senate' AND congress IS NULL AND session = 2024
     AND roll_number = 2040;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2024GS name admit: utah senate 2024 roll 2040 is missing — 20261002000000_vr_utah_2024gs_state_record.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'david_buxton', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- utah house 2024 roll 895 — H.B. 348 Precious Metals Amendments
  --   52-18-5, 13 newly admitted · https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2024GS&voteid=895&house=H
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'utah house' AND congress IS NULL AND session = 2024
     AND roll_number = 895;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Utah 2024GS name admit: utah house 2024 roll 895 is missing — 20261010000000_vr_vocab_wave_v1.sql must run first; this migration never creates a roll call because it holds none of the verified question, tally, date or source';
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc, 'brett_garner', 'nay'),
    (rc, 'brian_king', 'yea'),
    (rc, 'james_cobb', 'nay'),
    (rc, 'jeffrey_stenquist', 'not_voting'),
    (rc, 'joel_briscoe', 'nay'),
    (rc, 'judy_weeks_rohner', 'yea'),
    (rc, 'kera_birkeland', 'yea'),
    (rc, 'mark_wheatley', 'nay'),
    (rc, 'robert_spendlove', 'not_voting'),
    (rc, 'rosemary_lesser', 'nay'),
    (rc, 'steven_lund', 'yea'),
    (rc, 'susan_pulsipher', 'yea'),
    (rc, 'tim_jimenez', 'yea')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;
END $$;

-- ── Verification ─────────────────────────────────────────────────────────
DO $$
DECLARE n_rolls integer; short text;
BEGIN
  WITH want (chamber, session, roll_number) AS (VALUES
    ('utah house'::text, 2024::integer, 49::integer),
    ('utah senate'::text, 2024::integer, 118::integer),
    ('utah house'::text, 2024::integer, 121::integer),
    ('utah senate'::text, 2024::integer, 114::integer),
    ('utah house'::text, 2024::integer, 123::integer),
    ('utah senate'::text, 2024::integer, 45::integer),
    ('utah house'::text, 2024::integer, 1289::integer),
    ('utah senate'::text, 2024::integer, 1477::integer),
    ('utah house'::text, 2024::integer, 1273::integer),
    ('utah house'::text, 2024::integer, 1186::integer),
    ('utah house'::text, 2024::integer, 934::integer),
    ('utah senate'::text, 2024::integer, 1317::integer),
    ('utah house'::text, 2024::integer, 1368::integer),
    ('utah senate'::text, 2024::integer, 1934::integer),
    ('utah house'::text, 2024::integer, 1434::integer),
    ('utah senate'::text, 2024::integer, 2154::integer),
    ('utah house'::text, 2024::integer, 1177::integer),
    ('utah senate'::text, 2024::integer, 1839::integer),
    ('utah house'::text, 2024::integer, 760::integer),
    ('utah senate'::text, 2024::integer, 2022::integer),
    ('utah house'::text, 2024::integer, 1166::integer),
    ('utah senate'::text, 2024::integer, 1844::integer),
    ('utah house'::text, 2024::integer, 1147::integer),
    ('utah house'::text, 2024::integer, 968::integer),
    ('utah house'::text, 2024::integer, 1168::integer),
    ('utah senate'::text, 2024::integer, 1575::integer),
    ('utah house'::text, 2024::integer, 1193::integer),
    ('utah house'::text, 2024::integer, 1293::integer),
    ('utah house'::text, 2024::integer, 1338::integer),
    ('utah house'::text, 2024::integer, 1074::integer),
    ('utah house'::text, 2024::integer, 1170::integer),
    ('utah senate'::text, 2024::integer, 246::integer),
    ('utah house'::text, 2024::integer, 1000::integer),
    ('utah house'::text, 2024::integer, 859::integer),
    ('utah house'::text, 2024::integer, 638::integer),
    ('utah house'::text, 2024::integer, 314::integer),
    ('utah house'::text, 2024::integer, 1377::integer),
    ('utah house'::text, 2024::integer, 1362::integer),
    ('utah senate'::text, 2024::integer, 2040::integer),
    ('utah house'::text, 2024::integer, 895::integer)
  ), roll_ids AS (
    SELECT r.id FROM vr_rollcalls r JOIN want w
      ON r.chamber = w.chamber AND r.session = w.session AND r.roll_number = w.roll_number
     WHERE r.congress IS NULL
  ), expected (politician_id, n) AS (VALUES
    ('brett_garner'::text, 27::integer),
    ('brian_king'::text, 27::integer),
    ('david_buxton'::text, 13::integer),
    ('james_cobb'::text, 27::integer),
    ('jeffrey_stenquist'::text, 27::integer),
    ('joel_briscoe'::text, 27::integer),
    ('judy_weeks_rohner'::text, 27::integer),
    ('kera_birkeland'::text, 27::integer),
    ('mark_wheatley'::text, 27::integer),
    ('robert_spendlove'::text, 27::integer),
    ('rosemary_lesser'::text, 27::integer),
    ('steven_lund'::text, 27::integer),
    ('susan_pulsipher'::text, 27::integer),
    ('tim_jimenez'::text, 27::integer)
  ), got AS (
    SELECT e.politician_id, e.n AS want_n,
           (SELECT count(*) FROM vr_member_votes v
             WHERE v.rollcall_id IN (SELECT id FROM roll_ids) AND v.politician_id = e.politician_id) AS have_n
      FROM expected e
  )
  SELECT (SELECT count(*) FROM roll_ids),
         (SELECT string_agg(politician_id || ' (' || have_n || ' of ' || want_n || ')', ', ')
            FROM got WHERE have_n < want_n)
    INTO n_rolls, short;
  RAISE NOTICE 'Utah 2024GS name admit: % roll calls, 14 members, 364 votes expected', n_rolls;
  IF n_rolls <> 40 THEN
    RAISE EXCEPTION 'Utah 2024GS name admit: expected 40 state roll calls, found % — the state record did not land', n_rolls;
  END IF;
  IF short IS NOT NULL THEN
    RAISE EXCEPTION 'Utah 2024GS name admit: newly admitted member(s) arrived short: %', short;
  END IF;
END $$;
