-- ---------------------------------------------------------------------------
-- Stored vote corrections — each cell named, each cell cited
-- ---------------------------------------------------------------------------
-- Generated by scripts/vr-gen-vote-corrections-migration.mjs from db/vr-vote-corrections-seed.json.
-- Do not hand-edit: regenerate, or roll forward with a new migration.
--
-- 18 stored member votes corrected across 8 roll calls · 15 members
-- house + senate · 0 votes created · 0 votes deleted · 0 roll calls, measures, mappings,
-- stated positions or profiles touched
--
-- WHERE THESE CAME FROM
-- The August 2026 attribution backfill re-read the official documents for every roll
-- call it filled, and re-checked the cells we ALREADY held against them as it went.
-- 7,931 stored cells agreed. These did not. The backfill was ON CONFLICT DO NOTHING
-- throughout and deliberately refused to touch them, on the grounds that correcting a
-- stored vote is a deliberate act with its own citation. This is that act.
--
-- Most of them trace to attribution by inference in earlier seed waves — a member's
-- position filled in from a party's overall split rather than read off the roll — which
-- is exactly the failure mode that makes a not-voting member look like a voting one.
--
-- WHAT WAS VERIFIED BEFORE EACH LINE WAS WRITTEN
-- Every one of the 18 reported disagreements was re-checked from scratch by
-- scripts/vr-verify-vote-corrections.mjs: the roll call resolves to exactly one stored
-- row; the document identifies itself as that roll; the member is found in it by
-- published identifier (Bioguide via name-id for the House, LIS member id — confirmed
-- twice — for the Senate) and never by name; a fresh parse reproduces the official
-- position exactly; and the database still holds the value that was examined. A row
-- failing any of those is left alone and reported rather than corrected.
-- Verified: 18 · left uncorrected: 0
--
-- THE SHAPE OF THE CORRECTIONS
--    8 × stored yea → not_voting
--    5 × stored nay → not_voting
--    3 × stored yea → nay
--    2 × stored nay → yea
--   13 of the 18 move a member INTO present-or-not-voting, which is the direction
-- that matters most: a vote we recorded for someone who was not there is a sentence
-- about them that the record does not support.
--
-- is_party IS CORRECTED WITH THE POSITION
-- Where a member moves to not voting, is_party goes to NULL — no recorded vote, no side
-- to be with or against. Where the corrected position is a yea or a nay, is_party is
-- recomputed from that document's own party split, by the rule the backfill used.
--
-- IDEMPOTENT, AND FAIL-CLOSED
-- Each block reads the stored value first. It corrects only a cell still holding the
-- value the verification examined, treats a cell already holding the corrected value as
-- done, and RAISEs on a missing cell or on any third value — because at that point
-- something changed underneath this migration and it should stop, not overwrite.
--
-- Seed → member-map agreement: 18 cached politicianId(s) re-checked against
-- db/vr-member-map.json at generation time; 0 stale, 0 unresolvable.

DO $$
DECLARE
  rc BIGINT;
  cur TEXT;
  fixed INT := 0;
  already INT := 0;
BEGIN

  -- house 118/2 roll 456 · H.R. 82 · On Passage · 2024-11-12
  --   massie (M001184) stored 'nay' / is_party NULL; the document says 'yea' / with_party
  --   U.S. House roll call 2024-456 — https://clerk.house.gov/evs/2024/roll456.xml
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'house' AND congress = 118 AND session = 2
     AND roll_number = 456 LIMIT 1;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Vote correction: house 118/2 roll 456 is not in vr_rollcalls, so there is no cell to correct.';
  END IF;
  SELECT position INTO cur FROM vr_member_votes WHERE rollcall_id = rc AND politician_id = 'massie';
  IF cur IS NULL THEN
    RAISE EXCEPTION 'Vote correction: house 118/2 roll 456 holds no stored vote for massie. This migration corrects cells that exist and creates none.';
  ELSIF cur = 'nay' THEN
    UPDATE vr_member_votes
       SET position = 'yea', is_party = 'with_party'
     WHERE rollcall_id = rc AND politician_id = 'massie' AND position = 'nay';
    fixed := fixed + 1;
  ELSIF cur = 'yea' THEN
    already := already + 1;
  ELSE
    RAISE EXCEPTION 'Vote correction: house 118/2 roll 456 holds ''%'' for massie, which is neither the value this correction examined (''nay'') nor the value it would write (''yea''). Something changed underneath this migration; refusing to overwrite it.', cur;
  END IF;

  -- house 119/1 roll 12 · H.R. 28 · On Passage · 2025-01-14
  --   mcclain (M001136) stored 'yea' / with_party; the document says 'not_voting' / no side
  --   U.S. House roll call 2025-12 — https://clerk.house.gov/evs/2025/roll012.xml
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'house' AND congress = 119 AND session = 1
     AND roll_number = 12 LIMIT 1;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Vote correction: house 119/1 roll 12 is not in vr_rollcalls, so there is no cell to correct.';
  END IF;
  SELECT position INTO cur FROM vr_member_votes WHERE rollcall_id = rc AND politician_id = 'mcclain';
  IF cur IS NULL THEN
    RAISE EXCEPTION 'Vote correction: house 119/1 roll 12 holds no stored vote for mcclain. This migration corrects cells that exist and creates none.';
  ELSIF cur = 'yea' THEN
    UPDATE vr_member_votes
       SET position = 'not_voting', is_party = NULL
     WHERE rollcall_id = rc AND politician_id = 'mcclain' AND position = 'yea';
    fixed := fixed + 1;
  ELSIF cur = 'not_voting' THEN
    already := already + 1;
  ELSE
    RAISE EXCEPTION 'Vote correction: house 119/1 roll 12 holds ''%'' for mcclain, which is neither the value this correction examined (''yea'') nor the value it would write (''not_voting''). Something changed underneath this migration; refusing to overwrite it.', cur;
  END IF;

  -- house 119/1 roll 12 · H.R. 28 · On Passage · 2025-01-14
  --   stefanik (S001196) stored 'yea' / with_party; the document says 'not_voting' / no side
  --   U.S. House roll call 2025-12 — https://clerk.house.gov/evs/2025/roll012.xml
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'house' AND congress = 119 AND session = 1
     AND roll_number = 12 LIMIT 1;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Vote correction: house 119/1 roll 12 is not in vr_rollcalls, so there is no cell to correct.';
  END IF;
  SELECT position INTO cur FROM vr_member_votes WHERE rollcall_id = rc AND politician_id = 'stefanik';
  IF cur IS NULL THEN
    RAISE EXCEPTION 'Vote correction: house 119/1 roll 12 holds no stored vote for stefanik. This migration corrects cells that exist and creates none.';
  ELSIF cur = 'yea' THEN
    UPDATE vr_member_votes
       SET position = 'not_voting', is_party = NULL
     WHERE rollcall_id = rc AND politician_id = 'stefanik' AND position = 'yea';
    fixed := fixed + 1;
  ELSIF cur = 'not_voting' THEN
    already := already + 1;
  ELSE
    RAISE EXCEPTION 'Vote correction: house 119/1 roll 12 holds ''%'' for stefanik, which is neither the value this correction examined (''yea'') nor the value it would write (''not_voting''). Something changed underneath this migration; refusing to overwrite it.', cur;
  END IF;

  -- house 119/1 roll 27 · H.R. 21 · On Passage · 2025-01-23
  --   jayapal (J000298) stored 'nay' / with_party; the document says 'not_voting' / no side
  --   U.S. House roll call 2025-27 — https://clerk.house.gov/evs/2025/roll027.xml
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'house' AND congress = 119 AND session = 1
     AND roll_number = 27 LIMIT 1;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Vote correction: house 119/1 roll 27 is not in vr_rollcalls, so there is no cell to correct.';
  END IF;
  SELECT position INTO cur FROM vr_member_votes WHERE rollcall_id = rc AND politician_id = 'jayapal';
  IF cur IS NULL THEN
    RAISE EXCEPTION 'Vote correction: house 119/1 roll 27 holds no stored vote for jayapal. This migration corrects cells that exist and creates none.';
  ELSIF cur = 'nay' THEN
    UPDATE vr_member_votes
       SET position = 'not_voting', is_party = NULL
     WHERE rollcall_id = rc AND politician_id = 'jayapal' AND position = 'nay';
    fixed := fixed + 1;
  ELSIF cur = 'not_voting' THEN
    already := already + 1;
  ELSE
    RAISE EXCEPTION 'Vote correction: house 119/1 roll 27 holds ''%'' for jayapal, which is neither the value this correction examined (''nay'') nor the value it would write (''not_voting''). Something changed underneath this migration; refusing to overwrite it.', cur;
  END IF;

  -- house 119/1 roll 35 · H.R. 26 · On Passage · 2025-02-07
  --   brendan_boyle (B001296) stored 'nay' / with_party; the document says 'not_voting' / no side
  --   U.S. House roll call 2025-35 — https://clerk.house.gov/evs/2025/roll035.xml
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'house' AND congress = 119 AND session = 1
     AND roll_number = 35 LIMIT 1;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Vote correction: house 119/1 roll 35 is not in vr_rollcalls, so there is no cell to correct.';
  END IF;
  SELECT position INTO cur FROM vr_member_votes WHERE rollcall_id = rc AND politician_id = 'brendan_boyle';
  IF cur IS NULL THEN
    RAISE EXCEPTION 'Vote correction: house 119/1 roll 35 holds no stored vote for brendan_boyle. This migration corrects cells that exist and creates none.';
  ELSIF cur = 'nay' THEN
    UPDATE vr_member_votes
       SET position = 'not_voting', is_party = NULL
     WHERE rollcall_id = rc AND politician_id = 'brendan_boyle' AND position = 'nay';
    fixed := fixed + 1;
  ELSIF cur = 'not_voting' THEN
    already := already + 1;
  ELSE
    RAISE EXCEPTION 'Vote correction: house 119/1 roll 35 holds ''%'' for brendan_boyle, which is neither the value this correction examined (''nay'') nor the value it would write (''not_voting''). Something changed underneath this migration; refusing to overwrite it.', cur;
  END IF;

  -- house 119/1 roll 35 · H.R. 26 · On Passage · 2025-02-07
  --   dan_goldman (G000599) stored 'nay' / with_party; the document says 'not_voting' / no side
  --   U.S. House roll call 2025-35 — https://clerk.house.gov/evs/2025/roll035.xml
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'house' AND congress = 119 AND session = 1
     AND roll_number = 35 LIMIT 1;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Vote correction: house 119/1 roll 35 is not in vr_rollcalls, so there is no cell to correct.';
  END IF;
  SELECT position INTO cur FROM vr_member_votes WHERE rollcall_id = rc AND politician_id = 'dan_goldman';
  IF cur IS NULL THEN
    RAISE EXCEPTION 'Vote correction: house 119/1 roll 35 holds no stored vote for dan_goldman. This migration corrects cells that exist and creates none.';
  ELSIF cur = 'nay' THEN
    UPDATE vr_member_votes
       SET position = 'not_voting', is_party = NULL
     WHERE rollcall_id = rc AND politician_id = 'dan_goldman' AND position = 'nay';
    fixed := fixed + 1;
  ELSIF cur = 'not_voting' THEN
    already := already + 1;
  ELSE
    RAISE EXCEPTION 'Vote correction: house 119/1 roll 35 holds ''%'' for dan_goldman, which is neither the value this correction examined (''nay'') nor the value it would write (''not_voting''). Something changed underneath this migration; refusing to overwrite it.', cur;
  END IF;

  -- house 119/1 roll 35 · H.R. 26 · On Passage · 2025-02-07
  --   greg_landsman (L000601) stored 'nay' / with_party; the document says 'yea' / against_party
  --   U.S. House roll call 2025-35 — https://clerk.house.gov/evs/2025/roll035.xml
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'house' AND congress = 119 AND session = 1
     AND roll_number = 35 LIMIT 1;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Vote correction: house 119/1 roll 35 is not in vr_rollcalls, so there is no cell to correct.';
  END IF;
  SELECT position INTO cur FROM vr_member_votes WHERE rollcall_id = rc AND politician_id = 'greg_landsman';
  IF cur IS NULL THEN
    RAISE EXCEPTION 'Vote correction: house 119/1 roll 35 holds no stored vote for greg_landsman. This migration corrects cells that exist and creates none.';
  ELSIF cur = 'nay' THEN
    UPDATE vr_member_votes
       SET position = 'yea', is_party = 'against_party'
     WHERE rollcall_id = rc AND politician_id = 'greg_landsman' AND position = 'nay';
    fixed := fixed + 1;
  ELSIF cur = 'yea' THEN
    already := already + 1;
  ELSE
    RAISE EXCEPTION 'Vote correction: house 119/1 roll 35 holds ''%'' for greg_landsman, which is neither the value this correction examined (''nay'') nor the value it would write (''yea''). Something changed underneath this migration; refusing to overwrite it.', cur;
  END IF;

  -- house 119/1 roll 35 · H.R. 26 · On Passage · 2025-02-07
  --   jayapal (J000298) stored 'nay' / with_party; the document says 'not_voting' / no side
  --   U.S. House roll call 2025-35 — https://clerk.house.gov/evs/2025/roll035.xml
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'house' AND congress = 119 AND session = 1
     AND roll_number = 35 LIMIT 1;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Vote correction: house 119/1 roll 35 is not in vr_rollcalls, so there is no cell to correct.';
  END IF;
  SELECT position INTO cur FROM vr_member_votes WHERE rollcall_id = rc AND politician_id = 'jayapal';
  IF cur IS NULL THEN
    RAISE EXCEPTION 'Vote correction: house 119/1 roll 35 holds no stored vote for jayapal. This migration corrects cells that exist and creates none.';
  ELSIF cur = 'nay' THEN
    UPDATE vr_member_votes
       SET position = 'not_voting', is_party = NULL
     WHERE rollcall_id = rc AND politician_id = 'jayapal' AND position = 'nay';
    fixed := fixed + 1;
  ELSIF cur = 'not_voting' THEN
    already := already + 1;
  ELSE
    RAISE EXCEPTION 'Vote correction: house 119/1 roll 35 holds ''%'' for jayapal, which is neither the value this correction examined (''nay'') nor the value it would write (''not_voting''). Something changed underneath this migration; refusing to overwrite it.', cur;
  END IF;

  -- house 119/1 roll 35 · H.R. 26 · On Passage · 2025-02-07
  --   luna (L000596) stored 'yea' / with_party; the document says 'not_voting' / no side
  --   U.S. House roll call 2025-35 — https://clerk.house.gov/evs/2025/roll035.xml
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'house' AND congress = 119 AND session = 1
     AND roll_number = 35 LIMIT 1;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Vote correction: house 119/1 roll 35 is not in vr_rollcalls, so there is no cell to correct.';
  END IF;
  SELECT position INTO cur FROM vr_member_votes WHERE rollcall_id = rc AND politician_id = 'luna';
  IF cur IS NULL THEN
    RAISE EXCEPTION 'Vote correction: house 119/1 roll 35 holds no stored vote for luna. This migration corrects cells that exist and creates none.';
  ELSIF cur = 'yea' THEN
    UPDATE vr_member_votes
       SET position = 'not_voting', is_party = NULL
     WHERE rollcall_id = rc AND politician_id = 'luna' AND position = 'yea';
    fixed := fixed + 1;
  ELSIF cur = 'not_voting' THEN
    already := already + 1;
  ELSE
    RAISE EXCEPTION 'Vote correction: house 119/1 roll 35 holds ''%'' for luna, which is neither the value this correction examined (''yea'') nor the value it would write (''not_voting''). Something changed underneath this migration; refusing to overwrite it.', cur;
  END IF;

  -- house 119/1 roll 104 · S. 146 · On Motion to Suspend the Rules and Pass · 2025-04-28
  --   jim_mcgovern (M000312) stored 'yea' / with_party; the document says 'not_voting' / no side
  --   U.S. House roll call 2025-104 — https://clerk.house.gov/evs/2025/roll104.xml
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'house' AND congress = 119 AND session = 1
     AND roll_number = 104 LIMIT 1;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Vote correction: house 119/1 roll 104 is not in vr_rollcalls, so there is no cell to correct.';
  END IF;
  SELECT position INTO cur FROM vr_member_votes WHERE rollcall_id = rc AND politician_id = 'jim_mcgovern';
  IF cur IS NULL THEN
    RAISE EXCEPTION 'Vote correction: house 119/1 roll 104 holds no stored vote for jim_mcgovern. This migration corrects cells that exist and creates none.';
  ELSIF cur = 'yea' THEN
    UPDATE vr_member_votes
       SET position = 'not_voting', is_party = NULL
     WHERE rollcall_id = rc AND politician_id = 'jim_mcgovern' AND position = 'yea';
    fixed := fixed + 1;
  ELSIF cur = 'not_voting' THEN
    already := already + 1;
  ELSE
    RAISE EXCEPTION 'Vote correction: house 119/1 roll 104 holds ''%'' for jim_mcgovern, which is neither the value this correction examined (''yea'') nor the value it would write (''not_voting''). Something changed underneath this migration; refusing to overwrite it.', cur;
  END IF;

  -- house 119/1 roll 104 · S. 146 · On Motion to Suspend the Rules and Pass · 2025-04-28
  --   josh_gottheimer (G000583) stored 'yea' / with_party; the document says 'not_voting' / no side
  --   U.S. House roll call 2025-104 — https://clerk.house.gov/evs/2025/roll104.xml
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'house' AND congress = 119 AND session = 1
     AND roll_number = 104 LIMIT 1;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Vote correction: house 119/1 roll 104 is not in vr_rollcalls, so there is no cell to correct.';
  END IF;
  SELECT position INTO cur FROM vr_member_votes WHERE rollcall_id = rc AND politician_id = 'josh_gottheimer';
  IF cur IS NULL THEN
    RAISE EXCEPTION 'Vote correction: house 119/1 roll 104 holds no stored vote for josh_gottheimer. This migration corrects cells that exist and creates none.';
  ELSIF cur = 'yea' THEN
    UPDATE vr_member_votes
       SET position = 'not_voting', is_party = NULL
     WHERE rollcall_id = rc AND politician_id = 'josh_gottheimer' AND position = 'yea';
    fixed := fixed + 1;
  ELSIF cur = 'not_voting' THEN
    already := already + 1;
  ELSE
    RAISE EXCEPTION 'Vote correction: house 119/1 roll 104 holds ''%'' for josh_gottheimer, which is neither the value this correction examined (''yea'') nor the value it would write (''not_voting''). Something changed underneath this migration; refusing to overwrite it.', cur;
  END IF;

  -- house 119/1 roll 151 · H.R. 2483 · On Passage · 2025-06-04
  --   clyburn (C000537) stored 'yea' / with_party; the document says 'nay' / against_party
  --   U.S. House roll call 2025-151 — https://clerk.house.gov/evs/2025/roll151.xml
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'house' AND congress = 119 AND session = 1
     AND roll_number = 151 LIMIT 1;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Vote correction: house 119/1 roll 151 is not in vr_rollcalls, so there is no cell to correct.';
  END IF;
  SELECT position INTO cur FROM vr_member_votes WHERE rollcall_id = rc AND politician_id = 'clyburn';
  IF cur IS NULL THEN
    RAISE EXCEPTION 'Vote correction: house 119/1 roll 151 holds no stored vote for clyburn. This migration corrects cells that exist and creates none.';
  ELSIF cur = 'yea' THEN
    UPDATE vr_member_votes
       SET position = 'nay', is_party = 'against_party'
     WHERE rollcall_id = rc AND politician_id = 'clyburn' AND position = 'yea';
    fixed := fixed + 1;
  ELSIF cur = 'nay' THEN
    already := already + 1;
  ELSE
    RAISE EXCEPTION 'Vote correction: house 119/1 roll 151 holds ''%'' for clyburn, which is neither the value this correction examined (''yea'') nor the value it would write (''nay''). Something changed underneath this migration; refusing to overwrite it.', cur;
  END IF;

  -- house 119/1 roll 151 · H.R. 2483 · On Passage · 2025-06-04
  --   diana_degette (D000197) stored 'yea' / with_party; the document says 'nay' / against_party
  --   U.S. House roll call 2025-151 — https://clerk.house.gov/evs/2025/roll151.xml
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'house' AND congress = 119 AND session = 1
     AND roll_number = 151 LIMIT 1;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Vote correction: house 119/1 roll 151 is not in vr_rollcalls, so there is no cell to correct.';
  END IF;
  SELECT position INTO cur FROM vr_member_votes WHERE rollcall_id = rc AND politician_id = 'diana_degette';
  IF cur IS NULL THEN
    RAISE EXCEPTION 'Vote correction: house 119/1 roll 151 holds no stored vote for diana_degette. This migration corrects cells that exist and creates none.';
  ELSIF cur = 'yea' THEN
    UPDATE vr_member_votes
       SET position = 'nay', is_party = 'against_party'
     WHERE rollcall_id = rc AND politician_id = 'diana_degette' AND position = 'yea';
    fixed := fixed + 1;
  ELSIF cur = 'nay' THEN
    already := already + 1;
  ELSE
    RAISE EXCEPTION 'Vote correction: house 119/1 roll 151 holds ''%'' for diana_degette, which is neither the value this correction examined (''yea'') nor the value it would write (''nay''). Something changed underneath this migration; refusing to overwrite it.', cur;
  END IF;

  -- house 119/1 roll 151 · H.R. 2483 · On Passage · 2025-06-04
  --   jan_schakowsky (S001145) stored 'yea' / with_party; the document says 'nay' / against_party
  --   U.S. House roll call 2025-151 — https://clerk.house.gov/evs/2025/roll151.xml
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'house' AND congress = 119 AND session = 1
     AND roll_number = 151 LIMIT 1;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Vote correction: house 119/1 roll 151 is not in vr_rollcalls, so there is no cell to correct.';
  END IF;
  SELECT position INTO cur FROM vr_member_votes WHERE rollcall_id = rc AND politician_id = 'jan_schakowsky';
  IF cur IS NULL THEN
    RAISE EXCEPTION 'Vote correction: house 119/1 roll 151 holds no stored vote for jan_schakowsky. This migration corrects cells that exist and creates none.';
  ELSIF cur = 'yea' THEN
    UPDATE vr_member_votes
       SET position = 'nay', is_party = 'against_party'
     WHERE rollcall_id = rc AND politician_id = 'jan_schakowsky' AND position = 'yea';
    fixed := fixed + 1;
  ELSIF cur = 'nay' THEN
    already := already + 1;
  ELSE
    RAISE EXCEPTION 'Vote correction: house 119/1 roll 151 holds ''%'' for jan_schakowsky, which is neither the value this correction examined (''yea'') nor the value it would write (''nay''). Something changed underneath this migration; refusing to overwrite it.', cur;
  END IF;

  -- house 119/1 roll 151 · H.R. 2483 · On Passage · 2025-06-04
  --   josh_gottheimer (G000583) stored 'yea' / with_party; the document says 'not_voting' / no side
  --   U.S. House roll call 2025-151 — https://clerk.house.gov/evs/2025/roll151.xml
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'house' AND congress = 119 AND session = 1
     AND roll_number = 151 LIMIT 1;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Vote correction: house 119/1 roll 151 is not in vr_rollcalls, so there is no cell to correct.';
  END IF;
  SELECT position INTO cur FROM vr_member_votes WHERE rollcall_id = rc AND politician_id = 'josh_gottheimer';
  IF cur IS NULL THEN
    RAISE EXCEPTION 'Vote correction: house 119/1 roll 151 holds no stored vote for josh_gottheimer. This migration corrects cells that exist and creates none.';
  ELSIF cur = 'yea' THEN
    UPDATE vr_member_votes
       SET position = 'not_voting', is_party = NULL
     WHERE rollcall_id = rc AND politician_id = 'josh_gottheimer' AND position = 'yea';
    fixed := fixed + 1;
  ELSIF cur = 'not_voting' THEN
    already := already + 1;
  ELSE
    RAISE EXCEPTION 'Vote correction: house 119/1 roll 151 holds ''%'' for josh_gottheimer, which is neither the value this correction examined (''yea'') nor the value it would write (''not_voting''). Something changed underneath this migration; refusing to overwrite it.', cur;
  END IF;

  -- house 119/1 roll 151 · H.R. 2483 · On Passage · 2025-06-04
  --   rick_larsen (L000560) stored 'yea' / with_party; the document says 'not_voting' / no side
  --   U.S. House roll call 2025-151 — https://clerk.house.gov/evs/2025/roll151.xml
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'house' AND congress = 119 AND session = 1
     AND roll_number = 151 LIMIT 1;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Vote correction: house 119/1 roll 151 is not in vr_rollcalls, so there is no cell to correct.';
  END IF;
  SELECT position INTO cur FROM vr_member_votes WHERE rollcall_id = rc AND politician_id = 'rick_larsen';
  IF cur IS NULL THEN
    RAISE EXCEPTION 'Vote correction: house 119/1 roll 151 holds no stored vote for rick_larsen. This migration corrects cells that exist and creates none.';
  ELSIF cur = 'yea' THEN
    UPDATE vr_member_votes
       SET position = 'not_voting', is_party = NULL
     WHERE rollcall_id = rc AND politician_id = 'rick_larsen' AND position = 'yea';
    fixed := fixed + 1;
  ELSIF cur = 'not_voting' THEN
    already := already + 1;
  ELSE
    RAISE EXCEPTION 'Vote correction: house 119/1 roll 151 holds ''%'' for rick_larsen, which is neither the value this correction examined (''yea'') nor the value it would write (''not_voting''). Something changed underneath this migration; refusing to overwrite it.', cur;
  END IF;

  -- house 119/1 roll 201 · H.R. 1919 · On Passage · 2025-07-17
  --   massie (M001184) stored 'yea' / with_party; the document says 'not_voting' / no side
  --   U.S. House roll call 2025-201 — https://clerk.house.gov/evs/2025/roll201.xml
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'house' AND congress = 119 AND session = 1
     AND roll_number = 201 LIMIT 1;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Vote correction: house 119/1 roll 201 is not in vr_rollcalls, so there is no cell to correct.';
  END IF;
  SELECT position INTO cur FROM vr_member_votes WHERE rollcall_id = rc AND politician_id = 'massie';
  IF cur IS NULL THEN
    RAISE EXCEPTION 'Vote correction: house 119/1 roll 201 holds no stored vote for massie. This migration corrects cells that exist and creates none.';
  ELSIF cur = 'yea' THEN
    UPDATE vr_member_votes
       SET position = 'not_voting', is_party = NULL
     WHERE rollcall_id = rc AND politician_id = 'massie' AND position = 'yea';
    fixed := fixed + 1;
  ELSIF cur = 'not_voting' THEN
    already := already + 1;
  ELSE
    RAISE EXCEPTION 'Vote correction: house 119/1 roll 201 holds ''%'' for massie, which is neither the value this correction examined (''yea'') nor the value it would write (''not_voting''). Something changed underneath this migration; refusing to overwrite it.', cur;
  END IF;

  -- senate 119/1 roll 160 · S.J.Res. 37 · On Passage of the Joint Resolution · 2025-04-02
  --   roger_marshall (M001198) stored 'nay' / with_party; the document says 'not_voting' / no side
  --   U.S. Senate roll call 119-1-160 — https://www.senate.gov/legislative/LIS/roll_call_votes/vote1191/vote_119_1_00160.xml
  SELECT id INTO rc FROM vr_rollcalls
   WHERE chamber = 'senate' AND congress = 119 AND session = 1
     AND roll_number = 160 LIMIT 1;
  IF rc IS NULL THEN
    RAISE EXCEPTION 'Vote correction: senate 119/1 roll 160 is not in vr_rollcalls, so there is no cell to correct.';
  END IF;
  SELECT position INTO cur FROM vr_member_votes WHERE rollcall_id = rc AND politician_id = 'roger_marshall';
  IF cur IS NULL THEN
    RAISE EXCEPTION 'Vote correction: senate 119/1 roll 160 holds no stored vote for roger_marshall. This migration corrects cells that exist and creates none.';
  ELSIF cur = 'nay' THEN
    UPDATE vr_member_votes
       SET position = 'not_voting', is_party = NULL
     WHERE rollcall_id = rc AND politician_id = 'roger_marshall' AND position = 'nay';
    fixed := fixed + 1;
  ELSIF cur = 'not_voting' THEN
    already := already + 1;
  ELSE
    RAISE EXCEPTION 'Vote correction: senate 119/1 roll 160 holds ''%'' for roger_marshall, which is neither the value this correction examined (''nay'') nor the value it would write (''not_voting''). Something changed underneath this migration; refusing to overwrite it.', cur;
  END IF;

  RAISE NOTICE 'Vote corrections: % cell(s) corrected, % already correct (of 18 enumerated).', fixed, already;
END $$;
