-- ---------------------------------------------------------------------------
-- Federal wave F11 — first acts on empty poled keys
-- ---------------------------------------------------------------------------
-- Generated by scripts/vr-gen-federal-wave-f11-migration.mjs from
-- db/vr-federal-wave-f11-vote-seed.json and db/vr-federal-mapping-seed-f11.json.
-- Do not hand-edit: regenerate, or roll forward with a new migration.
--
-- 0 measures created · 1 roll call created · 1 issue mapping created · 2 issue mappings RETRACTED · 0 new issue keys
-- 430 member votes attributed across 1 House roll call · 430 distinct roster slugs · 0 unresolved
-- 1 measure status corrected (display only) · 0 stated positions written · 0 weights changed · 0 existing cells rewritten
-- 0 poles added · 0 *_balance keys touched · 0 floors moved
-- Keys filled: rural_ag (House) · housing_support (both chambers)
-- Keys emptied: property_rights (federal instrument count 1 → 0, disclosed below and in the seed)
--
-- STAMP PROVENANCE
-- 20261028000000 is F10's RESERVED STAMP, consumed here. F10 shipped no migration
-- because it admitted nothing, and recorded that stamp as reserved-and-unconsumed.
-- The directory tail was 20261027000000_vr_instrument_lever_summaries_w1.sql, so
-- this file is still last in the tree and no applied migration is touched.
--
-- WHAT THIS WAVE IS
-- Coverage, not a flag flip. F10 proved the chamber-gap and PRIMARY-promote hunt is
-- closed: reachable unread from a new PRIMARY on an existing mapped key is zero,
-- because _rdLeanAllowed() already returns true on any key holding a floor act and a
-- promote changes a label and no tier, read, direction or floor. What is left is keys
-- with no ACT at all. 93 of the vocabulary's keys are poled; 28 are suppressed as
-- poleless or *_balance by _rdSuppressedKey() and are not candidates for anything,
-- which is doctrine and not a hole to patch. 22 poled keys held no federal act in
-- either chamber. This migration fills two of them and the seed refuses the other 20
-- in writing, each with the measured reason.
--
-- THE ONE ACT
--   H.R. 7567   house 119/2/154   224-200   On Passage   rural_ag
--   The 2026 farm bill's own passage roll. Not a special rule, not a suspension, not a
--   motion to recommit, not a continuing resolution, not a rider on somebody else's
--   vehicle. Wave F9 curated this bill — five mapping rows including a w100 PRIMARY on
--   rural_ag — and had no roll to hang them on, because the House had not voted yet.
--   F11 is the wave that supplies the vote.
--
-- THE NAME IS NOT THE INSTRUMENT, IN BOTH DIRECTIONS (runbook rule 43)
--   F10 wrote rule 43 to catch bills whose titles promise more than their text
--   delivers, and refused four: weatherization that weatherized nothing, SWAPs that
--   turned out to be State Wildlife Action Plans, SPACE that turned out to be shared
--   federal office space, a screening mandate that was a permissive sunset pilot.
--   Those four stay refused. F11 found the inverse on the same print. A keyword scan
--   of all 657 House and 453 Senate legislative rolls of the 119th returned ZERO
--   candidates for housing_support, because H.R. 6644's short title is '21st Century
--   ROAD to Housing Act' and its long title is 'To increase the supply of housing in
--   America'. Neither says affordable, renter, tenant, voucher or rental assistance.
--   The enrolled text says all of them: Title I plus Sec. 204 (affordable-housing
--   construction as an eligible CDBG activity), Sec. 212 (Rental Assistance
--   Demonstration made permanent, cap 455,000 → 555,000, mandatory tenant lease
--   addendum), Sec. 405 (section 8(o)(8) voucher inspection), Sec. 501 (HOME
--   reauthorization, eligibility to 100% AMI) and Sec. 503 (McKinney-Vento waiver
--   authority). A title scan can refuse a key that has an act. The same print is
--   refused for housing_first_time in the seed, on three permissive pilots and an
--   evaluation — one print, one rule, two opposite answers, both from the text.
--
-- WHY ONE ACT IS ENOUGH, AND WHY NO SECOND COUSIN WAS SOUGHT
--   stance-helpers.js:1529 — _rdLeanAllowed() returns true whenever floorActs > 0, so
--   with judged === 1 and a floor act the 'single_weak_act' reason at :1231 is never
--   set and the row resolves as record_thin rather than staying empty. F10 measured
--   n=1 identical to n=2 across all 78 in-play Senate keys and all 77 House keys.
--   'Would fill the pattern' is not a reason and is not offered as one anywhere here.
--
-- A ROLL IS NOT FREE — WHY TWO MAPPINGS ARE DELETED
--   Landing an act makes EVERY live mapping row on that measure readable, not just
--   the row the wave argued for. F9 wrote five rows on H.R. 7567:
--     rural_ag        w100 PRIMARY yea_supports  → ARRIVES. This is the admit.
--     family_support  w70  yea_supports          → ARRIVES as a side effect. Reviewed
--       and left alone under rule 21 (the live rationale is the first writer's): its
--       basis is Title IV NUTRITION, which IS in the passed print, and the key is not
--       empty anyway — it already holds H.R. 1, H.R. 2483 and H.R. 1319 with acts.
--       Disclosed, not claimed: this wave takes no coverage credit for it.
--     enviro_balance  w60  yea_supports          → STAYS UNREAD. Matches /_balance$/,
--       so _rdSuppressedKey() returns 'balance_key' and suppression precedes every
--       wall, weight, lane and chamber check. The row exists, the act now exists, the
--       key publishes nothing. Doctrine working.
--     econ_corp_account w45 yea_opposes          → RETRACTED below.
--     property_rights   w40 yea_opposes          → RETRACTED below.
--   The last two read SEC. 10205, SEC. 10206 and SEC. 10207 — and their own
--   rationales say so, in the past conditional: 'would have shielded', 'both were
--   struck'. Section-by-section diff of the two House prints: BILLS-119hr7567rh runs
--   SEC. 10201 · 10202 · 10203 · 10204 · 10205 · 10206 · 10207 · 10211;
--   BILLS-119hr7567eh — the print the House passed on roll 154 — runs SEC. 10201 ·
--   10202 · 10203 · 10204 · 10211. The striking vote is H.Amdt. 196, House 119/2/148,
--   adopted 280-142, which F9 ingested separately and recorded in its own migration
--   header. While the parent had no roll these two rows were inert and read to nobody.
--   The moment this migration lands its roll, they would attribute to all
--   424 members who cast a side a position on a pesticide liability shield and a
--   state-label preemption that the text they passed does not contain. So they go.
--
-- WHAT THE RETRACTIONS COST, MEASURED
--   econ_corp_account: 0 reads lost. The key keeps ten rows, four federal, three of
--     those with acts (H.R. 6955 w60 ×2 rolls, H.R. 5376 w60 ×2, S.J.Res. 18 w75
--     PRIMARY ×2). It does not go empty and does not lose its PRIMARY.
--   property_rights: 0 reads lost and this one is NOT free. H.R. 7567 is the key's
--     ONLY federal mapping row; the other seven are Utah state bills. After the
--     DELETE the key holds no federal instrument at all, so the count of poled keys
--     with no federal instrument anywhere goes 20 → 21. Its Utah PRIMARY (H.B. 289
--     w55) and four Utah rolls are untouched, so no state legislator loses a read.
--     The trade is stated rather than buried: F11 makes one federal coverage number
--     worse in order not to publish 424 attributions the text cannot support. A key
--     that reads empty is honest; a key that reads a struck section is not.
--
-- CENSUS, BEFORE AND AFTER
--   poled vocabulary keys: 93 · suppressed and excluded up front: 28
--   no federal ACT anywhere:        22 → 20   (rural_ag and housing_support leave)
--   no federal ACT in the House:     2 →  2   (back_police, immigration_reform)
--   no federal ACT in the Senate:   38 → 37   (housing_support leaves; rural_ag stays,
--     because roll 154 is a House roll and no senator reads it)
--   no federal INSTRUMENT anywhere: 20 → 20   (housing_support out, property_rights in —
--     the count is unchanged and the membership is not, which is why both are named)
--   members newly thin-readable: 424 on rural_ag (House) · 96 House + 99 Senate = 195
--     on housing_support · 95 gain both · 524 distinct members gain at least one.
--     Measured against ATTRIBUTED rolls, not chamber headcounts: House roll 224 on
--     H.R. 6644 carries 108 attributed members, not 435, so 96 is the honest figure.
--   The 6 Not Voting on roll 154 gain nothing, which is correct. Present and Not
--   Voting are carried as their own positions with is_party NULL and are never read
--   as a direction.
--
-- WHAT --reach COULD AND COULD NOT MEASURE
--   The census the brief asked for was run twice, once without this wave and once
--   with it, and the two outputs are byte-identical except the two header lines
--   naming the wave list. Not one figure moves. That is the flag's construction and
--   not a defect: the --reach branch of scripts/vr-federal-fpi.mjs reads `winB` and
--   `before` — the database as it stands — and never `after`, where a wave's
--   projected rows live; and it counts UNREAD ROWS, rows that exist and are
--   suppressed, whereas this wave creates READS. rural_ag and housing_support print
--   unread 0 with a ceiling of a whole chamber both before and after. So the
--   movement above was measured with --json gainedReads/lostReads, which is a real
--   before/after pair over one engine, and --reach is quoted only for what it can
--   honestly say: the attribution ceiling holds at chamber headcount on every key in
--   both chambers (102 senators, max attributed 102; 435 members, max attributed
--   435), and every key with unread volume and a ceiling of zero — 10 in the Senate,
--   11 in the House — is one of the poleless or *_balance keys. Nothing with a
--   curated pole is unreachable. That is doctrine holding, not coverage missing.
--
-- THE 37 SENATE GAPS ARE UNCHANGED, NOT UNEXAMINED
--   Closing a Senate gap needs a SENATE ACT on a measure carrying the key — a
--   different instrument, not a different flag. F10 closed that hunt at zero and F11
--   did not reopen it. The one Senate gap this wave does close, housing_support,
--   closes because H.R. 6644 carried a Senate passage roll all along (119/2/53, 89-10,
--   'On Passage of the Bill') and nobody had written the mapping row that reads it.
--
-- NO SCORE MOVES
--   No pole added. No *_balance pole proposed. No new issue key: both admits land on
--   keys the vocabulary already carries with a curated directional chip, and the
--   brief's second condition — two instruments would use it this wave — could not be
--   met by a wave that admits two instruments in total. _RD_MIN_JUDGED, _RD_THIN_MIN,
--   _RD_THIN_MIN_STRENGTH, _RD_MIN_PRIMARY, the split floors and the member floor
--   literal are byte-identical. Nothing judicial is touched: THE WALL holds.
--   The status correction on H.R. 7567 is display only — every reader of
--   'passed_house' was located first (bill-detail.js:63 and :832,
--   all-seeing-eye.js:1945, digital-library.js:729/:739/:758/:926/:953,
--   bills-index.js) and all of them are labels or progress indicators. Nothing in
--   stance-helpers.js reads measure status, so no tier, weight, direction, floor or
--   Mandate figure moves.
--
-- pack-generation: derived — one row added and two removed, so mappingVersion() in
-- netlify/lib/vr-pack.ts moves on its own: both the row count and the md5 over the
-- ordered (measure_id, issue_key, weight, is_primary, support_meaning, rationale)
-- tuples change. The pack key member:<pid>@m<count>-<hash> therefore bumps for every
-- member and the six-hour PACK_TTL_MS cannot serve a pre-F11 blob past this deploy.
-- Mapping version start: m941-11954c943297 (941 rows, max id 12044).
-- Mapping version end:   m940-da41abc2f46d (940 rows = 941 - 2 + 1).
-- The end value is COMPUTED, not left unstated. mappingVersion() orders by id and the
-- new row lands last, so the digest depends on the exact rationale text inserted below
-- and not on which id the sequence hands out. Simulated against the live table with
-- the two retracted rows excluded and the new row appended. Edit a comma in that
-- rationale and scripts/test-vr-federal-wave-f11.mjs fires, which is the point.
--
-- MEASURED BEFORE THE DEPLOY, by the FPI projection over f1,f2,f3,f4,f10,f11:
--   rows that STOPPED being characterised: 0. The retractions cost zero existing
--     reads — the claim both retraction notes make, now measured rather than argued.
--   rows that STARTED being characterised: 936 · members whose shape moved: 530
--   tier weakening (readable→not, or fewer clear issues): 0 · split rows gained: 0
--   member empty/thin/readable: 0/6/653 before, 0/6/653 after, delta 0/0/0.
--   530 is the footprint; 524 is the coverage. The 6-member difference is
--   family_support arriving on members who had no other act on it — counted by the
--   FPI and deliberately not claimed here, because family_support was never empty.
-- ---------------------------------------------------------------------------

DO $$
DECLARE
  m_hr7567       bigint;
  m_hr6644       bigint;
  rc             bigint;
  n_votes        integer;
  n_sides        integer;
  n_noside       integer;
  n_retracted    integer;
  n_added        integer;
  v_status       text;
  v_primary      boolean;
  v_weight       integer;
  v_meaning      text;
BEGIN
  -- ══════════════════════════════════════════════════════════════════════════
  -- BOTH MEASURES MUST ALREADY EXIST. This wave creates nothing: H.R. 7567 was
  -- created by F9 and H.R. 6644 by an earlier wave. If either is missing then the
  -- corpus is not the corpus this seed was written against, and guessing an id
  -- would attach 430 votes to the wrong bill.
  -- ══════════════════════════════════════════════════════════════════════════
  SELECT id INTO m_hr7567 FROM vr_measures
   WHERE measure_type = 'bill' AND congress = 119 AND chamber = 'house' AND number = 'H.R. 7567' LIMIT 1;
  IF m_hr7567 IS NULL THEN
    RAISE EXCEPTION 'Federal wave F11: H.R. 7567 is not in vr_measures, so House roll 154 has nothing to attach to.';
  END IF;

  SELECT id INTO m_hr6644 FROM vr_measures
   WHERE measure_type = 'bill' AND congress = 119 AND chamber = 'house' AND number = 'H.R. 6644' LIMIT 1;
  IF m_hr6644 IS NULL THEN
    RAISE EXCEPTION 'Federal wave F11: H.R. 6644 is not in vr_measures, so its housing_support row cannot be written.';
  END IF;

  -- ══════════════════════════════════════════════════════════════════════════
  -- THE ACT. The full-chamber tally comes out of the clerk's own <totals-by-vote>
  -- block, not off a display page: 224 yea, 200 nay, 0 present, 6 not voting,
  -- 430 members recorded of 435 seats. All 430 resolve to a roster slug through
  -- db/vr-member-map.json in exactly one hop and 0 are unresolved, so nothing is
  -- skipped and nothing is guessed. The per-party figures below were recomputed from
  -- the recorded votes and cross-checked against the clerk's own <totals-by-party>
  -- block by the vote-seed generator, which throws on any disagreement.
  -- ══════════════════════════════════════════════════════════════════════════
  INSERT INTO vr_rollcalls (measure_id, chamber, congress, session, roll_number, vote_date, question, action_type, result, required_majority, totals, source_url, source_label)
  VALUES (m_hr7567, 'house', 119, 2, 154, TIMESTAMPTZ '2026-04-30T11:14:00-04:00', 'On Passage', 'passage', 'passed', 'simple',
    '{"yea":224,"nay":200,"present":0,"notVoting":6,"byParty":{"D":{"yea":14,"nay":197},"R":{"yea":209,"nay":3},"I":{"yea":1,"nay":0}}}'::jsonb,
    'https://clerk.house.gov/Votes/2026154', 'Office of the Clerk, U.S. House of Representatives')
  ON CONFLICT (chamber, congress, session, roll_number) DO NOTHING;
  SELECT id INTO rc FROM vr_rollcalls WHERE chamber = 'house' AND congress = 119 AND session = 2 AND roll_number = 154 LIMIT 1;
  IF rc IS NULL THEN RAISE EXCEPTION 'Federal wave F11: house 119/2 roll 154 could not be read back after insert.'; END IF;

  INSERT INTO vr_member_votes (rollcall_id, politician_id, position, is_party) VALUES
    (rc, 'aaron_bean', 'yea', 'with_party'),
    (rc, 'abraham_hamadeh', 'yea', 'with_party'),
    (rc, 'adam_gray', 'yea', 'against_party'),
    (rc, 'adam_smith', 'nay', 'with_party'),
    (rc, 'addison_mcdowell', 'yea', 'with_party'),
    (rc, 'adelita_grijalva', 'nay', 'with_party'),
    (rc, 'adrian_smith', 'yea', 'with_party'),
    (rc, 'adriano_espaillat', 'nay', 'with_party'),
    (rc, 'aguilar', 'nay', 'with_party'),
    (rc, 'al_green', 'nay', 'with_party'),
    (rc, 'alma_adams', 'nay', 'with_party'),
    (rc, 'ami_bera', 'nay', 'with_party'),
    (rc, 'analilia_mejia', 'nay', 'with_party'),
    (rc, 'andre_carson', 'nay', 'with_party'),
    (rc, 'andrea_salinas', 'nay', 'with_party'),
    (rc, 'andrew_clyde', 'yea', 'with_party'),
    (rc, 'andrew_ogles', 'yea', 'with_party'),
    (rc, 'andy_barr', 'yea', 'with_party'),
    (rc, 'andy_biggs', 'not_voting', NULL),
    (rc, 'andy_harris', 'yea', 'with_party'),
    (rc, 'angie_craig', 'nay', 'with_party'),
    (rc, 'ann_wagner', 'yea', 'with_party'),
    (rc, 'aoc', 'nay', 'with_party'),
    (rc, 'april_mcclain_delaney', 'nay', 'with_party'),
    (rc, 'arrington', 'yea', 'with_party'),
    (rc, 'ashley_hinson', 'yea', 'with_party'),
    (rc, 'austin_scott', 'yea', 'with_party'),
    (rc, 'ayanna_pressley', 'nay', 'with_party'),
    (rc, 'barry_loudermilk', 'not_voting', NULL),
    (rc, 'barry_moore', 'yea', 'with_party'),
    (rc, 'becca_balint', 'nay', 'with_party'),
    (rc, 'ben_cline', 'yea', 'with_party'),
    (rc, 'bennie_thompson', 'nay', 'with_party'),
    (rc, 'beth_van_duyne', 'yea', 'with_party'),
    (rc, 'betty_mccollum', 'nay', 'with_party'),
    (rc, 'bill_foster', 'nay', 'with_party'),
    (rc, 'bill_huizenga', 'yea', 'with_party'),
    (rc, 'bmoore', 'yea', 'with_party'),
    (rc, 'bobby_scott', 'nay', 'with_party'),
    (rc, 'boebert', 'yea', 'with_party'),
    (rc, 'bonnie_watson_coleman', 'nay', 'with_party'),
    (rc, 'brad_finstad', 'yea', 'with_party'),
    (rc, 'brad_knott', 'yea', 'with_party'),
    (rc, 'brad_schneider', 'nay', 'with_party'),
    (rc, 'brad_sherman', 'nay', 'with_party'),
    (rc, 'brandon_gill', 'yea', 'with_party'),
    (rc, 'brendan_boyle', 'nay', 'with_party'),
    (rc, 'brian_babin', 'yea', 'with_party'),
    (rc, 'brian_jack', 'yea', 'with_party'),
    (rc, 'brian_mast', 'yea', 'with_party'),
    (rc, 'brittany_pettersen', 'nay', 'with_party'),
    (rc, 'bruce_westerman', 'yea', 'with_party'),
    (rc, 'bryan_steil', 'yea', 'with_party'),
    (rc, 'buddy_carter', 'yea', 'with_party'),
    (rc, 'c_franklin', 'yea', 'with_party'),
    (rc, 'carlos_gimenez', 'yea', 'with_party'),
    (rc, 'carol_miller', 'yea', 'with_party'),
    (rc, 'casar', 'nay', 'with_party'),
    (rc, 'charles_chuck_edwards', 'yea', 'with_party'),
    (rc, 'chellie_pingree', 'nay', 'with_party'),
    (rc, 'chip_roy', 'yea', 'with_party'),
    (rc, 'chris_deluzio', 'nay', 'with_party'),
    (rc, 'chris_pappas', 'nay', 'with_party'),
    (rc, 'chris_smith', 'yea', 'with_party'),
    (rc, 'chrissy_houlahan', 'nay', 'with_party'),
    (rc, 'christian_menefee', 'nay', 'with_party'),
    (rc, 'chuck_fleischmann', 'yea', 'with_party'),
    (rc, 'chuy_garcia', 'nay', 'with_party'),
    (rc, 'claudia_tenney', 'yea', 'with_party'),
    (rc, 'clay_fuller', 'yea', 'with_party'),
    (rc, 'clay_higgins', 'yea', 'with_party'),
    (rc, 'cleo_fields', 'nay', 'with_party'),
    (rc, 'cliff_bentz', 'yea', 'with_party'),
    (rc, 'clyburn', 'nay', 'with_party'),
    (rc, 'comer', 'yea', 'with_party'),
    (rc, 'cory_mills', 'yea', 'with_party'),
    (rc, 'craig_goldman', 'yea', 'with_party'),
    (rc, 'crockett', 'nay', 'with_party'),
    (rc, 'dale_strong', 'yea', 'with_party'),
    (rc, 'dan_crenshaw', 'yea', 'with_party'),
    (rc, 'dan_goldman', 'nay', 'with_party'),
    (rc, 'dan_newhouse', 'yea', 'with_party'),
    (rc, 'daniel_meuser', 'yea', 'with_party'),
    (rc, 'daniel_webster', 'yea', 'with_party'),
    (rc, 'danny_davis', 'nay', 'with_party'),
    (rc, 'darin_lahood', 'yea', 'with_party'),
    (rc, 'darrell_issa', 'yea', 'with_party'),
    (rc, 'darren_soto', 'yea', 'against_party'),
    (rc, 'dave_min', 'nay', 'with_party'),
    (rc, 'david_joyce', 'yea', 'with_party'),
    (rc, 'david_kustoff', 'yea', 'with_party'),
    (rc, 'david_rouzer', 'yea', 'with_party'),
    (rc, 'david_schweikert', 'yea', 'with_party'),
    (rc, 'david_taylor', 'yea', 'with_party'),
    (rc, 'david_valadao', 'yea', 'with_party'),
    (rc, 'debbie_dingell', 'nay', 'with_party'),
    (rc, 'debbie_wasserman_schultz', 'nay', 'with_party'),
    (rc, 'deborah_ross', 'nay', 'with_party'),
    (rc, 'delauro', 'nay', 'with_party'),
    (rc, 'delbene', 'nay', 'with_party'),
    (rc, 'delia_ramirez', 'nay', 'with_party'),
    (rc, 'derek_schmidt', 'yea', 'with_party'),
    (rc, 'derek_tran', 'nay', 'with_party'),
    (rc, 'derrick_van_orden', 'yea', 'with_party'),
    (rc, 'diana_degette', 'nay', 'with_party'),
    (rc, 'diana_harshbarger', 'yea', 'with_party'),
    (rc, 'dina_titus', 'nay', 'with_party'),
    (rc, 'don_bacon', 'yea', 'with_party'),
    (rc, 'don_davis', 'yea', 'against_party'),
    (rc, 'donald_beyer', 'nay', 'with_party'),
    (rc, 'donald_norcross', 'nay', 'with_party'),
    (rc, 'donalds', 'yea', 'with_party'),
    (rc, 'doris_matsui', 'nay', 'with_party'),
    (rc, 'dusty_johnson', 'yea', 'with_party'),
    (rc, 'dwight_evans', 'nay', 'with_party'),
    (rc, 'ed_case', 'nay', 'with_party'),
    (rc, 'eli_crane', 'yea', 'with_party'),
    (rc, 'emanuel_cleaver', 'nay', 'with_party'),
    (rc, 'emilia_sykes', 'nay', 'with_party'),
    (rc, 'emily_randall', 'nay', 'with_party'),
    (rc, 'emmer', 'yea', 'with_party'),
    (rc, 'eric_burlison', 'not_voting', NULL),
    (rc, 'eric_sorensen', 'nay', 'with_party'),
    (rc, 'erin_houchin', 'yea', 'with_party'),
    (rc, 'eugene_vindman', 'nay', 'with_party'),
    (rc, 'fitzpatrick', 'nay', 'against_party'),
    (rc, 'foxx', 'yea', 'with_party'),
    (rc, 'frank_lucas', 'yea', 'with_party'),
    (rc, 'frank_mrvan', 'nay', 'with_party'),
    (rc, 'frederica_wilson', 'not_voting', NULL),
    (rc, 'french_hill', 'yea', 'with_party'),
    (rc, 'gabe_amo', 'nay', 'with_party'),
    (rc, 'gabe_evans', 'yea', 'with_party'),
    (rc, 'gabe_vasquez', 'yea', 'against_party'),
    (rc, 'garbarino', 'nay', 'against_party'),
    (rc, 'gary_palmer', 'yea', 'with_party'),
    (rc, 'george_latimer', 'nay', 'with_party'),
    (rc, 'george_whitesides', 'nay', 'with_party'),
    (rc, 'gilbert_cisneros', 'nay', 'with_party'),
    (rc, 'glenn_grothman', 'yea', 'with_party'),
    (rc, 'glenn_ivey', 'nay', 'with_party'),
    (rc, 'glenn_thompson', 'yea', 'with_party'),
    (rc, 'grace_meng', 'nay', 'with_party'),
    (rc, 'greg_landsman', 'nay', 'with_party'),
    (rc, 'greg_stanton', 'nay', 'with_party'),
    (rc, 'gregory_murphy', 'yea', 'with_party'),
    (rc, 'gus_bilirakis', 'yea', 'with_party'),
    (rc, 'guthrie', 'yea', 'with_party'),
    (rc, 'guy_reschenthaler', 'yea', 'with_party'),
    (rc, 'gwen_moore', 'nay', 'with_party'),
    (rc, 'h_griffith', 'yea', 'with_party'),
    (rc, 'hal_rogers', 'yea', 'with_party'),
    (rc, 'haley_stevens', 'nay', 'with_party'),
    (rc, 'hank_johnson', 'nay', 'with_party'),
    (rc, 'harriet_hageman', 'nay', 'against_party'),
    (rc, 'henry_cuellar', 'yea', 'against_party'),
    (rc, 'herbert_conaway', 'nay', 'with_party'),
    (rc, 'hillary_scholten', 'nay', 'with_party'),
    (rc, 'hudson', 'yea', 'with_party'),
    (rc, 'j_correa', 'nay', 'with_party'),
    (rc, 'jack_bergman', 'yea', 'with_party'),
    (rc, 'jahana_hayes', 'nay', 'with_party'),
    (rc, 'jake_auchincloss', 'nay', 'with_party'),
    (rc, 'jake_ellzey', 'yea', 'with_party'),
    (rc, 'james_baird', 'yea', 'with_party'),
    (rc, 'james_walkinshaw', 'nay', 'with_party'),
    (rc, 'jan_schakowsky', 'nay', 'with_party'),
    (rc, 'janelle_bynum', 'nay', 'with_party'),
    (rc, 'jared_golden', 'nay', 'with_party'),
    (rc, 'jared_huffman', 'nay', 'with_party'),
    (rc, 'jared_moskowitz', 'nay', 'with_party'),
    (rc, 'jason_crow', 'nay', 'with_party'),
    (rc, 'jason_smith', 'not_voting', NULL),
    (rc, 'jay_obernolte', 'yea', 'with_party'),
    (rc, 'jayapal', 'nay', 'with_party'),
    (rc, 'jeff_crank', 'yea', 'with_party'),
    (rc, 'jeff_hurd', 'yea', 'with_party'),
    (rc, 'jefferson_shreve', 'yea', 'with_party'),
    (rc, 'jefferson_van_drew', 'yea', 'with_party'),
    (rc, 'jeffries', 'nay', 'with_party'),
    (rc, 'jennifer_kiggans', 'yea', 'with_party'),
    (rc, 'jennifer_mcclellan', 'nay', 'with_party'),
    (rc, 'jill_tokuda', 'nay', 'with_party'),
    (rc, 'jim_costa', 'yea', 'against_party'),
    (rc, 'jim_himes', 'nay', 'with_party'),
    (rc, 'jim_jordan', 'yea', 'with_party'),
    (rc, 'jim_mcgovern', 'nay', 'with_party'),
    (rc, 'jimmy_gomez', 'nay', 'with_party'),
    (rc, 'jimmy_panetta', 'nay', 'with_party'),
    (rc, 'jimmy_patronis', 'yea', 'with_party'),
    (rc, 'joaquin_castro', 'nay', 'with_party'),
    (rc, 'joe_courtney', 'nay', 'with_party'),
    (rc, 'joe_wilson', 'yea', 'with_party'),
    (rc, 'john_carter', 'yea', 'with_party'),
    (rc, 'john_garamendi', 'nay', 'with_party'),
    (rc, 'john_james', 'yea', 'with_party'),
    (rc, 'john_joyce', 'yea', 'with_party'),
    (rc, 'john_larson', 'nay', 'with_party'),
    (rc, 'john_mannion', 'nay', 'with_party'),
    (rc, 'john_mcguire', 'yea', 'with_party'),
    (rc, 'john_moolenaar', 'yea', 'with_party'),
    (rc, 'john_rose', 'yea', 'with_party'),
    (rc, 'john_rutherford', 'yea', 'with_party'),
    (rc, 'johnny_olszewski', 'nay', 'with_party'),
    (rc, 'jonathan_jackson', 'nay', 'with_party'),
    (rc, 'joseph_morelle', 'nay', 'with_party'),
    (rc, 'josh_brecheen', 'yea', 'with_party'),
    (rc, 'josh_gottheimer', 'nay', 'with_party'),
    (rc, 'josh_harder', 'nay', 'with_party'),
    (rc, 'josh_riley', 'yea', 'against_party'),
    (rc, 'joyce_beatty', 'nay', 'with_party'),
    (rc, 'juan_ciscomani', 'yea', 'with_party'),
    (rc, 'juan_vargas', 'nay', 'with_party'),
    (rc, 'judy_chu', 'nay', 'with_party'),
    (rc, 'julia_brownley', 'nay', 'with_party'),
    (rc, 'julia_letlow', 'yea', 'with_party'),
    (rc, 'julie_fedorchak', 'yea', 'with_party'),
    (rc, 'julie_johnson', 'nay', 'with_party'),
    (rc, 'kat_cammack', 'yea', 'with_party'),
    (rc, 'kathy_castor', 'nay', 'with_party'),
    (rc, 'kclark', 'nay', 'with_party'),
    (rc, 'keith_self', 'yea', 'with_party'),
    (rc, 'kelly_morrison', 'nay', 'with_party'),
    (rc, 'ken_calvert', 'yea', 'with_party'),
    (rc, 'kennedy', 'yea', 'with_party'),
    (rc, 'kevin_hern', 'yea', 'with_party'),
    (rc, 'kevin_kiley', 'yea', 'with_party'),
    (rc, 'kevin_mullin', 'nay', 'with_party'),
    (rc, 'khanna', 'nay', 'with_party'),
    (rc, 'kim_schrier', 'yea', 'against_party'),
    (rc, 'kristen_mcdonald_rivet', 'yea', 'against_party'),
    (rc, 'kweisi_mfume', 'nay', 'with_party'),
    (rc, 'lamonica_mciver', 'nay', 'with_party'),
    (rc, 'lance_gooden', 'yea', 'with_party'),
    (rc, 'lateefah_simon', 'nay', 'with_party'),
    (rc, 'laura_friedman', 'nay', 'with_party'),
    (rc, 'laura_gillen', 'nay', 'with_party'),
    (rc, 'laurel_lee', 'yea', 'with_party'),
    (rc, 'lauren_underwood', 'nay', 'with_party'),
    (rc, 'linda_sanchez', 'nay', 'with_party'),
    (rc, 'lizzie_fletcher', 'nay', 'with_party'),
    (rc, 'lloyd_doggett', 'nay', 'with_party'),
    (rc, 'lloyd_smucker', 'yea', 'with_party'),
    (rc, 'lois_frankel', 'nay', 'with_party'),
    (rc, 'lori_trahan', 'nay', 'with_party'),
    (rc, 'lucy_mcbath', 'nay', 'with_party'),
    (rc, 'luna', 'yea', 'with_party'),
    (rc, 'luz_rivas', 'nay', 'with_party'),
    (rc, 'madeleine_dean', 'nay', 'with_party'),
    (rc, 'maggie_goodlander', 'nay', 'with_party'),
    (rc, 'maloy', 'yea', 'with_party'),
    (rc, 'marc_veasey', 'nay', 'with_party'),
    (rc, 'marcy_kaptur', 'yea', 'against_party'),
    (rc, 'maria_salazar', 'yea', 'with_party'),
    (rc, 'mariannette_miller_meeks', 'yea', 'with_party'),
    (rc, 'marie_gluesenkamp_perez', 'yea', 'against_party'),
    (rc, 'marilyn_strickland', 'nay', 'with_party'),
    (rc, 'mario_diaz_balart', 'yea', 'with_party'),
    (rc, 'mark_alford', 'yea', 'with_party'),
    (rc, 'mark_amodei', 'yea', 'with_party'),
    (rc, 'mark_desaulnier', 'nay', 'with_party'),
    (rc, 'mark_harris', 'yea', 'with_party'),
    (rc, 'mark_messmer', 'yea', 'with_party'),
    (rc, 'mark_pocan', 'nay', 'with_party'),
    (rc, 'marlin_stutzman', 'yea', 'with_party'),
    (rc, 'mary_miller', 'yea', 'with_party'),
    (rc, 'mary_scanlon', 'nay', 'with_party'),
    (rc, 'massie', 'yea', 'with_party'),
    (rc, 'matt_van_epps', 'yea', 'with_party'),
    (rc, 'max_miller', 'yea', 'with_party'),
    (rc, 'maxine_dexter', 'nay', 'with_party'),
    (rc, 'maxine_waters', 'nay', 'with_party'),
    (rc, 'maxwell_frost', 'nay', 'with_party'),
    (rc, 'mcclain', 'yea', 'with_party'),
    (rc, 'meeks', 'nay', 'with_party'),
    (rc, 'melanie_stansbury', 'nay', 'with_party'),
    (rc, 'michael_baumgartner', 'yea', 'with_party'),
    (rc, 'michael_cloud', 'yea', 'with_party'),
    (rc, 'michael_guest', 'yea', 'with_party'),
    (rc, 'michael_mccaul', 'yea', 'with_party'),
    (rc, 'michael_rulli', 'yea', 'with_party'),
    (rc, 'michael_turner', 'yea', 'with_party'),
    (rc, 'michelle_fischbach', 'yea', 'with_party'),
    (rc, 'mike_bost', 'yea', 'with_party'),
    (rc, 'mike_carey', 'yea', 'with_party'),
    (rc, 'mike_collins', 'yea', 'with_party'),
    (rc, 'mike_ezell', 'yea', 'with_party'),
    (rc, 'mike_flood', 'yea', 'with_party'),
    (rc, 'mike_haridopolos', 'yea', 'with_party'),
    (rc, 'mike_johnson', 'yea', 'with_party'),
    (rc, 'mike_kelly', 'yea', 'with_party'),
    (rc, 'mike_lawler', 'yea', 'with_party'),
    (rc, 'mike_levin', 'nay', 'with_party'),
    (rc, 'mike_quigley', 'nay', 'with_party'),
    (rc, 'mike_rogers_al', 'yea', 'with_party'),
    (rc, 'mike_simpson', 'yea', 'with_party'),
    (rc, 'mike_thompson', 'nay', 'with_party'),
    (rc, 'monica_de_la_cruz', 'yea', 'with_party'),
    (rc, 'morgan_luttrell', 'yea', 'with_party'),
    (rc, 'morgan_mcgarvey', 'nay', 'with_party'),
    (rc, 'nadler', 'nay', 'with_party'),
    (rc, 'nancy_mace', 'yea', 'with_party'),
    (rc, 'nancy_pelosi', 'nay', 'with_party'),
    (rc, 'nanette_barragan', 'nay', 'with_party'),
    (rc, 'nathaniel_moran', 'yea', 'with_party'),
    (rc, 'neal', 'nay', 'with_party'),
    (rc, 'neal_dunn', 'yea', 'with_party'),
    (rc, 'neguse', 'nay', 'with_party'),
    (rc, 'nellie_pou', 'nay', 'with_party'),
    (rc, 'nicholas_begich', 'yea', 'with_party'),
    (rc, 'nicholas_langworthy', 'yea', 'with_party'),
    (rc, 'nicolas_lalota', 'yea', 'with_party'),
    (rc, 'nicole_malliotakis', 'yea', 'with_party'),
    (rc, 'nicole_nikki_budzinski', 'nay', 'with_party'),
    (rc, 'nikema_williams', 'nay', 'with_party'),
    (rc, 'norma_torres', 'nay', 'with_party'),
    (rc, 'nydia_velazquez', 'nay', 'with_party'),
    (rc, 'omar', 'nay', 'with_party'),
    (rc, 'owens', 'yea', 'with_party'),
    (rc, 'pallone', 'nay', 'with_party'),
    (rc, 'pat_fallon', 'yea', 'with_party'),
    (rc, 'pat_harrigan', 'yea', 'with_party'),
    (rc, 'patrick_ryan', 'nay', 'with_party'),
    (rc, 'paul_gosar', 'yea', 'with_party'),
    (rc, 'paul_tonko', 'nay', 'with_party'),
    (rc, 'pete_sessions', 'yea', 'with_party'),
    (rc, 'pete_stauber', 'yea', 'with_party'),
    (rc, 'pfluger', 'yea', 'with_party'),
    (rc, 'raja_krishnamoorthi', 'nay', 'with_party'),
    (rc, 'ralph_norman', 'yea', 'with_party'),
    (rc, 'randy_feenstra', 'yea', 'with_party'),
    (rc, 'randy_weber', 'yea', 'with_party'),
    (rc, 'raskin', 'nay', 'with_party'),
    (rc, 'raul_ruiz', 'nay', 'with_party'),
    (rc, 'rfine', 'yea', 'with_party'),
    (rc, 'rich_mccormick', 'yea', 'with_party'),
    (rc, 'rick_allen', 'yea', 'with_party'),
    (rc, 'rick_crawford', 'yea', 'with_party'),
    (rc, 'rick_larsen', 'nay', 'with_party'),
    (rc, 'riley_moore', 'yea', 'with_party'),
    (rc, 'rob_bresnahan', 'yea', 'with_party'),
    (rc, 'robert_aderholt', 'yea', 'with_party'),
    (rc, 'robert_garcia', 'nay', 'with_party'),
    (rc, 'robert_latta', 'yea', 'with_party'),
    (rc, 'robert_menendez', 'nay', 'with_party'),
    (rc, 'robert_onder', 'yea', 'with_party'),
    (rc, 'robert_wittman', 'yea', 'with_party'),
    (rc, 'robin_kelly', 'nay', 'with_party'),
    (rc, 'roger_williams', 'yea', 'with_party'),
    (rc, 'ron_estes', 'yea', 'with_party'),
    (rc, 'ronny_jackson', 'yea', 'with_party'),
    (rc, 'rudy_yakym', 'yea', 'with_party'),
    (rc, 'russ_fulcher', 'yea', 'with_party'),
    (rc, 'russell_fry', 'yea', 'with_party'),
    (rc, 'ryan_mackenzie', 'yea', 'with_party'),
    (rc, 'ryan_zinke', 'yea', 'with_party'),
    (rc, 'salud_carbajal', 'nay', 'with_party'),
    (rc, 'sam_graves', 'yea', 'with_party'),
    (rc, 'sam_liccardo', 'nay', 'with_party'),
    (rc, 'sanford_bishop', 'yea', 'against_party'),
    (rc, 'sara_jacobs', 'nay', 'with_party'),
    (rc, 'sarah_elfreth', 'nay', 'with_party'),
    (rc, 'sarah_mcbride', 'nay', 'with_party'),
    (rc, 'scalise', 'yea', 'with_party'),
    (rc, 'scott_desjarlais', 'yea', 'with_party'),
    (rc, 'scott_fitzgerald', 'yea', 'with_party'),
    (rc, 'scott_perry', 'yea', 'with_party'),
    (rc, 'scott_peters', 'nay', 'with_party'),
    (rc, 'sean_casten', 'nay', 'with_party'),
    (rc, 'seth_magaziner', 'nay', 'with_party'),
    (rc, 'seth_moulton', 'nay', 'with_party'),
    (rc, 'sharice_davids', 'yea', 'against_party'),
    (rc, 'sheri_biggs', 'yea', 'with_party'),
    (rc, 'shomari_figures', 'nay', 'with_party'),
    (rc, 'shontel_brown', 'nay', 'with_party'),
    (rc, 'shri_thanedar', 'nay', 'with_party'),
    (rc, 'stefanik', 'yea', 'with_party'),
    (rc, 'steny_hoyer', 'nay', 'with_party'),
    (rc, 'stephanie_bice', 'yea', 'with_party'),
    (rc, 'stephen_lynch', 'nay', 'with_party'),
    (rc, 'steve_cohen', 'nay', 'with_party'),
    (rc, 'steve_womack', 'yea', 'with_party'),
    (rc, 'steven_horsford', 'nay', 'with_party'),
    (rc, 'suhas_subramanyam', 'nay', 'with_party'),
    (rc, 'summer_lee', 'nay', 'with_party'),
    (rc, 'susie_lee', 'nay', 'with_party'),
    (rc, 'suzanne_bonamici', 'nay', 'with_party'),
    (rc, 'sydney_kamlager_dove', 'nay', 'with_party'),
    (rc, 'sylvia_garcia', 'nay', 'with_party'),
    (rc, 'takano', 'nay', 'with_party'),
    (rc, 'ted_lieu', 'nay', 'with_party'),
    (rc, 'teresa_leger_fernandez', 'nay', 'with_party'),
    (rc, 'terri_sewell', 'nay', 'with_party'),
    (rc, 'thomas_kean', 'not_voting', NULL),
    (rc, 'thomas_tiffany', 'yea', 'with_party'),
    (rc, 'tim_burchett', 'yea', 'with_party'),
    (rc, 'tim_moore', 'yea', 'with_party'),
    (rc, 'timothy_kennedy', 'nay', 'with_party'),
    (rc, 'tlaib', 'nay', 'with_party'),
    (rc, 'tom_barrett', 'yea', 'with_party'),
    (rc, 'tom_cole', 'yea', 'with_party'),
    (rc, 'tom_mcclintock', 'yea', 'with_party'),
    (rc, 'tom_suozzi', 'nay', 'with_party'),
    (rc, 'tony_wied', 'yea', 'with_party'),
    (rc, 'torres', 'nay', 'with_party'),
    (rc, 'tracey_mann', 'yea', 'with_party'),
    (rc, 'trent_kelly', 'yea', 'with_party'),
    (rc, 'troy_balderson', 'yea', 'with_party'),
    (rc, 'troy_carter', 'nay', 'with_party'),
    (rc, 'troy_downing', 'yea', 'with_party'),
    (rc, 'troy_nehls', 'yea', 'with_party'),
    (rc, 'valerie_foushee', 'nay', 'with_party'),
    (rc, 'valerie_hoyle', 'nay', 'with_party'),
    (rc, 'vern_buchanan', 'yea', 'with_party'),
    (rc, 'veronica_escobar', 'nay', 'with_party'),
    (rc, 'vicente_gonzalez', 'yea', 'against_party'),
    (rc, 'victoria_spartz', 'yea', 'with_party'),
    (rc, 'vince_fong', 'yea', 'with_party'),
    (rc, 'w_steube', 'yea', 'with_party'),
    (rc, 'walberg', 'yea', 'with_party'),
    (rc, 'warren_davidson', 'yea', 'with_party'),
    (rc, 'wesley_bell', 'nay', 'with_party'),
    (rc, 'wesley_hunt', 'yea', 'with_party'),
    (rc, 'william_keating', 'nay', 'with_party'),
    (rc, 'william_timmons', 'yea', 'with_party'),
    (rc, 'yassamin_ansari', 'nay', 'with_party'),
    (rc, 'young_kim', 'yea', 'with_party'),
    (rc, 'yvette_clarke', 'nay', 'with_party'),
    (rc, 'zach_nunn', 'yea', 'with_party'),
    (rc, 'zoe_lofgren', 'nay', 'with_party')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;

  -- ══════════════════════════════════════════════════════════════════════════
  -- THE MAPPING. H.R. 6644 → housing_support w65 secondary yea_supports.
  -- No roll is written for this measure: both of its passage-form acts are already on
  -- file (house 119/2/224 rollcall 179, 108 attributed of whom 96 cast a side; senate
  -- 119/2/53 rollcall 2574, 100 attributed of whom 99 cast a side). One row, two acts,
  -- a key that had none, and both chambers filled at once.
  --
  -- WHY 65 AND SECONDARY. The pole is a conjunction — 'Fund affordable housing and
  -- protect renters with assistance and limits on evictions' — and the text satisfies
  -- its first half only. 'eviction' appears exactly twice in a 442 KB print: once as
  -- an eligible use of manufactured-housing community grant funds and once as a
  -- reporting metric. Neither is an operative limit. So the row is weighted for the
  -- assistance the text does contain and discounted for the half it does not, and 65
  -- sits deliberately between this measure's own permitting_reform w60 and housing
  -- w80. Runbook rule 25 asks why two similar instruments get different weights: the
  -- answer is recorded here rather than left to be inferred.
  --
  -- NOT RESTUFFING. The measure's existing rows are housing_build w100 PRIMARY,
  -- housing w80 PRIMARY, permitting_reform w60 and crypto_cbdc w40 — the supply,
  -- zoning and NEPA lane. housing_support is the subsidy-and-renter lane, kept
  -- separate by the vocabulary on purpose so a user can hold one without the other.
  -- Sec. 204, Sec. 212, Sec. 405, Sec. 501 and Sec. 503 are not the sections that
  -- earn housing_build its w100; they amend CDBG eligibility, the Rental Assistance
  -- Demonstration, section 8(o)(8) voucher inspection, HOME and McKinney-Vento.
  -- ══════════════════════════════════════════════════════════════════════════
  INSERT INTO vr_measure_issues (measure_id, issue_key, weight, is_primary, support_meaning, rationale)
  VALUES (m_hr6644, 'housing_support', 65, false, 'yea_supports',
    'Title I and five operative sections of the enrolled text are affordable-housing and renter assistance rather than supply: Sec. 204 adds new construction of affordable housing as an eligible CDBG activity (42 U.S.C. 5305(a)); Sec. 212 makes the Rental Assistance Demonstration permanent and raises its cap from 455,000 to 555,000 units with a mandatory tenant lease addendum; Sec. 405 amends section 8(o)(8) so LIHTC-financed units satisfy Housing Choice Voucher inspection, the operative barrier to landlord participation; Sec. 501 reauthorizes HOME and raises its income ceiling to 100 percent of area median; Sec. 503 gives McKinney-Vento recipients waiver authority over the expenditure limit. Weighted secondary at 65 rather than higher because the pole also asks for limits on evictions and the text has none — ''eviction'' appears twice in the whole print, once as an eligible use of grant funds and once as a reporting metric. The measure''s supply and zoning provisions are already read at housing_build w100 and housing w80; these sections are not those sections.')
  ON CONFLICT (measure_id, issue_key) DO NOTHING;

  -- ══════════════════════════════════════════════════════════════════════════
  -- RETRACTION — H.R. 7567 econ_corp_account w45 secondary yea_opposes.
  -- The row's own rationale says the provision is not in the text, and the
  -- row's polarity says a yea opposes corporate accountability. Both cannot be
  -- true of the same vote. F9 wrote this as a note about what the bill WOULD
  -- have done, which was harmless while the measure had no roll call: with
  -- zero acts on the measure the row was inert and read to nobody. F11 lands
  -- the passage roll. The moment it lands, this row attributes to all 424
  -- members who cast a side on roll 154 a position on a pesticide liability
  -- shield that the text they passed does not contain.
  --
  -- econ_corp_account keeps ten mapping rows after the DELETE, four of them
  -- federal and three of those carrying acts: H.R. 6955 (w60, 2 rolls), H.R.
  -- 5376 (w60, 2 rolls) and S.J.Res. 18 (w75 PRIMARY, 2 rolls). The key does
  -- not go empty, does not lose its PRIMARY and does not lose an act. What it
  -- loses is a row that has never been read by anyone and, left in place,
  -- would be read wrongly by 424 people.
  --
  -- Matched on measure_id AND issue_key AND weight AND is_primary AND
  -- support_meaning AND the exact rationale string. A row that has drifted since
  -- this seed was written is therefore NOT removed — the DELETE matches nothing and
  -- the verification block at the end raises, which is the correct outcome: a
  -- retraction argues about one specific row and must not silently take a different
  -- one (runbook rule 32).
  -- ══════════════════════════════════════════════════════════════════════════
  DELETE FROM vr_measure_issues
   WHERE measure_id = m_hr7567 AND issue_key = 'econ_corp_account'
     AND weight = 45 AND is_primary = false AND support_meaning = 'yea_opposes'
     AND rationale = 'The bill''s Sec. 10205 would have shielded pesticide makers from failure-to-warn suits; a bipartisan amendment struck it, so the enacted text does not include the shield.';

  -- ══════════════════════════════════════════════════════════════════════════
  -- RETRACTION — H.R. 7567 property_rights w40 secondary yea_opposes.
  -- The same defect, named in the row's own words: 'would have', 'both were
  -- struck'. The two sections this row reads are SEC. 10206 and SEC. 10207,
  -- and the passed print does not contain either. Landing roll 154 would tell
  -- 424 members they took a position on state label authority and local
  -- pesticide preemption in a bill whose text is silent on both.
  --
  -- This one is NOT free, and the seed says so rather than burying it. H.R.
  -- 7567 is property_rights' only federal mapping row; the other seven are
  -- Utah state bills. After the DELETE property_rights holds no federal
  -- instrument at all, so it moves out of the 37 poled keys that have a House
  -- instrument and no Senate one and into the group that has neither — the
  -- count of poled keys with no federal instrument anywhere goes 20 -> 21. Its
  -- Utah PRIMARY (H.B. 289, w55) and its four Utah rolls are untouched, so no
  -- state legislator loses a read. The trade is stated plainly: F11 makes one
  -- federal coverage number worse in order not to publish 424 attributions the
  -- text cannot support. A key that reads empty is honest; a key that reads a
  -- struck section is not.
  --
  -- Matched on measure_id AND issue_key AND weight AND is_primary AND
  -- support_meaning AND the exact rationale string. A row that has drifted since
  -- this seed was written is therefore NOT removed — the DELETE matches nothing and
  -- the verification block at the end raises, which is the correct outcome: a
  -- retraction argues about one specific row and must not silently take a different
  -- one (runbook rule 32).
  -- ══════════════════════════════════════════════════════════════════════════
  DELETE FROM vr_measure_issues
   WHERE measure_id = m_hr7567 AND issue_key = 'property_rights'
     AND weight = 40 AND is_primary = false AND support_meaning = 'yea_opposes'
     AND rationale = 'Secs. 10206–10207 would have limited state label authority and preempted local pesticide rules; both were struck by the same bipartisan amendment.';

  -- ══════════════════════════════════════════════════════════════════════════
  -- DISPLAY CORRECTION — H.R. 7567 status introduced → passed_house.
  -- The corpus row says 'introduced' because F9 curated the bill before the
  -- House voted. Roll 154 passed it 224-200. Leaving the status at
  -- 'introduced' next to a passage roll would publish a contradiction on the
  -- bill's own detail page.
  --
  -- Every reader of 'passed_house' was located before the UPDATE was written,
  -- because a status string that feeds a score is a different object from one
  -- that feeds a label. All of them are labels or progress indicators:
  -- bill-detail.js:63 and :832, all-seeing-eye.js:1945,
  -- digital-library.js:729, :739, :758, :926, :953, and bills-index.js.
  -- Nothing in stance-helpers.js reads measure status, so no tier, weight,
  -- direction, floor or Mandate figure moves. This is a display correction and
  -- is reported as one.
  -- Guarded on the from-value: if the status is not 'introduced' then somebody else
  -- has already moved it and this migration has no business overwriting them.
  -- ══════════════════════════════════════════════════════════════════════════
  UPDATE vr_measures SET status = 'passed_house', updated_at = now()
   WHERE id = m_hr7567 AND status = 'introduced';

  -- ══════════════════════════════════════════════════════════════════════════
  -- VERIFICATION. Everything this migration claims, asserted against what is on
  -- file. A wave whose whole argument is 'the text does not say that' has to be able
  -- to prove its own DELETEs landed, or it has published the thing it refused.
  -- ══════════════════════════════════════════════════════════════════════════
  SELECT count(*) INTO n_votes FROM vr_member_votes WHERE rollcall_id = rc;
  IF n_votes <> 430 THEN
    RAISE EXCEPTION 'Federal wave F11: roll 154 carries % member votes, expected 430.', n_votes;
  END IF;

  SELECT count(*) INTO n_sides FROM vr_member_votes WHERE rollcall_id = rc AND position IN ('yea','nay');
  IF n_sides <> 424 THEN
    RAISE EXCEPTION 'Federal wave F11: roll 154 carries % attributed sides, expected 424.', n_sides;
  END IF;
  IF n_sides > 435 THEN
    RAISE EXCEPTION 'Federal wave F11: % attributed sides exceeds the House headcount of 435.', n_sides;
  END IF;

  -- Present and Not Voting must never carry a direction.
  SELECT count(*) INTO n_noside FROM vr_member_votes
   WHERE rollcall_id = rc AND position IN ('present','not_voting') AND is_party IS NOT NULL;
  IF n_noside <> 0 THEN
    RAISE EXCEPTION 'Federal wave F11: % no-side votes carry an is_party value; Present and Not Voting are never a direction.', n_noside;
  END IF;

  SELECT count(*) INTO n_retracted FROM vr_measure_issues WHERE measure_id = m_hr7567 AND issue_key = 'econ_corp_account';
  IF n_retracted <> 0 THEN
    RAISE EXCEPTION 'Federal wave F11: H.R. 7567 still carries % econ_corp_account row(s) after the retraction. The DELETE did not match — the row on file has drifted from the seed and must be re-argued, not force-removed.', n_retracted;
  END IF;

  SELECT count(*) INTO n_retracted FROM vr_measure_issues WHERE measure_id = m_hr7567 AND issue_key = 'property_rights';
  IF n_retracted <> 0 THEN
    RAISE EXCEPTION 'Federal wave F11: H.R. 7567 still carries % property_rights row(s) after the retraction. The DELETE did not match — the row on file has drifted from the seed and must be re-argued, not force-removed.', n_retracted;
  END IF;

  SELECT count(*) INTO n_added FROM vr_measure_issues WHERE measure_id = m_hr6644 AND issue_key = 'housing_support';
  IF n_added <> 1 THEN
    RAISE EXCEPTION 'Federal wave F11: H.R. 6644 carries % housing_support row(s), expected exactly 1.', n_added;
  END IF;
  SELECT weight, is_primary, support_meaning INTO v_weight, v_primary, v_meaning
    FROM vr_measure_issues WHERE measure_id = m_hr6644 AND issue_key = 'housing_support';
  IF v_weight <> 65 OR v_primary <> false OR v_meaning <> 'yea_supports' THEN
    RAISE EXCEPTION 'Federal wave F11: H.R. 6644 housing_support landed as w% primary=% %, expected w65 primary=false yea_supports.', v_weight, v_primary, v_meaning;
  END IF;

  -- The admit's own key must still hold its PRIMARY and its polarity: the retractions
  -- took two rows off this measure and must not have taken a third.
  SELECT count(*) INTO n_added FROM vr_measure_issues
   WHERE measure_id = m_hr7567 AND issue_key = 'rural_ag' AND is_primary = true AND weight = 100 AND support_meaning = 'yea_supports';
  IF n_added <> 1 THEN
    RAISE EXCEPTION 'Federal wave F11: H.R. 7567 no longer carries its rural_ag w100 PRIMARY yea_supports row — the act this wave lands would have nothing to read.';
  END IF;

  -- The *_balance row stays on file and stays unread. Its presence is checked because
  -- doctrine is only doctrine if it is still there to be suppressed.
  SELECT count(*) INTO n_added FROM vr_measure_issues WHERE measure_id = m_hr7567 AND issue_key = 'enviro_balance';
  IF n_added <> 1 THEN
    RAISE EXCEPTION 'Federal wave F11: H.R. 7567 enviro_balance row is missing; this wave does not touch *_balance keys.';
  END IF;

  SELECT status INTO v_status FROM vr_measures WHERE id = m_hr7567;
  IF v_status <> 'passed_house' THEN
    RAISE EXCEPTION 'Federal wave F11: H.R. 7567 status is %, expected passed_house after a passed passage roll.', v_status;
  END IF;

  RAISE NOTICE 'Federal wave F11: 1 roll call, % member votes (% sides), 1 mapping added, 2 retracted, 1 status corrected. rural_ag and housing_support now hold federal acts.', n_votes, n_sides;
END $$;
