-- ─────────────────────────────────────────────────────────────────────────────
-- vr_measures / vr_measure_issues / vr_positions — Utah 2024GS committee-only measures
-- ─────────────────────────────────────────────────────────────────────────────
-- WHAT THIS ADDS. 12 Utah bills whose committee rows changed after the earlier
-- 2024GS migration shipped, restated in full: 12 reviewed issue mappings and
-- 124 committee positions across 16 standing-committee actions, of which whatever
-- the database already holds is a no-op. Every one of these bills was already in the
-- committee ingest's refusal bucket for 2024GS: a CONTESTED pass-out-favorably vote,
-- confirmed against the published minutes PDF, with every voting name resolved through
-- the reviewed printed-name map — refused only because nobody had reviewed an issue
-- mapping for the parent bill. Wave 4 read the enrolled text and reviewed them.
--
-- WHERE THE MAPPINGS CAME FROM. db/vr-utah-committee-bills-2024GS.json, one entry per
-- bill, each carrying a direction, a weight, exactly one primary key and prose saying
-- what in the text supports it. 77 of the 141 bills in the bucket are REFUSED in the
-- same file, in writing. No issue key was added to the vocabulary for this pass.
--
-- NO FLOOR VOTES. These measures carry no vr_rollcalls row. A bill reaches this file
-- precisely because it has no admitted floor roll for 2024GS — its floor votes were
-- near-unanimous under the shipped 10%-minority bar, or it never reached a floor vote,
-- or it died in the second chamber. No floor action code was widened and no margin bar
-- was lowered to manufacture one. The consequence is stated rather than hidden:
-- 124 of the 124 positions are the member's ONLY act on that bill and all of them
-- count, because there is no floor vote on these measures for stance-helpers to
-- supersede them with (0 are superseded).
--
-- ACTION TYPE AND WEIGHT ARE UNCHANGED. 'committee_vote' at 0.60 in stance-helpers'
-- act table, printing as "Committee vote", exactly as 20261004000000 wrote it. This
-- file changes no weight, no label, no floor and no threshold.
--
-- THE TIME OF DAY IS NOT KNOWN. The minutes state the meeting's date and do not
-- timestamp the motion, so acted_at is that date at midnight Mountain Standard Time.
--
-- SOURCES. Every measure cites its bill page; every position cites the minutes PDF the
-- act was confirmed against. Each measure's external_ids records which document the
-- mapping was read out of — enrolled text, or the last substitute where the bill never
-- enrolled — so a reader can check the mapping against the same file the curator used.
--
-- THIS IS A DELTA, NOT THE WHOLE SEED. The 2024GS committee mapping already shipped
-- in an earlier migration and that file is applied, so it is not edited. This one
-- carries only the 12 bill(s) whose rows changed afterwards:
--   HB0028 · H.B. 28
--   HB0111 · H.B. 111
--   HB0137 · H.B. 137
--   HB0186 · H.B. 186
--   HB0267 · H.B. 267
--   HB0284 · H.B. 284
--   HB0335 · H.B. 335
--   HB0429 · H.B. 429
--   HB0460 · H.B. 460
--   HB0463 · H.B. 463
--   HB0465 · H.B. 465
--   HB0534 · H.B. 534
-- Each block below is the same generated block as before, unmodified: it selects the
-- measure before inserting, guards every issue mapping with NOT EXISTS, and ends every
-- position insert with ON CONFLICT DO NOTHING. Re-stating a bill that is already in
-- the database is a no-op; only rows that are genuinely new land.
-- Generated by scripts/vr-utah-committee-mapping.mjs --sql --session 2024GS --bills HB0028,HB0111,HB0137,HB0186,HB0267,HB0284,HB0335,HB0429,HB0460,HB0463,HB0465,HB0534. Idempotent.
-- ─────────────────────────────────────────────────────────────────────────────

-- HB0028 · H.B. 28 · Emergency Responder Voting Amendments
--   mapping read from the introduced text: https://le.utah.gov/~2024/bills/hbillint/HB0028.htm
--   1 issue mapping(s), 1 committee action(s), 8 position(s)
DO $$
DECLARE m_id integer;
BEGIN
  SELECT id INTO m_id FROM vr_measures
   WHERE number = 'H.B. 28' AND chamber = 'utah house'
     AND external_ids->>'utahSession' = '2024GS' LIMIT 1;
  IF m_id IS NULL THEN
    INSERT INTO vr_measures (measure_type, congress, chamber, number, title,
      short_title, summary, status, source_url, source_label, external_ids)
    VALUES ('bill', NULL, 'utah house', 'H.B. 28', 'Emergency Responder Voting Amendments',
      'Emergency Responder Voting Amendments', 'This bill addresses voting procedures for emergency responders.', 'introduced',
      'https://le.utah.gov/~2024/bills/static/HB0028.html', 'Utah State Legislature',
      jsonb_build_object('utahSession', '2024GS', 'utahBill', 'HB0028',
        'primeSponsor', 'LESSER', 'floorSponsor', NULL,
        'mappingReadFrom', 'introduced', 'mappingTextUrl', 'https://le.utah.gov/~2024/bills/hbillint/HB0028.htm',
        'committeeOnly', true))
    RETURNING id INTO m_id;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM vr_measure_issues
                  WHERE measure_id = m_id AND issue_key = 'voting_access') THEN
    INSERT INTO vr_measure_issues (measure_id, issue_key, weight, is_primary,
      support_meaning, rationale, source_url)
    VALUES (m_id, 'voting_access', 45, true,
      'yea_supports', 'Introduced text lets a registered voter who is assisting with an emergency on election day outside the voter''s county of residence cast an electronic ballot after filing a declaration of eligibility, and requires the lieutenant governor to report annually. It adds a way for one class of voter to cast a ballot they would otherwise lose, which is a narrow but real access gain.', 'https://le.utah.gov/~2024/bills/hbillint/HB0028.htm');
  END IF;
  -- 2024-01-19 · House Government Operations Standing Committee · Rep. Dailey-Provost moved to pass H.B. 28 out favorably.
  --   printed tally 7-4-2 (yea-nay-absent); 8 named voter(s) on the PolitiDex roster
  INSERT INTO vr_positions (measure_id, politician_id, action_type, supports, acted_at, source_url, note) VALUES
    (m_id, 'andrew_stoddard', 'committee_vote', true, '2024-01-19T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00000428.pdf', 'House Government Operations Standing Committee · meeting 19018 · Rep. Dailey-Provost moved to pass H.B. 28 out favorably.'),
    (m_id, 'brammer_s21', 'committee_vote', false, '2024-01-19T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00000428.pdf', 'House Government Operations Standing Committee · meeting 19018 · Rep. Dailey-Provost moved to pass H.B. 28 out favorably.'),
    (m_id, 'candice_pierucci', 'committee_vote', false, '2024-01-19T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00000428.pdf', 'House Government Operations Standing Committee · meeting 19018 · Rep. Dailey-Provost moved to pass H.B. 28 out favorably.'),
    (m_id, 'cmusselman', 'committee_vote', true, '2024-01-19T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00000428.pdf', 'House Government Operations Standing Committee · meeting 19018 · Rep. Dailey-Provost moved to pass H.B. 28 out favorably.'),
    (m_id, 'cory_maloy_h52', 'committee_vote', true, '2024-01-19T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00000428.pdf', 'House Government Operations Standing Committee · meeting 19018 · Rep. Dailey-Provost moved to pass H.B. 28 out favorably.'),
    (m_id, 'mike_petersen', 'committee_vote', false, '2024-01-19T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00000428.pdf', 'House Government Operations Standing Committee · meeting 19018 · Rep. Dailey-Provost moved to pass H.B. 28 out favorably.'),
    (m_id, 'nthurston', 'committee_vote', true, '2024-01-19T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00000428.pdf', 'House Government Operations Standing Committee · meeting 19018 · Rep. Dailey-Provost moved to pass H.B. 28 out favorably.'),
    (m_id, 'sahara_hayes', 'committee_vote', true, '2024-01-19T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00000428.pdf', 'House Government Operations Standing Committee · meeting 19018 · Rep. Dailey-Provost moved to pass H.B. 28 out favorably.')
  ON CONFLICT (measure_id, politician_id, action_type) DO NOTHING;
END $$;

-- HB0111 · H.B. 111 · Employment Training Requirement Limitations
--   mapping read from the introduced text: https://le.utah.gov/~2024/bills/hbillint/HB0111.htm
--   1 issue mapping(s), 2 committee action(s), 15 position(s)
DO $$
DECLARE m_id integer;
BEGIN
  SELECT id INTO m_id FROM vr_measures
   WHERE number = 'H.B. 111' AND chamber = 'utah house'
     AND external_ids->>'utahSession' = '2024GS' LIMIT 1;
  IF m_id IS NULL THEN
    INSERT INTO vr_measures (measure_type, congress, chamber, number, title,
      short_title, summary, status, source_url, source_label, external_ids)
    VALUES ('bill', NULL, 'utah house', 'H.B. 111', 'Employment Training Requirement Limitations',
      'Employment Training Requirement Limitations', 'This bill prohibits, for purposes of employment discrimination, certain training or other requirements that compel or require adherence to or belief in certain concepts.', 'introduced',
      'https://le.utah.gov/~2024/bills/static/HB0111.html', 'Utah State Legislature',
      jsonb_build_object('utahSession', '2024GS', 'utahBill', 'HB0111',
        'primeSponsor', 'JIMENT', 'floorSponsor', 'MCCAYD',
        'mappingReadFrom', 'introduced', 'mappingTextUrl', 'https://le.utah.gov/~2024/bills/hbillint/HB0111.htm',
        'committeeOnly', true))
    RETURNING id INTO m_id;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM vr_measure_issues
                  WHERE measure_id = m_id AND issue_key = 'end_dei') THEN
    INSERT INTO vr_measure_issues (measure_id, issue_key, weight, is_primary,
      support_meaning, rationale, source_url)
    VALUES (m_id, 'end_dei', 70, true,
      'yea_supports', 'Introduced text makes it employment discrimination for an employer to impose training or other requirements that compel adherence to or belief in specified concepts about race, sex, and related characteristics, while clarifying that objective discussion is still allowed, and adds a severability clause. Banning compelled-belief training is the operative anti-DEI mechanism.', 'https://le.utah.gov/~2024/bills/hbillint/HB0111.htm');
  END IF;
  -- 2024-01-23 · House Business, Labor, and Commerce Standing Committee · Rep. Brammer moved to pass H.B. 111 out favorably as amended.
  --   printed tally 7-2-7 (yea-nay-absent); 8 named voter(s) on the PolitiDex roster
  INSERT INTO vr_positions (measure_id, politician_id, action_type, supports, acted_at, source_url, note) VALUES
    (m_id, 'ashlee_matthews', 'committee_vote', false, '2024-01-23T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001155.pdf', 'House Business, Labor, and Commerce Standing Committee · meeting 19033 · Rep. Brammer moved to pass H.B. 111 out favorably as amended.'),
    (m_id, 'brammer_s21', 'committee_vote', true, '2024-01-23T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001155.pdf', 'House Business, Labor, and Commerce Standing Committee · meeting 19033 · Rep. Brammer moved to pass H.B. 111 out favorably as amended.'),
    (m_id, 'cmusselman', 'committee_vote', true, '2024-01-23T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001155.pdf', 'House Business, Labor, and Commerce Standing Committee · meeting 19033 · Rep. Brammer moved to pass H.B. 111 out favorably as amended.'),
    (m_id, 'cory_maloy_h52', 'committee_vote', true, '2024-01-23T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001155.pdf', 'House Business, Labor, and Commerce Standing Committee · meeting 19033 · Rep. Brammer moved to pass H.B. 111 out favorably as amended.'),
    (m_id, 'jefferson_burton', 'committee_vote', true, '2024-01-23T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001155.pdf', 'House Business, Labor, and Commerce Standing Committee · meeting 19033 · Rep. Brammer moved to pass H.B. 111 out favorably as amended.'),
    (m_id, 'teuscher_h44', 'committee_vote', true, '2024-01-23T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001155.pdf', 'House Business, Labor, and Commerce Standing Committee · meeting 19033 · Rep. Brammer moved to pass H.B. 111 out favorably as amended.'),
    (m_id, 'thomas_peterson', 'committee_vote', true, '2024-01-23T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001155.pdf', 'House Business, Labor, and Commerce Standing Committee · meeting 19033 · Rep. Brammer moved to pass H.B. 111 out favorably as amended.'),
    (m_id, 'whyte_h63', 'committee_vote', true, '2024-01-23T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001155.pdf', 'House Business, Labor, and Commerce Standing Committee · meeting 19033 · Rep. Brammer moved to pass H.B. 111 out favorably as amended.')
  ON CONFLICT (measure_id, politician_id, action_type) DO NOTHING;
  -- 2024-02-09 · Senate Business and Labor Standing Committee · Sen. Sandall moved to pass H.B. 111 out favorably.
  --   printed tally 2-5-1 (yea-nay-absent); 7 named voter(s) on the PolitiDex roster
  INSERT INTO vr_positions (measure_id, politician_id, action_type, supports, acted_at, source_url, note) VALUES
    (m_id, 'blouin_s13', 'committee_vote', false, '2024-02-09T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001511.pdf', 'Senate Business and Labor Standing Committee · meeting 19198 · Sen. Sandall moved to pass H.B. 111 out favorably.'),
    (m_id, 'cbramble', 'committee_vote', false, '2024-02-09T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001511.pdf', 'Senate Business and Labor Standing Committee · meeting 19198 · Sen. Sandall moved to pass H.B. 111 out favorably.'),
    (m_id, 'dipson', 'committee_vote', false, '2024-02-09T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001511.pdf', 'Senate Business and Labor Standing Committee · meeting 19198 · Sen. Sandall moved to pass H.B. 111 out favorably.'),
    (m_id, 'kcullimore', 'committee_vote', false, '2024-02-09T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001511.pdf', 'Senate Business and Labor Standing Committee · meeting 19198 · Sen. Sandall moved to pass H.B. 111 out favorably.'),
    (m_id, 'kwan_s12', 'committee_vote', false, '2024-02-09T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001511.pdf', 'Senate Business and Labor Standing Committee · meeting 19198 · Sen. Sandall moved to pass H.B. 111 out favorably.'),
    (m_id, 'mccay_s11', 'committee_vote', true, '2024-02-09T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001511.pdf', 'Senate Business and Labor Standing Committee · meeting 19198 · Sen. Sandall moved to pass H.B. 111 out favorably.'),
    (m_id, 'ssandall', 'committee_vote', true, '2024-02-09T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001511.pdf', 'Senate Business and Labor Standing Committee · meeting 19198 · Sen. Sandall moved to pass H.B. 111 out favorably.')
  ON CONFLICT (measure_id, politician_id, action_type) DO NOTHING;
END $$;

-- HB0137 · H.B. 137 · Disability Coverage Amendments
--   mapping read from the introduced text: https://le.utah.gov/~2024/bills/hbillint/HB0137.htm
--   1 issue mapping(s), 1 committee action(s), 11 position(s)
DO $$
DECLARE m_id integer;
BEGIN
  SELECT id INTO m_id FROM vr_measures
   WHERE number = 'H.B. 137' AND chamber = 'utah house'
     AND external_ids->>'utahSession' = '2024GS' LIMIT 1;
  IF m_id IS NULL THEN
    INSERT INTO vr_measures (measure_type, congress, chamber, number, title,
      short_title, summary, status, source_url, source_label, external_ids)
    VALUES ('bill', NULL, 'utah house', 'H.B. 137', 'Disability Coverage Amendments',
      'Disability Coverage Amendments', 'This bill addresses wraparound services for certain individuals with a disability.', 'introduced',
      'https://le.utah.gov/~2024/bills/static/HB0137.html', 'Utah State Legislature',
      jsonb_build_object('utahSession', '2024GS', 'utahBill', 'HB0137',
        'primeSponsor', 'DAILEJ', 'floorSponsor', NULL,
        'mappingReadFrom', 'introduced', 'mappingTextUrl', 'https://le.utah.gov/~2024/bills/hbillint/HB0137.htm',
        'committeeOnly', true))
    RETURNING id INTO m_id;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM vr_measure_issues
                  WHERE measure_id = m_id AND issue_key = 'healthcare') THEN
    INSERT INTO vr_measure_issues (measure_id, issue_key, weight, is_primary,
      support_meaning, rationale, source_url)
    VALUES (m_id, 'healthcare', 55, true,
      'yea_supports', 'Introduced text requires the Department of Health and Human Services to seek a Medicaid waiver or state plan amendment providing wraparound services to qualified individuals with a disability, with sliding-scale cost sharing capped at stated percentages and maximums. It directs the state to add a Medicaid benefit that does not exist today.', 'https://le.utah.gov/~2024/bills/hbillint/HB0137.htm');
  END IF;
  -- 2024-02-05 · House Business, Labor, and Commerce Standing Committee · Rep. Matthews moved to pass H.B. 137 out favorably.
  --   printed tally 6-6-4 (yea-nay-absent); 11 named voter(s) on the PolitiDex roster
  INSERT INTO vr_positions (measure_id, politician_id, action_type, supports, acted_at, source_url, note) VALUES
    (m_id, 'ashlee_matthews', 'committee_vote', true, '2024-02-05T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001472.pdf', 'House Business, Labor, and Commerce Standing Committee · meeting 19221 · Rep. Matthews moved to pass H.B. 137 out favorably.'),
    (m_id, 'brammer_s21', 'committee_vote', false, '2024-02-05T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001472.pdf', 'House Business, Labor, and Commerce Standing Committee · meeting 19221 · Rep. Matthews moved to pass H.B. 137 out favorably.'),
    (m_id, 'cmusselman', 'committee_vote', false, '2024-02-05T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001472.pdf', 'House Business, Labor, and Commerce Standing Committee · meeting 19221 · Rep. Matthews moved to pass H.B. 137 out favorably.'),
    (m_id, 'cory_maloy_h52', 'committee_vote', false, '2024-02-05T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001472.pdf', 'House Business, Labor, and Commerce Standing Committee · meeting 19221 · Rep. Matthews moved to pass H.B. 137 out favorably.'),
    (m_id, 'james_dunnigan', 'committee_vote', true, '2024-02-05T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001472.pdf', 'House Business, Labor, and Commerce Standing Committee · meeting 19221 · Rep. Matthews moved to pass H.B. 137 out favorably.'),
    (m_id, 'jefferson_burton', 'committee_vote', true, '2024-02-05T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001472.pdf', 'House Business, Labor, and Commerce Standing Committee · meeting 19221 · Rep. Matthews moved to pass H.B. 137 out favorably.'),
    (m_id, 'nthurston', 'committee_vote', true, '2024-02-05T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001472.pdf', 'House Business, Labor, and Commerce Standing Committee · meeting 19221 · Rep. Matthews moved to pass H.B. 137 out favorably.'),
    (m_id, 'ryan_d_wilcox', 'committee_vote', false, '2024-02-05T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001472.pdf', 'House Business, Labor, and Commerce Standing Committee · meeting 19221 · Rep. Matthews moved to pass H.B. 137 out favorably.'),
    (m_id, 'teuscher_h44', 'committee_vote', false, '2024-02-05T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001472.pdf', 'House Business, Labor, and Commerce Standing Committee · meeting 19221 · Rep. Matthews moved to pass H.B. 137 out favorably.'),
    (m_id, 'walt_brooks', 'committee_vote', true, '2024-02-05T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001472.pdf', 'House Business, Labor, and Commerce Standing Committee · meeting 19221 · Rep. Matthews moved to pass H.B. 137 out favorably.'),
    (m_id, 'whyte_h63', 'committee_vote', false, '2024-02-05T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001472.pdf', 'House Business, Labor, and Commerce Standing Committee · meeting 19221 · Rep. Matthews moved to pass H.B. 137 out favorably.')
  ON CONFLICT (measure_id, politician_id, action_type) DO NOTHING;
END $$;

-- HB0186 · H.B. 186 · License Plate Requirements
--   mapping read from the substitute_1 text: https://le.utah.gov/~2024/bills/hbillint/HB0186S01.htm
--   1 issue mapping(s), 1 committee action(s), 4 position(s)
DO $$
DECLARE m_id integer;
BEGIN
  SELECT id INTO m_id FROM vr_measures
   WHERE number = 'H.B. 186' AND chamber = 'utah house'
     AND external_ids->>'utahSession' = '2024GS' LIMIT 1;
  IF m_id IS NULL THEN
    INSERT INTO vr_measures (measure_type, congress, chamber, number, title,
      short_title, summary, status, source_url, source_label, external_ids)
    VALUES ('bill', NULL, 'utah house', 'H.B. 186', 'License Plate Requirements',
      'License Plate Requirements', 'This bill amends provisions related to the issuance of personalized license plates.', 'introduced',
      'https://le.utah.gov/~2024/bills/static/HB0186.html', 'Utah State Legislature',
      jsonb_build_object('utahSession', '2024GS', 'utahBill', 'HB0186',
        'primeSponsor', 'THURSNK', 'floorSponsor', 'HARPEWA',
        'mappingReadFrom', 'substitute_1', 'mappingTextUrl', 'https://le.utah.gov/~2024/bills/hbillint/HB0186S01.htm',
        'committeeOnly', true))
    RETURNING id INTO m_id;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM vr_measure_issues
                  WHERE measure_id = m_id AND issue_key = 'free_speech') THEN
    INSERT INTO vr_measure_issues (measure_id, issue_key, weight, is_primary,
      support_meaning, rationale, source_url)
    VALUES (m_id, 'free_speech', 45, true,
      'yea_opposes', 'First substitute text defines the words that may appear on a personalized license plate and prohibits the Motor Vehicle Division from issuing a plate whose requested combination is indecent, obscene, profane, or connotes certain illegal activities or substances, with a severability clause. The state is deciding which expressive combinations it will refuse, which is a speech restriction, narrow because the forum is a state-issued plate.', 'https://le.utah.gov/~2024/bills/hbillint/HB0186S01.htm');
  END IF;
  -- 2024-01-24 · House Transportation Standing Committee · Rep. Matthews moved to pass H.B. 186 out favorably.
  --   printed tally 7-3-2 (yea-nay-absent); 4 named voter(s) on the PolitiDex roster
  INSERT INTO vr_positions (measure_id, politician_id, action_type, supports, acted_at, source_url, note) VALUES
    (m_id, 'ashlee_matthews', 'committee_vote', true, '2024-01-24T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00000689.pdf', 'House Transportation Standing Committee · meeting 19040 · Rep. Matthews moved to pass H.B. 186 out favorably.'),
    (m_id, 'karen_m_peterson', 'committee_vote', true, '2024-01-24T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00000689.pdf', 'House Transportation Standing Committee · meeting 19040 · Rep. Matthews moved to pass H.B. 186 out favorably.'),
    (m_id, 'kay_christofferson', 'committee_vote', false, '2024-01-24T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00000689.pdf', 'House Transportation Standing Committee · meeting 19040 · Rep. Matthews moved to pass H.B. 186 out favorably.'),
    (m_id, 'nelson_abbott', 'committee_vote', true, '2024-01-24T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00000689.pdf', 'House Transportation Standing Committee · meeting 19040 · Rep. Matthews moved to pass H.B. 186 out favorably.')
  ON CONFLICT (measure_id, politician_id, action_type) DO NOTHING;
END $$;

-- HB0267 · H.B. 267 · Telemedicine Amendments
--   mapping read from the substitute_1 text: https://le.utah.gov/~2024/bills/hbillint/HB0267S01.htm
--   1 issue mapping(s), 1 committee action(s), 13 position(s)
DO $$
DECLARE m_id integer;
BEGIN
  SELECT id INTO m_id FROM vr_measures
   WHERE number = 'H.B. 267' AND chamber = 'utah house'
     AND external_ids->>'utahSession' = '2024GS' LIMIT 1;
  IF m_id IS NULL THEN
    INSERT INTO vr_measures (measure_type, congress, chamber, number, title,
      short_title, summary, status, source_url, source_label, external_ids)
    VALUES ('bill', NULL, 'utah house', 'H.B. 267', 'Telemedicine Amendments',
      'Telemedicine Amendments', 'This bill amends provisions relating to reimbursement for telemedicine services.', 'introduced',
      'https://le.utah.gov/~2024/bills/static/HB0267.html', 'Utah State Legislature',
      jsonb_build_object('utahSession', '2024GS', 'utahBill', 'HB0267',
        'primeSponsor', 'HAWKIJ', 'floorSponsor', 'VICKEEJ',
        'mappingReadFrom', 'substitute_1', 'mappingTextUrl', 'https://le.utah.gov/~2024/bills/hbillint/HB0267S01.htm',
        'committeeOnly', true))
    RETURNING id INTO m_id;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM vr_measure_issues
                  WHERE measure_id = m_id AND issue_key = 'healthcare') THEN
    INSERT INTO vr_measure_issues (measure_id, issue_key, weight, is_primary,
      support_meaning, rationale, source_url)
    VALUES (m_id, 'healthcare', 50, true,
      'yea_supports', 'First substitute text conditionally requires a health benefit plan to reimburse a provider for telemedicine services at no less than ninety percent of the rate the plan pays that provider for the same service delivered in person in Utah. Payment parity is what keeps a telehealth option available to patients, so the bill expands access rather than merely describing it.', 'https://le.utah.gov/~2024/bills/hbillint/HB0267S01.htm');
  END IF;
  -- 2024-02-13 · House Business, Labor, and Commerce Standing Committee · Rep. Matthews moved to pass 1st Substitute H.B. 267 out favorably.
  --   printed tally 3-11-2 (yea-nay-absent); 13 named voter(s) on the PolitiDex roster
  INSERT INTO vr_positions (measure_id, politician_id, action_type, supports, acted_at, source_url, note) VALUES
    (m_id, 'ashlee_matthews', 'committee_vote', true, '2024-02-13T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001663.pdf', 'House Business, Labor, and Commerce Standing Committee · meeting 19224 · Rep. Matthews moved to pass 1st Substitute H.B. 267 out favorably.'),
    (m_id, 'brammer_s21', 'committee_vote', false, '2024-02-13T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001663.pdf', 'House Business, Labor, and Commerce Standing Committee · meeting 19224 · Rep. Matthews moved to pass 1st Substitute H.B. 267 out favorably.'),
    (m_id, 'cmusselman', 'committee_vote', false, '2024-02-13T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001663.pdf', 'House Business, Labor, and Commerce Standing Committee · meeting 19224 · Rep. Matthews moved to pass 1st Substitute H.B. 267 out favorably.'),
    (m_id, 'cory_maloy_h52', 'committee_vote', false, '2024-02-13T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001663.pdf', 'House Business, Labor, and Commerce Standing Committee · meeting 19224 · Rep. Matthews moved to pass 1st Substitute H.B. 267 out favorably.'),
    (m_id, 'james_dunnigan', 'committee_vote', false, '2024-02-13T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001663.pdf', 'House Business, Labor, and Commerce Standing Committee · meeting 19224 · Rep. Matthews moved to pass 1st Substitute H.B. 267 out favorably.'),
    (m_id, 'jefferson_burton', 'committee_vote', false, '2024-02-13T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001663.pdf', 'House Business, Labor, and Commerce Standing Committee · meeting 19224 · Rep. Matthews moved to pass 1st Substitute H.B. 267 out favorably.'),
    (m_id, 'jon_hawkins', 'committee_vote', true, '2024-02-13T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001663.pdf', 'House Business, Labor, and Commerce Standing Committee · meeting 19224 · Rep. Matthews moved to pass 1st Substitute H.B. 267 out favorably.'),
    (m_id, 'nthurston', 'committee_vote', false, '2024-02-13T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001663.pdf', 'House Business, Labor, and Commerce Standing Committee · meeting 19224 · Rep. Matthews moved to pass 1st Substitute H.B. 267 out favorably.'),
    (m_id, 'ryan_d_wilcox', 'committee_vote', false, '2024-02-13T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001663.pdf', 'House Business, Labor, and Commerce Standing Committee · meeting 19224 · Rep. Matthews moved to pass 1st Substitute H.B. 267 out favorably.'),
    (m_id, 'teuscher_h44', 'committee_vote', false, '2024-02-13T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001663.pdf', 'House Business, Labor, and Commerce Standing Committee · meeting 19224 · Rep. Matthews moved to pass 1st Substitute H.B. 267 out favorably.'),
    (m_id, 'thomas_peterson', 'committee_vote', false, '2024-02-13T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001663.pdf', 'House Business, Labor, and Commerce Standing Committee · meeting 19224 · Rep. Matthews moved to pass 1st Substitute H.B. 267 out favorably.'),
    (m_id, 'walt_brooks', 'committee_vote', false, '2024-02-13T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001663.pdf', 'House Business, Labor, and Commerce Standing Committee · meeting 19224 · Rep. Matthews moved to pass 1st Substitute H.B. 267 out favorably.'),
    (m_id, 'whyte_h63', 'committee_vote', false, '2024-02-13T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001663.pdf', 'House Business, Labor, and Commerce Standing Committee · meeting 19224 · Rep. Matthews moved to pass 1st Substitute H.B. 267 out favorably.')
  ON CONFLICT (measure_id, politician_id, action_type) DO NOTHING;
END $$;

-- HB0284 · H.B. 284 · Initiative Amendments
--   mapping read from the introduced text: https://le.utah.gov/~2024/bills/hbillint/HB0284.htm
--   1 issue mapping(s), 2 committee action(s), 16 position(s)
DO $$
DECLARE m_id integer;
BEGIN
  SELECT id INTO m_id FROM vr_measures
   WHERE number = 'H.B. 284' AND chamber = 'utah house'
     AND external_ids->>'utahSession' = '2024GS' LIMIT 1;
  IF m_id IS NULL THEN
    INSERT INTO vr_measures (measure_type, congress, chamber, number, title,
      short_title, summary, status, source_url, source_label, external_ids)
    VALUES ('bill', NULL, 'utah house', 'H.B. 284', 'Initiative Amendments',
      'Initiative Amendments', 'This bill modifies provisions relating to a statewide initiative.', 'introduced',
      'https://le.utah.gov/~2024/bills/static/HB0284.html', 'Utah State Legislature',
      jsonb_build_object('utahSession', '2024GS', 'utahBill', 'HB0284',
        'primeSponsor', 'KYLEJB', 'floorSponsor', 'FILLML',
        'mappingReadFrom', 'introduced', 'mappingTextUrl', 'https://le.utah.gov/~2024/bills/hbillint/HB0284.htm',
        'committeeOnly', true))
    RETURNING id INTO m_id;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM vr_measure_issues
                  WHERE measure_id = m_id AND issue_key = 'voting_access') THEN
    INSERT INTO vr_measure_issues (measure_id, issue_key, weight, is_primary,
      support_meaning, rationale, source_url)
    VALUES (m_id, 'voting_access', 55, true,
      'yea_opposes', 'Introduced text, contingent on a constitutional amendment, raises the vote percentage required for a statewide initiative that would impose a new tax or increase a tax rate to pass, and adds application and fiscal impact statement requirements about how a proposed law would be funded. A supermajority threshold means a majority of voters can approve an initiative and still lose, which is a restriction on the ballot route.', 'https://le.utah.gov/~2024/bills/hbillint/HB0284.htm');
  END IF;
  -- 2024-01-30 · House Government Operations Standing Committee · Rep. Pierucci moved to pass H.B. 284 out favorably.
  --   printed tally 7-3-3 (yea-nay-absent); 8 named voter(s) on the PolitiDex roster
  INSERT INTO vr_positions (measure_id, politician_id, action_type, supports, acted_at, source_url, note) VALUES
    (m_id, 'andrew_stoddard', 'committee_vote', false, '2024-01-30T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001178.pdf', 'House Government Operations Standing Committee · meeting 19097 · Rep. Pierucci moved to pass H.B. 284 out favorably.'),
    (m_id, 'candice_pierucci', 'committee_vote', true, '2024-01-30T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001178.pdf', 'House Government Operations Standing Committee · meeting 19097 · Rep. Pierucci moved to pass H.B. 284 out favorably.'),
    (m_id, 'cmusselman', 'committee_vote', true, '2024-01-30T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001178.pdf', 'House Government Operations Standing Committee · meeting 19097 · Rep. Pierucci moved to pass H.B. 284 out favorably.'),
    (m_id, 'cory_maloy_h52', 'committee_vote', true, '2024-01-30T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001178.pdf', 'House Government Operations Standing Committee · meeting 19097 · Rep. Pierucci moved to pass H.B. 284 out favorably.'),
    (m_id, 'mike_petersen', 'committee_vote', true, '2024-01-30T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001178.pdf', 'House Government Operations Standing Committee · meeting 19097 · Rep. Pierucci moved to pass H.B. 284 out favorably.'),
    (m_id, 'nthurston', 'committee_vote', true, '2024-01-30T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001178.pdf', 'House Government Operations Standing Committee · meeting 19097 · Rep. Pierucci moved to pass H.B. 284 out favorably.'),
    (m_id, 'sahara_hayes', 'committee_vote', false, '2024-01-30T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001178.pdf', 'House Government Operations Standing Committee · meeting 19097 · Rep. Pierucci moved to pass H.B. 284 out favorably.'),
    (m_id, 'valpeterson_h56', 'committee_vote', true, '2024-01-30T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001178.pdf', 'House Government Operations Standing Committee · meeting 19097 · Rep. Pierucci moved to pass H.B. 284 out favorably.')
  ON CONFLICT (measure_id, politician_id, action_type) DO NOTHING;
  -- 2024-02-12 · Senate Revenue and Taxation Standing Committee · Sen. Fillmore moved to pass H.B. 284 out favorably.
  --   printed tally 5-3-0 (yea-nay-absent); 8 named voter(s) on the PolitiDex roster
  INSERT INTO vr_positions (measure_id, politician_id, action_type, supports, acted_at, source_url, note) VALUES
    (m_id, 'cbramble', 'committee_vote', false, '2024-02-12T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001641.pdf', 'Senate Revenue and Taxation Standing Committee · meeting 19335 · Sen. Fillmore moved to pass H.B. 284 out favorably.'),
    (m_id, 'cwilson', 'committee_vote', true, '2024-02-12T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001641.pdf', 'Senate Revenue and Taxation Standing Committee · meeting 19335 · Sen. Fillmore moved to pass H.B. 284 out favorably.'),
    (m_id, 'dipson', 'committee_vote', true, '2024-02-12T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001641.pdf', 'Senate Revenue and Taxation Standing Committee · meeting 19335 · Sen. Fillmore moved to pass H.B. 284 out favorably.'),
    (m_id, 'harper_s16', 'committee_vote', false, '2024-02-12T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001641.pdf', 'Senate Revenue and Taxation Standing Committee · meeting 19335 · Sen. Fillmore moved to pass H.B. 284 out favorably.'),
    (m_id, 'kcullimore', 'committee_vote', true, '2024-02-12T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001641.pdf', 'Senate Revenue and Taxation Standing Committee · meeting 19335 · Sen. Fillmore moved to pass H.B. 284 out favorably.'),
    (m_id, 'lescamilla', 'committee_vote', false, '2024-02-12T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001641.pdf', 'Senate Revenue and Taxation Standing Committee · meeting 19335 · Sen. Fillmore moved to pass H.B. 284 out favorably.'),
    (m_id, 'lincoln_fillmore', 'committee_vote', true, '2024-02-12T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001641.pdf', 'Senate Revenue and Taxation Standing Committee · meeting 19335 · Sen. Fillmore moved to pass H.B. 284 out favorably.'),
    (m_id, 'mccay_s11', 'committee_vote', true, '2024-02-12T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001641.pdf', 'Senate Revenue and Taxation Standing Committee · meeting 19335 · Sen. Fillmore moved to pass H.B. 284 out favorably.')
  ON CONFLICT (measure_id, politician_id, action_type) DO NOTHING;
END $$;

-- HB0335 · H.B. 335 · State Grant Process Amendments
--   mapping read from the substitute_4 text: https://le.utah.gov/~2024/bills/hbillint/HB0335S04.htm
--   1 issue mapping(s), 1 committee action(s), 7 position(s)
DO $$
DECLARE m_id integer;
BEGIN
  SELECT id INTO m_id FROM vr_measures
   WHERE number = 'H.B. 335' AND chamber = 'utah house'
     AND external_ids->>'utahSession' = '2024GS' LIMIT 1;
  IF m_id IS NULL THEN
    INSERT INTO vr_measures (measure_type, congress, chamber, number, title,
      short_title, summary, status, source_url, source_label, external_ids)
    VALUES ('bill', NULL, 'utah house', 'H.B. 335', 'State Grant Process Amendments',
      'State Grant Process Amendments', 'This bill enacts provisions governing the administration of state grants.', 'enacted',
      'https://le.utah.gov/~2024/bills/static/HB0335.html', 'Utah State Legislature',
      jsonb_build_object('utahSession', '2024GS', 'utahBill', 'HB0335',
        'primeSponsor', 'PETERVL', 'floorSponsor', 'STEVEJW',
        'mappingReadFrom', 'substitute_4', 'mappingTextUrl', 'https://le.utah.gov/~2024/bills/hbillint/HB0335S04.htm',
        'committeeOnly', true))
    RETURNING id INTO m_id;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM vr_measure_issues
                  WHERE measure_id = m_id AND issue_key = 'audit_spending') THEN
    INSERT INTO vr_measure_issues (measure_id, issue_key, weight, is_primary,
      support_meaning, rationale, source_url)
    VALUES (m_id, 'audit_spending', 55, true,
      'yea_supports', 'Fourth substitute text requires a state grant recipient to submit a proposed budget and agree to deliverables, reporting, audit, and clawback requirements before receiving any funds, sets the disbursement schedule, requires later review of grants funded by ongoing appropriations, and adds requirements specific to direct award and competitive grants. Every clause attaches accountability to public money.', 'https://le.utah.gov/~2024/bills/hbillint/HB0335S04.htm');
  END IF;
  -- 2024-02-08 · House Government Operations Standing Committee · Rep. Michael Petersen moved to pass 1st Substitute H.B. 335 out favorably.
  --   printed tally 7-1-5 (yea-nay-absent); 7 named voter(s) on the PolitiDex roster
  INSERT INTO vr_positions (measure_id, politician_id, action_type, supports, acted_at, source_url, note) VALUES
    (m_id, 'andrew_stoddard', 'committee_vote', true, '2024-02-08T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001465.pdf', 'House Government Operations Standing Committee · meeting 19161 · Rep. Michael Petersen moved to pass 1st Substitute H.B. 335 out favorably.'),
    (m_id, 'candice_pierucci', 'committee_vote', true, '2024-02-08T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001465.pdf', 'House Government Operations Standing Committee · meeting 19161 · Rep. Michael Petersen moved to pass 1st Substitute H.B. 335 out favorably.'),
    (m_id, 'cmusselman', 'committee_vote', true, '2024-02-08T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001465.pdf', 'House Government Operations Standing Committee · meeting 19161 · Rep. Michael Petersen moved to pass 1st Substitute H.B. 335 out favorably.'),
    (m_id, 'mike_petersen', 'committee_vote', true, '2024-02-08T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001465.pdf', 'House Government Operations Standing Committee · meeting 19161 · Rep. Michael Petersen moved to pass 1st Substitute H.B. 335 out favorably.'),
    (m_id, 'nthurston', 'committee_vote', true, '2024-02-08T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001465.pdf', 'House Government Operations Standing Committee · meeting 19161 · Rep. Michael Petersen moved to pass 1st Substitute H.B. 335 out favorably.'),
    (m_id, 'sahara_hayes', 'committee_vote', false, '2024-02-08T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001465.pdf', 'House Government Operations Standing Committee · meeting 19161 · Rep. Michael Petersen moved to pass 1st Substitute H.B. 335 out favorably.'),
    (m_id, 'valpeterson_h56', 'committee_vote', true, '2024-02-08T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001465.pdf', 'House Government Operations Standing Committee · meeting 19161 · Rep. Michael Petersen moved to pass 1st Substitute H.B. 335 out favorably.')
  ON CONFLICT (measure_id, politician_id, action_type) DO NOTHING;
END $$;

-- HB0429 · H.B. 429 · State Employment Revisions
--   mapping read from the introduced text: https://le.utah.gov/~2024/bills/hbillint/HB0429.htm
--   1 issue mapping(s), 2 committee action(s), 12 position(s)
DO $$
DECLARE m_id integer;
BEGIN
  SELECT id INTO m_id FROM vr_measures
   WHERE number = 'H.B. 429' AND chamber = 'utah house'
     AND external_ids->>'utahSession' = '2024GS' LIMIT 1;
  IF m_id IS NULL THEN
    INSERT INTO vr_measures (measure_type, congress, chamber, number, title,
      short_title, summary, status, source_url, source_label, external_ids)
    VALUES ('bill', NULL, 'utah house', 'H.B. 429', 'State Employment Revisions',
      'State Employment Revisions', 'This bill amends provisions of the Utah State Personnel Management Act.', 'introduced',
      'https://le.utah.gov/~2024/bills/static/HB0429.html', 'Utah State Legislature',
      jsonb_build_object('utahSession', '2024GS', 'utahBill', 'HB0429',
        'primeSponsor', 'CHRISKJ', 'floorSponsor', 'VICKEEJ',
        'mappingReadFrom', 'introduced', 'mappingTextUrl', 'https://le.utah.gov/~2024/bills/hbillint/HB0429.htm',
        'committeeOnly', true))
    RETURNING id INTO m_id;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM vr_measure_issues
                  WHERE measure_id = m_id AND issue_key = 'civil_service_control') THEN
    INSERT INTO vr_measure_issues (measure_id, issue_key, weight, is_primary,
      support_meaning, rationale, source_url)
    VALUES (m_id, 'civil_service_control', 65, true,
      'yea_supports', 'Introduced text classifies a state employee as exempt from career service status beginning January 2025 unless the position requires POST certification, career status is needed to keep federal funding, or the employee held career status before reclassification, and it redefines career service by reference to the system section. Stripping tenure protections from the state workforce is exactly what this key tracks.', 'https://le.utah.gov/~2024/bills/hbillint/HB0429.htm');
  END IF;
  -- 2024-02-09 · House Government Operations Standing Committee · Rep. Thurston moved to pass H.B. 429 out favorably.
  --   printed tally 5-4-4 (yea-nay-absent); 7 named voter(s) on the PolitiDex roster
  INSERT INTO vr_positions (measure_id, politician_id, action_type, supports, acted_at, source_url, note) VALUES
    (m_id, 'andrew_stoddard', 'committee_vote', false, '2024-02-09T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001569.pdf', 'House Government Operations Standing Committee · meeting 19154 · Rep. Thurston moved to pass H.B. 429 out favorably.'),
    (m_id, 'cmusselman', 'committee_vote', true, '2024-02-09T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001569.pdf', 'House Government Operations Standing Committee · meeting 19154 · Rep. Thurston moved to pass H.B. 429 out favorably.'),
    (m_id, 'cory_maloy_h52', 'committee_vote', true, '2024-02-09T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001569.pdf', 'House Government Operations Standing Committee · meeting 19154 · Rep. Thurston moved to pass H.B. 429 out favorably.'),
    (m_id, 'mike_petersen', 'committee_vote', true, '2024-02-09T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001569.pdf', 'House Government Operations Standing Committee · meeting 19154 · Rep. Thurston moved to pass H.B. 429 out favorably.'),
    (m_id, 'nthurston', 'committee_vote', true, '2024-02-09T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001569.pdf', 'House Government Operations Standing Committee · meeting 19154 · Rep. Thurston moved to pass H.B. 429 out favorably.'),
    (m_id, 'sahara_hayes', 'committee_vote', false, '2024-02-09T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001569.pdf', 'House Government Operations Standing Committee · meeting 19154 · Rep. Thurston moved to pass H.B. 429 out favorably.'),
    (m_id, 'valpeterson_h56', 'committee_vote', true, '2024-02-09T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001569.pdf', 'House Government Operations Standing Committee · meeting 19154 · Rep. Thurston moved to pass H.B. 429 out favorably.')
  ON CONFLICT (measure_id, politician_id, action_type) DO NOTHING;
  -- 2024-02-23 · Senate Business and Labor Standing Committee · Sen. Sandall moved to pass H.B. 429 out favorably.
  --   printed tally 2-3-3 (yea-nay-absent); 5 named voter(s) on the PolitiDex roster
  INSERT INTO vr_positions (measure_id, politician_id, action_type, supports, acted_at, source_url, note) VALUES
    (m_id, 'blouin_s13', 'committee_vote', false, '2024-02-23T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001825.pdf', 'Senate Business and Labor Standing Committee · meeting 19202 · Sen. Sandall moved to pass H.B. 429 out favorably.'),
    (m_id, 'cbramble', 'committee_vote', false, '2024-02-23T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001825.pdf', 'Senate Business and Labor Standing Committee · meeting 19202 · Sen. Sandall moved to pass H.B. 429 out favorably.'),
    (m_id, 'kcullimore', 'committee_vote', true, '2024-02-23T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001825.pdf', 'Senate Business and Labor Standing Committee · meeting 19202 · Sen. Sandall moved to pass H.B. 429 out favorably.'),
    (m_id, 'kwan_s12', 'committee_vote', false, '2024-02-23T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001825.pdf', 'Senate Business and Labor Standing Committee · meeting 19202 · Sen. Sandall moved to pass H.B. 429 out favorably.'),
    (m_id, 'ssandall', 'committee_vote', true, '2024-02-23T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001825.pdf', 'Senate Business and Labor Standing Committee · meeting 19202 · Sen. Sandall moved to pass H.B. 429 out favorably.')
  ON CONFLICT (measure_id, politician_id, action_type) DO NOTHING;
END $$;

-- HB0460 · H.B. 460 · Government Employee Conscience Protection Amendments
--   mapping read from the substitute_3 text: https://le.utah.gov/~2024/bills/hbillamd/HB0460S03.htm
--   1 issue mapping(s), 1 committee action(s), 6 position(s)
DO $$
DECLARE m_id integer;
BEGIN
  SELECT id INTO m_id FROM vr_measures
   WHERE number = 'H.B. 460' AND chamber = 'utah house'
     AND external_ids->>'utahSession' = '2024GS' LIMIT 1;
  IF m_id IS NULL THEN
    INSERT INTO vr_measures (measure_type, congress, chamber, number, title,
      short_title, summary, status, source_url, source_label, external_ids)
    VALUES ('bill', NULL, 'utah house', 'H.B. 460', 'Government Employee Conscience Protection Amendments',
      'Government Employee Conscience Protection Amendments', 'This bill addresses required reasonable accommodations for government employees in certain circumstances.', 'enacted',
      'https://le.utah.gov/~2024/bills/static/HB0460.html', 'Utah State Legislature',
      jsonb_build_object('utahSession', '2024GS', 'utahBill', 'HB0460',
        'primeSponsor', 'PETERM', 'floorSponsor', 'WEILET',
        'mappingReadFrom', 'substitute_3', 'mappingTextUrl', 'https://le.utah.gov/~2024/bills/hbillamd/HB0460S03.htm',
        'committeeOnly', true))
    RETURNING id INTO m_id;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM vr_measure_issues
                  WHERE measure_id = m_id AND issue_key = 'religious_liberty') THEN
    INSERT INTO vr_measure_issues (measure_id, issue_key, weight, is_primary,
      support_meaning, rationale, source_url)
    VALUES (m_id, 'religious_liberty', 55, true,
      'yea_supports', 'Third substitute text requires a governmental entity to grant an employee''s request to be relieved from performing a task that violates the employee''s conscience, defined as a sincerely held belief about the rightness or wrongness of an action, unless doing so would impose undue hardship, and creates protections and a cause of action for a denied employee. Conscience protection with a remedy attached.', 'https://le.utah.gov/~2024/bills/hbillamd/HB0460S03.htm');
  END IF;
  -- 2024-02-23 · House Political Subdivisions Standing Committee · Rep. Judkins moved to pass 2nd Substitute H.B. 460 out favorably.
  --   printed tally 7-3-1 (yea-nay-absent); 6 named voter(s) on the PolitiDex roster
  INSERT INTO vr_positions (measure_id, politician_id, action_type, supports, acted_at, source_url, note) VALUES
    (m_id, 'gay_lynn_bennion', 'committee_vote', false, '2024-02-23T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001834.pdf', 'House Political Subdivisions Standing Committee · meeting 19210 · Rep. Judkins moved to pass 2nd Substitute H.B. 460 out favorably.'),
    (m_id, 'james_dunnigan', 'committee_vote', true, '2024-02-23T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001834.pdf', 'House Political Subdivisions Standing Committee · meeting 19210 · Rep. Judkins moved to pass 2nd Substitute H.B. 460 out favorably.'),
    (m_id, 'kohler_h59', 'committee_vote', true, '2024-02-23T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001834.pdf', 'House Political Subdivisions Standing Committee · meeting 19210 · Rep. Judkins moved to pass 2nd Substitute H.B. 460 out favorably.'),
    (m_id, 'r_neil_walter', 'committee_vote', false, '2024-02-23T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001834.pdf', 'House Political Subdivisions Standing Committee · meeting 19210 · Rep. Judkins moved to pass 2nd Substitute H.B. 460 out favorably.'),
    (m_id, 'teuscher_h44', 'committee_vote', true, '2024-02-23T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001834.pdf', 'House Political Subdivisions Standing Committee · meeting 19210 · Rep. Judkins moved to pass 2nd Substitute H.B. 460 out favorably.'),
    (m_id, 'tlee', 'committee_vote', true, '2024-02-23T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001834.pdf', 'House Political Subdivisions Standing Committee · meeting 19210 · Rep. Judkins moved to pass 2nd Substitute H.B. 460 out favorably.')
  ON CONFLICT (measure_id, politician_id, action_type) DO NOTHING;
END $$;

-- HB0463 · H.B. 463 · Medicaid Funding Amendments
--   mapping read from the substitute_2 text: https://le.utah.gov/~2024/bills/hbillint/HB0463S02.htm
--   1 issue mapping(s), 1 committee action(s), 13 position(s)
DO $$
DECLARE m_id integer;
BEGIN
  SELECT id INTO m_id FROM vr_measures
   WHERE number = 'H.B. 463' AND chamber = 'utah house'
     AND external_ids->>'utahSession' = '2024GS' LIMIT 1;
  IF m_id IS NULL THEN
    INSERT INTO vr_measures (measure_type, congress, chamber, number, title,
      short_title, summary, status, source_url, source_label, external_ids)
    VALUES ('bill', NULL, 'utah house', 'H.B. 463', 'Medicaid Funding Amendments',
      'Medicaid Funding Amendments', 'This bill amends provisions related to the Medicaid program and Medicaid expansion.', 'introduced',
      'https://le.utah.gov/~2024/bills/static/HB0463.html', 'Utah State Legislature',
      jsonb_build_object('utahSession', '2024GS', 'utahBill', 'HB0463',
        'primeSponsor', 'BRAMMB', 'floorSponsor', NULL,
        'mappingReadFrom', 'substitute_2', 'mappingTextUrl', 'https://le.utah.gov/~2024/bills/hbillint/HB0463S02.htm',
        'committeeOnly', true))
    RETURNING id INTO m_id;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM vr_measure_issues
                  WHERE measure_id = m_id AND issue_key = 'healthcare') THEN
    INSERT INTO vr_measure_issues (measure_id, issue_key, weight, is_primary,
      support_meaning, rationale, source_url)
    VALUES (m_id, 'healthcare', 55, true,
      'yea_opposes', 'Second substitute text defines a Medicaid shortfall and requires that on a shortfall the responsible departments suspend hiring, suspend wage increases, suspend increases in provider payment rates, suspend expanding reimbursement benefits including drug reimbursements, and close enrollment to new members. A mandatory enrollment freeze is a coverage contraction written into statute ahead of time.', 'https://le.utah.gov/~2024/bills/hbillint/HB0463S02.htm');
  END IF;
  -- 2024-02-15 · House Business, Labor, and Commerce Standing Committee · Rep. Musselman moved to pass 2nd Substitute H.B. 463 out favorably.
  --   printed tally 10-4-2 (yea-nay-absent); 13 named voter(s) on the PolitiDex roster
  INSERT INTO vr_positions (measure_id, politician_id, action_type, supports, acted_at, source_url, note) VALUES
    (m_id, 'ashlee_matthews', 'committee_vote', false, '2024-02-15T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001694.pdf', 'House Business, Labor, and Commerce Standing Committee · meeting 19225 · Rep. Musselman moved to pass 2nd Substitute H.B. 463 out favorably.'),
    (m_id, 'brammer_s21', 'committee_vote', true, '2024-02-15T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001694.pdf', 'House Business, Labor, and Commerce Standing Committee · meeting 19225 · Rep. Musselman moved to pass 2nd Substitute H.B. 463 out favorably.'),
    (m_id, 'carl_albrecht', 'committee_vote', false, '2024-02-15T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001694.pdf', 'House Business, Labor, and Commerce Standing Committee · meeting 19225 · Rep. Musselman moved to pass 2nd Substitute H.B. 463 out favorably.'),
    (m_id, 'cmusselman', 'committee_vote', true, '2024-02-15T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001694.pdf', 'House Business, Labor, and Commerce Standing Committee · meeting 19225 · Rep. Musselman moved to pass 2nd Substitute H.B. 463 out favorably.'),
    (m_id, 'cory_maloy_h52', 'committee_vote', true, '2024-02-15T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001694.pdf', 'House Business, Labor, and Commerce Standing Committee · meeting 19225 · Rep. Musselman moved to pass 2nd Substitute H.B. 463 out favorably.'),
    (m_id, 'james_dunnigan', 'committee_vote', false, '2024-02-15T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001694.pdf', 'House Business, Labor, and Commerce Standing Committee · meeting 19225 · Rep. Musselman moved to pass 2nd Substitute H.B. 463 out favorably.'),
    (m_id, 'jefferson_burton', 'committee_vote', true, '2024-02-15T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001694.pdf', 'House Business, Labor, and Commerce Standing Committee · meeting 19225 · Rep. Musselman moved to pass 2nd Substitute H.B. 463 out favorably.'),
    (m_id, 'jon_hawkins', 'committee_vote', true, '2024-02-15T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001694.pdf', 'House Business, Labor, and Commerce Standing Committee · meeting 19225 · Rep. Musselman moved to pass 2nd Substitute H.B. 463 out favorably.'),
    (m_id, 'nthurston', 'committee_vote', true, '2024-02-15T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001694.pdf', 'House Business, Labor, and Commerce Standing Committee · meeting 19225 · Rep. Musselman moved to pass 2nd Substitute H.B. 463 out favorably.'),
    (m_id, 'teuscher_h44', 'committee_vote', true, '2024-02-15T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001694.pdf', 'House Business, Labor, and Commerce Standing Committee · meeting 19225 · Rep. Musselman moved to pass 2nd Substitute H.B. 463 out favorably.'),
    (m_id, 'thomas_peterson', 'committee_vote', true, '2024-02-15T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001694.pdf', 'House Business, Labor, and Commerce Standing Committee · meeting 19225 · Rep. Musselman moved to pass 2nd Substitute H.B. 463 out favorably.'),
    (m_id, 'walt_brooks', 'committee_vote', true, '2024-02-15T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001694.pdf', 'House Business, Labor, and Commerce Standing Committee · meeting 19225 · Rep. Musselman moved to pass 2nd Substitute H.B. 463 out favorably.'),
    (m_id, 'whyte_h63', 'committee_vote', true, '2024-02-15T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001694.pdf', 'House Business, Labor, and Commerce Standing Committee · meeting 19225 · Rep. Musselman moved to pass 2nd Substitute H.B. 463 out favorably.')
  ON CONFLICT (measure_id, politician_id, action_type) DO NOTHING;
END $$;

-- HB0465 · H.B. 465 · Housing Affordability Revisions
--   mapping read from the substitute_3 text: https://le.utah.gov/~2024/bills/hbillamd/HB0465S03.htm
--   1 issue mapping(s), 1 committee action(s), 6 position(s)
DO $$
DECLARE m_id integer;
BEGIN
  SELECT id INTO m_id FROM vr_measures
   WHERE number = 'H.B. 465' AND chamber = 'utah house'
     AND external_ids->>'utahSession' = '2024GS' LIMIT 1;
  IF m_id IS NULL THEN
    INSERT INTO vr_measures (measure_type, congress, chamber, number, title,
      short_title, summary, status, source_url, source_label, external_ids)
    VALUES ('bill', NULL, 'utah house', 'H.B. 465', 'Housing Affordability Revisions',
      'Housing Affordability Revisions', 'This bill addresses funding issues related to housing affordability.', 'enacted',
      'https://le.utah.gov/~2024/bills/static/HB0465.html', 'Utah State Legislature',
      jsonb_build_object('utahSession', '2024GS', 'utahBill', 'HB0465',
        'primeSponsor', 'WHYTESL', 'floorSponsor', 'FILLML',
        'mappingReadFrom', 'substitute_3', 'mappingTextUrl', 'https://le.utah.gov/~2024/bills/hbillamd/HB0465S03.htm',
        'committeeOnly', true))
    RETURNING id INTO m_id;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM vr_measure_issues
                  WHERE measure_id = m_id AND issue_key = 'housing_support') THEN
    INSERT INTO vr_measure_issues (measure_id, issue_key, weight, is_primary,
      support_meaning, rationale, source_url)
    VALUES (m_id, 'housing_support', 55, true,
      'yea_supports', 'Third substitute text authorizes redevelopment and community development agencies to fund acquisition, construction, or rehabilitation of income targeted housing, requires the Department of Workforce Services to create pass-through funding agreements that spend state funds on stated affordable housing investments, modifies the low-income housing tax credit, and adjusts moderate income housing reporting. The bill''s money and mandates run toward income-targeted units.', 'https://le.utah.gov/~2024/bills/hbillamd/HB0465S03.htm');
  END IF;
  -- 2024-02-14 · House Government Operations Standing Committee · Rep. Pierucci moved to pass 2nd Substitute H.B. 465 out favorably.
  --   printed tally 7-2-4 (yea-nay-absent); 6 named voter(s) on the PolitiDex roster
  INSERT INTO vr_positions (measure_id, politician_id, action_type, supports, acted_at, source_url, note) VALUES
    (m_id, 'andrew_stoddard', 'committee_vote', true, '2024-02-14T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001686.pdf', 'House Government Operations Standing Committee · meeting 19156 · Rep. Pierucci moved to pass 2nd Substitute H.B. 465 out favorably.'),
    (m_id, 'candice_pierucci', 'committee_vote', true, '2024-02-14T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001686.pdf', 'House Government Operations Standing Committee · meeting 19156 · Rep. Pierucci moved to pass 2nd Substitute H.B. 465 out favorably.'),
    (m_id, 'cmusselman', 'committee_vote', true, '2024-02-14T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001686.pdf', 'House Government Operations Standing Committee · meeting 19156 · Rep. Pierucci moved to pass 2nd Substitute H.B. 465 out favorably.'),
    (m_id, 'cory_maloy_h52', 'committee_vote', true, '2024-02-14T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001686.pdf', 'House Government Operations Standing Committee · meeting 19156 · Rep. Pierucci moved to pass 2nd Substitute H.B. 465 out favorably.'),
    (m_id, 'nthurston', 'committee_vote', true, '2024-02-14T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001686.pdf', 'House Government Operations Standing Committee · meeting 19156 · Rep. Pierucci moved to pass 2nd Substitute H.B. 465 out favorably.'),
    (m_id, 'sahara_hayes', 'committee_vote', true, '2024-02-14T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001686.pdf', 'House Government Operations Standing Committee · meeting 19156 · Rep. Pierucci moved to pass 2nd Substitute H.B. 465 out favorably.')
  ON CONFLICT (measure_id, politician_id, action_type) DO NOTHING;
END $$;

-- HB0534 · H.B. 534 · Boards and Commissions Modifications
--   mapping read from the substitute_1 text: https://le.utah.gov/~2024/bills/hbillint/HB0534S01.htm
--   1 issue mapping(s), 2 committee action(s), 13 position(s)
DO $$
DECLARE m_id integer;
BEGIN
  SELECT id INTO m_id FROM vr_measures
   WHERE number = 'H.B. 534' AND chamber = 'utah house'
     AND external_ids->>'utahSession' = '2024GS' LIMIT 1;
  IF m_id IS NULL THEN
    INSERT INTO vr_measures (measure_type, congress, chamber, number, title,
      short_title, summary, status, source_url, source_label, external_ids)
    VALUES ('bill', NULL, 'utah house', 'H.B. 534', 'Boards and Commissions Modifications',
      'Boards and Commissions Modifications', 'This bill modifies boards and commissions.', 'enacted',
      'https://le.utah.gov/~2024/bills/static/HB0534.html', 'Utah State Legislature',
      jsonb_build_object('utahSession', '2024GS', 'utahBill', 'HB0534',
        'primeSponsor', 'MUSSECR', 'floorSponsor', 'MCCAYD',
        'mappingReadFrom', 'substitute_1', 'mappingTextUrl', 'https://le.utah.gov/~2024/bills/hbillint/HB0534S01.htm',
        'committeeOnly', true))
    RETURNING id INTO m_id;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM vr_measure_issues
                  WHERE measure_id = m_id AND issue_key = 'gov_waste') THEN
    INSERT INTO vr_measure_issues (measure_id, issue_key, weight, is_primary,
      support_meaning, rationale, source_url)
    VALUES (m_id, 'gov_waste', 45, true,
      'yea_supports', 'First substitute text repeals roughly two dozen boards, commissions, task forces, and advisory councils outright and folds seven separate professional licensing boards into consolidated boards, along with repealing the COVID-19 Health and Economic Response Act chapter. It is a streamlining bill whose every clause removes or merges a standing body rather than creating one.', 'https://le.utah.gov/~2024/bills/hbillint/HB0534S01.htm');
  END IF;
  -- 2024-02-20 · House Government Operations Standing Committee · Rep. Brammer moved to pass H.B. 534 out favorably.
  --   printed tally 10-2-1 (yea-nay-absent); 9 named voter(s) on the PolitiDex roster
  INSERT INTO vr_positions (measure_id, politician_id, action_type, supports, acted_at, source_url, note) VALUES
    (m_id, 'andrew_stoddard', 'committee_vote', false, '2024-02-20T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001740.pdf', 'House Government Operations Standing Committee · meeting 19157 · Rep. Brammer moved to pass H.B. 534 out favorably.'),
    (m_id, 'brammer_s21', 'committee_vote', true, '2024-02-20T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001740.pdf', 'House Government Operations Standing Committee · meeting 19157 · Rep. Brammer moved to pass H.B. 534 out favorably.'),
    (m_id, 'candice_pierucci', 'committee_vote', true, '2024-02-20T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001740.pdf', 'House Government Operations Standing Committee · meeting 19157 · Rep. Brammer moved to pass H.B. 534 out favorably.'),
    (m_id, 'cmusselman', 'committee_vote', true, '2024-02-20T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001740.pdf', 'House Government Operations Standing Committee · meeting 19157 · Rep. Brammer moved to pass H.B. 534 out favorably.'),
    (m_id, 'cory_maloy_h52', 'committee_vote', true, '2024-02-20T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001740.pdf', 'House Government Operations Standing Committee · meeting 19157 · Rep. Brammer moved to pass H.B. 534 out favorably.'),
    (m_id, 'mike_petersen', 'committee_vote', true, '2024-02-20T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001740.pdf', 'House Government Operations Standing Committee · meeting 19157 · Rep. Brammer moved to pass H.B. 534 out favorably.'),
    (m_id, 'nthurston', 'committee_vote', true, '2024-02-20T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001740.pdf', 'House Government Operations Standing Committee · meeting 19157 · Rep. Brammer moved to pass H.B. 534 out favorably.'),
    (m_id, 'sahara_hayes', 'committee_vote', false, '2024-02-20T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001740.pdf', 'House Government Operations Standing Committee · meeting 19157 · Rep. Brammer moved to pass H.B. 534 out favorably.'),
    (m_id, 'valpeterson_h56', 'committee_vote', true, '2024-02-20T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001740.pdf', 'House Government Operations Standing Committee · meeting 19157 · Rep. Brammer moved to pass H.B. 534 out favorably.')
  ON CONFLICT (measure_id, politician_id, action_type) DO NOTHING;
  -- 2024-02-27 · Senate Economic Development and Workforce Services Standing Committee · Sen. McKell moved to pass 1st Substitute H.B. 534 out favorably.
  --   printed tally 2-2-2 (yea-nay-absent); 4 named voter(s) on the PolitiDex roster
  INSERT INTO vr_positions (measure_id, politician_id, action_type, supports, acted_at, source_url, note) VALUES
    (m_id, 'dhinkins', 'committee_vote', false, '2024-02-27T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001936.pdf', 'Senate Economic Development and Workforce Services Standing Committee · meeting 19282 · Sen. McKell moved to pass 1st Substitute H.B. 534 out favorably.'),
    (m_id, 'dowens_st', 'committee_vote', true, '2024-02-27T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001936.pdf', 'Senate Economic Development and Workforce Services Standing Committee · meeting 19282 · Sen. McKell moved to pass 1st Substitute H.B. 534 out favorably.'),
    (m_id, 'kwan_s12', 'committee_vote', false, '2024-02-27T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001936.pdf', 'Senate Economic Development and Workforce Services Standing Committee · meeting 19282 · Sen. McKell moved to pass 1st Substitute H.B. 534 out favorably.'),
    (m_id, 'mckell_s25', 'committee_vote', true, '2024-02-27T00:00:00-07:00'::timestamptz, 'https://le.utah.gov/interim/2024/pdf/00001936.pdf', 'Senate Economic Development and Workforce Services Standing Committee · meeting 19282 · Sen. McKell moved to pass 1st Substitute H.B. 534 out favorably.')
  ON CONFLICT (measure_id, politician_id, action_type) DO NOTHING;
END $$;

