-- ─────────────────────────────────────────────────────────────────────────────
-- vr_vocab_wave_v1 — three new issue keys, and the Utah bills that finally have
-- a home under them
-- ─────────────────────────────────────────────────────────────────────────────
-- WHAT THIS IS. Vocab wave V1 added three keys to ISSUE_MAP (alignment-tool.js,
-- regenerated into db/issue-keys.json): sound_money, tobacco_nicotine and
-- dev_district_finance. Each was added because two or more real instruments asked
-- for it and were REFUSED for want of a key — the refusal notes in
-- db/vr-utah-bills*.json and db/vr-utah-committee-bills-*.json name them and say
-- so. The boundary prose for each key, including what it is deliberately NOT
-- (crypto_cbdc, medical_freedom, prop_tax/property_tax, housing_build,
-- econ_growth, infrastructure), lives above the entry in alignment-tool.js.
--
-- WHAT THIS MIGRATION DOES. It lands the five Utah bills whose refusal was purely
-- "clear direction, no key" and which have a CONTESTED recorded floor roll, so the
-- new keys arrive with real acts behind them rather than as empty chips:
--
--   2024GS H.B. 348  Precious Metals Amendments                   sound_money 80
--     House 52-18-5 (roll 895) — losing side 25.7% of votes cast
--   2025GS H.B. 67   Precious Metals Investment & Administration   sound_money 40
--     Senate 19-6-4 (roll 1528). The House roll was 70-0 and is NOT ingested:
--     near-unanimous votes differentiate nobody (see the runbook's rule).
--   2025GS S.B. 26   Housing and Transit Reinvestment Zone Amdts   dev_district_finance 60
--     Senate concurrence 21-5-3 (roll 2029). House was 64-5, near-unanimous, out.
--   2025GS S.B. 316  MIDA and Other Development Zone Amendments    dev_district_finance 70
--     House 38-27-10 (roll 1601) and Senate concurrence 22-5-2 (roll 2235)
--   2025GS S.B. 336  Utah Fairpark District Modifications          dev_district_finance 75
--     House 54-16-5 (roll 1443) and Senate concurrence 22-5-2 (roll 2034)
--
-- Every mapping carries a rationale that names the provisions it reads, and every
-- rationale's source_url is the ENROLLED text it was read from, not the bill index
-- page — which is also what external_ids.mappingReadFrom / mappingTextUrl record,
-- so the measure explainer can print "read from the enrolled text" with a link a
-- reader can open. Generated by scripts/vr-utah-ingest.mjs --sql from
-- db/vr-utah-vote-seed.json and db/vr-utah-vote-seed-2024GS.json (which this change
-- also regenerated), then reduced to the five new bills by hand: every other bill
-- in those seeds is already in an applied migration and re-emitting it would be
-- noise. Nothing here rewrites an existing row.
--
-- WHAT IT DOES NOT DO. It does not touch Direction Match, weights on any existing
-- mapping, or any other key's rows. tobacco_nicotine gets NO rows here on purpose:
-- both of its instruments (2024GS S.B. 61, 2025GS S.B. 186) are committee-only,
-- their curator mappings are in db/vr-utah-committee-bills-*.json, and the committee
-- pipeline needs the minutes bucket that scripts/vr-utah-committee-ingest.mjs
-- --bucket produces. Same for 2025GS H.B. 528 under sound_money and 2024GS H.B. 562
-- under dev_district_finance. Those four land in the committee wave's own pass, not
-- here, because attributing a committee vote without the minutes roster would mean
-- guessing who was in the room.
--
-- IDEMPOTENT. Every measure, mapping, roll call and member vote is guarded
-- (IF m_id IS NULL / IF NOT EXISTS / ON CONFLICT DO NOTHING), so a re-run is a
-- no-op. The two partial unique indexes the state record depends on were created by
-- 20260930000000_vr_utah_state_dedupe_indexes and are not repeated.
-- ─────────────────────────────────────────────────────────────────────────────

-- ── H.B. 67 — Precious Metals Investment and Administration Amendments  (2025GS/HB0067) ─────────────────────────
DO $$
DECLARE m_id integer; rc_id integer;
BEGIN
  SELECT id INTO m_id FROM vr_measures
   WHERE number = 'H.B. 67' AND chamber = 'utah house'
     AND external_ids->>'utahSession' = '2025GS' LIMIT 1;
  IF m_id IS NULL THEN
    INSERT INTO vr_measures (measure_type, congress, chamber, number, title,
      short_title, summary, status, source_url, source_label, external_ids)
    VALUES ('bill', NULL, 'utah house', 'H.B. 67', 'Precious Metals Investment and Administration Amendments',
      'Precious Metals Investment and Administration Amendments', 'This bill allows the state treasurer to deduct administrative costs for investing in precious metals from earnings generated by the investments in certain funds.', 'enacted',
      'https://le.utah.gov/~2025/bills/static/HB0067.html', 'Utah State Legislature',
      jsonb_build_object('utahSession', '2025GS', 'utahBill', 'HB0067',
        'primeSponsor', 'Rep. Ivory, Ken', 'floorSponsor', 'Sen. Stratton, Keven J.',
        'mappingReadFrom', 'enrolled', 'mappingTextUrl', 'https://le.utah.gov/Session/2025/bills/enrolled/HB0067.xml'))
    RETURNING id INTO m_id;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM vr_measure_issues
                  WHERE measure_id = m_id AND issue_key = 'sound_money') THEN
    INSERT INTO vr_measure_issues (measure_id, issue_key, weight, is_primary,
      support_meaning, rationale, source_url)
    VALUES (m_id, 'sound_money', 40, true,
      'yea_supports', 'Enrolled text lets the state treasurer deduct the administrative costs of investing in precious metals from the earnings those investments generate in certain funds. Administering the state''s precious-metals holdings is the bill''s only subject: it gives the investment authority the legislature granted the treasurer in 2024 a cost-recovery mechanism of its own, so a yea keeps that program operable. Weighted well below the bills that decide whether to hold metal at all, because this one decides only how the holding pays for itself.', 'https://le.utah.gov/Session/2025/bills/enrolled/HB0067.xml');
  END IF;
  SELECT id INTO rc_id FROM vr_rollcalls WHERE chamber = 'utah senate'
     AND congress IS NULL AND session = 2025
     AND roll_number = 1528 LIMIT 1;
  IF rc_id IS NULL THEN
    INSERT INTO vr_rollcalls (measure_id, chamber, congress, session, roll_number,
      vote_date, question, action_type, result, totals, source_url, source_label)
    VALUES (m_id, 'utah senate', NULL, 2025, 1528,
      '2025-03-03T15:18:00-07:00'::timestamptz, 'On passage, third reading', 'passage', 'passed',
      '{"yea":19,"nay":6,"notVoting":4}'::jsonb, 'https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2025GS&voteid=1528&house=S', 'Utah State Legislature · Utah Senate roll call')
    RETURNING id INTO rc_id;
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc_id, 'sadams', 'yea'),
    (rc_id, 'heidi_balderree', 'yea'),
    (rc_id, 'lescamilla', 'yea'),
    (rc_id, 'kgrover', 'yea'),
    (rc_id, 'harper_s16', 'yea'),
    (rc_id, 'dhinkins', 'yea'),
    (rc_id, 'kwan_s12', 'yea'),
    (rc_id, 'mccay_s11', 'yea'),
    (rc_id, 'amillner', 'yea'),
    (rc_id, 'cmusselman', 'yea'),
    (rc_id, 'dowens_st', 'yea'),
    (rc_id, 'stephanie_pitcher', 'yea'),
    (rc_id, 'ssandall', 'yea'),
    (rc_id, 'jstevenson', 'yea'),
    (rc_id, 'kstratton', 'yea'),
    (rc_id, 'daniel_thatcher', 'yea'),
    (rc_id, 'tweiler', 'yea'),
    (rc_id, 'cwilson', 'yea'),
    (rc_id, 'rwinterton', 'yea'),
    (rc_id, 'blouin_s13', 'nay'),
    (rc_id, 'dipson', 'nay'),
    (rc_id, 'john_johnson', 'nay'),
    (rc_id, 'jennifer_plumb', 'nay'),
    (rc_id, 'kathleen_riebe', 'nay'),
    (rc_id, 'evickers', 'nay'),
    (rc_id, 'brammer_s21', 'not_voting'),
    (rc_id, 'kcullimore', 'not_voting'),
    (rc_id, 'lincoln_fillmore', 'not_voting'),
    (rc_id, 'mckell_s25', 'not_voting')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;
END $$;
--> statement-breakpoint

-- ── S.B. 26 — Housing and Transit Reinvestment Zone Amendments  (2025GS/SB0026) ─────────────────────────
DO $$
DECLARE m_id integer; rc_id integer;
BEGIN
  SELECT id INTO m_id FROM vr_measures
   WHERE number = 'S.B. 26' AND chamber = 'utah senate'
     AND external_ids->>'utahSession' = '2025GS' LIMIT 1;
  IF m_id IS NULL THEN
    INSERT INTO vr_measures (measure_type, congress, chamber, number, title,
      short_title, summary, status, source_url, source_label, external_ids)
    VALUES ('bill', NULL, 'utah senate', 'S.B. 26', 'Housing and Transit Reinvestment Zone Amendments',
      'Housing and Transit Reinvestment Zone Amendments', 'This bill amends provisions relating to the Housing and Transit Reinvestment Zone Act.', 'enacted',
      'https://le.utah.gov/~2025/bills/static/SB0026.html', 'Utah State Legislature',
      jsonb_build_object('utahSession', '2025GS', 'utahBill', 'SB0026',
        'primeSponsor', 'Sen. Harper, Wayne A.', 'floorSponsor', 'Rep. Dunnigan, James A.',
        'mappingReadFrom', 'enrolled', 'mappingTextUrl', 'https://le.utah.gov/Session/2025/bills/enrolled/SB0026.xml'))
    RETURNING id INTO m_id;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM vr_measure_issues
                  WHERE measure_id = m_id AND issue_key = 'dev_district_finance') THEN
    INSERT INTO vr_measure_issues (measure_id, issue_key, weight, is_primary,
      support_meaning, rationale, source_url)
    VALUES (m_id, 'dev_district_finance', 60, true,
      'yea_supports', 'Enrolled text creates a process to propose a convention center reinvestment zone in a county of the first class that may capture state and certain local sales and use tax increment, may capture property tax increment, and may distribute funds to enable bonding; it also opens certain sales and use tax revenue and the Hotel Impact Mitigation Fund to convention center revitalization. The mechanism the bill adds is a tax-capture district, so a yea is a vote to create one. The bill''s housing provisions are deliberately left unmapped: it moves the affordability threshold to county median gross income and loosens the bedroom-mix requirement in the same text, so no housing key has one direction here.', 'https://le.utah.gov/Session/2025/bills/enrolled/SB0026.xml');
  END IF;
  SELECT id INTO rc_id FROM vr_rollcalls WHERE chamber = 'utah senate'
     AND congress IS NULL AND session = 2025
     AND roll_number = 2029 LIMIT 1;
  IF rc_id IS NULL THEN
    INSERT INTO vr_rollcalls (measure_id, chamber, congress, session, roll_number,
      vote_date, question, action_type, result, totals, source_url, source_label)
    VALUES (m_id, 'utah senate', NULL, 2025, 2029,
      '2025-03-07T11:54:00-07:00'::timestamptz, 'On concurrence in amendments', 'passage', 'passed',
      '{"yea":21,"nay":5,"notVoting":3}'::jsonb, 'https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2025GS&voteid=2029&house=S', 'Utah State Legislature · Utah Senate roll call')
    RETURNING id INTO rc_id;
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc_id, 'sadams', 'yea'),
    (rc_id, 'blouin_s13', 'yea'),
    (rc_id, 'kcullimore', 'yea'),
    (rc_id, 'lescamilla', 'yea'),
    (rc_id, 'kgrover', 'yea'),
    (rc_id, 'harper_s16', 'yea'),
    (rc_id, 'dhinkins', 'yea'),
    (rc_id, 'dipson', 'yea'),
    (rc_id, 'kwan_s12', 'yea'),
    (rc_id, 'mccay_s11', 'yea'),
    (rc_id, 'mckell_s25', 'yea'),
    (rc_id, 'amillner', 'yea'),
    (rc_id, 'cmusselman', 'yea'),
    (rc_id, 'stephanie_pitcher', 'yea'),
    (rc_id, 'jennifer_plumb', 'yea'),
    (rc_id, 'ssandall', 'yea'),
    (rc_id, 'jstevenson', 'yea'),
    (rc_id, 'evickers', 'yea'),
    (rc_id, 'tweiler', 'yea'),
    (rc_id, 'cwilson', 'yea'),
    (rc_id, 'rwinterton', 'yea'),
    (rc_id, 'heidi_balderree', 'nay'),
    (rc_id, 'brammer_s21', 'nay'),
    (rc_id, 'lincoln_fillmore', 'nay'),
    (rc_id, 'john_johnson', 'nay'),
    (rc_id, 'kathleen_riebe', 'nay'),
    (rc_id, 'dowens_st', 'not_voting'),
    (rc_id, 'kstratton', 'not_voting'),
    (rc_id, 'daniel_thatcher', 'not_voting')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;
END $$;
--> statement-breakpoint

-- ── S.B. 316 — Military Installation Development Authority and Other Development Zone Amendments  (2025GS/SB0316) ─────────────────────────
DO $$
DECLARE m_id integer; rc_id integer;
BEGIN
  SELECT id INTO m_id FROM vr_measures
   WHERE number = 'S.B. 316' AND chamber = 'utah senate'
     AND external_ids->>'utahSession' = '2025GS' LIMIT 1;
  IF m_id IS NULL THEN
    INSERT INTO vr_measures (measure_type, congress, chamber, number, title,
      short_title, summary, status, source_url, source_label, external_ids)
    VALUES ('bill', NULL, 'utah senate', 'S.B. 316', 'Military Installation Development Authority and Other Development Zone Amendments',
      'Military Installation Development Authority and Other Development Zone Amendments', 'This bill deals with the Military Installation Development Authority and the distribution of certain sales tax revenues related to certain authorities and zones.', 'enacted',
      'https://le.utah.gov/~2025/bills/static/SB0316.html', 'Utah State Legislature',
      jsonb_build_object('utahSession', '2025GS', 'utahBill', 'SB0316',
        'primeSponsor', 'Sen. Stevenson, Jerry W.', 'floorSponsor', 'Rep. Peterson, Val L.',
        'mappingReadFrom', 'enrolled', 'mappingTextUrl', 'https://le.utah.gov/Session/2025/bills/enrolled/SB0316.xml'))
    RETURNING id INTO m_id;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM vr_measure_issues
                  WHERE measure_id = m_id AND issue_key = 'dev_district_finance') THEN
    INSERT INTO vr_measure_issues (measure_id, issue_key, weight, is_primary,
      support_meaning, rationale, source_url)
    VALUES (m_id, 'dev_district_finance', 70, true,
      'yea_supports', 'Enrolled text authorizes an eligible basic special district to use tax revenue, sets a formula for the State Tax Commission to distribute local revenue from the sale of construction materials inside a qualified development zone, provides for distributing revenue generated by a Schedule J sale, lets the Military Installation Development Authority agree with the state to spend revenue generated from a project area outside that project area where the project area sits on state or armory board land, and lets a public infrastructure district the authority created be a subsidiary of it. Every operative provision widens what a development zone authority may capture and where it may spend it, so a yea is a vote to widen it.', 'https://le.utah.gov/Session/2025/bills/enrolled/SB0316.xml');
  END IF;
  SELECT id INTO rc_id FROM vr_rollcalls WHERE chamber = 'utah house'
     AND congress IS NULL AND session = 2025
     AND roll_number = 1601 LIMIT 1;
  IF rc_id IS NULL THEN
    INSERT INTO vr_rollcalls (measure_id, chamber, congress, session, roll_number,
      vote_date, question, action_type, result, totals, source_url, source_label)
    VALUES (m_id, 'utah house', NULL, 2025, 1601,
      '2025-03-07T21:48:00-07:00'::timestamptz, 'On passage, third reading', 'passage', 'passed',
      '{"yea":38,"nay":27,"notVoting":10}'::jsonb, 'https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2025GS&voteid=1601&house=H', 'Utah State Legislature · Utah House roll call')
    RETURNING id INTO rc_id;
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc_id, 'nelson_abbott', 'yea'),
    (rc_id, 'cheryl_acton', 'yea'),
    (rc_id, 'carl_albrecht', 'yea'),
    (rc_id, 'mballard', 'yea'),
    (rc_id, 'stewart_e_barlow', 'yea'),
    (rc_id, 'bolinder_h68', 'yea'),
    (rc_id, 'walt_brooks', 'yea'),
    (rc_id, 'jefferson_burton', 'yea'),
    (rc_id, 'chew_h68', 'yea'),
    (rc_id, 'kay_christofferson', 'yea'),
    (rc_id, 'paul_a_cutler', 'yea'),
    (rc_id, 'jennifer_dailey_provost', 'yea'),
    (rc_id, 'defay_h15', 'yea'),
    (rc_id, 'eliason_h45', 'yea'),
    (rc_id, 'gwynn_h6', 'yea'),
    (rc_id, 'sahara_hayes', 'yea'),
    (rc_id, 'ivory_h39', 'yea'),
    (rc_id, 'anthony_loubet', 'yea'),
    (rc_id, 'matt_macpherson', 'yea'),
    (rc_id, 'cory_maloy_h52', 'yea'),
    (rc_id, 'verona_mauga', 'yea'),
    (rc_id, 'carol_spackman_moss', 'yea'),
    (rc_id, 'hoang_nguyen', 'yea'),
    (rc_id, 'clinton_okerlund', 'yea'),
    (rc_id, 'thomas_peterson', 'yea'),
    (rc_id, 'valpeterson_h56', 'yea'),
    (rc_id, 'candice_pierucci', 'yea'),
    (rc_id, 'calvin_roberts', 'yea'),
    (rc_id, 'jake_sawyer', 'yea'),
    (rc_id, 'mschultz', 'yea'),
    (rc_id, 'david_shallenberger', 'yea'),
    (rc_id, 'rshipp', 'yea'),
    (rc_id, 'andrew_stoddard', 'yea'),
    (rc_id, 'teuscher_h44', 'yea'),
    (rc_id, 'rward', 'yea'),
    (rc_id, 'christine_watkins', 'yea'),
    (rc_id, 'whyte_h63', 'yea'),
    (rc_id, 'ryan_d_wilcox', 'yea'),
    (rc_id, 'auxier_h4', 'nay'),
    (rc_id, 'gay_lynn_bennion', 'nay'),
    (rc_id, 'kristen_chevrier', 'nay'),
    (rc_id, 'rosalba_dominguez', 'nay'),
    (rc_id, 'joseph_elison', 'nay'),
    (rc_id, 'doug_fiefia', 'nay'),
    (rc_id, 'fitisemanu_h30', 'nay'),
    (rc_id, 'gricius_h50', 'nay'),
    (rc_id, 'hall_h11', 'nay'),
    (rc_id, 'hollins_h24', 'nay'),
    (rc_id, 'colin_w_jack', 'nay'),
    (rc_id, 'koford_h10', 'nay'),
    (rc_id, 'jason_b_kyle', 'nay'),
    (rc_id, 'tlee', 'nay'),
    (rc_id, 'grant_miller', 'nay'),
    (rc_id, 'tracy_miller', 'nay'),
    (rc_id, 'logan_monson', 'nay'),
    (rc_id, 'doug_owens', 'nay'),
    (rc_id, 'nicholeen_p_peck', 'nay'),
    (rc_id, 'mike_petersen', 'nay'),
    (rc_id, 'karen_m_peterson', 'nay'),
    (rc_id, 'shelley_h66', 'nay'),
    (rc_id, 'lisa_shepherd', 'nay'),
    (rc_id, 'mark_strong', 'nay'),
    (rc_id, 'nthurston', 'nay'),
    (rc_id, 'r_neil_walter', 'nay'),
    (rc_id, 'doug_welton', 'nay'),
    (rc_id, 'tyler_clancy', 'not_voting'),
    (rc_id, 'james_dunnigan', 'not_voting'),
    (rc_id, 'jon_hawkins', 'not_voting'),
    (rc_id, 'kohler_h59', 'not_voting'),
    (rc_id, 'lisonbee_h14', 'not_voting'),
    (rc_id, 'ashlee_matthews', 'not_voting'),
    (rc_id, 'jefferson_moss', 'not_voting'),
    (rc_id, 'aromero', 'not_voting'),
    (rc_id, 'snider_h5', 'not_voting'),
    (rc_id, 'jason_thompson', 'not_voting')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;
  SELECT id INTO rc_id FROM vr_rollcalls WHERE chamber = 'utah senate'
     AND congress IS NULL AND session = 2025
     AND roll_number = 2235 LIMIT 1;
  IF rc_id IS NULL THEN
    INSERT INTO vr_rollcalls (measure_id, chamber, congress, session, roll_number,
      vote_date, question, action_type, result, totals, source_url, source_label)
    VALUES (m_id, 'utah senate', NULL, 2025, 2235,
      '2025-03-07T23:33:00-07:00'::timestamptz, 'On concurrence in amendments', 'passage', 'passed',
      '{"yea":22,"nay":5,"notVoting":2}'::jsonb, 'https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2025GS&voteid=2235&house=S', 'Utah State Legislature · Utah Senate roll call')
    RETURNING id INTO rc_id;
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc_id, 'sadams', 'yea'),
    (rc_id, 'kcullimore', 'yea'),
    (rc_id, 'lescamilla', 'yea'),
    (rc_id, 'lincoln_fillmore', 'yea'),
    (rc_id, 'kgrover', 'yea'),
    (rc_id, 'dhinkins', 'yea'),
    (rc_id, 'dipson', 'yea'),
    (rc_id, 'john_johnson', 'yea'),
    (rc_id, 'kwan_s12', 'yea'),
    (rc_id, 'mccay_s11', 'yea'),
    (rc_id, 'mckell_s25', 'yea'),
    (rc_id, 'amillner', 'yea'),
    (rc_id, 'cmusselman', 'yea'),
    (rc_id, 'dowens_st', 'yea'),
    (rc_id, 'stephanie_pitcher', 'yea'),
    (rc_id, 'jennifer_plumb', 'yea'),
    (rc_id, 'ssandall', 'yea'),
    (rc_id, 'jstevenson', 'yea'),
    (rc_id, 'evickers', 'yea'),
    (rc_id, 'tweiler', 'yea'),
    (rc_id, 'cwilson', 'yea'),
    (rc_id, 'rwinterton', 'yea'),
    (rc_id, 'heidi_balderree', 'nay'),
    (rc_id, 'blouin_s13', 'nay'),
    (rc_id, 'brammer_s21', 'nay'),
    (rc_id, 'harper_s16', 'nay'),
    (rc_id, 'kathleen_riebe', 'nay'),
    (rc_id, 'kstratton', 'not_voting'),
    (rc_id, 'daniel_thatcher', 'not_voting')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;
END $$;
--> statement-breakpoint

-- ── S.B. 336 — Utah Fairpark Area Investment and Restoration District Modifications  (2025GS/SB0336) ─────────────────────────
DO $$
DECLARE m_id integer; rc_id integer;
BEGIN
  SELECT id INTO m_id FROM vr_measures
   WHERE number = 'S.B. 336' AND chamber = 'utah senate'
     AND external_ids->>'utahSession' = '2025GS' LIMIT 1;
  IF m_id IS NULL THEN
    INSERT INTO vr_measures (measure_type, congress, chamber, number, title,
      short_title, summary, status, source_url, source_label, external_ids)
    VALUES ('bill', NULL, 'utah senate', 'S.B. 336', 'Utah Fairpark Area Investment and Restoration District Modifications',
      'Utah Fairpark Area Investment and Restoration District Modifications', 'This bill modifies provisions relating to the Utah Fairpark Area Investment and Restoration District.', 'enacted',
      'https://le.utah.gov/~2025/bills/static/SB0336.html', 'Utah State Legislature',
      jsonb_build_object('utahSession', '2025GS', 'utahBill', 'SB0336',
        'primeSponsor', 'Sen. Sandall, Scott D.', 'floorSponsor', 'Rep. Wilcox, Ryan D.',
        'mappingReadFrom', 'enrolled', 'mappingTextUrl', 'https://le.utah.gov/Session/2025/bills/enrolled/SB0336.xml'))
    RETURNING id INTO m_id;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM vr_measure_issues
                  WHERE measure_id = m_id AND issue_key = 'dev_district_finance') THEN
    INSERT INTO vr_measure_issues (measure_id, issue_key, weight, is_primary,
      support_meaning, rationale, source_url)
    VALUES (m_id, 'dev_district_finance', 75, true,
      'yea_supports', 'Enrolled text modifies the taxing authority and the land use authority of the Utah Fairpark Area Investment and Restoration District, broadens the permissible uses of a fairpark land lease, enables the public infrastructure district the fairpark district created to levy property taxes and to spend bond proceeds on public utility infrastructure and specified development, provides funding for the district, and designates the district a qualifying jurisdiction that may receive tax information from the State Tax Commission. The financing power of one development district is the bill''s whole subject, and a yea enlarges it.', 'https://le.utah.gov/Session/2025/bills/enrolled/SB0336.xml');
  END IF;
  SELECT id INTO rc_id FROM vr_rollcalls WHERE chamber = 'utah house'
     AND congress IS NULL AND session = 2025
     AND roll_number = 1443 LIMIT 1;
  IF rc_id IS NULL THEN
    INSERT INTO vr_rollcalls (measure_id, chamber, congress, session, roll_number,
      vote_date, question, action_type, result, totals, source_url, source_label)
    VALUES (m_id, 'utah house', NULL, 2025, 1443,
      '2025-03-07T10:44:00-07:00'::timestamptz, 'On passage, third reading', 'passage', 'passed',
      '{"yea":54,"nay":16,"notVoting":5}'::jsonb, 'https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2025GS&voteid=1443&house=H', 'Utah State Legislature · Utah House roll call')
    RETURNING id INTO rc_id;
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc_id, 'nelson_abbott', 'yea'),
    (rc_id, 'cheryl_acton', 'yea'),
    (rc_id, 'carl_albrecht', 'yea'),
    (rc_id, 'mballard', 'yea'),
    (rc_id, 'stewart_e_barlow', 'yea'),
    (rc_id, 'gay_lynn_bennion', 'yea'),
    (rc_id, 'bolinder_h68', 'yea'),
    (rc_id, 'walt_brooks', 'yea'),
    (rc_id, 'jefferson_burton', 'yea'),
    (rc_id, 'kristen_chevrier', 'yea'),
    (rc_id, 'kay_christofferson', 'yea'),
    (rc_id, 'tyler_clancy', 'yea'),
    (rc_id, 'paul_a_cutler', 'yea'),
    (rc_id, 'jennifer_dailey_provost', 'yea'),
    (rc_id, 'defay_h15', 'yea'),
    (rc_id, 'rosalba_dominguez', 'yea'),
    (rc_id, 'james_dunnigan', 'yea'),
    (rc_id, 'eliason_h45', 'yea'),
    (rc_id, 'joseph_elison', 'yea'),
    (rc_id, 'doug_fiefia', 'yea'),
    (rc_id, 'fitisemanu_h30', 'yea'),
    (rc_id, 'gricius_h50', 'yea'),
    (rc_id, 'gwynn_h6', 'yea'),
    (rc_id, 'jon_hawkins', 'yea'),
    (rc_id, 'sahara_hayes', 'yea'),
    (rc_id, 'hollins_h24', 'yea'),
    (rc_id, 'colin_w_jack', 'yea'),
    (rc_id, 'anthony_loubet', 'yea'),
    (rc_id, 'cory_maloy_h52', 'yea'),
    (rc_id, 'ashlee_matthews', 'yea'),
    (rc_id, 'verona_mauga', 'yea'),
    (rc_id, 'grant_miller', 'yea'),
    (rc_id, 'tracy_miller', 'yea'),
    (rc_id, 'carol_spackman_moss', 'yea'),
    (rc_id, 'jefferson_moss', 'yea'),
    (rc_id, 'hoang_nguyen', 'yea'),
    (rc_id, 'clinton_okerlund', 'yea'),
    (rc_id, 'doug_owens', 'yea'),
    (rc_id, 'karen_m_peterson', 'yea'),
    (rc_id, 'thomas_peterson', 'yea'),
    (rc_id, 'valpeterson_h56', 'yea'),
    (rc_id, 'candice_pierucci', 'yea'),
    (rc_id, 'calvin_roberts', 'yea'),
    (rc_id, 'aromero', 'yea'),
    (rc_id, 'mschultz', 'yea'),
    (rc_id, 'david_shallenberger', 'yea'),
    (rc_id, 'andrew_stoddard', 'yea'),
    (rc_id, 'teuscher_h44', 'yea'),
    (rc_id, 'r_neil_walter', 'yea'),
    (rc_id, 'rward', 'yea'),
    (rc_id, 'christine_watkins', 'yea'),
    (rc_id, 'doug_welton', 'yea'),
    (rc_id, 'whyte_h63', 'yea'),
    (rc_id, 'ryan_d_wilcox', 'yea'),
    (rc_id, 'auxier_h4', 'nay'),
    (rc_id, 'chew_h68', 'nay'),
    (rc_id, 'ivory_h39', 'nay'),
    (rc_id, 'koford_h10', 'nay'),
    (rc_id, 'kohler_h59', 'nay'),
    (rc_id, 'jason_b_kyle', 'nay'),
    (rc_id, 'tlee', 'nay'),
    (rc_id, 'logan_monson', 'nay'),
    (rc_id, 'nicholeen_p_peck', 'nay'),
    (rc_id, 'mike_petersen', 'nay'),
    (rc_id, 'jake_sawyer', 'nay'),
    (rc_id, 'shelley_h66', 'nay'),
    (rc_id, 'lisa_shepherd', 'nay'),
    (rc_id, 'mark_strong', 'nay'),
    (rc_id, 'jason_thompson', 'nay'),
    (rc_id, 'nthurston', 'nay'),
    (rc_id, 'hall_h11', 'not_voting'),
    (rc_id, 'lisonbee_h14', 'not_voting'),
    (rc_id, 'matt_macpherson', 'not_voting'),
    (rc_id, 'rshipp', 'not_voting'),
    (rc_id, 'snider_h5', 'not_voting')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;
  SELECT id INTO rc_id FROM vr_rollcalls WHERE chamber = 'utah senate'
     AND congress IS NULL AND session = 2025
     AND roll_number = 2034 LIMIT 1;
  IF rc_id IS NULL THEN
    INSERT INTO vr_rollcalls (measure_id, chamber, congress, session, roll_number,
      vote_date, question, action_type, result, totals, source_url, source_label)
    VALUES (m_id, 'utah senate', NULL, 2025, 2034,
      '2025-03-07T12:00:00-07:00'::timestamptz, 'On concurrence in amendments', 'passage', 'passed',
      '{"yea":22,"nay":5,"notVoting":2}'::jsonb, 'https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2025GS&voteid=2034&house=S', 'Utah State Legislature · Utah Senate roll call')
    RETURNING id INTO rc_id;
  END IF;
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc_id, 'sadams', 'yea'),
    (rc_id, 'kcullimore', 'yea'),
    (rc_id, 'lescamilla', 'yea'),
    (rc_id, 'lincoln_fillmore', 'yea'),
    (rc_id, 'kgrover', 'yea'),
    (rc_id, 'harper_s16', 'yea'),
    (rc_id, 'dhinkins', 'yea'),
    (rc_id, 'dipson', 'yea'),
    (rc_id, 'kwan_s12', 'yea'),
    (rc_id, 'mccay_s11', 'yea'),
    (rc_id, 'mckell_s25', 'yea'),
    (rc_id, 'amillner', 'yea'),
    (rc_id, 'cmusselman', 'yea'),
    (rc_id, 'stephanie_pitcher', 'yea'),
    (rc_id, 'jennifer_plumb', 'yea'),
    (rc_id, 'kathleen_riebe', 'yea'),
    (rc_id, 'ssandall', 'yea'),
    (rc_id, 'jstevenson', 'yea'),
    (rc_id, 'evickers', 'yea'),
    (rc_id, 'tweiler', 'yea'),
    (rc_id, 'cwilson', 'yea'),
    (rc_id, 'rwinterton', 'yea'),
    (rc_id, 'heidi_balderree', 'nay'),
    (rc_id, 'blouin_s13', 'nay'),
    (rc_id, 'brammer_s21', 'nay'),
    (rc_id, 'john_johnson', 'nay'),
    (rc_id, 'kstratton', 'nay'),
    (rc_id, 'dowens_st', 'not_voting'),
    (rc_id, 'daniel_thatcher', 'not_voting')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;
END $$;
--> statement-breakpoint

-- ── H.B. 348 — Precious Metals Amendments  (2024GS/HB0348) ─────────────────────────
DO $$
DECLARE m_id integer; rc_id integer;
BEGIN
  SELECT id INTO m_id FROM vr_measures
   WHERE number = 'H.B. 348' AND chamber = 'utah house'
     AND external_ids->>'utahSession' = '2024GS' LIMIT 1;
  IF m_id IS NULL THEN
    INSERT INTO vr_measures (measure_type, congress, chamber, number, title,
      short_title, summary, status, source_url, source_label, external_ids)
    VALUES ('bill', NULL, 'utah house', 'H.B. 348', 'Precious Metals Amendments',
      'Precious Metals Amendments', 'This bill modifies provisions related to precious metals.', 'enacted',
      'https://le.utah.gov/~2024/bills/static/HB0348.html', 'Utah State Legislature',
      jsonb_build_object('utahSession', '2024GS', 'utahBill', 'HB0348',
        'primeSponsor', 'Rep. Ivory, Ken', 'floorSponsor', 'Sen. Cullimore, Kirk A.',
        'mappingReadFrom', 'enrolled', 'mappingTextUrl', 'https://le.utah.gov/~2024/bills/xmlEnrolled/HB0348.xml'))
    RETURNING id INTO m_id;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM vr_measure_issues
                  WHERE measure_id = m_id AND issue_key = 'sound_money') THEN
    INSERT INTO vr_measure_issues (measure_id, issue_key, weight, is_primary,
      support_meaning, rationale, source_url)
    VALUES (m_id, 'sound_money', 80, true,
      'yea_supports', 'Enrolled text exempts a portion of the funds in certain budget reserve accounts from the State Money Management Act, authorizes the state treasurer to invest a portion of those reserve funds in precious metals, and requires the treasurer to conduct a precious-metals study. Taking part of the state''s reserves out of the ordinary money-management rules in order to buy bullion is the whole bill, so a yea is a vote for the state holding metal.', 'https://le.utah.gov/~2024/bills/xmlEnrolled/HB0348.xml');
  END IF;
  SELECT id INTO rc_id FROM vr_rollcalls WHERE chamber = 'utah house'
     AND congress IS NULL AND session = 2024
     AND roll_number = 895 LIMIT 1;
  IF rc_id IS NULL THEN
    INSERT INTO vr_rollcalls (measure_id, chamber, congress, session, roll_number,
      vote_date, question, action_type, result, totals, source_url, source_label)
    VALUES (m_id, 'utah house', NULL, 2024, 895,
      '2024-02-22T20:41:00-07:00'::timestamptz, 'On passage, third reading', 'passage', 'passed',
      '{"yea":52,"nay":18,"notVoting":5}'::jsonb, 'https://le.utah.gov/DynaBill/svotes.jsp?sessionid=2024GS&voteid=895&house=H', 'Utah State Legislature · Utah House roll call')
    RETURNING id INTO rc_id;
  END IF;
  -- 16 of the 75 members recorded on this roll call are not on the PolitiDex roster; their
  -- votes are not written. Names are listed once at the head of this file.
  INSERT INTO vr_member_votes (rollcall_id, politician_id, position) VALUES
    (rc_id, 'cheryl_acton', 'yea'),
    (rc_id, 'carl_albrecht', 'yea'),
    (rc_id, 'stewart_e_barlow', 'yea'),
    (rc_id, 'bolinder_h68', 'yea'),
    (rc_id, 'brammer_s21', 'yea'),
    (rc_id, 'walt_brooks', 'yea'),
    (rc_id, 'jefferson_burton', 'yea'),
    (rc_id, 'chew_h68', 'yea'),
    (rc_id, 'kay_christofferson', 'yea'),
    (rc_id, 'tyler_clancy', 'yea'),
    (rc_id, 'paul_a_cutler', 'yea'),
    (rc_id, 'defay_h15', 'yea'),
    (rc_id, 'eliason_h45', 'yea'),
    (rc_id, 'gricius_h50', 'yea'),
    (rc_id, 'gwynn_h6', 'yea'),
    (rc_id, 'hall_h11', 'yea'),
    (rc_id, 'jon_hawkins', 'yea'),
    (rc_id, 'hollins_h24', 'yea'),
    (rc_id, 'ivory_h39', 'yea'),
    (rc_id, 'colin_w_jack', 'yea'),
    (rc_id, 'kohler_h59', 'yea'),
    (rc_id, 'jason_b_kyle', 'yea'),
    (rc_id, 'tlee', 'yea'),
    (rc_id, 'lisonbee_h14', 'yea'),
    (rc_id, 'anthony_loubet', 'yea'),
    (rc_id, 'matt_macpherson', 'yea'),
    (rc_id, 'cory_maloy_h52', 'yea'),
    (rc_id, 'mike_petersen', 'yea'),
    (rc_id, 'karen_m_peterson', 'yea'),
    (rc_id, 'thomas_peterson', 'yea'),
    (rc_id, 'valpeterson_h56', 'yea'),
    (rc_id, 'candice_pierucci', 'yea'),
    (rc_id, 'mschultz', 'yea'),
    (rc_id, 'snider_h5', 'yea'),
    (rc_id, 'kstratton', 'yea'),
    (rc_id, 'mark_strong', 'yea'),
    (rc_id, 'teuscher_h44', 'yea'),
    (rc_id, 'nthurston', 'yea'),
    (rc_id, 'rward', 'yea'),
    (rc_id, 'christine_watkins', 'yea'),
    (rc_id, 'doug_welton', 'yea'),
    (rc_id, 'whyte_h63', 'yea'),
    (rc_id, 'ryan_d_wilcox', 'yea'),
    (rc_id, 'nelson_abbott', 'nay'),
    (rc_id, 'mballard', 'nay'),
    (rc_id, 'gay_lynn_bennion', 'nay'),
    (rc_id, 'jennifer_dailey_provost', 'nay'),
    (rc_id, 'james_dunnigan', 'nay'),
    (rc_id, 'joseph_elison', 'nay'),
    (rc_id, 'sahara_hayes', 'nay'),
    (rc_id, 'ashlee_matthews', 'nay'),
    (rc_id, 'carol_spackman_moss', 'nay'),
    (rc_id, 'doug_owens', 'nay'),
    (rc_id, 'aromero', 'nay'),
    (rc_id, 'andrew_stoddard', 'nay'),
    (rc_id, 'r_neil_walter', 'nay'),
    (rc_id, 'jefferson_moss', 'not_voting'),
    (rc_id, 'cmusselman', 'not_voting'),
    (rc_id, 'rshipp', 'not_voting')
  ON CONFLICT (rollcall_id, politician_id) DO NOTHING;
END $$;
--> statement-breakpoint

-- ── Verification ─────────────────────────────────────────────────────────────
-- Every write above is sentinelled, which makes the whole file a legal no-op: on a
-- re-run that is the point, and on the first run it would be a silent failure. So
-- the counts are asserted. They are scoped to the five bills and the three new
-- keys, not to a session, because two applied migrations already own most of each
-- session's rows and this file must not assert anything about theirs.
--
-- Note for anyone re-running the archive: 20261002000000_vr_utah_2024gs_state_record
-- asserts `n_measures <> 28` for 2024GS, and this file makes that session's count
-- 29. That migration is applied and will not run again; if it ever is replayed on a
-- fresh database, replay it BEFORE this one.
DO $$
DECLARE n_measures integer; n_rolls integer; n_votes integer; n_issues integer; n_orphan integer;
BEGIN
  SELECT count(*) INTO n_measures FROM vr_measures
   WHERE external_ids->>'utahBill' IN ('HB0067', 'SB0026', 'SB0316', 'SB0336', 'HB0348')
     AND external_ids->>'utahSession' IN ('2025GS', '2024GS');
  SELECT count(*) INTO n_issues FROM vr_measure_issues
   WHERE issue_key IN ('sound_money', 'dev_district_finance', 'tobacco_nicotine');
  SELECT count(*) INTO n_rolls FROM vr_rollcalls r
    JOIN vr_measures m ON m.id = r.measure_id
   WHERE r.congress IS NULL
     AND m.external_ids->>'utahBill' IN ('HB0067', 'SB0026', 'SB0316', 'SB0336', 'HB0348')
     AND m.external_ids->>'utahSession' IN ('2025GS', '2024GS');
  SELECT count(*) INTO n_votes FROM vr_member_votes v
    JOIN vr_rollcalls r ON r.id = v.rollcall_id
    JOIN vr_measures m ON m.id = r.measure_id
   WHERE r.congress IS NULL
     AND m.external_ids->>'utahBill' IN ('HB0067', 'SB0026', 'SB0316', 'SB0336', 'HB0348')
     AND m.external_ids->>'utahSession' IN ('2025GS', '2024GS');
  SELECT count(*) INTO n_orphan FROM vr_member_votes v
    JOIN vr_rollcalls r ON r.id = v.rollcall_id
    JOIN vr_measures m ON m.id = r.measure_id
   WHERE r.congress IS NULL
     AND m.external_ids->>'utahBill' IN ('HB0067', 'SB0026', 'SB0316', 'SB0336', 'HB0348')
     AND m.external_ids->>'utahSession' IN ('2025GS', '2024GS')
     AND v.politician_id NOT IN ('amillner', 'andrew_stoddard', 'anthony_loubet', 'aromero', 'ashlee_matthews', 'auxier_h4', 'blouin_s13', 'bolinder_h68', 'brammer_s21', 'calvin_roberts', 'candice_pierucci', 'carl_albrecht', 'carol_spackman_moss', 'cheryl_acton', 'chew_h68', 'christine_watkins', 'clinton_okerlund', 'cmusselman', 'colin_w_jack', 'cory_maloy_h52', 'cwilson', 'daniel_thatcher', 'david_shallenberger', 'defay_h15', 'dhinkins', 'dipson', 'doug_fiefia', 'doug_owens', 'doug_welton', 'dowens_st', 'eliason_h45', 'evickers', 'fitisemanu_h30', 'gay_lynn_bennion', 'grant_miller', 'gricius_h50', 'gwynn_h6', 'hall_h11', 'harper_s16', 'heidi_balderree', 'hoang_nguyen', 'hollins_h24', 'ivory_h39', 'jake_sawyer', 'james_dunnigan', 'jason_b_kyle', 'jason_thompson', 'jefferson_burton', 'jefferson_moss', 'jennifer_dailey_provost', 'jennifer_plumb', 'john_johnson', 'jon_hawkins', 'joseph_elison', 'jstevenson', 'karen_m_peterson', 'kathleen_riebe', 'kay_christofferson', 'kcullimore', 'kgrover', 'koford_h10', 'kohler_h59', 'kristen_chevrier', 'kstratton', 'kwan_s12', 'lescamilla', 'lincoln_fillmore', 'lisa_shepherd', 'lisonbee_h14', 'logan_monson', 'mark_strong', 'matt_macpherson', 'mballard', 'mccay_s11', 'mckell_s25', 'mike_petersen', 'mschultz', 'nelson_abbott', 'nicholeen_p_peck', 'nthurston', 'paul_a_cutler', 'r_neil_walter', 'rosalba_dominguez', 'rshipp', 'rward', 'rwinterton', 'ryan_d_wilcox', 'sadams', 'sahara_hayes', 'shelley_h66', 'snider_h5', 'ssandall', 'stephanie_pitcher', 'stewart_e_barlow', 'teuscher_h44', 'thomas_peterson', 'tlee', 'tracy_miller', 'tweiler', 'tyler_clancy', 'valpeterson_h56', 'verona_mauga', 'walt_brooks', 'whyte_h63');
  RAISE NOTICE 'Vocab wave V1: % measures, % roll calls, % member votes, % issue mappings',
    n_measures, n_rolls, n_votes, n_issues;
  IF n_measures <> 5 THEN
    RAISE EXCEPTION 'Vocab wave V1: expected 5 newly homed measures, found %', n_measures;
  END IF;
  IF n_rolls <> 7 THEN
    RAISE EXCEPTION 'Vocab wave V1: expected 7 roll calls, found %', n_rolls;
  END IF;
  IF n_votes < 325 THEN
    RAISE EXCEPTION 'Vocab wave V1: expected at least 325 member votes, found % — the inserts did not land', n_votes;
  END IF;
  IF n_issues <> 5 THEN
    RAISE EXCEPTION 'Vocab wave V1: expected 5 mappings on the three new keys, found %', n_issues;
  END IF;
  IF n_orphan > 0 THEN
    RAISE EXCEPTION 'Vocab wave V1: % member vote(s) name a politician_id outside the reviewed member maps', n_orphan;
  END IF;
END $$;
