#!/usr/bin/env node
// ---------------------------------------------------------------------------
// PolitiDex — split the monolithic politician-stances.js into two chunks
// ---------------------------------------------------------------------------
// politician-stances.js shipped ~1.1 MB of curated stance data as a single
// eager download. It is pure data (window.ISSUE_STANCE_DATA — plain strings,
// no functions), so it can be split losslessly by partitioning the top-level
// politician keys and re-emitting each half as JSON that augments the SAME
// window.ISSUE_STANCE_DATA object.
//
//   • politician-stances-core.js — officials linked to the curated
//     accountability layer (window.ACCT_SPOTLIGHT). These are the people the
//     Say-vs-Do hero needs immediately and the ones most likely to be searched
//     or opened, so this chunk is precached in the service-worker app shell.
//   • politician-stances-ext.js  — the long-tail (mostly local) officials.
//     Loaded at low priority; kept fresh by the SW runtime cache.
//
// BOTH files are loaded with `defer`, so window.ISSUE_STANCE_DATA is fully
// populated by DOMContentLoaded exactly as it was with the single file — every
// existing consumer (alignment coverage, stance library, profiles) sees the
// complete dataset and nothing changes functionally. The win is a ~55% smaller
// eager/precached payload and a low-priority tail that no longer competes with
// render-critical bytes on first load.
//
//   node scripts/split-stances.mjs          # regenerate the two chunks
//
// Re-run this whenever politician-stances.js (or, historically, the source of
// truth) changes. It is deterministic and lossless — it verifies round-trip
// integrity before writing.
// ---------------------------------------------------------------------------
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SRC = path.join(ROOT, 'politician-stances.js');
const INDEX = path.join(ROOT, 'index.html');

function evalGlobal(code, pick) {
  const prev = globalThis.window;
  const window = globalThis.window = {};
  try {
    // eslint-disable-next-line no-eval
    (0, eval)(code);
    return pick(window);
  } finally {
    globalThis.window = prev;
  }
}

// 1) Load the full stance dataset.
const stanceData = evalGlobal(fs.readFileSync(SRC, 'utf8'), (w) => w.ISSUE_STANCE_DATA);
if (!stanceData || typeof stanceData !== 'object') {
  console.error('Could not read window.ISSUE_STANCE_DATA from', SRC);
  process.exit(1);
}

// 2) Determine the "notable" set from the curated accountability layer, which is
//    embedded in index.html as window.ACCT_SPOTLIGHT = window.ACCT_SPOTLIGHT || { ... };
//    Extract it line-wise (from the assignment to its `    };` terminator) and
//    eval the statement with a window shim — robust to braces/apostrophes that
//    appear inside the data's own strings and comments.
const html = fs.readFileSync(INDEX, 'utf8');
const lines = html.split('\n');
let acctPids = new Set();
let startLine = -1;
for (let i = 0; i < lines.length; i++) {
  if (lines[i].indexOf('window.ACCT_SPOTLIGHT = window.ACCT_SPOTLIGHT || {') !== -1) { startLine = i; break; }
}
if (startLine !== -1) {
  let endLine = -1;
  for (let i = startLine + 1; i < lines.length; i++) {
    if (lines[i] === '    };') { endLine = i; break; }
  }
  if (endLine !== -1) {
    const block = lines.slice(startLine, endLine + 1).join('\n');
    try {
      acctPids = new Set(Object.keys(evalGlobal(block, (w) => w.ACCT_SPOTLIGHT || {})));
    } catch (e) {
      console.warn('ACCT_SPOTLIGHT parse failed, falling back to a size-based split:', e.message);
    }
  }
}
if (!acctPids.size) {
  console.error('Refusing to split: could not resolve the accountability (core) set from index.html.');
  process.exit(1);
}

// 3) Partition.
const core = {}, ext = {};
for (const pid of Object.keys(stanceData)) {
  (acctPids.has(pid) ? core : ext)[pid] = stanceData[pid];
}

// 4) Integrity check (order-independent, JSON round-trip).
const merged = Object.assign({}, core, ext);
let bad = 0;
for (const pid of Object.keys(stanceData)) {
  if (JSON.stringify(stanceData[pid]) !== JSON.stringify(merged[pid])) bad++;
}
if (bad !== 0 || Object.keys(merged).length !== Object.keys(stanceData).length) {
  console.error('Integrity check FAILED — refusing to write.', { bad });
  process.exit(1);
}

// 5) Emit.
const banner = (which, note) =>
  `/* PolitiDex stance data — ${which} chunk. GENERATED by scripts/split-stances.mjs.\n` +
  `   ${note}\n` +
  `   Both chunks are loaded with \`defer\`, so window.ISSUE_STANCE_DATA is fully\n` +
  `   populated by DOMContentLoaded. Do not edit by hand — regenerate instead. */\n`;

const emit = (obj) =>
  `(function(){'use strict';\n` +
  `var S = window.ISSUE_STANCE_DATA || (window.ISSUE_STANCE_DATA = {});\n` +
  `var d = ${JSON.stringify(obj)};\n` +
  `for (var k in d) if (Object.prototype.hasOwnProperty.call(d, k)) S[k] = d[k];\n` +
  `})();\n`;

fs.writeFileSync(
  path.join(ROOT, 'politician-stances-core.js'),
  banner('CORE', 'Officials linked to the accountability layer — precached in the app shell.') + emit(core)
);
fs.writeFileSync(
  path.join(ROOT, 'politician-stances-ext.js'),
  banner('EXTENDED', 'Long-tail officials — low priority, kept fresh by the SW runtime cache.') + emit(ext)
);

console.log(`Wrote politician-stances-core.js (${Object.keys(core).length} officials) and ` +
  `politician-stances-ext.js (${Object.keys(ext).length} officials). Integrity OK.`);
